import { VERIFIED_TOTAL, CATEGORY_TREE } from "./commands";

/** Bump this whenever you ship something users should be told about. */
export const APP_VERSION = "2.34.0";

export interface ReleaseNote {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

/** Newest first. The top entry drives the "What's new" popup. */
export const CHANGELOG: ReleaseNote[] = [
  {
    version: "2.34.0",
    date: "2026-09-21",
    title: "Search visibility: a real icon, honest counts, every page in the sitemap",
    changes: [
      "Fixed the blank icon in Google results. The site shipped a 64px and a 32px favicon and no /favicon.ico at all — Google ignores both of those, because it needs a square icon that is a multiple of 48px. There is now a real 16/32/48 favicon.ico plus 48px and 96px PNGs, linked on every page",
      "Every tool page is in the sitemap now. The 160 hand-built tools (BMI, EMI, cron, colour picker and the rest) were missing from it entirely, which took sitemap.xml from 518 to 677 URLs",
      "Titles and search snippets quote the real catalogue totals — 5,704 commands, 289 tools, 71 games, 138 glossary terms — instead of stale guesses like '5,000+', '150+' and '560+'. The numbers are generated from the data, so they cannot drift out of date again",
      "Removed an invalid search-box block from the structured data: it pointed Google at a page the site itself tells it not to crawl",
      "The share card image reads those same live counts, and the sitemap now regenerates on every build instead of only when somebody remembered to run it",
    ],
  },
  {
    version: "2.33.0",
    date: "2026-09-21",
    title: "Quality pass: real games and real tools replace the filler",
    changes: [
      "Removed the 1,000+ generated converter kits and the 500 auto-chunked game packs. They inflated the counts without earning a place, so they are gone",
      "Commands trimmed back to the curated catalogue — the platform-variant padding is out, leaving 5,700 hand-picked commands across 45 categories",
      "Six real sports games: Table Tennis (top-down table, 11-point scoring, spin), Air Hockey, Penalty Shootout (five each way, you shoot then you keep), Darts (a true 501 board with trebles, doubles and busts), Basketball (60-second shootout) and Bowling (ten frames with real strike and spare scoring)",
      "Six new brain boosters: Sudoku (generated in your browser, guaranteed single solution, four difficulties), Nonogram (11 hand-drawn pictures with real run-length clues), Sliding Puzzle (8/15/24, always solvable), Mastermind, Tower of Hanoi, a 12-theme Word Search and Word Scramble",
      "New SlashKits toolkit: 130 honest tools at /tools/<name> — text and case utilities, JSON/CSV/regex/diff, SHA hashing, Base64/URL/HTML/hex/binary/Morse/Unicode encoding, colour conversion and CSS generators, date maths, meta tags and sitemaps, passwords and passphrases",
      "Where a new tool would have duplicated an existing one (JSON formatter, CSV to JSON, JWT decoder, UUID generator, word frequency), it was dropped rather than shipped twice",
      "Every new tool runs fully in the browser and says what it does — no uploads, no accounts, no unit-converter permutations",
    ],
  },
  {
    version: "2.32.0",
    date: "2026-09-20",
    title: "The big content wave: 10k commands, 500 games, 1,100 kits",
    changes: [
      "The command library doubles past 10,000, with whole new wings for social media creators (reels, carousels, CapCut-style editing), image enhancement, vibe coding, students (boards, JEE, NEET, placements), corporate work and kids",
      "SlashPlay jumps to 560+ games: hundreds of new quiz packs (capitals, flags, currencies, science, cricket, movies), word packs (scramble, hangman, spelling, opposites), memory boards, emoji puzzles and would-you-rather decks — every pack fully playable, most kid-friendly",
      "New Daily 8-Puzzle: a fresh sliding challenge every day, plus Sliding Numbers up to 5×5",
      "Kids Corner groups the gentle stuff in one place, and 'Take me somewhere fun' flings you to the best of the useless web — each site explained before you click",
      "SlashKits gains 1,000+ instant kits: every unit-pair converter you can think of, the full periodic table as fact pages, Indian state guides, world currencies, times tables and squares up to 20, copyable cheat sheets (git, Excel, flexbox, Hindi alphabet, VS Code), and a curated directory of free web tools with honest explanations",
      "Today's puzzle banner on SlashPlay rotates through every pack, once a day, forever",
    ],
  },
  {
    version: "2.31.0",
    date: "2026-09-20",
    title: "SlashAI Stores — free storefronts for small businesses",
    changes: [
      "New at /stores: a multi-tenant store platform. Anybody can sign in, create a store, add products and take orders — free, with no platform fees and no commission",
      "Each store gets its own web address: yourstore.slashai.in once the wildcard domain is live, and /stores/<slug> today. Both point at the same live shop",
      "Shoppers buy without an account — cart, checkout with just a name and phone, a real order code, and a one-tap WhatsApp hand-off for the order",
      "Store owner dashboard: products with photo upload, prices, stock and 'was' prices; orders with customer details, address and notes, moving through New → Confirmed → Shipped → Delivered",
      "Built on Supabase (Postgres + Auth + Storage) with Row Level Security, so a store account can only ever see its own store — safe to hand a subdomain to a friend or client",
      "Checkout runs through a server-side place_order function that re-reads every price from the database, so client prices can never be trusted",
      "Every existing feature keeps working with no backend at all until the Supabase keys are added — the store screens show a setup notice until then",
    ],
  },
  {
    version: "2.30.0",
    date: "2026-09-18",
    title: "Two new courses, a regex trainer and smarter everyday tools",
    changes: [
      "Two new courses on /learn: AI for Study & Research (study plans, quizzes, honest summaries, academic integrity) and Build a Real Website (HTML, CSS flexbox, shipping free to a live URL) — both with real lessons and graded module tests",
      "Learning paths updated: the AI Beginner and Developer paths now sequence the new courses, taking the catalogue to 5 courses · 24 lessons · 37 test questions",
      "The Regex Playground now teaches: a 5-challenge Regex Trainer with hints and a personal best, plus a tappable cheat sheet that inserts syntax into your pattern",
      "SEO Meta Tag Generator: live Google search preview, WhatsApp/X-style social card preview, character counters against the 60/155 limits, and a checks list that explains what to fix",
      "URL Encoder/Decoder breaks any link into origin, path and a query-parameter table with encoded-value flags — paste a share link to see exactly what it carries",
      "Percentage Calculator shows the worked line behind every answer, with quick chips for 18% GST, 5% GST, 10% tips and 50% off",
    ],
  },
  {
    version: "2.29.0",
    date: "2026-09-18",
    title: "The site updates itself again",
    changes: [
      "Fixed the reason nothing refreshed for weeks: every scheduled job was failing to push because its GitHub token was read-only, so daily news, deals, quotes and the weekly trending lists silently stopped updating. They commit cleanly now",
      "Trending tools are real tools again — Product Hunt's feed is Atom rather than RSS and was parsing to zero items, and two Hacker News articles about Nvidia were being listed as tools",
      "New Live tab on /trending: today's AI headlines, trending prompt libraries, and a quote plus artwork of the day, all refreshed automatically",
      "Gathering jobs now refuse to overwrite good data with an empty result, so a source going down can no longer blank a page",
    ],
  },
  {
    version: "2.28.0",
    date: "2026-09-18",
    title: "Guided commands, smarter browsing, a deeper cricket game",
    changes: [
      "Every command now shows a difficulty badge (🟢 Beginner / 🟡 Intermediate / 🔴 Advanced) worked out from its placeholders, plus a 4-step 'How to use this command' guide that opens for first-time visitors and collapses afterwards",
      "One-tap 'Try in ChatGPT / Gemini / Claude' buttons copy the command and open the assistant for you; the command detail page also links to 'You might also like' and a one-tap 'Something wrong? Report it'",
      "SlashKits: a 'Just added' shelf for new tools, 🆕 New and 🔥 Popular badges, a '🔒 Runs in your browser · Nothing uploaded' trust line on every card, and a 'How to use / Similar tools' block on every tool page",
      "SlashPlay: session length and difficulty on every game card (⏱ 2 min · 🎯 Easy), a 'Surprise me' random-game button, a New Games row and your personal best shown right on the card",
      "Slash Courses: 4 structured learning paths (AI, Developer, Creator, Career), topic filters, hour estimates and progress tracking that remembers what you have started",
      "Discover now opens with 'Start Here' — pick student, professional or developer and jump straight to the right hub",
      "New floating 'copy the last command again' pill (fades after 30s) and a back-to-top button that appears once you scroll",
      "Cricket got a real upgrade: 4 formats (Blitz 12, Solo 24, Chase AI, 2P duel), a share-your-score button, a beat-your-best challenge, and physics that run at the same speed on 60Hz and 120Hz screens",
      "HTML Compiler ships 14 ready-made starter projects — landing page, portfolio, pricing table, to-do app, gallery, login, dashboard, countdown, quiz, clock, navbar, particles and more. Load one, preview it, edit it and download a single .html file",
      "The homepage suggests 4 things 'You might like' once you have browsed a little — based only on your own device",
    ],
  },
  {
    version: "2.27.0",
    date: "2026-09-17",
    title: "Founder story, blog, hub intros and a big Learn fix",
    changes: [
      "Fixed: course lessons on /learn now open properly - lesson pages were unreachable due to a routing bug",
      "New blog at /blog, starting with 'Best Free AI Prompts for Professionals in India (2026)' - 10 copy-ready prompts from the library",
      "About page rewritten as an honest founder story from Waseem Ahmed (Hyderabad, India)",
      "Every hub now opens with a short intro: who it's for and what's inside",
      "Homepage additions: 'What is a slash command?' explainer, a library stats bar, and a real always-current week number on weekly finds",
      "Command of the day now shows 'Best for / Use it in / How to use' - three lines, no guessing",
      "Footer credits: Built in India by Waseem Ahmed - and it stays free forever",
    ],
  },
  {
    version: "2.26.0",
    date: "2026-09-16",
    title: "Learn courses, 10 tools, 6 games, one About",
    changes: [
      "Slash Learning rebuilt as real courses: 3 full courses with modules, proper lessons and a quiz test at the end of every module - progress and scores saved locally",
      "SlashKits grows by 10 new tools: Random Picker, Days Between Dates, Click Speed Test, VAT / Sales Tax, Hourly to Salary, Morse Code, Metronome, Nim Strategy Trainer, Word Scramble and Code Breaker",
      "SlashPlay grows by 6 new games: Word Scramble, Reach 24, Peg Jump, Odd One Out, World Capitals and RPS Lizard Spock",
      "About merged: the about-the-app page and the full FAQ now live together on /about - one place for everything",
      "Duplicate game entries removed so every tool and game opens a real page",
    ],
  },
  {
    version: "2.25.0",
    date: "2026-09-15",
    title: "Welcome tour + own domain",
    changes: [
      "First-time visitors now get a short welcome tour that explains what SlashAI is and where to start",
      "The site now lives at slashai.in - its own domain - and every share link, QR code and canonical URL points there",
      "Cleaned up: no more mentions of the tools used to build the site anywhere users can see",
      "Privacy policy, about page and changelog refreshed to match reality today",
    ],
  },
  {
    version: "2.20.1",
    date: "2026-09-12",
    title: "Universal search on the homepage",
    changes: [
      "The homepage hero search is now the full universal search: live results across commands, tools, games and the web as you type - no more plain redirect",
      "Recent searches appear when the empty search is focused; keyboard navigation (up/down/enter) works everywhere",
      "'See everything matching' link at the bottom of results opens the full Find Anything page",
    ],
  },
  {
    version: "2.20.0",
    date: "2026-09-12",
    title: "The big content expansion",
    changes: [
      "11 new working tools in SlashKits: Interest Calculator, UUID Generator, JWT Decoder, Word Frequency Analyser, Meeting Time Planner, Interval Timer, Matrix Rain, Signature Maker, Water Tracker, Periodic Table and Watermark Maker",
      "7 new games in SlashPlay: Stop the Color, Kindle, Guess the Year, Cosmic Dive, Maze Runner, Tap the Difference and Bounce - plus duplicates fixed so every listing matches a real page",
      "32 new trending commands added (5,682 total): agent swarms, Veo/video-scene prompts, headshot recipes, podcast clip scripts, programmatic SEO, interview war rooms and more",
      "SlashBar content pools roughly doubled - 710 curated entries across facts, hacks, shopping safety, study, career, romance and nearby-search guides",
      "New unified Find Anything search (/tools/finder): one box across commands, tools, games and the web, wired into the homepage hero",
      "Sidebar rebuilt: all 13 real hubs listed, SlashBar leaves mirror the rail exactly, Discovery/Commands tabs light up on all their sub-pages",
      "Duplicate SlashKits listings removed - every tool in the catalogue now opens a real page",
    ],
  },
  {
    version: "2.19.0",
    date: "2026-09-11",
    title: "SlashBar launcher - the app drawer",
    changes: [
      "SlashBar is now a full-screen launcher: tap the ⚡ centre button and an app drawer slides up with every Slash app organised into clear sections",
      "Live search inside the launcher with a found-count, plus swipe-down or × to close",
      "Bottom nav redesigned: lifted accent SlashBar button, active dots above tabs, accurate route matching",
      "Header cleanup: changelog link removed, proper gear icon for settings",
      "Homepage: stats bar now shows all five counts including Generators, Tool of the Day moved above Your Week, titles never cut mid-word",
      "SlashKits and SlashPlay preview sections added to the homepage",
      "Commands page got quick-link pills (Search, Collections, Saved, Recent); discovery, hubs, tools and play pages got stat rows",
    ],
  },
  {
    version: "2.18.0",
    date: "2026-09-04",
    title: "Clean-up release - paywalls removed, honest catalogue",
    changes: [
      "Removed the paid 'Glass' tier everywhere: no upgrade prompts, no waitlist, every theme and design is free",
      "Homepage: removed the dead email-subscribe box and the non-working 'More' chip; real counts in the stats bar",
      "Rebuilt the homepage footer into four verified link columns",
      "SlashKits reorganisation: duplicates removed (regex, diff, markdown, JSON), developer tools grouped under Developer, thin categories filled (Health, Learning, Languages), sections renamed clearly",
      "Tool of the Day now rotates daily on the homepage and SlashKits",
      "SlashKits search shows a found-count and a helpful empty state",
      "Settings: every theme is free, data-clear buttons show item counts, no more 'planned' placeholders",
      "Breadcrumbs (Home › Section › Page) across tools, hubs, commands, resources and top-level pages",
      "About page rewritten with accurate numbers; hub index shows only real hubs with live resource counts",
      "Discover search now returns live matches with a count across the whole catalogue",
      "Fixed broken Urdu-hub links and made tool descriptions honest (Islamic names count, temp-email inbox note, age-of-things)",
    ],
  },
  {
    version: "2.17.0",
    date: "2026-09-04",
    title: "AI Tools Directory - 100+ curated tools",
    changes: [
      "Rebuilt /ai-tools as a full directory: 100+ curated AI tools across 16 categories (writing, image, video, audio, coding, design, voice, marketing, data, automation, 3D, music and more)",
      "Every tool lists pricing (Free / Freemium / Paid / Open Source), free-tier limits, tags and a direct link to matching SlashAI commands",
      "Search, category chips with counts, and 'Free first' sorting across the whole catalog",
      "Featured + Trending rows and a Tool of the Day spotlight",
      "AI Tools now lives in the sidebar navigation and on the homepage",
    ],
  },
  {
    version: "2.16.0",
    date: "2026-09-03",
    title: "Document scanner, mock interviews, knowledge graph + analyser",
    changes: [
      "Document Scanner at /tools/scanner - capture pages with your camera (or upload on desktop), enhance and export multi-page PDF",
      "Mock Interview Simulator at /tools/interview - 500+ real questions with voice or typed answers and instant feedback on length, fillers, STAR and pace",
      "Website Analyser at /tools/analyze - free PageSpeed, security headers, SEO and social-meta audit of any URL",
      "Personal Knowledge Graph at /graph - saved commands, resources, collections and notes as an interactive force graph",
      "Install prompt: add SlashAI to your home screen after a few visits; full offline banner when your connection drops",
    ],
  },
  {
    version: "2.15.0",
    date: "2026-09-03",
    title: "Smart search, voice + AI Workflows",
    changes: [
      "Command Intelligence Engine - SlashAI learns the commands you copy, open and save (on-device only)",
      "Personalised search: usage-weighted results and a 'Based on your usage' section once you have history",
      "'Your most used' on the homepage after 10+ interactions",
      "Voice search in the homepage and search bars - English, Hindi, Arabic, Urdu",
      "AI Workflows at /workflow - chain commands into one copy-ready multi-step prompt",
      "Reorder steps by drag or arrows and mark a step to use the previous step's output",
    ],
  },
  {
    version: "2.9.0",
    date: "2026-08-29",
    title: "Free Tools - 22 browser utilities",
    changes: [
      "22 browser-based tools at /tools - all run in your browser, nothing uploaded",
      "File tools: Image Compressor, Image Converter, Images to PDF, HTML to PDF, Markdown to HTML, CSV to JSON",
      "Calculators: SIP, EMI, GST, BMI, Percentage, Age - with charts and live results",
      "Time tools: World Clock (12 cities), Pomodoro Timer, Countdown Timer",
      "Screens: Flip Clock, Focus Screen, Rain Screen, Starfield, New Tab, Quote of the Day",
      "Tools added to bottom nav bar, homepage grid, and sidebar",
    ],
  },
  {
    version: "2.8.0",
    date: "2026-08-28",
    title: "Daily Quiz",
    changes: [
      "Daily Quiz launched at /quiz with 24 trivia categories",
      "Fresh questions every calendar day per category (Open Trivia Database)",
      "Timer, streaks, score review, and share your score",
      "Open Trivia DB and The Trivia API added to Discover",
    ],
  },
  {
    version: "2.7.0",
    date: "2026-08-27",
    title: "Navigation, live ticker, version popup and polish",
    changes: [
      "Bottom navigation updated to 5 tabs: Home, Commands, Discover, Hubs, Saved",
      "Live ticker added to homepage top with markets, crypto, forex, prayer and weather data",
      "What's New popup shows on first visit after each update",
      "Loading tagline skipped on return visits for faster startup",
      "Theme toggle consolidated to desktop header only (Sun/Moon icon)",
      "FOUC prevention: inline theme script in <head> eliminates flash",
      "Scroll position resets to top on every route change",
      "Global smooth scroll with 80px scroll-margin-top on anchor targets",
      "Skeleton shimmer loading on all async content sections",
      "Page enter animation: 200ms fade+slide on route changes",
      "Homepage Hubs section redesigned as visual icon cards",
      "Homepage quick tool links replaced with clean 3×3 icon grid",
      "About page simplified and decluttered",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-08-24",
    title: "Build Ideas Library",
    changes: [
      "New Build Ideas library: 150 researched product ideas with the problem, target users, MVP scope, tech stack, pricing and a first-10-customers plan.",
      "Search and filter ideas by category, difficulty, business model, build type and who they suit.",
      "'Build this' generates a full product spec plus a paste-ready AI app-builder prompt, cached on your device so it opens instantly and works offline.",
      "Idea validator: describe your own idea and get scores for problem clarity, competition, monetization, build and acquisition difficulty.",
      "My projects tracks saved ideas from Idea to Launch with auto-saving notes - all on-device, no account needed.",
      "Sidebar sections for Discover and Build Ideas now collapse and expand with a toggle.",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-08-23",
    title: "Free AI, Reddit and themes",
    changes: [
      "New Free AI section: Andi, Duck.ai, HuggingChat, Eye2, LMArena, Le Chat, DeepSeek, Groq, local model apps and more.",
      "New Reddit section - the subreddits and wikis that actually hold free resources, from r/freebies to the r/learnprogramming wiki.",
      "New Free Time section: legal free movies and TV, public-domain books, radio, games and good blogs.",
      "New Websites section for single-purpose sites that do one thing properly.",
      "Four new themes - Batman, Ocean, Moonlight and Warm - alongside Dark, Light and AMOLED.",
      "'I want to…' shortcuts on the home screen for when you don't know what to search.",
      "Every command now shows where to run it, with a tip for ChatGPT, Claude, Gemini, Grok, Perplexity, DeepSeek and Duck.ai.",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-08-22",
    title: "More than commands",
    changes: [
      "New Discover hub: curated AI tools, free utilities, GitHub gems, courses, YouTube channels and practical tricks.",
      "Free Radar collects new free tools, student offers and free courses - with the conditions and a last-checked date on every entry.",
      "Free alternatives to popular paid software, grouped by what they replace.",
      "Student, Professional, Developer and Creator hubs.",
      "What's New page with weekly finds, monthly drops and yearly guides.",
      "Calmer home and simpler navigation: four items on mobile, nested Discover in the sidebar, endless feed removed.",
      "Search now returns curated resources alongside commands.",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-08-22",
    title: "Cleaner, faster, more yours",
    changes: [
      `Catalog grown to ${VERIFIED_TOTAL.toLocaleString()} commands across ${CATEGORY_TREE.length} categories - money, health, travel, social and home added.`,
      "Simpler home screen: less text, bigger tap targets, filters tucked into one button.",
      "Smarter search - type several words in any order and it still finds the right command.",
      "Six accent colours to pick from in Settings.",
      "Backup and restore your favourites, history and settings as a single file.",
      "Smoother 120Hz-friendly animations and a proper launch screen instead of a black flash.",
      "This update popup, plus a full changelog in Settings.",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-08-01",
    title: "SlashAI launch",
    changes: [
      "Searchable library of AI slash commands with copy-ready prompts.",
      "Favourites, recently used and shareable command links.",
      "Works offline and installs as an app.",
    ],
  },
];

export const LATEST_RELEASE = CHANGELOG[0]!;

export const APP_DETAILS = {
  name: "SlashAI",
  tagline: "A pocket library of AI slash commands.",
  version: APP_VERSION,
  creator: "Waseem Ahmed",
  website: "https://slashai.in",
  storage: "Everything stays on this device - no account, no tracking.",
};
