/**
 * 40 new free APIs — public data, utility, creative, no credit card required.
 */

export interface FreeApi {
  id: string;
  name: string;
  description: string;
  auth: string;
  rateLimit: string;
  category: string;
  url: string;
}

export const NEW_APIS: FreeApi[] = [
  // ── PUBLIC DATA ──
  {
    id: "data-gov-in",
    name: "data.gov.in",
    description: "India government open data portal — thousands of datasets, completely free.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://data.gov.in",
  },
  {
    id: "data-gov-us",
    name: "data.gov (US)",
    description: "US federal government datasets — 200,000+ datasets, completely free.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://data.gov",
  },
  {
    id: "data-europa",
    name: "data.europa.eu",
    description: "EU open data portal — thousands of European government datasets.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://data.europa.eu",
  },
  {
    id: "world-bank-api",
    name: "World Bank Open Data API",
    description: "Global development indicators — economic, social, environmental data for 200+ countries.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://datahelpdesk.worldbank.org",
  },
  {
    id: "un-data-api",
    name: "UN Data API",
    description: "United Nations statistics — population, trade, education, health across all countries.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://data.un.org",
  },
  {
    id: "imf-data",
    name: "IMF Data API",
    description: "International Monetary Fund datasets — economic outlook, balance of payments, debt.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://data.imf.org",
  },
  {
    id: "who-gho",
    name: "WHO Global Health Observatory",
    description: "World Health Organization health statistics — disease, mortality, health systems.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://ghoapi.azureedge.net",
  },
  {
    id: "oecd-data",
    name: "OECD Data API",
    description: "Organisation for Economic Co-operation and Development — economic and social data.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://stats.oecd.org",
  },
  {
    id: "ogd-pakistan",
    name: "ogd.data.gov.pk",
    description: "Pakistan open government data — datasets on economy, health, education.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Public Data",
    url: "https://ogd.data.gov.pk",
  },

  // ── UTILITY ──
  {
    id: "abstract-holidays",
    name: "Abstract Holidays API",
    description: "Public holidays for 200+ countries — upcoming and historical dates.",
    auth: "Free tier",
    rateLimit: "1000 req/month",
    category: "Utility",
    url: "https://abstractapi.com/api/holidays-api",
  },
  {
    id: "calendarific",
    name: "Calendarific API",
    description: "Holidays and observances globally — filter by country, year, type.",
    auth: "Free key",
    rateLimit: "1000 req/month",
    category: "Utility",
    url: "https://calendarific.com",
  },
  {
    id: "timezone-db",
    name: "TimeZoneDB",
    description: "Timezone data for any location — convert, DST, time zone lookup.",
    auth: "Free key",
    rateLimit: "1000 req/day",
    category: "Utility",
    url: "https://timezonedb.com",
  },
  {
    id: "mediastack",
    name: "MediaStack",
    description: "Global news API — real-time news from 7,500+ sources in 50+ languages.",
    auth: "Free tier",
    rateLimit: "500 req/month",
    category: "Utility",
    url: "https://mediastack.com",
  },
  {
    id: "newsdata-io",
    name: "NewsData.io",
    description: "Multilingual news API — includes Urdu, Arabic, Bengali, Hindi sources.",
    auth: "Free tier",
    rateLimit: "200 req/day",
    category: "Utility",
    url: "https://newsdata.io",
  },
  {
    id: "gdelt",
    name: "GDELT Project",
    description: "Global news event database — largest free corpus of global news events.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Utility",
    url: "https://api.gdeltproject.org",
  },
  {
    id: "polygon-io",
    name: "Polygon.io",
    description: "US stock market data — real-time and historical prices for stocks, options, crypto.",
    auth: "Free tier",
    rateLimit: "5 req/min",
    category: "Utility",
    url: "https://polygon.io",
  },
  {
    id: "alpha-vantage",
    name: "Alpha Vantage",
    description: "Stocks, forex, crypto market data — real-time and historical, 25+ indicators.",
    auth: "Free key",
    rateLimit: "25 req/day",
    category: "Utility",
    url: "https://alphavantage.co",
  },

  // ── CREATIVE / CULTURAL ──
  {
    id: "art-institute-chicago",
    name: "Art Institute of Chicago API",
    description: "100,000+ artwork images — high-res images, artist info, exhibition data.",
    auth: "No key",
    rateLimit: "60 req/min",
    category: "Creative",
    url: "https://api.artic.edu",
  },
  {
    id: "met-museum",
    name: "Metropolitan Museum API",
    description: "400,000+ art objects — paintings, sculptures, textiles from 5,000 years of culture.",
    auth: "No key",
    rateLimit: "80 req/s",
    category: "Creative",
    url: "https://collectionapi.metmuseum.org",
  },
  {
    id: "harvard-art",
    name: "Harvard Art Museums API",
    description: "250,000+ works — paintings, prints, photographs, sculptures from Harvard's collection.",
    auth: "Free key",
    rateLimit: "25 req/s",
    category: "Creative",
    url: "https://api.harvardartmuseums.org",
  },
  {
    id: "nasa-images",
    name: "NASA Images and Video Library",
    description: "NASA's full media archive — images, videos, audio from all NASA missions.",
    auth: "No key",
    rateLimit: "1000 req/hour",
    category: "Creative",
    url: "https://images-api.nasa.gov",
  },
  {
    id: "smithsonian-oa",
    name: "Smithsonian Open Access API",
    description: "4.7 million+ collection items — art, history, science, culture from 19 museums.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://api.si.edu",
  },
  {
    id: "library-congress",
    name: "Library of Congress API",
    description: "Digital library — millions of books, photos, maps, audio from US national library.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://www.loc.gov",
  },
  {
    id: "gutendex",
    name: "Gutendex",
    description: "Project Gutenberg books API — 70,000+ free eBooks in multiple languages.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://gutendex.com",
  },
  {
    id: "open-trivia",
    name: "Open Trivia Database",
    description: "Quiz questions across 20+ categories — perfect for building trivia games.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://opentdb.com/api",
  },
  {
    id: "quotable",
    name: "Quotable API",
    description: "1,600+ quotes — by author, tag, or random. Great for apps and websites.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://github.com/lukePeavey/quotable",
  },
  {
    id: "affirmations-dev",
    name: "Affirmations.dev",
    description: "Daily positive affirmations — simple API for wellness and motivation apps.",
    auth: "No key",
    rateLimit: "Unlimited",
    category: "Creative",
    url: "https://www.affirmations.dev",
  },
];
