/**
 * Extra curated resources: Free AI, Reddit, Websites and Free Time.
 *
 * Same rules as `resources.ts` — nothing is invented. Where a service is only
 * free in some places (library cards, regions) that condition is written into
 * `eligibility`. We list legal sources only; no piracy hubs, ever.
 */
import type { Resource } from "./resources";

const D = "2026-08-23";

const r = (
  x: Omit<Resource, "addedDate" | "lastUpdated" | "lastVerified" | "status"> &
    Partial<Pick<Resource, "addedDate" | "lastUpdated" | "lastVerified" | "status">>,
): Resource => ({
  addedDate: D,
  lastUpdated: D,
  lastVerified: D,
  status: "Active",
  ...x,
});

export const EXTRA_RESOURCES: Resource[] = [
  // ------------------------------------------------------------- Free AI
  r({
    id: "fa-andi",
    name: "Andi",
    url: "https://andisearch.com",
    description: "Ad-free AI answer engine that summarises pages and never tracks you.",
    section: "free-ai",
    category: "AI Search",
    audience: ["Everyone", "Students"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["search", "privacy", "answers"],
    notes: "The calmest AI search on this list — no ads, no account prompt.",
    radar: "New Free AI Tool",
    commandQuery: "research",
  }),
  r({
    id: "fa-duck-ai",
    name: "DuckDuckGo AI Chat",
    url: "https://duck.ai",
    description: "Anonymous chat with several models through DuckDuckGo's privacy proxy.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["privacy", "chat", "anonymous"],
    notes: "No sign-in, chats are not used for training. Good default for private questions.",
    commandQuery: "summarize",
  }),
  r({
    id: "fa-huggingchat",
    name: "HuggingChat",
    url: "https://huggingface.co/chat",
    description: "Chat interface running open-weight models hosted by Hugging Face.",
    section: "free-ai",
    category: "Open Models",
    audience: ["Everyone", "Developers"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["open-source", "chat", "models"],
  }),
  r({
    id: "fa-eye2",
    name: "Eye2.ai",
    url: "https://www.eye2.ai",
    description: "Ask one question and compare answers from many AI models side by side.",
    section: "free-ai",
    category: "AI Comparison",
    audience: ["Researchers", "Students", "Everyone"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["compare", "fact-check", "hidden-gem"],
    notes:
      "When an answer matters, ask several models at once — disagreement is the signal to dig deeper.",
    radar: "New Free AI Tool",
    commandQuery: "fact check",
  }),
  r({
    id: "fa-lmarena",
    name: "LMArena",
    url: "https://lmarena.ai",
    description: "Try two anonymous models on the same prompt and vote for the better answer.",
    section: "free-ai",
    category: "AI Comparison",
    audience: ["Everyone", "Researchers"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["compare", "benchmark", "models"],
  }),
  r({
    id: "fa-google-ai-studio",
    name: "Google AI Studio",
    url: "https://aistudio.google.com",
    description: "Browser workspace for prompting Gemini models and testing an API key.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Developers", "Everyone"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["gemini", "api", "prompting"],
    radar: "Free API Credits",
  }),
  r({
    id: "fa-groq",
    name: "Groq",
    url: "https://groq.com",
    description: "Very fast hosted inference for open models, with a free developer tier.",
    section: "free-ai",
    category: "Open Models",
    audience: ["Developers"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["inference", "api", "fast"],
    radar: "Free API Credits",
  }),
  r({
    id: "fa-mistral-chat",
    name: "Le Chat (Mistral)",
    url: "https://chat.mistral.ai",
    description: "European assistant from Mistral with a usable free plan.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Everyone"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["chat", "europe", "assistant"],
  }),
  r({
    id: "fa-deepseek",
    name: "DeepSeek",
    url: "https://chat.deepseek.com",
    description: "Assistant with strong reasoning and coding output on a free web tier.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Developers", "Students"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["reasoning", "coding", "chat"],
    commandQuery: "debug",
  }),
  r({
    id: "fa-qwen",
    name: "Qwen Chat",
    url: "https://chat.qwen.ai",
    description: "Alibaba's assistant with open-weight model options and image support.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Everyone"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["chat", "multilingual", "open-weights"],
  }),
  r({
    id: "fa-phind",
    name: "Phind",
    url: "https://www.phind.com",
    description: "Answer engine tuned for programming questions, with sources.",
    section: "free-ai",
    category: "AI Search",
    audience: ["Developers"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["developers", "search", "code"],
    commandQuery: "explain code",
  }),
  r({
    id: "fa-you",
    name: "You.com",
    url: "https://you.com",
    description: "AI search that lets you pick a model and keeps a private mode.",
    section: "free-ai",
    category: "AI Search",
    audience: ["Everyone"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["search", "privacy", "models"],
  }),
  r({
    id: "fa-pi",
    name: "Pi",
    url: "https://pi.ai",
    description: "Conversational assistant designed for talking things through, not tasks.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["conversation", "voice", "calm"],
  }),
  r({
    id: "fa-lumo",
    name: "Lumo",
    url: "https://lumo.proton.me",
    description: "Proton's assistant with encrypted chat history and no training on your data.",
    section: "free-ai",
    category: "Free AI Chat",
    audience: ["Everyone", "Professionals"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web", "Android", "iOS"],
    tags: ["privacy", "encrypted", "chat"],
  }),
  r({
    id: "fa-openrouter",
    name: "OpenRouter",
    url: "https://openrouter.ai",
    description: "One API key for many models, including a rotating set of free ones.",
    section: "free-ai",
    category: "Open Models",
    audience: ["Developers"],
    pricing: "Free Tier",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["api", "models", "gateway"],
    radar: "Free API Credits",
  }),
  r({
    id: "fa-jan",
    name: "Jan",
    url: "https://jan.ai",
    description: "Desktop app that runs open models fully offline on your own machine.",
    section: "free-ai",
    category: "Open Models",
    audience: ["Developers", "Everyone"],
    pricing: "Open Source",
    type: "Software",
    platform: ["Windows", "macOS", "Linux"],
    tags: ["local-ai", "offline", "privacy"],
    difficulty: "Intermediate",
    alternativeTo: ["ChatGPT Plus"],
  }),
  r({
    id: "fa-lmstudio",
    name: "LM Studio",
    url: "https://lmstudio.ai",
    description: "Download and chat with local models through a friendly desktop interface.",
    section: "free-ai",
    category: "Open Models",
    audience: ["Developers"],
    pricing: "Completely Free",
    type: "Software",
    platform: ["Windows", "macOS", "Linux"],
    tags: ["local-ai", "models", "offline"],
    difficulty: "Intermediate",
  }),
  r({
    id: "fa-ideavo",
    name: "Ideavo",
    url: "https://ideavo.ai",
    description: "Build web apps by chatting with AI, using your own provider API key.",
    section: "free-ai",
    category: "AI Coding",
    audience: ["Entrepreneurs", "Developers", "Students"],
    pricing: "Completely Free",
    type: "AI Tool",
    platform: ["Web"],
    tags: ["app-builder", "byok", "no-code"],
    difficulty: "Beginner",
    notes:
      "Bring-your-own-key means no subscription and no lock-in if you already have an API key.",
    radar: "New Free AI Tool",
    commandQuery: "product spec",
  }),

  // -------------------------------------------------------------- Reddit
  r({
    id: "rd-freebies",
    name: "r/freebies",
    url: "https://www.reddit.com/r/freebies/",
    description: "Community feed of genuinely free samples, downloads and giveaways.",
    section: "reddit",
    category: "Free Stuff",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web", "Android", "iOS"],
    tags: ["freebies", "deals", "community"],
    notes: "Read the sidebar rules first — the wiki explains how the flair system marks scams.",
  }),
  r({
    id: "rd-freegamefindings",
    name: "r/FreeGameFindings",
    url: "https://www.reddit.com/r/FreeGameFindings/",
    description: "Posts every legitimately free game giveaway across the major stores.",
    section: "reddit",
    category: "Free Stuff",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["games", "giveaways", "steam"],
  }),
  r({
    id: "rd-gamedeals",
    name: "r/GameDeals",
    url: "https://www.reddit.com/r/GameDeals/",
    description: "Verified game discounts and free claims, with a strict no-key-reselling rule.",
    section: "reddit",
    category: "Free Stuff",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["deals", "games"],
  }),
  r({
    id: "rd-freeebooks",
    name: "r/FreeEBOOKS",
    url: "https://www.reddit.com/r/FreeEBOOKS/",
    description: "Author- and publisher-approved free ebook offers, posted daily.",
    section: "reddit",
    category: "Books & Reading",
    audience: ["Everyone", "Students"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["books", "reading", "free"],
  }),
  r({
    id: "rd-moviesuggestions",
    name: "r/MovieSuggestions",
    url: "https://www.reddit.com/r/MovieSuggestions/",
    description: "Ask for a film by mood or theme and get human recommendations, not algorithms.",
    section: "reddit",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["movies", "recommendations"],
  }),
  r({
    id: "rd-fullmoviesonyoutube",
    name: "r/FullMoviesOnYouTube",
    url: "https://www.reddit.com/r/fullmoviesonyoutube/",
    description: "Full films that rights holders have published free on YouTube.",
    section: "reddit",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["movies", "youtube", "legal"],
    notes:
      "Only official or public-domain uploads belong here — check the channel before watching.",
  }),
  r({
    id: "rd-documentaries",
    name: "r/Documentaries",
    url: "https://www.reddit.com/r/Documentaries/",
    description: "Free-to-watch documentaries, most of them hosted by the original broadcaster.",
    section: "reddit",
    category: "Movies & TV",
    audience: ["Everyone", "Students"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["documentary", "watch", "learning"],
  }),
  r({
    id: "rd-cordcutters",
    name: "r/Cordcutters",
    url: "https://www.reddit.com/r/cordcutters/",
    description: "How people watch TV legally without a cable bill, including free services.",
    section: "reddit",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["streaming", "tv", "free"],
  }),
  r({
    id: "rd-learnprogramming-wiki",
    name: "r/learnprogramming wiki",
    url: "https://www.reddit.com/r/learnprogramming/wiki/index/",
    description: "A maintained index of free courses, books and project ideas for beginners.",
    section: "reddit",
    category: "Wikis & Megathreads",
    audience: ["Students", "Developers"],
    pricing: "Completely Free",
    type: "Wiki",
    platform: ["Web"],
    tags: ["wiki", "learning", "programming"],
    notes: "One of the best free curricula on the internet, and it is just a subreddit wiki.",
    commandQuery: "learn code",
  }),
  r({
    id: "rd-personalfinance-wiki",
    name: "r/personalfinance wiki",
    url: "https://www.reddit.com/r/personalfinance/wiki/index/",
    description: "Step-by-step money guides and free spreadsheet templates.",
    section: "reddit",
    category: "Wikis & Megathreads",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Wiki",
    platform: ["Web"],
    tags: ["wiki", "money", "guides"],
    region: "US-centric, principles apply widely",
  }),
  r({
    id: "rd-askhistorians-books",
    name: "r/AskHistorians books & resources",
    url: "https://www.reddit.com/r/AskHistorians/wiki/books/",
    description: "Historian-vetted reading lists organised by period and region.",
    section: "reddit",
    category: "Wikis & Megathreads",
    audience: ["Students", "Researchers"],
    pricing: "Completely Free",
    type: "Wiki",
    platform: ["Web"],
    tags: ["wiki", "history", "reading-list"],
  }),
  r({
    id: "rd-datahoarder",
    name: "r/DataHoarder",
    url: "https://www.reddit.com/r/DataHoarder/",
    description: "Archiving, backups and public dataset rescue, with a deep resource wiki.",
    section: "reddit",
    category: "Wikis & Megathreads",
    audience: ["Developers", "Researchers"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["archive", "backup", "wiki"],
  }),
  r({
    id: "rd-localllama",
    name: "r/LocalLLaMA",
    url: "https://www.reddit.com/r/LocalLLaMA/",
    description: "The fastest place to learn what open models can actually run on your hardware.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Developers"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["local-ai", "models", "community"],
  }),
  r({
    id: "rd-artificial",
    name: "r/artificial",
    url: "https://www.reddit.com/r/artificial/",
    description: "General AI news and discussion without the hype-only tone.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["ai", "news"],
  }),
  r({
    id: "rd-chatgpt",
    name: "r/ChatGPT",
    url: "https://www.reddit.com/r/ChatGPT/",
    description: "Prompt techniques and workarounds shared by heavy assistant users.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["prompts", "chatgpt"],
    commandQuery: "prompt",
  }),
  r({
    id: "rd-coolgithubprojects",
    name: "r/coolgithubprojects",
    url: "https://www.reddit.com/r/coolgithubprojects/",
    description: "A steady stream of small open-source projects worth a look.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Developers"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["github", "open-source"],
  }),
  r({
    id: "rd-selfhosted",
    name: "r/selfhosted",
    url: "https://www.reddit.com/r/selfhosted/",
    description: "Free replacements for paid SaaS that you can run yourself.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Developers"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["self-host", "open-source", "alternatives"],
  }),
  r({
    id: "rd-internetisbeautiful",
    name: "r/InternetIsBeautiful",
    url: "https://www.reddit.com/r/InternetIsBeautiful/",
    description: "Single-purpose free websites that are genuinely delightful.",
    section: "reddit",
    category: "Free Stuff",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["websites", "discovery", "fun"],
  }),
  r({
    id: "rd-androidapps",
    name: "r/androidapps",
    url: "https://www.reddit.com/r/androidapps/",
    description: "App discovery and free-app threads, with a long-running recommendation wiki.",
    section: "reddit",
    category: "Tech & AI",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web", "Android"],
    tags: ["android", "apps"],
  }),
  r({
    id: "rd-blogging",
    name: "r/Blogging",
    url: "https://www.reddit.com/r/Blogging/",
    description: "Practical advice on starting and growing a blog on free platforms.",
    section: "reddit",
    category: "Blogs & Writing",
    audience: ["Creators", "Entrepreneurs"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["blogging", "writing", "seo"],
    commandQuery: "blog post",
  }),
  r({
    id: "rd-writing",
    name: "r/writing",
    url: "https://www.reddit.com/r/writing/",
    description: "Craft discussion plus a wiki of free tools, prompts and publishing advice.",
    section: "reddit",
    category: "Blogs & Writing",
    audience: ["Creators", "Students"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["writing", "craft", "wiki"],
    commandQuery: "writing",
  }),
  r({
    id: "rd-getstudying",
    name: "r/GetStudying",
    url: "https://www.reddit.com/r/GetStudying/",
    description: "Study systems, focus methods and free study resources from students.",
    section: "reddit",
    category: "Learning",
    audience: ["Students"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["study", "focus", "students"],
    commandQuery: "study plan",
  }),
  r({
    id: "rd-freecourses",
    name: "r/FREECOURSES",
    url: "https://www.reddit.com/r/FREECOURSES/",
    description: "Course coupons and permanently free classes posted by the community.",
    section: "reddit",
    category: "Learning",
    audience: ["Students"],
    pricing: "Completely Free",
    type: "Subreddit",
    platform: ["Web"],
    tags: ["courses", "learning", "coupons"],
    notes: "Verify each link — coupon posts expire quickly and some are simply marketing.",
  }),

  // ------------------------------------------------------------ Websites
  r({
    id: "web-cobalt",
    name: "Cobalt",
    url: "https://cobalt.tools",
    description: "Save video or audio from public links with no ads and no sign-up.",
    section: "websites",
    category: "Hidden Gems",
    audience: ["Creators", "Everyone"],
    pricing: "Open Source",
    type: "Website",
    platform: ["Web"],
    tags: ["download", "video", "clean"],
    notes: "Only download material you have the right to keep.",
  }),
  r({
    id: "web-tally",
    name: "Tally",
    url: "https://tally.so",
    description: "Form builder with an unusually generous free plan and no per-response cap.",
    section: "websites",
    category: "Productivity",
    audience: ["Professionals", "Entrepreneurs"],
    pricing: "Free Tier",
    type: "Website",
    platform: ["Web"],
    tags: ["forms", "surveys"],
    alternativeTo: ["Typeform"],
  }),
  r({
    id: "web-calcom",
    name: "Cal.com",
    url: "https://cal.com",
    description: "Open-source scheduling you can use hosted or run on your own server.",
    section: "websites",
    category: "Productivity",
    audience: ["Professionals"],
    pricing: "Open Source",
    type: "Website",
    platform: ["Web"],
    tags: ["scheduling", "calendar"],
    alternativeTo: ["Calendly"],
  }),
  r({
    id: "web-kagi",
    name: "Kagi",
    url: "https://kagi.com",
    description: "Ad-free search engine; a limited number of free searches, then paid.",
    section: "websites",
    category: "Search",
    audience: ["Everyone"],
    pricing: "Paid",
    type: "Website",
    platform: ["Web"],
    tags: ["search", "no-ads"],
    eligibility: "Free trial searches only — this is a paid product, listed for honesty.",
  }),
  r({
    id: "web-photopea-alt",
    name: "Vectorizer.io",
    url: "https://www.vectorizer.io",
    description: "Turn a raster logo into clean vector paths in the browser.",
    section: "websites",
    category: "Design",
    audience: ["Designers", "Creators"],
    pricing: "Free Tier",
    type: "Website",
    platform: ["Web"],
    tags: ["vector", "logo", "convert"],
  }),
  r({
    id: "web-tinywow",
    name: "TinyWow",
    url: "https://tinywow.com",
    description: "A large set of file, PDF and image utilities that work without an account.",
    section: "websites",
    category: "Utilities",
    audience: ["Everyone"],
    pricing: "Free Tier",
    type: "Website",
    platform: ["Web"],
    tags: ["pdf", "convert", "utilities"],
  }),
  r({
    id: "web-wolframalpha",
    name: "Wolfram Alpha",
    url: "https://www.wolframalpha.com",
    description: "Computational answers for maths, science and unit-heavy questions.",
    section: "websites",
    category: "Utilities",
    audience: ["Students", "Researchers"],
    pricing: "Freemium",
    type: "Website",
    platform: ["Web"],
    tags: ["maths", "science", "calculator"],
    commandQuery: "solve",
  }),

  // ----------------------------------------------------------- Free Time
  r({
    id: "ft-tubi",
    name: "Tubi",
    url: "https://tubitv.com",
    description: "Thousands of licensed films and shows, free with ad breaks.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["movies", "streaming", "legal"],
    region: "Availability varies by country",
  }),
  r({
    id: "ft-pluto",
    name: "Pluto TV",
    url: "https://pluto.tv",
    description: "Free live channels and on-demand films, no account required.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["tv", "streaming", "live"],
    region: "Availability varies by country",
  }),
  r({
    id: "ft-plex-free",
    name: "Plex free movies",
    url: "https://watch.plex.tv",
    description: "Ad-supported free catalogue of films and channels inside Plex.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["movies", "streaming"],
  }),
  r({
    id: "ft-archive-films",
    name: "Internet Archive — Feature Films",
    url: "https://archive.org/details/feature_films",
    description: "Public-domain and freely licensed films you can stream or download.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Everyone", "Researchers"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["public-domain", "archive", "movies"],
  }),
  r({
    id: "ft-kanopy",
    name: "Kanopy",
    url: "https://www.kanopy.com",
    description: "Curated films and documentaries, free through participating libraries.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Students", "Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["library", "documentary", "film"],
    eligibility: "Requires a library card or university login at a participating institution.",
  }),
  r({
    id: "ft-hoopla",
    name: "Hoopla",
    url: "https://www.hoopladigital.com",
    description: "Borrow films, audiobooks and comics free with a library card.",
    section: "free-time",
    category: "Movies & TV",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["library", "audiobooks", "movies"],
    eligibility: "Requires a card from a participating library.",
  }),
  r({
    id: "ft-gutenberg",
    name: "Project Gutenberg",
    url: "https://www.gutenberg.org",
    description: "Tens of thousands of public-domain ebooks in open formats.",
    section: "free-time",
    category: "Reading",
    audience: ["Everyone", "Students"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["ebooks", "public-domain", "reading"],
  }),
  r({
    id: "ft-standard-ebooks",
    name: "Standard Ebooks",
    url: "https://standardebooks.org",
    description: "Public-domain classics, carefully typeset and proofread by volunteers.",
    section: "free-time",
    category: "Reading",
    audience: ["Everyone"],
    pricing: "Open Source",
    type: "Website",
    platform: ["Web"],
    tags: ["ebooks", "classics", "typography"],
  }),
  r({
    id: "ft-open-library",
    name: "Open Library",
    url: "https://openlibrary.org",
    description: "Borrow scanned books digitally from the Internet Archive's lending library.",
    section: "free-time",
    category: "Reading",
    audience: ["Everyone", "Students"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["books", "borrow", "archive"],
  }),
  r({
    id: "ft-devto",
    name: "Dev.to",
    url: "https://dev.to",
    description: "Developer articles that stay free to read and free to publish on.",
    section: "free-time",
    category: "Blogs",
    audience: ["Developers"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["blogs", "developers", "writing"],
  }),
  r({
    id: "ft-hackernews",
    name: "Hacker News",
    url: "https://news.ycombinator.com",
    description: "Tech and startup links with comment threads that are often better than the link.",
    section: "free-time",
    category: "Blogs",
    audience: ["Developers", "Entrepreneurs"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["news", "tech", "discussion"],
  }),
  r({
    id: "ft-substack",
    name: "Substack",
    url: "https://substack.com",
    description: "Independent newsletters on almost any subject, many entirely free.",
    section: "free-time",
    category: "Blogs",
    audience: ["Everyone"],
    pricing: "Freemium",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["newsletters", "reading", "writing"],
  }),
  r({
    id: "ft-lichess",
    name: "Lichess",
    url: "https://lichess.org",
    description: "Fully free, ad-free, open-source chess with lessons and puzzles.",
    section: "free-time",
    category: "Games",
    audience: ["Everyone"],
    pricing: "Open Source",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["chess", "games", "no-ads"],
  }),
  r({
    id: "ft-monkeytype",
    name: "Monkeytype",
    url: "https://monkeytype.com",
    description: "Minimal typing test with detailed stats and no clutter.",
    section: "free-time",
    category: "Games",
    audience: ["Everyone", "Students"],
    pricing: "Open Source",
    type: "Website",
    platform: ["Web"],
    tags: ["typing", "practice"],
  }),
  r({
    id: "ft-nealfun",
    name: "Neal.fun",
    url: "https://neal.fun",
    description: "Small interactive experiences that teach something in a few minutes.",
    section: "free-time",
    category: "Fun",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["interactive", "fun", "learning"],
  }),
  r({
    id: "ft-radio-garden",
    name: "Radio Garden",
    url: "https://radio.garden",
    description: "Spin a globe and listen to live local radio anywhere in the world.",
    section: "free-time",
    category: "Music & Radio",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web", "Android", "iOS"],
    tags: ["radio", "music", "world"],
  }),
  r({
    id: "ft-window-swap",
    name: "WindowSwap",
    url: "https://www.window-swap.com",
    description: "Look out of a stranger's window somewhere else in the world.",
    section: "free-time",
    category: "Fun",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "Website",
    platform: ["Web"],
    tags: ["calm", "fun", "break"],
  }),

  // -------------------------------------------------------------- GitHub
  r({
    id: "gh-cross-platform-llm-client",
    name: "cross-platform-llm-client",
    url: "https://github.com/orailnoor/cross-platform-llm-client",
    description: "A cross-platform client for chatting with local language models.",
    section: "github",
    category: "Local AI",
    audience: ["Developers"],
    pricing: "Open Source",
    type: "GitHub",
    owner: "orailnoor",
    platform: ["Windows", "macOS", "Linux"],
    tags: ["local-ai", "client", "cross-platform"],
    difficulty: "Intermediate",
  }),
  r({
    id: "gh-private-agent",
    name: "PrivateAgent",
    url: "https://github.com/orailnoor/private-agent",
    description:
      "Open-source Android agent that reads your screen and performs multi-step tasks from plain-language instructions.",
    section: "github",
    category: "Automation",
    audience: ["Developers"],
    pricing: "Open Source",
    type: "GitHub",
    owner: "orailnoor",
    language: "Dart",
    platform: ["Android"],
    tags: ["android", "automation", "agent"],
    difficulty: "Intermediate",
    eligibility: "Needs your own DeepSeek API key and Android accessibility permission.",
    notes: "Real phone automation from natural language, not recorded macros.",
  }),

  // ------------------------------------------------------------- YouTube
  r({
    id: "yt-tech-jarves",
    name: "Tech Jarves",
    url: "https://youtube.com/@techjarves",
    description: "Practical walkthroughs of AI tools and everyday tech, aimed at non-experts.",
    section: "youtube",
    category: "AI",
    audience: ["Everyone"],
    pricing: "Completely Free",
    type: "YouTube",
    platform: ["Web", "Android", "iOS"],
    tags: ["ai", "tutorials", "tech"],
    difficulty: "Beginner",
    notes: "Good starting point if you want to see a tool used before you try it yourself.",
    radar: "YouTube Pick",
  }),
];
