/**
 * AUTO-GENERATED by scripts/generate-seo-counts.mjs — do not edit by hand.
 * Real catalogue totals for the SEO layer. Regenerate with `bun run seo:counts`.
 */

export const SEO_COUNTS = {
  commands: 5704,
  categories: 45,
  subcategories: 381,
  tools: 310,
  games: 91,
  collections: 16,
  glossaryTerms: 138,
  glossaryCategories: 12,
  buildIdeas: 150,
  aiTools: 117,
  aiToolCategories: 16,
  courses: 6,
  lessons: 30,
  testQuestions: 46,
  roadmaps: 20,
  resources: 171,
} as const;
