/**
 * SlashBar mega content pools — real, useful, curated items per app.
 * Every entry is original writing (no scraping), organised so the
 * tap-to-reveal decks read like tiny field guides.
 */

/* ─── facts ─── */
export const MEGA_FACTS: string[] = [
  "Honey found in Egyptian tombs is still edible after 3,000 years - its low water and high acidity make it hostile to microbes.",
  "Octopuses have three hearts; two pump blood to the gills, one to the body - and the body one stops when they swim.",
  "There are more legal chess positions than atoms in the observable universe by many orders of magnitude.",
  "Botanically, bananas are berries and strawberries are not - berries develop from a single ovary.",
  "A day on Venus lasts longer than its year: it rotates once every 243 Earth days but orbits the Sun in 225.",
  "Sharks predate trees - the first sharks appeared about 450 million years ago, trees roughly 390 million years ago.",
  "The Eiffel Tower can grow about 15 cm taller on hot days as the iron expands.",
  "Your brain is about 2% of your body weight but uses roughly 20% of its energy.",
  "Wombats produce cube-shaped poop, which stops it rolling away and marks territory reliably.",
  "Lightning strikes the Empire State Building around 25 times per year.",
  "Hot water can freeze faster than cold under some conditions - the Mpemba effect is real but still debated.",
  "There are more trees on Earth than stars in the Milky Way - about 3 trillion versus 100-400 billion.",
  "A bolt of lightning is about five times hotter than the surface of the Sun.",
  "Scotland's national animal is the unicorn - a symbol of purity and power since the 12th century.",
  "The shortest war in history lasted 38 minutes - Britain vs Zanzibar, 1896.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "The total weight of ants on Earth once roughly equalled the total weight of humans; now ants have the edge again.",
  "Sloths can hold their breath longer than dolphins - up to 40 minutes by slowing their heart rate.",
  "A day on Mercury lasts about two Mercury years - slow spin, fast orbit.",
  "The first computer bug was an actual moth found inside Harvard's Mark II in 1947.",
  "Space smells like seared steak and hot metal, according to astronauts after spacewalks.",
  "Bananas are slightly radioactive - potassium-40 - but you'd need millions at once for danger.",
  "Cows have best friends and show measurable stress when separated.",
  "The Great Wall of China is not visible from the Moon with the naked eye.",
  "Venus is the hottest planet, not Mercury - its CO2 atmosphere traps heat at ~465°C.",
  "The Moon is drifting away from Earth at about 3.8 cm per year.",
  "Some metals are so reactive they explode on contact with water - like cesium.",
  "A teaspoonful of neutron star would weigh about 6 billion tonnes.",
  "Humans share about 60% of their DNA with bananas.",
  "The Pacific Ocean is shrinking slowly - roughly 2-3 cm per year as plates converge.",
  "Butterflies taste with their feet - sensors on their legs detect chemicals in leaves.",
  "The unicorn seaweed 'glass sponges' can live over 10,000 years - among Earth's oldest animals.",
  "Your stomach gets a new lining every 3-4 days, otherwise it would digest itself.",
  "One in 6,000 people has an extra rib called a cervical rib.",
  "The word 'robot' comes from the Czech 'robota', meaning forced labour.",
  "Earth's core is about as hot as the surface of the Sun - roughly 5,400°C.",
  "Whale songs can travel hundreds of kilometres through the ocean's sound channel.",
  "Paper can only be folded about 7-8 times regardless of size - thickness doubles each fold.",
  "The average person walks the equivalent of three times around the Earth in a lifetime.",
  "Saturn would float in water - its density is lower than water's.",
  "Some turtles can breathe through their rear ends while hibernating underwater.",
  "The Sahara used to be a green savannah with lakes - monsoon shifts changed it ~5,000 years ago.",
  "A shrimp's heart is in its head.",
  "There are more possible iterations of a Rubik's Cube (43 quintillion) than seconds since the Big Bang.",
  "Humans are bioluminescent - we emit visible light, just about 1,000 times too faint to see.",
  "The loudest animal on Earth is the sperm whale - its clicks can exceed 230 decibels underwater.",
  "Bamboo can grow nearly a metre in a single day.",
  "Rain contains vitamin B12 - produced by soil bacteria lifted into the atmosphere.",
  "The Antarctic ice sheet holds about 60% of Earth's fresh water.",
  "Bubble wrap was originally invented as textured wallpaper in 1957.",
  "An adult human body contains enough iron to make a nail about 5 cm long.",
];

/* ─── myths ─── */
export const MEGA_MYTHS: string[] = [
  "We use only 10% of our brains → Myth. Brain imaging shows virtually all regions are active over a day.",
  "Lightning never strikes the same place twice → Myth. Tall structures get hit repeatedly - the Empire State dozens of times a year.",
  "Goldfish have 3-second memories → Myth. They remember for months and can learn tricks.",
  "The Great Wall is visible from space with the naked eye → Myth. Astronauts confirm it's too narrow.",
  "Sugar makes children hyperactive → Myth in double-blind trials - parental expectation drives the perception.",
  "Hair and nails grow after death → Myth. Skin dehydrates and retracts, exposing more of what's already there.",
  "Bats are blind → Myth. Most species see well; many also echolocate.",
  "Dogs see only black and white → Myth. They see blues and yellows, just not reds and greens.",
  "You swallow 8 spiders a year in your sleep → Myth. Spiders avoid you; you're warm, noisy breathing and vibration.",
  "Cracking knuckles causes arthritis → Myth. Large studies found no arthritis link; the sound is gas cavitation.",
  "Vikings wore horned helmets → Myth. That's 19th-century opera costume design.",
  "Einstein failed maths → Myth. He mastered calculus by 15; the rumor misreads a grading-system change.",
  "Humans have five senses → Myth. Balance, temperature, proprioception and pain are distinct senses.",
  "The 5-second rule makes dropped food safe → Myth. Bacteria transfer near-instantly on contact; moisture matters more.",
  "Shaving makes hair grow back thicker → Myth. Blunt tips feel coarser; the follicle is unchanged.",
  "Money is the top source of divorce → Partly myth. Studies repeatedly find communication and contempt predict divorce more.",
  "Camels store water in their humps → Myth. Humps store fat; the water is spread through their blood and tissues.",
  "Bubble wrap pops keep you calm forever → True-ish. A small 1992 study found decreased fatigue and muscle tension. Enjoy responsibly.",
  "Glass is a slow-flowing liquid → Myth. Old windows are thicker at the bottom because of manufacturing, not flow.",
  "Reading in dim light ruins your eyes → Myth. It strains them temporarily but causes no lasting damage.",
  "Left-brained vs right-brained people → Myth. Both hemispheres cooperate in nearly everything; no personality split.",
  "Eating before swimming causes dangerous cramps → Myth. Mild and rare; the body easily handles it.",
  "You should wait 24 hours to report a missing person → Dangerous myth. Report immediately - the first hours matter most.",
  "Chemtrail conspiracies → Myth. Contrails are ice crystals; persistent ones reflect atmospheric humidity.",
  "Detox diets remove toxins → Myth. Your liver and kidneys already do this; commercial 'detox' has no proven mechanism.",
];

/* ─── brain teasers ─── */
export const MEGA_TEASERS: string[] = [
  "A bat and ball cost ₹1.10 together. The bat costs ₹1 more than the ball. Ball? → 5 paise. (Not 10 - that's the intuitive trap.)",
  "5 machines make 5 widgets in 5 minutes. How long do 100 machines take for 100 widgets? → 5 minutes.",
  "Lily pads double daily and fill the lake in 48 days. When is it half full? → Day 47.",
  "You have two ropes that each burn for exactly 60 min but unevenly. Measure 45 minutes. → Light rope A at both ends and rope B at one end. When A finishes (30 min), light B's other end (15 more).",
  "What comes once in a minute, twice in a moment, but never in a thousand years? → The letter M.",
  "A man looks at a painting and says 'brothers and sisters I have none, but that man's father is my father's son.' Who is in the painting? → His son.",
  "Three switches, one bulb upstairs. You may go up once. Identify the right switch. → Turn switch 1 on for 10 min, off; switch 2 on; go up. Lit = 2, warm-off = 1, cold-off = 3.",
  "Two coins add to 30 paise; one is not a 20-paise coin. What are they? → 20 and 10 - the other one is the 20.",
  "You're in a race and overtake second place. What place are you in? → Second. (Not first.)",
  "A farmer needs to cross a river with a wolf, a goat and cabbage; boat fits him + one. Wolf eats goat, goat eats cabbage. Order? → Goat over; back; wolf over, goat back; cabbage over; goat over.",
  "Which weighs more: a kilo of feathers or a kilo of steel? → Equal. The trap is units, not weight.",
  "A clock shows 3:15. What is the angle between the hands? → 7.5 degrees.",
  "I have keys but no locks, space but no rooms, and you can enter but not go in. What am I? → A keyboard.",
  "If you're running a race and you pass the person in last place, what place are you in? → This is impossible - you can't pass last place.",
  "Forward I am heavy, backward I am not. What am I? → The word 'ton'.",
  "What can travel around the world while staying in one corner? → A postage stamp.",
  "The more you take, the more you leave behind. What are they? → Footsteps.",
  "A woman has 7 daughters, each daughter has a brother. How many children? → 8 - the one brother is shared.",
  "What gets bigger the more you take away from it? → A hole.",
  "I speak without a mouth and hear without ears; I have no body but come alive with wind. What am I? → An echo.",
];

/* ─── life hacks ─── */
export const MEGA_HACKS: string[] = [
  "2-minute rule: if a task takes under two minutes, do it now. Deferral costs more than the task itself.",
  "Park your phone in another room while working - not face-down on the desk, another room. Focus measurably improves.",
  "Write tomorrow's first task tonight. Mornings start with momentum instead of decisions.",
  "Order your grocery list by the store's layout. It halves shopping time and kills most impulse buys.",
  "Automate savings on payday, not month-end. You can't spend money you never see.",
  "Keep a 'done list' alongside your to-do list. Visible progress is fuel for motivation.",
  "Charge your phone outside the bedroom. The first hour awake belongs to you, not notifications.",
  "Set two alarms: one to wake, one across the room to stand up. The second one works.",
  "Email triage in batches twice a day, never continuously. Constant inbox-checking fragments attention for hours.",
  "Prep gym clothes the night before. Removing friction beats adding willpower.",
  "Drink a full glass of water before every coffee. Fixes most afternoon headaches and crashes.",
  "Keep a 'waiting for' list: who owes you what, since when. Projects stop falling through cracks.",
  "Use timers, not willpower: 25 minutes on, 5 off. The timer makes the decision so you don't.",
  "Have one 'reset ritual' after work - change clothes, 10-minute walk, anything that signals the day is done.",
  "Batch-cook one protein and one carb on Sunday. Weeknight dinners drop to assembly, not cooking.",
  "Unsubscribe ruthlessly every Friday for 10 minutes. Inbox zero without discipline.",
  "Say no with: 'I can't take this on right now.' No apology, no essay, no false reasons.",
  "Put books you want to read face-out on a shelf you pass daily. Environment beats intention.",
  "Do the worst task first ('eat the frog'). Everything after feels lighter for the rest of the day.",
  "Set a monthly money-review date - 30 minutes with your statements. Wealth is mostly attention.",
  "Keep a water bottle on your desk. Visible water gets drunk; invisible water doesn't.",
  "Schedule worry time: 15 minutes to think about anxieties deliberately, then closed for the day.",
  "Use the 'one-touch' rule for paper and messages: handle each once - act, file or bin.",
  "Break big projects into 'next physical actions', not goals. 'Draft intro paragraph' beats 'write thesis'.",
  "Learn keyboard shortcuts for the 5 apps you use most. Ten minutes now, hours saved over a year.",
  "Meal-plan around 5 rotating dinners. Decision fatigue at 6pm is real and expensive.",
  "Turn all phone badges off. Badges are other people's priorities wearing your battery.",
  "Walk during phone calls. Ideas move when legs move - and you hit your step count.",
  "Keep a 'small wins' note. On bad days, evidence beats self-talk.",
  "Set calendar 'focus blocks' as busy. If it's not on the calendar, it's not real.",
  "The 10-minute declutter: set a timer, clear one surface, stop when it rings. Sustainable minimalism.",
  "Read 10 pages a day - that's 12+ books a year with zero lifestyle change.",
  "Pre-decide breakfast and lunch for weekdays. Save decision quality for things that matter.",
  "Keep a default 'no' until excitement is proven. Enthusiasm inflates; calendars confirm.",
  "Text a friend once a week just to share something good. Relationships die of silence, not conflict.",
  "Double the vegetables, halve the portion of everything else. Easiest nutrition upgrade there is.",
  "When angry, write the email but wait an hour before sending. You'll edit 90% of them.",
  "Two-minute tidy before bed. Waking to a clean room changes the whole morning's tone.",
  "Use cash for discretionary spending - the pain of payment is a feature, not a bug.",
  "Replace 'I have to' with 'I get to' for one week. Reframing is free medicine.",
];

/* ─── impulse brakes ─── */
export const MEGA_BRAKES: string[] = [
  "The 30-day list: want it? Add it with today's date. Buy only if the want survives 30 days.",
  "Cost in hours: divide the price by your hourly rate. 'That's 9 hours of my life' hits differently.",
  "The cart test: leave it in the cart overnight. Most urges die quietly by morning.",
  "One-in-one-out for clothes, gadgets and gear. New item in, old item out, no exceptions.",
  "Would I buy this again at full price if I already owned it? If no, skip the purchase.",
  "Per-use maths: ₹12,000 jacket worn 200 times is ₹60/wear. ₹1,200 jacket worn twice is ₹600/wear.",
  "The friend test: 'Would you tell me to buy this?' Send a photo. Let someone else be your prefrontal cortex.",
  "Payment friction: delete saved cards from shopping apps. Re-entering card details is a speed bump that works.",
  "The 24-hour rule for anything over ₹5,000. No exceptions. Especially not 'the sale ends tonight'.",
  "Ask: am I buying this for the life I have, or the life I imagine having on Sunday evenings?",
  "Unsubscribe from marketing emails. If the deal is real, you'll hear about it anyway.",
  "Sleep on every 'limited time' offer. Manufactured urgency is a sales tactic, not information.",
  "Convert the price to your daily earnings. A ₹3,000 impulse is a full day of work for many people.",
  "Screenshot the wishlist instead of buying. Half the time you never open the screenshot again.",
  "Delete shopping apps during sale weeks. The app is the casino; the browser is the exit.",
  "Set a monthly 'fun budget' in cash. When the envelope is empty, the fun is done - guilt-free.",
  "Ask: does this solve a problem I have, or one I saw in an ad ten minutes ago?",
  "Track your 'return rate' honestly. If you return a third of what you buy, you're a warehouse with feelings.",
  "The cost-per-day test for gadgets: ₹8,000 earbuds used daily for 2 years is ₹11/day. Fair. Used weekly, it's ₹77/day. Not fair.",
  "Watch the unboxing urge: the happiest moment of most purchases is the 10 minutes after delivery. Optimise for ownership, not arrival.",
  "Before checkout, name the last three things you bought in this category. Can't remember? You didn't need those either.",
  "Use a 48-hour rule for all 'influencer made me' purchases. The link will still be there; the trance won't.",
  "Cancel one subscription every payday. Most households carry 3 they forgot about.",
  "The child test: would you hand a kid ₹2,000 to spend on this? If it feels absurd, that's your wisdom talking.",
  "Keep a 'didn't buy' running total of money saved. Seeing ₹14,000 banked is better than any dopamine parcel.",
  "Wait for the item to be boring. If you still want it when it's no longer exciting, it's a need.",
  "Round up every want to the 'with tax and shipping' number. The true price is always the second number.",
];

/* ─── discount stack order ─── */
export const MEGA_STACK: string[] = [
  "1. Base sale price first - never stack anything on the inflated 'MRP'. Verify the pre-sale price with a price tracker.",
  "2. Bank/card offer second - usually the single biggest cut. Check the card portal before checkout.",
  "3. Coupon code third - search '[site] coupon [month]' before paying. Cashback sites often have exclusives.",
  "4. Wallet cashback last - and only count it if you'd shop there anyway. Points aren't money until spent.",
  "5. Exchange/buy-back offers - take them only after checking the item's resale value yourself.",
  "Why order matters: percentage offers apply to the running total. Biggest percentage first = smaller base for the rest.",
  "EMI 'no cost' offers: the discount is often just the interest renamed. Compare against the cash price, always.",
  "Warranty extension at checkout: usually the worst value in retail. Card warranties often already cover it.",
  "Cashback portals after card offers: activate the portal session first, then pay with the offer card. Order matters.",
  "Festive bank sales stack with existing offers - plan big buys for sale calendars, not whims.",
  "Student discounts never expire quietly: most brands keep them forever with a college ID or .edu email.",
  "Corporate benefit portals hide the best codes - check yours before any electronics purchase.",
  "Price-tracking tools beat vigilance: set an alert at your target price and let the robot wait.",
  "Coupon-browser extensions: use one, but watch it at checkout - some quietly pick affiliate codes that cost you the bank offer.",
  "Open-box and display units from brand stores: 15-30% off with full warranty if you inspect before paying.",
  "Exchange offers: negotiate the new-device price FIRST, then mention the exchange. Mention it early and it's baked in against you.",
  "Gift cards from resale platforms at 5-10% off are free money on purchases you already planned.",
  "Referral credits before sales: stock up your own account and your family's - then spend during the sale window.",
  "The 3-price rule: never buy without checking the same item on at least three platforms. The spread is often 20%.",
  "Cashback credit cards work only if you'd buy the thing anyway. The card is a discount, never a reason.",
  "Timing electronics: buy phones right after the successor launches; buy laptops before the fiscal-year end.",
  "Insurance from the retailer is almost always resold brand insurance. Buy directly and it's cheaper.",
  "Bundle check: sometimes the 'bundle' with case+charger costs more than buying each separately. Do the maths at checkout, every time.",
];

/* ─── safe sale steps ─── */
export const MEGA_SAFE_SALE: string[] = [
  "Meet in public, in daylight, ideally somewhere with CCTV - many metro and police stations have 'exchange spots'.",
  "Cash or instant UPI, confirmed on YOUR screen before you hand anything over. Screenshots aren't confirmation.",
  "For phones: remove all accounts and factory-reset in front of the buyer. Locked phones are bricks; honest sellers show this.",
  "Share your live location with someone for the meetup, and set a check-in text afterwards.",
  "If the buyer rushes you, changes the venue, or 'sends' overpayment, walk away. There is always another buyer.",
  "Photograph the item and its serial number before the meetup. Protects you in any dispute.",
  "Never ship before payment clears - no exceptions, not even for 'my cousin will pick it up later'.",
  "Price with 15% negotiating room. Marketplace culture expects a haggle; feel free to enjoy it.",
  "Video-call verification for high-value items: ask the seller to show the item live, powered on, with today's date written on paper.",
  "For laptops: boot into BIOS and check cycle count, battery health and total hours before paying anything.",
  "For bikes and cars: verify the service book, chassis number match, and pending challans before the test ride.",
  "Never share an OTP - not for 'verification', not for 'payment confirmation'. No legitimate buyer needs it.",
  "Beware 'army officer transferred to your city' stories - it's the oldest marketplace scam script and still works on smart people.",
  "For furniture: check for bedbugs along seams and screw holes. One infested sofa can cost more than it sold for.",
  "Bring your own tester: a charging cable for phones, a USB stick for laptops, a tape measure for furniture.",
  "Mark payment as 'goods purchase' in UPI notes. It creates a clean trail if things go sideways.",
  "Don't carry the full cash amount to first meetings. Deposit a token amount to hold, settle the rest at handover.",
  "Bill/invoice matters for warranty transfer: ask for the original purchase invoice, not a photocopy.",
  "Check stolen-goods registers for phones via the IMEI before buying second-hand. Thirty seconds, huge relief.",
  "For cameras: count shutter actuations, inspect sensor for dust at smallest aperture, test all dial positions.",
  "Season timing sells: list winter gear in October, fans and coolers in March. Off-season buyers negotiate hard.",
  "Reply speed is trust: responding within an hour signals a serious seller and doubles close rates.",
  "If a deal feels 40% too good, it is. The anxiety you feel checking the listing twice is data.",
];

/* ─── first visit checklists ─── */
export const MEGA_FIRST_VISIT: string[] = [
  "New city: locate the 24-hour pharmacy, the best coffee within a 10-minute walk, and the cheapest reliable transport. Those three fix 80% of problems.",
  "New gym: visit at your planned workout time before joining. The 6 pm crowd can quietly kill a membership.",
  "New cafe for work: check outlets, wifi speed (fast.com), and whether staff mind laptops. Five minutes of checking saves weeks.",
  "New barber or salon: book the cheapest service first - a trim, not a full cut. Low-risk test of their skill.",
  "New landlord: photograph everything on day one, check water pressure and mobile signal in every room, test the geyser.",
  "New doctor: check credentials and whether they explain reasoning, not just prescriptions. You're hiring them.",
  "New phone: set up 'find my device', remove bloatware, and turn off notification badges before installing anything fun.",
  "New job: write down what success looks like in 90 days, from your manager's mouth, in their words. Revisit monthly.",
  "New city: join two groups that meet in person - one for your work, one for your body. Both keep loneliness away.",
  "New neighbourhood: walk a 15-minute radius on your first weekend. You'll use those discoveries for years.",
  "New phone: check camera, speaker and microphone in the store BEFORE leaving the counter. Returns get harder after day one.",
  "New laptop: update firmware and calibrate the battery on day one; most 'battery issues' are never calibrated.",
  "New house: locate the main water valve and the electrical panel in week one. Emergencies don't wait for exploration.",
  "New school/college: find the one person who knows the systems - the office assistant, not the principal.",
  "New restaurant: order their most-ordered dish first visit. Judge the kitchen at its strength before experimenting.",
  "New hobby: rent or borrow gear for the first month. Passion confirmed, then invest.",
  "New bank: check the nearest ATM and the app's rating before moving your salary. Convenience is the real product.",
  "New project: write down the definition of 'done' before writing anything else. Scope creep enters through vague endings.",
  "New client: get the payment terms in the first email, not the last invoice. Early awkwardness prevents late desperation.",
  "New roommate: agree on dishes, guests and noise in week one. Every flat war traces back to unstated defaults.",
  "New manager: ask how they prefer updates - message, doc or meeting. Matching their style fast-tracks trust.",
  "New gym routine: two weeks of half-effort before any full send. Consistency first, intensity second.",
  "New medication: set alarms for the first two weeks until it becomes a meal-linked habit.",
];

/* ─── community roles ─── */
export const MEGA_ROLES: string[] = [
  "The Connector - introduces people to each other. Every community needs one or two; they're the glue.",
  "The Notary - remembers what was decided and writes it down. Future members will thank them.",
  "The Spark - starts things, doesn't finish them. Pair them with a Finisher and magic happens.",
  "The Finisher - takes half-done things across the line. Rarer than Sparks, more valuable at scale.",
  "The Welcomer - talks to the new person first. Communities live or die by this person.",
  "The Historian - knows why things are the way they are. Prevents re-litigating old decisions.",
  "The Mediator - absorbs heat in conflicts and finds the shared interest underneath the positions.",
  "The Merchant - handles money, sponsorships, logistics. Underappreciated until they leave.",
  "The Critic - asks the uncomfortable question early. Painful now, cheaper later.",
  "The Bridge - connects your community to other communities. Growth rarely comes from inside.",
  "The Curator - filters the flood into a weekly 'worth your time' list. Attention is the community's scarcest asset.",
  "The Mentor - takes the newest member under their wing. One mentor relationship raises retention dramatically.",
  "The Energiser - shows up when attendance dips. Morale is a renewable resource only if someone renews it.",
  "The Standards-Keeper - gently enforces the culture. Every community decays without one.",
  "The Newbie - asks the questions experts forgot they had. Protect them; they keep the content accessible.",
  "The Operator - runs the boring logistics: rooms, links, reminders. Communities run on their quiet labour.",
  "The Rival - friendly competition keeps skill communities sharp. Rivalry with respect is fuel.",
  "The Storyteller - turns member wins into narratives. Stories recruit; feature lists don't.",
  "The Gardener - deletes, merges and tidies without being asked. Entropy is the default state of every group.",
  "The Sponsor - brings resources and asks for nothing. Protect them from becoming the community's ATM.",
  "The Ghost - lurks for months, then contributes brilliantly. Never shame the quiet; they're the majority.",
];

/* ─── how-to guides ─── */
export const MEGA_HOW_TO: string[] = [
  "Credit score: pay in full before the due date, keep utilisation under 30%, never close old cards. That's 80% of it.",
  "Jump a car battery: red to dead, red to donor, black to donor, black to unpainted metal on the dead car. In that order.",
  "Unclog a sink without chemicals: baking soda + vinegar, wait 15 minutes, flush with boiling water. Twice if needed.",
  "Negotiate rent: offer a 12-month commitment and immediate move-in for a lower rate. Landlords value certainty over theory.",
  "Iron a shirt properly: collar first, cuffs, shoulders, then body. Damp fabric, low heat for synthetics.",
  "Apologise properly: name what you did, no 'but', state the fix. Three sentences, done.",
  "Write a complaint that works: facts, dates, what you want, deadline. Politeness optional; specifics mandatory.",
  "Change a tyre: loosen nuts BEFORE jacking up, jack at the reinforced point, tighten in a star pattern after lowering.",
  "Read a contract: last pages first (signatures, terms), then money clauses, then termination clauses. Those are where it bites.",
  "Store fresh herbs: trim stems, jar with water like flowers, loose plastic bag on top, fridge. Lasts 2-3× longer.",
  "Stop a minor bleed: direct pressure with a clean cloth for 10 minutes without peeking. Elevation helps. Peeking doesn't.",
  "Draft an email that gets replies: one subject per email, the ask in the first two lines, deadline included.",
  "Take a passport photo that lasts: plain background, day light from the front, no shadow, neutral face, no glasses.",
  "Prepare for an interview in 30 minutes: read their last 3 news items, rehearse 2 stories with numbers, prepare 3 questions.",
  "Shine shoes without polish: banana peel rubbed in, buffed with a cloth. Emergency-only, genuinely works.",
  "Cancel any subscription: try the chat bot first, then 'cancel subscription' verbatim, then card-block as the nuclear option.",
  "Remove stains: cold water for blood, warm for sweat, salt water for red wine, and never hot water on protein stains.",
  "Pack for 10 days in carry-on: 5 tops, 2 bottoms, 2 shoes, 1 jacket, all in one colour family. Laundry on day 5.",
];

/* ─── thinking prompts ─── */
export const MEGA_PROMPTS: string[] = [
  "What would you do this year if you knew nobody would judge the result?",
  "Which 'someday' goal have you postponed for over two years - and what is the real reason?",
  "What do you believe that you'd struggle to defend to a smart 15-year-old?",
  "If your current pace continued for five years, where would you end up? Is that okay?",
  "What are you optimising for right now - and did you choose that, or did it choose you?",
  "What conversation are you avoiding that a five-minute version of would dissolve?",
  "Which of your daily habits would your 80-year-old self pay you to keep?",
  "What's the smallest version of your big goal that you could finish this month?",
  "Where in your life are you confusing comfort with happiness?",
  "If money were solved, what would you do on a Tuesday? What's stopping you from doing a little of it now?",
  "What skill would make everything else you're doing easier? Why aren't you learning it first?",
  "Who do you envy, and what does that envy actually point at?",
  "What are you tolerating right now that you could fix in under an hour?",
  "If you had to cut one commitment from your life this week, which would hurt least? Then why keep it?",
  "What advice would you give someone exactly where you were five years ago?",
  "Which belief about yourself is just a repeated thought wearing a lab coat?",
  "What's the most useful thing you could learn from the person you disagree with most?",
  "What would you attempt if you knew you could handle the embarrassment of failing publicly?",
  "Where are you currently spending money to solve a problem that fewer habits would solve free?",
  "What does 'enough' look like in your biggest goal - and will you notice when you get there?",
];

/* ─── jokes ─── */
export const MEGA_JOKES: string[] = [
  "Why don't scientists trust atoms? → Because they make up everything.",
  "I told my computer I needed a break → It said 'no problem, I'll go to sleep.'",
  "Why did the scarecrow win an award? → He was outstanding in his field.",
  "Parallel lines have so much in common → It's a shame they'll never meet.",
  "I'm reading a book about anti-gravity → Impossible to put down.",
  "Why did the bicycle fall over? → It was two-tired.",
  "What do you call a fake noodle? → An impasta.",
  "Why don't eggs tell jokes? → They'd crack each other up.",
  "I used to hate facial hair → Then it grew on me.",
  "What do you call a bear with no teeth? → A gummy bear.",
  "Why did the math book look sad? → Too many problems.",
  "What do you call cheese that isn't yours? → Nacho cheese.",
  "Why can't you give Elsa a balloon? → Because she'll let it go.",
  "What does a clock do when it's hungry? → It goes back four seconds.",
  "I have a fear of speed bumps → I'm slowly getting over it.",
  "Why did the golfer bring two pairs of pants? → In case he got a hole in one.",
  "What did the ocean say to the beach? → Nothing, it just waved.",
  "Why do we tell actors to 'break a leg'? → Because every play has a cast.",
  "What's brown and sticky? → A stick.",
  "Why did the coffee file a police report? → It got mugged.",
  "How does a penguin build its house? → Igloos it together.",
  "What do you call a sleeping bull? → A bulldozer.",
  "Why are ghosts bad liars? → You can see right through them.",
  "I ordered a chicken and an egg online → I'll let you know.",
  "What did the janitor say when he jumped out of the closet? → 'Supplies!'",
  "Why did the cookie go to the hospital? → It was feeling crummy.",
  "What's orange and sounds like a parrot? → A carrot.",
  "Why can't your nose be 12 inches long? → Because then it would be a foot.",
  "What do you call a fish without eyes? → A fsh.",
  "Why did the stadium get so hot? → All the fans left.",
];

/* ─── tongue twisters ─── */
export const MEGA_TWISTERS: string[] = [
  "Red lorry, yellow lorry, red lorry, yellow lorry.",
  "She sells sea shells by the sea shore - the shells she sells are surely seashells.",
  "Peter Piper picked a peck of pickled peppers; a peck of pickled peppers Peter Piper picked.",
  "The sixth sick sheikh's sixth sheep's sick.",
  "Toy boat, toy boat, toy boat (try saying it fast five times).",
  "Irish wristwatch, Irish wristwatch, Irish wristwatch.",
  "Unique New York, unique New York, you know you need unique New York.",
  "Pad kid poured curd pulled cod (MIT's hardest twister).",
  "Imagine an imaginary menagerie manager imagining managing an imaginary menagerie.",
  "Six slippery snails slid silently seaward.",
  "A proper copper coffee pot.",
  "Fresh French fried fly fritters.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses and bludgeons.",
  "Three thin thieves thought a thousand thoughts.",
  "Which wristwatches are Swiss wristwatches?",
];

/* ─── search operators ─── */
export const MEGA_OPERATORS: string[] = [
  '"exact phrase" — forces the exact wording in results',
  'site:reddit.com — restrict results to one site',
  '-word — exclude a word from all results',
  "filetype:pdf — find documents, presentations, templates",
  "OR — combine alternatives: 'react OR vue'",
  "before:2020 — only older content",
  "after:2023 — only fresh content",
  "intitle:review — the word must appear in the page title",
  "inurl:guide — the word must appear in the URL",
  "related:site.com — find similar sites",
  "cache:site.com — see Google's last snapshot",
  '"*' + '" wildcard — fill in the blank: \"how to * in Python\"',
  "numrange: 10..50 — number ranges: 'laptop ₹40,000..60,000'",
  "allintext: — all words must appear in the body text",
  "site:*.edu — any educational domain",
];

/* ─── scale facts (gallery) ─── */
export const MEGA_SCALE: { title: string; desc: string }[] = [
  { title: "8,000,000,000", desc: "humans alive right now — you could give each one a unique 33-bit ID" },
  { title: "4,000,000 tonnes", desc: "of mass the Sun fuses into energy every single second" },
  { title: "1.4 billion", desc: "photos are taken globally per day — about 16,000 every second" },
  { title: "95%", desc: "of the ocean remains unmapped and unexplored in detail" },
  { title: "100,000 miles", desc: "of blood vessels inside one human body — 4× around the Earth" },
  { title: "43 quintillion", desc: "possible Rubik's Cube positions — more than grains of sand on Earth" },
  { title: "300 billion", desc: "stars in the Milky Way, and 2 trillion galaxies observable" },
  { title: "0.0000001%", desc: "of the universe's volume is occupied by ordinary matter" },
];

/* ─── presence drill ─── */
export const MEGA_PRESENCE: string[] = [
  "Eye contact for the length of one full sentence. Practise on baristas - low stakes, high reps.",
  "Slow your speech by 10%. Rushed speech reads as nervous; measured reads as confident.",
  "Keep hands visible and calm. Pockets and fidgeting leak anxiety you didn't consent to leaking.",
  "Pause two full seconds before answering any question. It reads as thought, not delay.",
  "Stand still while talking. Pacing is for podcasts; grounded presence is for rooms.",
  "Say their name once in the first minute and once when leaving. People remember how you said their name.",
  "Ask one question per conversation that has nothing to do with work or the weather.",
  "Breathe out longer than you breathe in before entering any room. Four counts in, six out. Nervous system resets.",
  "Arrive two minutes early to every meeting. Calm arrival changes the tone of your first sentence.",
  "Remember one detail from the last conversation and open with it. 'How did the marathon go?' builds more than small talk.",
  "Put your phone away during the entire conversation - not face-down, away. Divided attention is visible attention.",
  "Match their energy for the first minute: fast with fast, calm with calm. Then lead where you want the room to go.",
  "Learn one genuine compliment per person and deliver it specifically. 'Your budget doc saved us a week' lands; 'you're great' floats.",
  "Sit at the corner of the table rather than opposite. Corner = collaborator; opposite = opponent. Bodies read geometry.",
  "Practise the pause mid-sentence for emphasis. Rushed speakers are forgettable; deliberate ones are quoted.",
  "Dress one notch above the room's average. Respect shown through fabric is still respect.",
  "When challenged, slow down instead of speeding up. Defensiveness accelerates; confidence is unhurried.",
  "Leave conversations before you run out of things to say. Ending on a high note is how 'great to talk to' reputations form.",
  "Follow up within 48 hours with one useful thing - a link, a name, a file. Generosity is memorable currency.",
];

/* ─── community/event data ─── */
export const MEGA_ICEBREAKERS: string[] = [
  "What's the best thing you've watched, read or played this month - and why should we care?",
  "What's a skill you have that would surprise everyone here?",
  "What's the most useless talent you're secretly proud of?",
  "What did you want to be at age 8, and what happened to that dream?",
  "What's the best purchase you've ever made under ₹1,000?",
  "If you could instantly master one skill, what would you do with it first?",
  "What's a hill you'd die on that doesn't matter at all?",
  "What's the most interesting place you've ever been that nobody talks about?",
  "What app or tool do you use that feels like a cheat code?",
  "What's something you believed for way too long?",
  "What's the most useful thing you own that costs less than ₹500?",
  "What's a food combo you defend that everyone around you doubts?",
  "What's the last thing you changed your mind about - and what did it?",
  "What's your most controversial opinion about something extremely minor?",
  "What hobby would you try if money and time were no object?",
  "What's the weirdest job you've ever had or applied for?",
  "Which app on your phone has your highest screen time, and are you proud?",
  "What's the best advice you've received that sounded stupid at first?",
  "What's something everyone seems to love that you just don't get?",
  "What's a small thing that instantly improves your mood?",
  "If your week had a fifth weekend day, what would you do with it?",
  "What's the kindest thing a stranger has done for you?",
  "What song takes you straight back to being 16?",
  "What's your 'I know more about this than most people' niche?",
  "What's the worst haircut you've ever had? Details mandatory.",
];

export const MEGA_COMMUNITY_TIPS: string[] = [
  "Start meetings exactly on time. Respects the punctual and trains the rest within three weeks.",
  "One-round intros: name plus one sentence. No life stories; the meeting is the point.",
  "Every event needs a visible countdown for the main activity. Drift is the enemy of good rooms.",
  "End with decisions and next steps, then social time. Hard stop at the hour. People respect clarity.",
  "Name a Welcomer explicitly. The new person's second visit depends entirely on their first five minutes.",
  "Rotate facilitation. Ownership is contagious; spectators are made, not born.",
  "Keep a shared decisions log. Future you will not remember why the group chose the blue one.",
  "Feed people. Attendance doubles. This is the most reliable finding in community management.",
  "Set the norm in the first message: what this group is, what it isn't, and who it's for. Norms formed in week one never need enforcing.",
  "Celebrate small wins publicly and specifically. A screenshot of a member's first sale does more than any announcement.",
  "Reply to every first-time poster within hours. The first interaction decides whether there's a second one.",
  "Keep one channel strictly off-topic. The meme room is where the real community bonds.",
  "Run a recurring ritual - monthly demo day, Friday wins thread. Rituals are the skeleton of belonging.",
  "Ask for help publicly as a leader. Leaders who ask give everyone else permission to ask.",
  "Archive ruthlessly. A channel list longer than a hand's fingers is a graveyard, not a workspace.",
  "When conflict flares, take it to DM within one exchange. Public spirals recruit spectators, and spectators pick sides.",
  "Survey the quiet 80% twice a year. The loudest members are not the average member.",
  "Document the 'why' behind every rule. Rules with reasons survive leadership changes.",
  "Never scale past what you can moderate. A spam-filled large community is worth less than a lively small one.",
  "Invite guests who have nothing to sell. Fresh expertise with no pitch is a gift members remember.",
  "End every event with one clear next step. Momentum dies in the gap between 'great session' and 'so what now?'",
  "Track one number only: returning members. Growth without return is a leaky bucket with better marketing.",
];

/* ─── gadget/tech lists ─── */
export const MEGA_DESK_TIPS: string[] = [
  "Chair first, always. 40% of budget on the chair is not crazy - your spine is the main display.",
  "Monitor at arm's length, top edge at eye height. Free ergonomics upgrade worth more than any gadget.",
  "One good desk lamp beats every RGB strip combined. Light for work, dim for mood.",
  "Cable trays underneath the desk change how your workspace feels. ₹300, transformative.",
  "Keyboard before mouse, by a wide margin. You touch the keyboard 10× more.",
  "A second monitor helps most for reading-while-writing work. It doesn't help focus work - one big screen can be better.",
  "A footrest fixes chairs that are slightly too tall. Underpriced, underrated.",
  "Plants don't clean your air (that study was about sealed chambers) but they do make you want to be at the desk.",
  "Mechanical keyboard boards are fun but test the sound in person first. Your open-plan neighbours will thank you.",
  "Get a laptop stand plus external keyboard. Your neck undoes a decade of hunching within a month.",
  "A ₹200 door draft stopper beats most room heaters for 'feels warmer'. Physics before purchases.",
  "One drawer for daily carry: keys, wallet, charger, earphones. Searching for these daily costs hours a year.",
  "Warm light (2700K) after sunset, cool light (5000K) during work. Same room, two different brains.",
  "A whiteboard on the wall outperforms three productivity apps. Visible tasks get done.",
  "Cable labels at both ends. Future-you during the next gadget swap will beam with gratitude.",
  "Keep a microfibre cloth taped under the desk edge. Smudged screens make everything look worse than it is.",
  "The pen test: buy pens in bulk, keep one everywhere. Small friction removed adds up to a functioning life.",
  "Invest in one great chair mat if you have wheels on carpet. Quietly eliminates most 'my back hurts'.",
];

export const MEGA_GADGET_RULES: string[] = [
  "Buy last year's flagship over this year's midrange. Usually cheaper, always better hardware.",
  "Battery health beats capacity: check cycles count on used phones before anything else.",
  "If the brand doesn't publish repairability info, assume it's bad. Your future self pays for today's convenience.",
  "Wait 72 hours after any keynote. Prices of previous models always fall; hype always peaks.",
  "Read 3-star reviews - they're the most honest. 1-star is rage, 5-star is honeymoon, 3-star is lived-in truth.",
  "Compatibility is the real spec. The best gadget that doesn't fit your ecosystem is a drawer ornament.",
  "Refurbished from the manufacturer usually beats new midrange - full warranty, half the price, better parts.",
  "Accessories are where brands make margin. Third-party chargers and cases are usually 80% as good for 30% of the price.",
  "The 10-10-10 rule for smart devices: would I still want this in 10 days, 10 months, 10 years? Most smart gadgets fail month two.",
  "Never buy storage tiers at launch prices for cloud services - annual plans discounted during sales are the actual price.",
  "Repair before replace: screen and battery replacements cost a tenth of new. The upgrade urge peaks at month 20; wait for month 30.",
  "Check the teardown video before buying anything you'll keep for years. If it needs heat-gun surgery to open, assume repair is impossible.",
  "Dongle reality check: count the ports you need, then add one. The hub you buy in month two is never the good one.",
  "Water resistance ratings (IP67/68) cover fresh water only. One pool dunk voids most warranties regardless.",
  "Firmware support length is the real phone spec. Five years of updates beats a faster chip you'll never notice.",
  "Watches and bands: sensor accuracy matters less than whether you'll wear it while sleeping. Comfort wins the data game.",
  "Earbuds: fit beats frequency response. The best-sounding buds are useless if they fall out on the second step.",
  "Power banks: check the rated capacity, not the marketing one. A 20,000mAh bank realistically delivers ~12,000mAh.",
  "Router placement beats router price. Central, elevated, away from metal - free speed for the whole flat.",
  "Backups: one local, one cloud, one offline rotated monthly. The backup you test is the only backup you have.",
  "The 'it works with everything' trap: proprietary ecosystems age badly. Prefer USB-C, Bluetooth standard and Matter.",
  "Camera bumps and cases: a ₹400 case preserves ₹40,000 of resale value. The maths is not close.",
];

/* ─── exam/study ─── */
export const MEGA_STUDY: string[] = [
  "Active recall beats rereading every time. Close the book and write what you remember first.",
  "Spaced repetition: review at day 1, 3, 7, 21. Four short sessions beat one long one.",
  "Interleave topics in one session (A, B, C, A). It feels worse and works better - trust the research.",
  "Teach it to an imaginary student. If you can't simplify it, you haven't learned it yet.",
  "Practice tests are the highest-yield study activity ever measured. Do them early, not just before the exam.",
  "Sleep is study time - memory consolidation happens then. All-nighters actively erase the day's work.",
  "Handwrite the hardest concepts once. Slower processing forces real understanding.",
  "Study the same subject at the same time daily. The cue itself starts focus.",
  "Past papers first, textbook second. The exam's shape teaches you what matters.",
  "Feynman technique: explain it in plain language, find the gap, go back to the source for just that gap.",
  "Change study locations between subjects. Context variety strengthens retrieval cues.",
  "Timer on, phone in another room, water on desk. Environment first, discipline second.",
  "Do the hardest subject when you're freshest, usually the first 90 minutes after waking.",
  "Make a 'confusion list' while studying instead of stopping. Clear all doubts in one batch later.",
  "End every session by writing tomorrow's first task. Starting is the hard part; pre-decide it.",
  "Blurting: dump everything you know on paper before checking notes. The gaps you find ARE the syllabus.",
  "Study the confusing thing at hour two of the session, not hour one - warm brains handle abstract better.",
  "Use the 3-pass method for dense texts: skim for structure, read for understanding, then re-read only the marked parts.",
  "Convert notes to questions immediately. Notes say 'mitochondria = powerhouse'; questions ask 'why does size correlate with energy need?'",
  "Two-minute rule for flashcards: if you can't answer in two minutes, the card is too big. Split it.",
  "Sleep within 3 hours of learning something new. Napping on new material measurably boosts retention.",
  "Study groups: form them for teaching, not for studying. Explaining is studying; co-reading is chatting.",
  "Error journals: keep a log of every mistake on practice tests. Patterns in your errors beat patterns in the syllabus.",
  "The 80/20 of any subject: 20% of the topics carry 80% of the marks. Find the weighting map before opening chapter one.",
  "Walking recitation: recite definitions while walking. Movement anchors memory better than desk repetition.",
  "Phone rules that actually work: airplane mode + app blockers + phone in a drawer. Screen-down on the desk is a myth of control.",
  "Do weekly reviews on Sunday: what stuck, what faded, what's next. 15 minutes prevents 2 weeks of drift.",
  "Practice under exam conditions once a week. Time pressure is a skill separate from knowledge.",
  "Reward sessions, not outcomes: after each focused block, take a real break - walk, snack, stretch. Scroll breaks don't restore attention.",
];

/* ─── interview/salary ─── */
export const MEGA_INTERVIEW_Q: string[] = [
  "Walk me through your background as it relates to this role → present role, two relevant wins with numbers, why here.",
  "Tell me about the hardest problem you've solved → STAR: Situation, Task, Action, Result. Numbers mandatory.",
  "Why are you leaving your current role? → growth-toward, never escape-from. One sentence, then pivot forward.",
  "What's your biggest weakness? → real weakness, real mitigation. 'I'm a perfectionist' ends interviews.",
  "Where do you see yourself in five years? → skill trajectory, not titles. Interviewers want direction, not ambition theatre.",
  "Tell me about a conflict with a colleague → facts, your part in it, what you'd do differently. No blame, no villains.",
  "Why this company? → two specific things about them, connected to what you want to learn next.",
  "Tell me about a failure → choose a real one, show the lesson, show the change in behaviour since.",
  "How do you handle deadlines? → one system (prioritisation, communication) plus one concrete example.",
  "Do you have any questions for us? → ask about success metrics, team challenges, growth. 'No' is a red flag to them.",
  "Tell me about a time you failed → pick a failure with a real cost, own your decision in it, then show the system you built so it never repeats.",
  "What motivates you? → tie motivation to the actual work, not to perks. 'Shipping things users touch' beats 'good vibes and snacks'.",
  "How do you prioritise when everything is urgent? → show a framework (impact × effort, stakeholder cost) plus one war story.",
  "Describe your ideal work environment → answer honestly but name behaviours, not perks: 'written-first, few meetings' is information; 'free snacks' is noise.",
  "Why should we hire you? → one sentence: your strongest relevant win + the specific need they mentioned. No speeches.",
  "What are your salary expectations? → deflect once gracefully, then give a researched range if pressed. Research beats hope.",
  "Tell me about a time you disagreed with your manager → focus on how you disagreed respectfully, the data you brought, and the outcome either way.",
  "How do you handle feedback? → give an example of feedback you acted on and what changed. Defensiveness in the story is disqualifying.",
  "What do you do outside work? → pick something with evidence of passion - depth in one thing beats a list of ten.",
  "Have you applied elsewhere? → be honest but focused: 'a couple of conversations, but this role is my first priority because of X'.",
  "What's your biggest professional achievement? → the one with a number attached and a before/after. Rehearse it to 60 seconds.",
];

export const MEGA_SALARY_TIPS: string[] = [
  "Never give the first number. 'What range is budgeted for this role?' is a complete, professional answer.",
  "If pressed for a number, give a researched range with your floor at the bottom - never a single point.",
  "Research three anchors: local market data, company's pay band if known, your current total comp.",
  "Never negotiate against yourself. If they counter low, repeat your range with one new reason, then stop talking.",
  "Total comp > base: bonus structure, insurance, learning budget, remote policy all have rupee value.",
  "Get every verbal promise in writing before signing. Kindness and paperwork are not opposites.",
  "The best time to negotiate is at offer stage, not after. The second-best time is at your annual review with evidence.",
  "Silence after a number is a tool. Most people fill it and concede. Practise holding four seconds of quiet.",
  "Anchor with market data, not need: 'market rate for this scope in this city is X-Y'. Needs invite sympathy, data invites respect.",
  "Negotiate scope before salary when salary is capped: sign-on bonus, review at 6 months, title, or remote days all have value.",
  "The 'range collapse' move: if they give a wide band, ask 'what determines placement within that band?' - then answer exactly that.",
  "Practise out loud with a friend. Negotiation is a performance; reading tips is not rehearsal.",
  "Competing offers: mention them only if real and provable. Bluffs get called and end negotiations.",
  "Get the final number in writing before accepting verbally. Enthusiasm plus paperwork is the professional combo.",
  "Percentage framing beats absolute framing: '20% below market' lands harder than '₹3 lakh short'.",
  "The annual-review stack: keep a wins doc all year with numbers. Reviews decided by memory become reviews decided by mood.",
  "Never accept or reject on the call. 'I'm excited - I'll confirm by Thursday' buys you 48 hours of clear thinking.",
];

export const MEGA_EMAIL_TIPS: string[] = [
  "Cold email rule: under 120 words, one ask, one specific reason it's them and not anyone.",
  "Subject lines: 'quick question about [specific thing]' outperforms 'opportunity' every time.",
  "First line must be about them, not you. 'I saw your talk on X' beats 'I am a great candidate'.",
  "The ask: make it a 10-minute favour, not a life decision. Smaller asks convert dramatically better.",
  "Follow up once after 5-7 days, once more after 2 weeks, then move on. Three touches maximum.",
  "Attach proof: one link to your best relevant work. Not a portfolio, not a resume - the one thing.",
  "End with an easy out: 'If this isn't your area, I'd appreciate a pointer to who it belongs to.'",
  "Write at their reading level, not your writing level. Simple sentences signal confidence.",
  "Send Tuesday-Thursday mornings in their timezone. Monday is triage; Friday is fantasy.",
  "One follow-up that adds value (a link, a result) outperforms three 'just bumping this' nudges.",
  "Personalise the first line with something only a human could write. Mail-merge gibberish converts worse than no personalisation.",
  "Kill the attachments on first contact. Links open; attachments trigger IT filters and trust issues.",
  "Signature: name, role, one link. Banners, quotes and logos belong in spam folders.",
  "The 'unsubscribe' subject test: would you open this if it came from a stranger? Write it until the answer is yes.",
  "Track reply rate, not open rate. Opens are inflated by scanners; replies are truth.",
  "Ask for a specific next step: '15 minutes Tuesday?' beats 'let me know your thoughts'. Vagueness is where replies go to die.",
  "Read your email on a phone before sending. If the ask is below the fold, rewrite.",
];

/* ─── romance ─── */
export const MEGA_DATE_IDEAS: string[] = [
  "Cook one recipe from the other person's childhood - the story matters more than the food.",
  "Bookshop challenge: 10 minutes each to pick a book for the other person, explain why over chai.",
  "Sunset walk plus one question neither of you has ever answered out loud.",
  "Take the worst tourist activity in your city, together, completely seriously. Photos mandatory.",
  "Rearrange one room at midnight. Chaos builds consensus - and it's fun.",
  "Learn a 30-second dance from a video, perform it for each other, vote for the winner.",
  "Street-food crawl with a fixed small budget - pick dishes neither of you has tried.",
  "Go to the airport viewing gallery and invent lives for people based on their luggage.",
  "Museum gift shops only. The weirdest object wins; the museum itself is optional.",
  "Write letters to your future selves, seal them, open them in exactly one year.",
  "Silent date: three hours doing your own thing in the same room. Somehow it works.",
  "Cook a completely invented dish together. Naming rights go to whoever's idea was worse.",
  "Golden-hour photo walk: one phone, one hour, best shot wins. Loser makes dinner.",
  "Take a class neither of you knows anything about - pottery, salsa, basic car repair. Equal incompetence is romantic.",
  "Recreate your first date as closely as possible. The details you remember (and don't) are the conversation.",
  "Volunteer together for one evening. Watching each other be kind is quietly attractive.",
  "Build a two-person book club: same short story, one pot of chai, thirty minutes of arguing.",
  "Stargaze with a free sky-map app on the terrace, away from streetlights. Free, ancient, never fails.",
  "Do a full grocery shop together with a ₹500 mystery-basket theme - 'only orange foods', 'everything starts with P'.",
  "Swap phones for an hour - not to snoop, but to teach each other your most-used apps. Curiosity without surveillance.",
  "Go to a hardware store and plan an absurd home project. Buy zero tools. Dream at scale.",
  "Bakery crawl: three bakeries, one croissant each, strict scorecards. Brunch is solved.",
  "Repair something together that's been broken for months. The shelf will outlast the argument it caused.",
  "Have a 'questions jar' dinner: write 10 questions, no phones, pull one at a time. Deeper than any small talk.",
  "Learn each other's comfort meals, then cook yours for them on a random Tuesday. No occasion needed.",
];

export const MEGA_COMPLIMENTS: string[] = [
  "You have the rare ability to make ordinary days feel like small occasions.",
  "I noticed how you handled that - calmly, when most people wouldn't have. It stuck with me.",
  "You listen like the conversation is the most important thing happening right now. Very few people do.",
  "The way you think out loud makes other people smarter just by being near it.",
  "Your taste in small things - colours, words, songs - is quietly excellent.",
  "You're the kind of person whose texts actually improve my day.",
  "You make it easy for people to be honest around you. That's a superpower, not an accident.",
  "I've never seen you be cruel to someone who couldn't do anything for you. It says everything.",
  "You ask the question everyone was thinking but nobody wanted to ask first.",
  "Your enthusiasm is contagious in the best, least annoying way.",
  "You remember small things people mention once. Being remembered by you feels like an honour.",
  "You have the honesty that makes people trust your compliments - so when you praise something, it means something.",
  "You stay calm in chaos, and it gives everyone around you permission to think clearly.",
  "Your work ethic is the quiet kind - no announcements, just things getting better around you.",
  "You ask follow-up questions. Actual ones. Conversations with you feel like being genuinely met.",
  "You apologise well and change visibly. That combination is rare enough to be remarkable.",
  "You're generous with credit and stingy with blame. Rooms work better with you in them.",
  "You make learning look joyful instead of dutiful. It's changed how I think about my own habits.",
  "You show up - not just to events, but to the unglamorous moments where it actually counts.",
  "Your standards for the things you make have quietly raised the bar for everyone watching.",
  "You laugh with your whole face. It's impossible to have a bad day entirely, near that.",
  "You give space without making people feel dropped. That balance is a kind of art.",
  "You notice when someone's off, and you check in without making it a scene. Rare instinct.",
  "You turn boring logistics into something almost fun. Group trips would collapse without people like you.",
  "You're the same person in every room. Consistency like yours is quietly magnetic.",
];

/* ─── simulators ─── */
export const MEGA_SIM_TIPS: string[] = [
  "₹5,000/month at 8% for 20 years ≈ ₹29.6 lakh. You'd deposit ₹12 lakh; the rest is compounding. Start today, not 'when income improves'.",
  "20 pages a day is roughly 24 books a year. Nobody feels like reading daily; the ones who do it anyway read 24 books a year.",
  "45 minutes of practice daily for one year is 273 hours - competent at almost any skill.",
  "Cutting one ₹300/week takeaway saves ₹15,600/year - a real vacation fund, funded by Fridays.",
  "Walking 30 minutes daily is ~1,800 km/year. That's the distance from Delhi to Mumbai on your feet.",
  "Saving 10% of income feels impossible; automating it feels like nothing. Payroll can't spend what it never sees.",
  "One hour of learning daily for 5 years is 1,800 hours - enough to be in the top 1% of most fields.",
  "10,000 steps is about 8 km and burns roughly 300-400 extra calories. Consistency beats intensity, always.",
  "₹2,000/month invested at 12% from age 25 to 60 becomes ₹1.2 crore. The same investment starting at 35: ₹35 lakh. Time is the ingredient.",
  "Sleep 7.5 hours instead of 6 for a month and you've gained 45 hours of restoration - two full waking days of brain repair.",
  "Reading 30 minutes before bed instead of scrolling: same 30 minutes, minus the blue light, plus a book a month.",
  "One cold shower a day for a year is 365 reps of doing hard things on purpose. The skill transfers.",
  "Cooking at home 4 nights a week vs delivery saves roughly ₹8,000-₹12,000 monthly in most metros - plus you learn the skill forever.",
  "Keeping your phone on silent permanently: the average person checks it 96 times a day anyway. You'll miss nothing real.",
  "Two strength sessions a week for a year doubles most beginners' baseline strength. Two hours a week, that's all.",
  "Writing 200 words a day is a 73,000-word manuscript a year. One book, entirely composed in bathroom-scroll time.",
  "A weekly 10-minute money review compounds like interest: subscriptions cancelled, leaks spotted, plans adjusted.",
  "Learning 5 words of a language daily is 1,825 words a year - comfortably conversational in a second language.",
  "One no-spend day a week is 52 days a year of free wins. Most people can find three in week one.",
  "Stretching 5 minutes after every shower anchors the habit to an existing one - the oldest behavioural trick there is.",
  "Decluttering one drawer a week is 52 drawers a year - most homes only have 40.",
  "Calling your parents twice a week for 10 years is 1,040 conversations. Nobody regrets this habit.",
  "Taking the stairs daily is roughly 2,600 flights a year - free cardio, zero gym membership.",
  "Sunlight within an hour of waking resets your body clock - better sleep that night, deeper focus that day.",
  "₹100/day on snacks is ₹36,500/year. Making snacks a weekend thing funds a very good holiday.",
];

/* ─── clothing/grooming ─── */
export const MEGA_CAPSULE: string[] = [
  "Base palette: white, black, navy, grey, one accent colour. Everything must match everything.",
  "12 pieces that interchange: 4 tops, 2 layers, 3 bottoms, 2 shoes, 1 jacket. That's 60+ outfits.",
  "Fit beats brand, always. A tailored ₹800 shirt beats a ₹8,000 bad fit every single time.",
  "Rule for new purchases: it must match at least 3 things you already own, or it doesn't join.",
  "Shoes and belt should agree. Watch metal and glasses metal should agree. That's 90% of 'looking put together'.",
  "Two full-length mirrors minimum. What you can't see is what everyone else sees.",
  "Replace basics annually: white tees, socks, underwear. They quietly expire and drag the whole outfit down.",
  "Dry-clean-only items: count the cleaning cost into the price before buying. Some bargains aren't.",
  "Tailor once, wear for years: a good alterations guy is the best-kept secret in menswear.",
  "Own one proper jacket. It upgrades everything from t-shirts to formal shirts.",
  "The tuck rule: if the shirt has a straight hem, wear it out. If it curves, tuck it. Ancient wisdom, always right.",
  "Sleeves should end at the wrist bone; trousers should barely touch the shoe. Two measurements, whole outfit transformed.",
  "Layer light to heavy: tee, shirt, jacket. Bulk order matters more than brand names.",
  "Monochrome outfits look expensive automatically - same colour, different shades, head to toe.",
  "One good white sneaker (kept clean) pairs with 90% of casual menswear. Protect it accordingly.",
  "Fabric before pattern: texture reads as expensive; busy prints read as cheap, whatever the price.",
  "Roll sleeves to just below the elbow with the cuff visible. Effortless is a technique, not an accident.",
  "Match socks to trousers, not shoes - legs look longer, mistakes disappear.",
  "Occasion dressing: overdress casually, underdress formally. The middle path embarrasses nobody.",
  "Iron the collar and cuffs; the rest forgives. 80% of 'crisp' is those two zones.",
  "Belts: matte leather for casual, subtle shine for formal. Same belt for everything does neither job.",
  "Gym clothes are for the gym. Athleisure is a marketing category, not a style strategy.",
  "Sunglasses should match your face shape: round frames for square faces, square frames for round. Try before buying online.",
  "A pressed handkerchief in the jacket pocket does more than a logo anything. Details are the luxury.",
  "Buy winter clothes in March and summer clothes in September. Off-season discounts are the only discounts that matter.",
];

export const MEGA_GROOMING: string[] = [
  "AM: water rinse, moisturiser, SPF 50. PM: cleanser, moisturiser. That's the whole routine.",
  "SPF is the anti-ageing product with actual evidence behind it. Everything else is support cast.",
  "Add one active (retinol or vitamin C) only after 2 consistent weeks of basics. More products ≠ better skin.",
  "Change pillowcases twice a week. Cheapest skin fix there is.",
  "Hair: find one barber and stay. Photos of the good cut on your phone. Loyalty pays in consistency.",
  "Beard: define the neckline (two fingers above Adam's apple) and cheek line. Everything else is maintenance.",
  "Nails: weekly trim, file rough edges. People notice hands more than they admit.",
  "Fragrance: one on the wrist, one on the chest, never rubbed in - sprayed and left to dry.",
  "Teeth: twice daily, plus flossing. Whitening strips occasionally. That's it; no influencer gums required.",
  "Lips: one balm at night. Chapped lips are a hydration and friction problem, not a product problem.",
  "Wash your face after the gym, not before. Sweat sitting on skin is the acne trigger, not the workout.",
  "Use lukewarm water, never hot. Hot water strips the oils your skin is trying to balance.",
  "Pat dry, don't rub. Towel friction is micro-damage your moisturiser then has to fix.",
  "Apply moisturiser to damp skin within 60 seconds of washing. It locks the water in instead of chasing it.",
  "Sunscreen needs reapplication every 3-4 hours outdoors. Morning SPF is not a full-day shield.",
  "Beard dandruff is usually dry skin underneath - same moisturiser, applied under the beard, fixes it.",
  "Trim nose and ear hair monthly. Nobody mentions it; everybody notices.",
  "Hands show age first: carry one hand cream, use after every wash. Twelve seconds, visible difference in months.",
  "Don't pick. Not pimples, not cuticles, not anything. Picking turns 3-day problems into 3-week scars.",
  "Drink water like it's a skincare product, because it is. Dehydration shows up on the face before it shows up in thirst.",
  "One clean towel for the face, changed weekly. Body towel for body, always separate.",
  "Haircuts every 4-5 weeks keep the shape. 'It'll style out' is hopeful fiction by week six.",
  "Aftershave splash on the neck, deodorant on clean dry skin, fragrance last on wrists and chest. Order changes how long each lasts.",
  "Sleep is the cheapest skincare: two bad nights show up, two good nights show up too. Track which.",
];

/* ─── courses ─── */
export const MEGA_COURSE_TIPS: string[] = [
  "Free-first resources: YouTube, freeCodeCamp, MIT OpenCourseWare, Khan Academy, university open pages. Certificates cost; knowledge doesn't.",
  "One 4-week plan beats ten bookmarked courses. Depth over breadth, always.",
  "Week 1: map the field and its 10 core terms. Week 2: build something tiny. Week 3: go deep on one area. Week 4: teach or ship it.",
  "Watch at 1.25× and take notes by hand. Speed plus handwriting beats passive video consumption.",
  "Do projects from week one. Courses make you feel productive; projects make you productive.",
  "Join one community for the topic. Questions answered in 5 minutes beat hours of solo confusion.",
  "Publicly commit: a tweet, a note, a friend. Social contracts work when motivation doesn't.",
  "Study 45 minutes daily beats 6 hours on Sunday. Consistency compounds; cramming evaporates.",
  "If stuck for 30 minutes, ask. If stuck for 30 seconds, google. Calibrate the gap between them.",
  "Finish ugly. The finished mediocre project teaches more than the abandoned perfect one.",
  "Choose courses with projects attached, not completion certificates. Certificates decorate profiles; projects build them.",
  "The two-week rule: if a free course has not hooked you in two weeks, drop it guilt-free. Good courses grab early.",
  "Learn the tool last, the concept first. Software changes yearly; fundamentals transfer.",
  "Build a learning-in-public log - one post per week on what you learnt. Accountability plus a portfolio in one.",
  "Course-hoarding is procrastination in a productive costume. Finish one before bookmarking the next.",
  "Stack skills, not credentials: writing + data beats another certificate in either alone.",
  "Use university syllabi as free curricula - course outlines are maps to the field essentials.",
  "The 30-minute daily rule: show up daily for a month before judging progress. Skill arrives quietly, then all at once.",
  "Study the field classic book (everyone cites it) before the trending one. Fashion is downstream of classics.",
  "Reward finishing, not starting: archive courses you will never finish. A clean library is a clear mind.",
  "Practice retrieval between sessions - close everything and summarise from memory in 5 bullets.",
  "Trade notes with a peer studying the same thing. Explaining your notes reveals what you skipped.",
];

/* ─── nearby ─── */
export const MEGA_NEARBY_TIPS: string[] = [
  "For quiet work spots: search 'quiet cafe laptop work [area]' on maps, then check recent photo reviews - not star ratings.",
  "For groceries: 'international grocery near me' finds the specialty stores regular maps misses.",
  "For events: local library noticeboards, Instagram location tags, and university event pages beat event apps in most cities.",
  "For doctors: filter by 'accepts new patients' first, reviews second. Availability is the scarce resource.",
  "For running routes: maps' 'walking' mode with terrain layer on shows parks and quieter roads instantly.",
  "For food: 'best [dish] in [city] reddit' outperforms every food blog's SEO content.",
  "For photo spots: search the location on Instagram, sort by recent, note the exact spot from geotags.",
  "For transport: check the last service time BEFORE the plan, not after. Most 'lost phone' stories start with an assumption.",
  "For studying away from home: public library study hall [city] finds the free AC-and-wifi rooms tourists never mention.",
  "For quick meetings: hotel lobby cafes have seating, wifi and no purchase pressure. The universal neutral ground.",
  "For late-night food: search maps open-now + food, sort by distance not rating - 2am stars are thin data.",
  "For walks: park and riverside loops are the city quietest paths. Go at golden hour for the bonus.",
  "For weekend trips: search [city] hidden viewpoints on image maps - pins with photos beat blog listicles.",
  "For printers: every city has copy shops that print for pennies. Know your nearest one before the emergency.",
  "For sports: football turf near me finds the five-a-side grounds - morning slots are half price.",
  "For quiet phone calls: library steps and cultural-centre courtyards are the city free phone booths.",
  "For festival shopping: wholesale markets cluster by item - ask a rickshaw driver which street; they know instantly.",
  "For repairs: [device] repair near me - independent shops fix what brand stores replace.",
  "For emergency pharmacies: 24-hour chains exist near most hospitals. Save the nearest one location now, thank yourself later.",
];
