/**
 * South Asia & Global Free Resources — India, Pakistan, Bangladesh, Arab world.
 * Each entry has name, URL, description, country, category, free-tier badge.
 */

export interface SouthAsiaResource {
  id: string;
  name: string;
  url: string;
  description: string;
  country: string;
  flag: string;
  category: string;
  freeTier: string;
}

export const SOUTH_ASIA_RESOURCES: SouthAsiaResource[] = [
  // ── INDIA ──
  {
    id: "nptel",
    name: "NPTEL",
    url: "https://nptel.ac.in",
    description: "IIT/IISc free courses across 500+ subjects with certificates on completion.",
    country: "India",
    flag: "🇮🇳",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "swayam",
    name: "Swayam",
    url: "https://swayam.gov.in",
    description: "Government of India free online courses from school to postgraduate level.",
    country: "India",
    flag: "🇮🇳",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "nasscom-futureskills",
    name: "NASSCOM FutureSkills",
    url: "https://futureskillsprime.in",
    description: "Free AI/digital upskilling from India's tech industry body.",
    country: "India",
    flag: "🇮🇳",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "startup-india",
    name: "Startup India",
    url: "https://startupindia.gov.in",
    description: "Free startup registration, resources, and government mentorship.",
    country: "India",
    flag: "🇮🇳",
    category: "Tools",
    freeTier: "Free",
  },
  {
    id: "digilocker",
    name: "DigiLocker",
    url: "https://digilocker.gov.in",
    description: "Free government-verified digital document storage for all Indian citizens.",
    country: "India",
    flag: "🇮🇳",
    category: "Tools",
    freeTier: "Free",
  },
  {
    id: "epathshala",
    name: "ePathshala",
    url: "https://epathshala.nic.in",
    description: "Free NCERT textbooks and e-resources for all Indian school classes.",
    country: "India",
    flag: "🇮🇳",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "ndl",
    name: "National Digital Library",
    url: "https://ndl.gov.in",
    description: "4 million+ free books, articles, and thesis papers from Indian institutions.",
    country: "India",
    flag: "🇮🇳",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "zerodha-varsity",
    name: "Zerodha Varsity",
    url: "https://zerodha.com/varsity",
    description: "Complete free stock market education — Hindi + English, beginner to advanced.",
    country: "India",
    flag: "🇮🇳",
    category: "Finance",
    freeTier: "Free",
  },
  {
    id: "screener-in",
    name: "Screener.in",
    url: "https://screener.in",
    description: "Free Indian stock fundamental analysis — screen, compare, and track companies.",
    country: "India",
    flag: "🇮🇳",
    category: "Finance",
    freeTier: "Free",
  },
  {
    id: "amfi-nav-api",
    name: "AMFI NAV API",
    url: "https://amfiindia.com",
    description: "Official free mutual fund NAV data API from Association of Mutual Funds in India.",
    country: "India",
    flag: "🇮🇳",
    category: "APIs",
    freeTier: "Free",
  },
  {
    id: "codewithharry",
    name: "CodeWithHarry",
    url: "https://youtube.com/@CodeWithHarry",
    description: "Most subscribed Indian coding channel — Hindi tutorials on web, Python, and more.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "apna-college",
    name: "Apna College",
    url: "https://youtube.com/@ApnaCollegeOfficial",
    description: "Hindi DSA and full-stack development courses — popular with Indian CS students.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "ca-rachna-ranade",
    name: "CA Rachana Ranade",
    url: "https://youtube.com/@CARachanaRanade",
    description: "Free financial education in Hindi — stock market, personal finance, investing.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "pranjal-kamra",
    name: "Pranjal Kamra",
    url: "https://youtube.com/@PranjalKamra",
    description: "Long-term investing philosophy explained in simple Hindi for Indian audiences.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "ishan-sharma",
    name: "Ishan Sharma",
    url: "https://youtube.com/@IshanSharma",
    description: "Tech, AI, and productivity content in Hindi — startup and career advice.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "varun-mayya",
    name: "Varun Mayya",
    url: "https://youtube.com/@VarunMayya",
    description: "Tech career and startup advice — hiring, scaling, and building products.",
    country: "India",
    flag: "🇮🇳",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "ispirt",
    name: "iSPIRT",
    url: "https://ispirt.in",
    description: "India's software product think tank — free resources for builders and startups.",
    country: "India",
    flag: "🇮🇳",
    category: "Tools",
    freeTier: "Free",
  },

  // ── PAKISTAN ──
  {
    id: "vu-pakistan",
    name: "Virtual University of Pakistan",
    url: "https://vu.edu.pk",
    description: "Free video lectures for 200+ university courses — Pakistani online education pioneer.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "digiskills-pk",
    name: "DigiSkills.pk",
    url: "https://digiskills.pk",
    description: "Pakistani government's free digital skills training platform with certifications.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "sabaq-foundation",
    name: "Sabaq Foundation",
    url: "https://sabaq.pk",
    description: "Free Urdu-medium video lessons for K-12 Pakistani students.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "panacloud",
    name: "PanaCloud",
    url: "https://youtube.com/@PanaCloud",
    description: "Pakistani AI/Web3/cloud developer education — free full courses on YouTube.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "career-khata",
    name: "CareerKhata",
    url: "https://youtube.com/@CareerKhata",
    description: "Pakistani career and tech guidance — job prep, skills, and industry insights.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "YouTube",
    freeTier: "Free",
  },
  {
    id: "pasha",
    name: "PASHA",
    url: "https://pasha.org.pk",
    description: "Pakistan Software Houses Association — free resources for Pakistani tech industry.",
    country: "Pakistan",
    flag: "🇵🇰",
    category: "Tools",
    freeTier: "Free",
  },

  // ── BANGLADESH ──
  {
    id: "10-minute-school",
    name: "10 Minute School",
    url: "https://10minuteschool.com",
    description: "Bangladesh's largest free education platform — school to professional courses.",
    country: "Bangladesh",
    flag: "🇧🇩",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "bohubrihi",
    name: "Bohubrihi",
    url: "https://bohubrihi.com",
    description: "Bangla data science and programming courses — free content available.",
    country: "Bangladesh",
    flag: "🇧🇩",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "programming-hero",
    name: "Programming Hero (Bangla)",
    url: "https://youtube.com/@ProgrammingHeroBangla",
    description: "Bangla web development full courses — completely free on YouTube.",
    country: "Bangladesh",
    flag: "🇧🇩",
    category: "YouTube",
    freeTier: "Free",
  },

  // ── ARAB WORLD ──
  {
    id: "rwaq",
    name: "Rwaq",
    url: "https://rwaq.org",
    description: "Arabic MOOC platform with hundreds of free Arabic-language university courses.",
    country: "Arab World",
    flag: "🌍",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "edraak",
    name: "Edraak",
    url: "https://edraak.org",
    description: "Jordan's Coursera equivalent — Arabic, completely free online courses.",
    country: "Arab World",
    flag: "🌍",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "mahara-tech",
    name: "Mahara Tech",
    url: "https://maharatech.gov.eg",
    description: "Egyptian government's free tech courses — web, mobile, data, and more.",
    country: "Arab World",
    flag: "🌍",
    category: "Courses",
    freeTier: "Free",
  },

  // ── GLOBAL / MULTILINGUAL ──
  {
    id: "duolingo",
    name: "Duolingo",
    url: "https://duolingo.com",
    description: "Free language learning for 40+ languages — gamified, no signup required.",
    country: "Global",
    flag: "🌐",
    category: "Tools",
    freeTier: "Free",
  },
  {
    id: "bbc-learning-english",
    name: "BBC Learning English",
    url: "https://bbc.co.uk/learningenglish",
    description: "Completely free English learning — videos, audio, grammar, vocabulary.",
    country: "Global",
    flag: "🌐",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "open-culture",
    name: "Open Culture",
    url: "https://openculture.com",
    description: "1,500+ free courses from top universities — MIT, Stanford, Yale, and more.",
    country: "Global",
    flag: "🌐",
    category: "Courses",
    freeTier: "Free",
  },
  {
    id: "commonlit",
    name: "CommonLit",
    url: "https://commonlit.org",
    description: "Free English reading and writing platform for all levels — no account needed.",
    country: "Global",
    flag: "🌐",
    category: "Courses",
    freeTier: "Free",
  },
];

export const SOUTH_ASIA_CATEGORIES = [
  "All",
  "Courses",
  "YouTube",
  "Tools",
  "Finance",
  "APIs",
] as const;
