import { useState, useCallback } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/library/AppShell";
import { Download, Plus, Trash2 } from "lucide-react";
import jsPDF from "jspdf";

export const Route = createFileRoute("/tools/invoice")({
  head: () => ({ meta: [{ title: "Invoice Generator — SlashAI" }] }),
  component: InvoiceGenerator,
});

type LineItem = { desc: string; qty: number; rate: number };

function InvoiceGenerator() {
  const [from, setFrom] = useState({ name: "", address: "", email: "", phone: "" });
  const [to, setTo] = useState({ name: "", address: "", email: "" });
  const [items, setItems] = useState<LineItem[]>([{ desc: "", qty: 1, rate: 0 }]);
  const [gstRate, setGstRate] = useState(18);
  const [invoiceNo, setInvoiceNo] = useState(() => {
    try { return `INV-${String(parseInt(localStorage.getItem("inv_count") || "0") + 1).padStart(4, "0")}`; } catch { return "INV-0001"; }
  });
  const [template, setTemplate] = useState<"freelancer" | "agency" | "consultant">("freelancer");
  const [upiId, setUpiId] = useState("");
  const [bankAcct, setBankAcct] = useState("");

  const subtotal = items.reduce((sum, item) => sum + item.qty * item.rate, 0);
  const gstAmount = (subtotal * gstRate) / 100;
  const total = subtotal + gstAmount;

  const updateItem = (idx: number, field: keyof LineItem, val: string | number) => {
    setItems((prev) => prev.map((item, i) => (i === idx ? { ...item, [field]: val } : item)));
  };

  const addItem = () => setItems((prev) => [...prev, { desc: "", qty: 1, rate: 0 }]);
  const removeItem = (idx: number) => setItems((prev) => prev.filter((_, i) => i !== idx));

  const generatePDF = useCallback(() => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(88, 166, 255);
    doc.text("INVOICE", 20, 30);

    doc.setFontSize(10);
    doc.setTextColor(139, 148, 158);
    doc.text(invoiceNo, 20, 38);
    doc.text(new Date().toLocaleDateString("en-IN"), pageW - 20, 38, { align: "right" });

    // From
    doc.setFontSize(9);
    doc.setTextColor(139, 148, 158);
    doc.text("FROM", 20, 55);
    doc.setTextColor(240, 246, 252);
    doc.setFontSize(11);
    doc.text(from.name || "Your Name", 20, 62);
    doc.setFontSize(9);
    doc.setTextColor(139, 148, 158);
    if (from.address) doc.text(from.address, 20, 68);
    if (from.email) doc.text(from.email, 20, 74);
    if (from.phone) doc.text(from.phone, 20, 80);

    // To
    doc.setTextColor(139, 148, 158);
    doc.setFontSize(9);
    doc.text("BILL TO", pageW - 70, 55);
    doc.setTextColor(240, 246, 252);
    doc.setFontSize(11);
    doc.text(to.name || "Client Name", pageW - 70, 62);
    doc.setFontSize(9);
    doc.setTextColor(139, 148, 158);
    if (to.address) doc.text(to.address, pageW - 70, 68);
    if (to.email) doc.text(to.email, pageW - 70, 74);

    // Table header
    let y = 95;
    doc.setFillColor(22, 27, 34);
    doc.rect(20, y - 5, pageW - 40, 10, "F");
    doc.setFontSize(9);
    doc.setTextColor(139, 148, 158);
    doc.text("Description", 22, y + 2);
    doc.text("Qty", 120, y + 2);
    doc.text("Rate", 140, y + 2);
    doc.text("Amount", pageW - 22, y + 2, { align: "right" });

    // Items
    y += 15;
    doc.setTextColor(240, 246, 252);
    items.forEach((item) => {
      if (item.desc) {
        doc.setFontSize(10);
        doc.text(item.desc, 22, y);
        doc.text(String(item.qty), 122, y);
        doc.text(`₹${item.rate.toLocaleString("en-IN")}`, 140, y);
        doc.text(`₹${(item.qty * item.rate).toLocaleString("en-IN")}`, pageW - 22, y, { align: "right" });
        y += 8;
      }
    });

    // Totals
    y += 5;
    doc.setDrawColor(33, 38, 45);
    doc.line(120, y, pageW - 20, y);
    y += 10;
    doc.setFontSize(10);
    doc.text("Subtotal", 130, y);
    doc.text(`₹${subtotal.toLocaleString("en-IN")}`, pageW - 22, y, { align: "right" });
    y += 8;
    doc.text(`GST (${gstRate}%)`, 130, y);
    doc.text(`₹${gstAmount.toLocaleString("en-IN")}`, pageW - 22, y, { align: "right" });
    y += 10;
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Total", 130, y);
    doc.text(`₹${total.toLocaleString("en-IN")}`, pageW - 22, y, { align: "right" });

    // Payment details
    y += 20;
    if (upiId || bankAcct) {
      doc.setFontSize(9);
      doc.setTextColor(139, 148, 158);
      doc.text("PAYMENT DETAILS", 20, y);
      y += 8;
      doc.setTextColor(240, 246, 252);
      if (upiId) { doc.text(`UPI: ${upiId}`, 20, y); y += 6; }
      if (bankAcct) { doc.text(`Bank: ${bankAcct}`, 20, y); y += 6; }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by SlashAI — slashai-nu.vercel.app", pageW / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });

    doc.save(`${invoiceNo}.pdf`);

    // Increment invoice counter
    try {
      const count = parseInt(localStorage.getItem("inv_count") || "0");
      localStorage.setItem("inv_count", String(count + 1));
    } catch { /* ignore */ }
  }, [from, to, items, gstRate, invoiceNo, subtotal, gstAmount, total, upiId, bankAcct]);

  return (
    <AppShell title="Invoice Generator">
      <div className="mx-auto max-w-3xl space-y-6 pt-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Invoice Generator</h1>
            <p className="mt-1 text-sm text-muted-foreground">Create and download professional invoices as PDF.</p>
          </div>
          <button onClick={generatePDF} className="flex items-center gap-1.5 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white transition-all hover:bg-primary/90">
            <Download className="size-4" /> Download PDF
          </button>
        </div>

        {/* Invoice # + template */}
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">Invoice Number</label>
            <input value={invoiceNo} onChange={(e) => setInvoiceNo(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground focus:border-primary/50 focus:outline-none" />
          </div>
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">Template</label>
            <select value={template} onChange={(e) => setTemplate(e.target.value as any)} className="h-10 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground focus:outline-none">
              <option value="freelancer">Freelancer</option>
              <option value="agency">Agency</option>
              <option value="consultant">Consultant</option>
            </select>
          </div>
        </div>

        {/* From / To */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <h3 className="mb-2 text-xs font-semibold uppercase text-muted-foreground">From</h3>
            {(["name", "address", "email", "phone"] as const).map((f) => (
              <input key={f} value={from[f]} onChange={(e) => setFrom((p) => ({ ...p, [f]: e.target.value }))} placeholder={f.charAt(0).toUpperCase() + f.slice(1)} className="mb-1.5 h-9 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:border-primary/50 focus:outline-none" />
            ))}
          </div>
          <div>
            <h3 className="mb-2 text-xs font-semibold uppercase text-muted-foreground">Bill To</h3>
            {(["name", "address", "email"] as const).map((f) => (
              <input key={f} value={to[f]} onChange={(e) => setTo((p) => ({ ...p, [f]: e.target.value }))} placeholder={f.charAt(0).toUpperCase() + f.slice(1)} className="mb-1.5 h-9 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:border-primary/50 focus:outline-none" />
            ))}
          </div>
        </div>

        {/* Line items */}
        <div>
          <h3 className="mb-2 text-xs font-semibold uppercase text-muted-foreground">Items</h3>
          <div className="space-y-2">
            {items.map((item, idx) => (
              <div key={idx} className="flex items-center gap-2">
                <input value={item.desc} onChange={(e) => updateItem(idx, "desc", e.target.value)} placeholder="Description" className="flex-1 h-9 rounded-lg border border-border bg-surface px-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:border-primary/50 focus:outline-none" />
                <input type="number" value={item.qty} onChange={(e) => updateItem(idx, "qty", parseInt(e.target.value) || 1)} className="h-9 w-16 rounded-lg border border-border bg-surface px-2 text-center text-sm text-foreground focus:outline-none" />
                <input type="number" value={item.rate || ""} onChange={(e) => updateItem(idx, "rate", parseFloat(e.target.value) || 0)} placeholder="Rate" className="h-9 w-24 rounded-lg border border-border bg-surface px-2 text-center text-sm text-foreground focus:outline-none" />
                <span className="w-24 text-right text-sm text-muted-foreground">₹{(item.qty * item.rate).toLocaleString("en-IN")}</span>
                {items.length > 1 && (
                  <button onClick={() => removeItem(idx)} className="text-muted-foreground hover:text-red"><Trash2 className="size-4" /></button>
                )}
              </div>
            ))}
          </div>
          <button onClick={addItem} className="mt-2 flex items-center gap-1 text-xs text-primary hover:text-primary/80">
            <Plus className="size-3.5" /> Add item
          </button>
        </div>

        {/* GST + totals */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">GST %</label>
            <input type="number" value={gstRate} onChange={(e) => setGstRate(parseFloat(e.target.value) || 0)} className="h-10 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground focus:outline-none" />
          </div>
          <div className="flex flex-col items-end justify-center">
            <div className="text-sm text-muted-foreground">Subtotal: ₹{subtotal.toLocaleString("en-IN")}</div>
            <div className="text-sm text-muted-foreground">GST: ₹{gstAmount.toLocaleString("en-IN")}</div>
            <div className="mt-1 text-lg font-bold text-foreground">Total: ₹{total.toLocaleString("en-IN")}</div>
          </div>
        </div>

        {/* Payment details */}
        <div className="rounded-[10px] border border-border bg-surface p-4">
          <h3 className="mb-2 text-xs font-semibold uppercase text-muted-foreground">Payment Details (optional)</h3>
          <div className="grid grid-cols-2 gap-3">
            <input value={upiId} onChange={(e) => setUpiId(e.target.value)} placeholder="UPI ID" className="h-9 rounded-lg border border-border bg-surface-elevated px-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none" />
            <input value={bankAcct} onChange={(e) => setBankAcct(e.target.value)} placeholder="Bank Account Number" className="h-9 rounded-lg border border-border bg-surface-elevated px-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none" />
          </div>
        </div>
      </div>
    </AppShell>
  );
}
