/**
 * Seed data for the quiz pack family. Packs are generated from these tables at
 * module load (see ./registry) — every pack is a real, playable set of rounds
 * with runtime-sampled distractors, not padding.
 */

/* ── countries: iso2, name, continent, capital, currency ────────────── */
export interface CountryRow {
  iso: string;
  name: string;
  continent: "Asia" | "Europe" | "Africa" | "Americas" | "Oceania";
  capital: string;
  currency: string;
}

export const COUNTRIES: CountryRow[] = [
  { iso: "IN", name: "India", continent: "Asia", capital: "New Delhi", currency: "Rupee" },
  { iso: "JP", name: "Japan", continent: "Asia", capital: "Tokyo", currency: "Yen" },
  { iso: "CN", name: "China", continent: "Asia", capital: "Beijing", currency: "Yuan" },
  { iso: "KR", name: "South Korea", continent: "Asia", capital: "Seoul", currency: "Won" },
  { iso: "TH", name: "Thailand", continent: "Asia", capital: "Bangkok", currency: "Baht" },
  { iso: "VN", name: "Vietnam", continent: "Asia", capital: "Hanoi", currency: "Dong" },
  { iso: "ID", name: "Indonesia", continent: "Asia", capital: "Jakarta", currency: "Rupiah" },
  { iso: "MY", name: "Malaysia", continent: "Asia", capital: "Kuala Lumpur", currency: "Ringgit" },
  { iso: "SG", name: "Singapore", continent: "Asia", capital: "Singapore", currency: "Dollar" },
  { iso: "PK", name: "Pakistan", continent: "Asia", capital: "Islamabad", currency: "Rupee" },
  { iso: "BD", name: "Bangladesh", continent: "Asia", capital: "Dhaka", currency: "Taka" },
  { iso: "LK", name: "Sri Lanka", continent: "Asia", capital: "Colombo", currency: "Rupee" },
  { iso: "NP", name: "Nepal", continent: "Asia", capital: "Kathmandu", currency: "Rupee" },
  { iso: "IR", name: "Iran", continent: "Asia", capital: "Tehran", currency: "Rial" },
  { iso: "IQ", name: "Iraq", continent: "Asia", capital: "Baghdad", currency: "Dinar" },
  { iso: "SA", name: "Saudi Arabia", continent: "Asia", capital: "Riyadh", currency: "Riyal" },
  { iso: "AE", name: "United Arab Emirates", continent: "Asia", capital: "Abu Dhabi", currency: "Dirham" },
  { iso: "TR", name: "Turkey", continent: "Asia", capital: "Ankara", currency: "Lira" },
  { iso: "IL", name: "Israel", continent: "Asia", capital: "Jerusalem", currency: "Shekel" },
  { iso: "KZ", name: "Kazakhstan", continent: "Asia", capital: "Astana", currency: "Tenge" },
  { iso: "GB", name: "United Kingdom", continent: "Europe", capital: "London", currency: "Pound" },
  { iso: "FR", name: "France", continent: "Europe", capital: "Paris", currency: "Euro" },
  { iso: "DE", name: "Germany", continent: "Europe", capital: "Berlin", currency: "Euro" },
  { iso: "IT", name: "Italy", continent: "Europe", capital: "Rome", currency: "Euro" },
  { iso: "ES", name: "Spain", continent: "Europe", capital: "Madrid", currency: "Euro" },
  { iso: "PT", name: "Portugal", continent: "Europe", capital: "Lisbon", currency: "Euro" },
  { iso: "NL", name: "Netherlands", continent: "Europe", capital: "Amsterdam", currency: "Euro" },
  { iso: "BE", name: "Belgium", continent: "Europe", capital: "Brussels", currency: "Euro" },
  { iso: "CH", name: "Switzerland", continent: "Europe", capital: "Bern", currency: "Franc" },
  { iso: "AT", name: "Austria", continent: "Europe", capital: "Vienna", currency: "Euro" },
  { iso: "SE", name: "Sweden", continent: "Europe", capital: "Stockholm", currency: "Krona" },
  { iso: "NO", name: "Norway", continent: "Europe", capital: "Oslo", currency: "Krone" },
  { iso: "DK", name: "Denmark", continent: "Europe", capital: "Copenhagen", currency: "Krone" },
  { iso: "FI", name: "Finland", continent: "Europe", capital: "Helsinki", currency: "Euro" },
  { iso: "PL", name: "Poland", continent: "Europe", capital: "Warsaw", currency: "Zloty" },
  { iso: "CZ", name: "Czechia", continent: "Europe", capital: "Prague", currency: "Koruna" },
  { iso: "GR", name: "Greece", continent: "Europe", capital: "Athens", currency: "Euro" },
  { iso: "HU", name: "Hungary", continent: "Europe", capital: "Budapest", currency: "Forint" },
  { iso: "UA", name: "Ukraine", continent: "Europe", capital: "Kyiv", currency: "Hryvnia" },
  { iso: "IE", name: "Ireland", continent: "Europe", capital: "Dublin", currency: "Euro" },
  { iso: "EG", name: "Egypt", continent: "Africa", capital: "Cairo", currency: "Pound" },
  { iso: "NG", name: "Nigeria", continent: "Africa", capital: "Abuja", currency: "Naira" },
  { iso: "KE", name: "Kenya", continent: "Africa", capital: "Nairobi", currency: "Shilling" },
  { iso: "ET", name: "Ethiopia", continent: "Africa", capital: "Addis Ababa", currency: "Birr" },
  { iso: "ZA", name: "South Africa", continent: "Africa", capital: "Pretoria", currency: "Rand" },
  { iso: "MA", name: "Morocco", continent: "Africa", capital: "Rabat", currency: "Dirham" },
  { iso: "DZ", name: "Algeria", continent: "Africa", capital: "Algiers", currency: "Dinar" },
  { iso: "GH", name: "Ghana", continent: "Africa", capital: "Accra", currency: "Cedi" },
  { iso: "TZ", name: "Tanzania", continent: "Africa", capital: "Dodoma", currency: "Shilling" },
  { iso: "GH2", name: "Ghana2", continent: "Africa", capital: "Accra", currency: "Cedi" },
  { iso: "US", name: "United States", continent: "Americas", capital: "Washington, D.C.", currency: "Dollar" },
  { iso: "CA", name: "Canada", continent: "Americas", capital: "Ottawa", currency: "Dollar" },
  { iso: "MX", name: "Mexico", continent: "Americas", capital: "Mexico City", currency: "Peso" },
  { iso: "BR", name: "Brazil", continent: "Americas", capital: "Brasília", currency: "Real" },
  { iso: "AR", name: "Argentina", continent: "Americas", capital: "Buenos Aires", currency: "Peso" },
  { iso: "CL", name: "Chile", continent: "Americas", capital: "Santiago", currency: "Peso" },
  { iso: "CO", name: "Colombia", continent: "Americas", capital: "Bogotá", currency: "Peso" },
  { iso: "PE", name: "Peru", continent: "Americas", capital: "Lima", currency: "Sol" },
  { iso: "CU", name: "Cuba", continent: "Americas", capital: "Havana", currency: "Peso" },
  { iso: "AU", name: "Australia", continent: "Oceania", capital: "Canberra", currency: "Dollar" },
  { iso: "NZ", name: "New Zealand", continent: "Oceania", capital: "Wellington", currency: "Dollar" },
  { iso: "FJ", name: "Fiji", continent: "Oceania", capital: "Suva", currency: "Dollar" },
  { iso: "PG", name: "Papua New Guinea", continent: "Oceania", capital: "Port Moresby", currency: "Kina" },
];

/** flag emoji from ISO code (skip the placeholder row) */
export function flagEmoji(iso: string): string {
  if (!/^[A-Z]{2}$/.test(iso)) return "🏳️";
  return String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

/* ── spelling: [correct, wrong1, wrong2, wrong3, hint] ───────────────── */
export const SPELLING: [string, string, string, string, string][] = [
  ["because", "becuase", "becuse", "beacuse", "Big Elephants Can Always Understand Small Elephants"],
  ["believe", "beleive", "belive", "beleeve", "i before e, except after c"],
  ["necessary", "neccessary", "necesary", "necessery", "one c, two s — it's shirt size"],
  ["tomorrow", "tommorow", "tommorrow", "tomorow", "one m, two r"],
  ["friend", "freind", "frient", "frirend", "Remember: end with END"],
  ["beautiful", "beutiful", "beautifull", "beautful", "one l at the end"],
  ["separate", "seperate", "sepparate", "separete", "there's A RAT hiding in sep-A-RAT-e"],
  ["definitely", "definately", "defenitely", "definitly", "site — as in definitely sure"],
  ["rhythm", "rythm", "rhythim", "rhythem", "no vowels — helps you spell it"],
  ["pronunciation", "pronounciation", "pronunciaton", "prononciation", "say it: pro-NUN-ciation"],
  ["occasionally", "ocasionally", "occassionally", "occaisionally", "two c, two s, one l"],
  ["embarrass", "embarass", "embarras", "emberrass", "two r, two s — double trouble"],
  ["restaurant", "restaraunt", "resturant", "restarant", "au — like French"],
  ["government", "goverment", "governmant", "govermant", "never skip the first n"],
  ["which", "wich", "whitch", "wihch", "starts like whale"],
  ["surprise", "suprise", "surprize", "surpriese", "there's an r in the middle"],
  ["library", "libary", "libraray", "librery", "don't skip the first r"],
  ["acknowledge", "acknowlege", "aknowledge", "acknowladge", "the word KNOW is hiding inside"],
];

/* ── opposites: [word, opposite] — engine adds distractors ──────────── */
export const OPPOSITES: [string, string][] = [
  ["hot", "cold"], ["big", "small"], ["up", "down"], ["fast", "slow"],
  ["day", "night"], ["happy", "sad"], ["brave", "afraid"], ["ancient", "modern"],
  ["expand", "shrink"], ["generous", "stingy"], ["early", "late"], ["empty", "full"],
  ["strong", "weak"], ["clean", "dirty"], ["loud", "quiet"], ["open", "closed"],
  ["light", "heavy"], ["wide", "narrow"], ["win", "lose"], ["remember", "forget"],
  ["arrive", "depart"], ["accept", "refuse"], ["profit", "loss"], ["scatter", "gather"],
];

/* ── plurals: [singular, plural] ────────────────────────────────────── */
export const PLURALS: [string, string][] = [
  ["box", "boxes"], ["baby", "babies"], ["leaf", "leaves"], ["mouse", "mice"],
  ["tooth", "teeth"], ["child", "children"], ["person", "people"], ["knife", "knives"],
  ["city", "cities"], ["hero", "heroes"], ["sheep", "sheep"], ["fish", "fish"],
  ["foot", "feet"], ["goose", "geese"], ["wolf", "wolves"], ["potato", "potatoes"],
];

/* ── rhymes: [word, [rhymes with…]] ─────────────────────────────────── */
export const RHYMES: [string, string[]][] = [
  ["cat", ["hat", "bat", "mat", "rat"]],
  ["star", ["car", "far", "jar", "bar"]],
  ["cake", ["bake", "lake", "make", "rake"]],
  ["light", ["night", "sight", "fight", "right"]],
  ["tree", ["bee", "free", "sea", "key"]],
  ["ring", ["king", "sing", "wing", "thing"]],
  ["day", ["play", "say", "way", "clay"]],
  ["book", ["cook", "look", "hook", "nook"]],
  ["moon", ["soon", "spoon", "noon", "tune"]],
  ["snow", ["glow", "flow", "grow", "slow"]],
];

/* ── animal babies: [adult, baby] ───────────────────────────────────── */
export const BABIES: [string, string][] = [
  ["cow", "calf"], ["dog", "puppy"], ["cat", "kitten"], ["sheep", "lamb"],
  ["hen", "chick"], ["horse", "foal"], ["kangaroo", "joey"], ["deer", "fawn"],
  ["frog", "tadpole"], ["bear", "cub"], ["swan", "cygnet"], ["goat", "kid"],
  ["lion", "cub"], ["duck", "duckling"], ["pig", "piglet"], ["elephant", "calf"],
];

/* ── community helpers: [tool or place, the helper] ─────────────────── */
export const HELPERS: [string, string, string[]][] = [
  ["drives a bus", "Bus driver", ["Pilot", "Farmer"]],
  ["flies an aeroplane", "Pilot", ["Sailor", "Driver"]],
  ["grows crops for us", "Farmer", ["Baker", "Painter"]],
  ["bakes bread and cakes", "Baker", ["Butcher", "Chef"]],
  ["fights fires", "Firefighter", ["Police officer", "Lifeguard"]],
  ["fixes leaking pipes", "Plumber", ["Electrician", "Carpenter"]],
  ["fixes electrical wiring", "Electrician", ["Plumber", "Mechanic"]],
  ["delivers letters", "Postal worker", ["Courier", "Newsagent"]],
  ["keeps us safe and catches thieves", "Police officer", ["Firefighter", "Security guard"]],
  ["treats sick animals", "Veterinarian", ["Doctor", "Zookeeper"]],
];

/* ── colour mixing: [a + b, result, distract1, distract2] ───────────── */
export const COLOUR_MIX: [string, string, string, string][] = [
  ["red + blue", "Purple", "Orange", "Green"],
  ["red + yellow", "Orange", "Purple", "Brown"],
  ["blue + yellow", "Green", "Teal", "Purple"],
  ["red + white", "Pink", "Peach", "Cream"],
  ["black + white", "Grey", "Silver", "Brown"],
  ["red + green", "Brown", "Olive", "Maroon"],
  ["all colours of light", "White", "Black", "Grey"],
  ["no light at all", "Black", "White", "Grey"],
];

/* ── calendar: [question, answer, distractors…] ─────────────────────── */
export const CALENDAR: [string, string, string, string, string][] = [
  ["Which day comes after Tuesday?", "Wednesday", "Thursday", "Monday", "Friday"],
  ["Which day comes after Friday?", "Saturday", "Sunday", "Thursday", "Monday"],
  ["Which month comes after March?", "April", "May", "February", "June"],
  ["Which month comes before September?", "August", "October", "July", "June"],
  ["How many days in a leap year?", "366", "365", "364", "367"],
  ["Which month has 28 or 29 days?", "February", "January", "April", "March"],
  ["Which season is coldest in India?", "Winter", "Summer", "Monsoon", "Spring"],
  ["How many months have 31 days?", "7", "6", "5", "8"],
  ["Which day comes two days after Monday?", "Wednesday", "Tuesday", "Thursday", "Sunday"],
  ["Which month comes between June and August?", "July", "May", "September", "April"],
  ["Which is the first month of the year?", "January", "December", "March", "June"],
  ["How many seasons does India traditionally have?", "6", "4", "3", "5"],
];

/* ── themed quiz tables: [question, answer, w1, w2, w3] ─────────────── */
export const INVENTIONS: [string, string, string, string, string][] = [
  ["Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"],
  ["Who made the first practical light bulb?", "Thomas Edison", "Alexander Bell", "James Watt", "Benjamin Franklin"],
  ["Who flew the first powered aeroplane?", "The Wright brothers", "Amelia Earhart", "Charles Lindbergh", "Igor Sikorsky"],
  ["Who invented the World Wide Web?", "Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Vint Cerf"],
  ["Who invented the printing press?", "Johannes Gutenberg", "Leonardo da Vinci", "Galileo Galilei", "Isaac Newton"],
  ["Who discovered penicillin?", "Alexander Fleming", "Louis Pasteur", "Edward Jenner", "Robert Koch"],
  ["Who invented the radio?", "Guglielmo Marconi", "David Sarnoff", "Heinrich Hertz", "John Logie Baird"],
  ["Who invented dynamite?", "Alfred Nobel", "Rudolf Diesel", "Alfred Wegener", "Hiram Maxim"],
  ["Who is considered the first computer programmer?", "Ada Lovelace", "Charles Babbage", "Alan Turing", "Grace Hopper"],
  ["Who discovered X-rays?", "Wilhelm Röntgen", "Marie Curie", "Henri Becquerel", "Max Planck"],
];

export const BOOKS: [string, string, string, string, string][] = [
  ["Who wrote the Harry Potter series?", "J.K. Rowling", "Rick Riordan", "Roald Dahl", "Suzanne Collins"],
  ["Who wrote Romeo and Juliet?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
  ["Who wrote the Jungle Book?", "Rudyard Kipling", "Enid Blyton", "Aesop", "Lewis Carroll"],
  ["Who wrote Alice in Wonderland?", "Lewis Carroll", "J.M. Barrie", "C.S. Lewis", "L. Frank Baum"],
  ["Who wrote the Chronicles of Narnia?", "C.S. Lewis", "J.R.R. Tolkien", "Philip Pullman", "Eoin Colfer"],
  ["Who created Sherlock Holmes?", "Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Raymond Chandler"],
  ["In which book does a boy find a golden ticket?", "Charlie and the Chocolate Factory", "Matilda", "The BFG", "James and the Giant Peach"],
  ["Who wrote Gulliver's Travels?", "Jonathan Swift", "Daniel Defoe", "H.G. Wells", "Jules Verne"],
  ["The Panchatantra is a collection of what?", "Animal fables", "War poems", "Love letters", "Space stories"],
  ["Who wrote the Diary of a Young Girl?", "Anne Frank", "Malala Yousafzai", "Helen Keller", "Corrie ten Boom"],
];

export const PLACES: [string, string, string, string, string][] = [
  ["In which city is the Eiffel Tower?", "Paris", "London", "Rome", "Berlin"],
  ["In which city is the Taj Mahal?", "Agra", "Delhi", "Jaipur", "Lucknow"],
  ["Where is the Statue of Liberty?", "New York", "Washington, D.C.", "Boston", "Miami"],
  ["The Great Wall is in which country?", "China", "Japan", "Mongolia", "Korea"],
  ["The Pyramids of Giza are in which country?", "Egypt", "Sudan", "Mexico", "Iraq"],
  ["Big Ben stands in which city?", "London", "Dublin", "Paris", "Amsterdam"],
  ["The Colosseum is in which city?", "Rome", "Athens", "Naples", "Milan"],
  ["Burj Khalifa, the tallest building, is in which city?", "Dubai", "Doha", "Abu Dhabi", "Riyadh"],
  ["Machu Picchu is in which country?", "Peru", "Chile", "Bolivia", "Ecuador"],
  ["Mount Fuji is in which country?", "Japan", "China", "Indonesia", "Philippines"],
];

export const SPACE_MISSIONS: [string, string, string, string, string][] = [
  ["First artificial satellite?", "Sputnik 1", "Explorer 1", "Vostok 1", "Apollo 1"],
  ["First human in space?", "Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "John Glenn"],
  ["First woman in space?", "Valentina Tereshkova", "Sally Ride", "Kalpana Chawla", "Sunita Williams"],
  ["First Indian in space?", "Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "Vikram Sarabhai"],
  ["Which mission first landed humans on the Moon?", "Apollo 11", "Apollo 8", "Gemini 4", "Artemis 1"],
  ["Chandrayaan-3 landed near the Moon's…", "South pole", "North pole", "Equator", "Far side centre"],
  ["India's Mars mission is called?", "Mangalyaan", "Chandrayaan", "Aditya", "Gaganyaan"],
  ["Farthest human-made object from Earth?", "Voyager 1", "Pioneer 10", "New Horizons", "Hubble"],
  ["The ISS orbits Earth roughly every…", "90 minutes", "24 hours", "7 days", "30 minutes"],
  ["Who walked first on the Moon?", "Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Yuri Gagarin"],
];

export const BODY_FACTS: [string, string, string, string, string][] = [
  ["How many bones does an adult have?", "206", "300", "186", "256"],
  ["Which is the largest organ?", "Skin", "Liver", "Brain", "Lungs"],
  ["How many milk teeth does a child have?", "20", "32", "16", "24"],
  ["Which blood type is the universal donor?", "O negative", "AB positive", "A positive", "B negative"],
  ["The smallest bone sits in the…", "Ear", "Nose", "Finger", "Eye"],
  ["Which sense uses the retina?", "Sight", "Hearing", "Smell", "Taste"],
  ["How many chambers does the heart have?", "4", "2", "3", "6"],
  ["What carries oxygen in the blood?", "Haemoglobin", "Plasma", "Platelets", "White cells"],
  ["Which organ cleans the blood?", "Kidneys", "Liver", "Spleen", "Pancreas"],
  ["Adults have how many teeth?", "32", "28", "30", "36"],
];

export const WORLD_FOOD: [string, string, string, string, string][] = [
  ["Pizza and pasta come from…", "Italy", "Greece", "Spain", "France"],
  ["Sushi comes from…", "Japan", "China", "Korea", "Thailand"],
  ["Tacos come from…", "Mexico", "Brazil", "Cuba", "Peru"],
  ["Croissants come from…", "France", "Belgium", "Austria", "Switzerland"],
  ["Kimchi is from…", "Korea", "Japan", "Vietnam", "China"],
  ["Dim sum is from…", "China", "Japan", "Malaysia", "Indonesia"],
  ["Pad Thai is from…", "Thailand", "Laos", "Cambodia", "Myanmar"],
  ["Baklava is from…", "Turkey", "Greece", "Egypt", "Syria"],
  ["Feijoada is from…", "Brazil", "Portugal", "Argentina", "Colombia"],
  ["Dosa and idli are from…", "South India", "North India", "Nepal", "Sri Lanka"],
];

export const FESTIVALS: [string, string, string, string, string][] = [
  ["Festival of lights?", "Diwali", "Holi", "Eid", "Pongal"],
  ["Which festival is on December 25?", "Christmas", "Easter", "Halloween", "Thanksgiving"],
  ["Which festival follows Ramadan?", "Eid-ul-Fitr", "Eid-ul-Adha", "Muharram", "Shab-e-Barat"],
  ["Festival of colours?", "Holi", "Diwali", "Onam", "Baisakhi"],
  ["Harvest festival of Tamil Nadu?", "Pongal", "Onam", "Bihu", "Lohri"],
  ["Which festival celebrates brothers and sisters?", "Raksha Bandhan", "Karva Chauth", "Navratri", "Gudi Padwa"],
  ["Harvest festival of Kerala?", "Onam", "Pongal", "Bihu", "Vishu"],
  ["Assam's harvest festival?", "Bihu", "Onam", "Lohri", "Makar Sankranti"],
  ["Which community celebrates Guru Nanak Jayanti?", "Sikhs", "Buddhists", "Jains", "Hindus"],
  ["Easter is always on a…", "Sunday", "Friday", "Monday", "Saturday"],
];

export const TECH_BRANDS: [string, string, string, string, string][] = [
  ["Who makes the iPhone?", "Apple", "Samsung", "Google", "OnePlus"],
  ["Who owns Android?", "Google", "Microsoft", "Apple", "Samsung"],
  ["Who makes Windows?", "Microsoft", "Apple", "IBM", "Intel"],
  ["What did Amazon first sell?", "Books", "Electronics", "Clothes", "Toys"],
  ["Who bought YouTube in 2006?", "Google", "Microsoft", "Meta", "Yahoo"],
  ["Which company makes the PlayStation?", "Sony", "Microsoft", "Nintendo", "Sega"],
  ["Whose logo is a swoosh?", "Nike", "Adidas", "Puma", "Reebok"],
  ["Who founded Microsoft with Paul Allen?", "Bill Gates", "Steve Jobs", "Larry Page", "Jeff Bezos"],
  ["Which country is Samsung from?", "South Korea", "Japan", "China", "Taiwan"],
  ["Which bird was Twitter's old logo?", "Bluebird", "Eagle", "Owl", "Parrot"],
];

export const SPORTS_FACTS: [string, string, string, string, string][] = [
  ["How many players per football side?", "11", "9", "10", "12"],
  ["How often are the Summer Olympics held?", "Every 4 years", "Every 2 years", "Every 3 years", "Every 5 years"],
  ["In tennis, what score is 'love'?", "Zero", "One", "Tie", "Fifteen"],
  ["How many overs in a T20 innings?", "20", "15", "25", "50"],
  ["How long is a marathon?", "42.195 km", "40 km", "35 km", "50 km"],
  ["Who holds the 100m world record?", "Usain Bolt", "Tyson Gay", "Yohan Blake", "Carl Lewis"],
  ["India won its first Cricket World Cup in…", "1983", "1975", "1992", "2007"],
  ["How many Olympic golds does Michael Phelps have?", "23", "18", "21", "28"],
  ["Kabaddi raiders must hold their breath…", "In one breath", "For 60 seconds", "While sitting", "On one leg"],
  ["Badminton is played with a…", "Shuttlecock", "Ball", "Frisbee", "Puck"],
];

export const RIDDLES: [string, string, string, string, string][] = [
  ["What has hands but cannot clap?", "A clock", "A robot", "A statue", "A tree"],
  ["What must be broken before you use it?", "An egg", "A plate", "A code", "A stick"],
  ["I'm full of holes but still hold water. What am I?", "A sponge", "A bucket", "A net", "A cloth"],
  ["What goes up but never comes down?", "Your age", "A balloon", "Smoke", "The sun"],
  ["What has keys but opens no locks?", "A piano", "A map", "A car", "A diary"],
  ["What gets wetter the more it dries?", "A towel", "Soap", "A fan", "The sun"],
  ["What travels the world while staying in a corner?", "A stamp", "A coin", "A globe", "A shadow"],
  ["What has one eye but cannot see?", "A needle", "A cyclone", "A camera", "A potato"],
  ["What has a neck but no head?", "A bottle", "A shirt", "A guitar", "A road"],
  ["What building has the most stories?", "A library", "A mall", "A tower", "A hotel"],
  ["What runs around a whole yard without moving?", "A fence", "A dog", "A hose", "A road"],
  ["I follow you all day but vanish at night. What am I?", "Your shadow", "Your echo", "The wind", "A cloud"],
];

/* ── hand-written GK packs: 12 questions each, 6 easy + 6 hard ──────── */
export interface HandPack {
  id: string;
  name: string;
  icon: string;
  desc: string;
  rows: [string, string, string, string, string][]; // [q, answer, w1, w2, w3]
}

export const GK_PACKS: HandPack[] = [
  {
    id: "animal-kingdom", name: "Animal Kingdom", icon: "🐘",
    desc: "The biggest, fastest and weirdest facts from the animal world",
    rows: [
      ["Which is the tallest animal?", "Giraffe", "Elephant", "Camel", "Ostrich"],
      ["Fastest land animal?", "Cheetah", "Lion", "Horse", "Leopard"],
      ["Largest animal on Earth?", "Blue whale", "African elephant", "Giraffe", "Whale shark"],
      ["Only bird that flies backwards?", "Hummingbird", "Kingfisher", "Parrot", "Swallow"],
      ["Largest land animal?", "African elephant", "White rhino", "Giraffe", "Hippo"],
      ["Polar bears live at the…", "North Pole (Arctic)", "South Pole (Antarctica)", "Himalayas", "Siberian forests"],
      ["A snail can sleep for up to…", "3 years", "3 days", "3 weeks", "3 months"],
      ["How many hearts does an octopus have?", "3", "1", "2", "8"],
      ["Flamingos are pink because they eat…", "Shrimp and algae", "Berries", "Clay", "Fish"],
      ["Which animal cannot walk backwards?", "Kangaroo", "Elephant", "Crab", "Ostrich"],
      ["Sharks existed before…", "Trees", "Dinosaurs", "Grass", "Jellyfish"],
      ["Jellyfish have no…", "Brain or heart", "Stomach", "Tentacles", "Eyes"],
    ],
  },
  {
    id: "space-kids", name: "Space for Kids", icon: "🚀",
    desc: "Planets, moons and missions — the cosmic basics",
    rows: [
      ["Which planet is called the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury"],
      ["Largest planet in our solar system?", "Jupiter", "Saturn", "Neptune", "Earth"],
      ["Nearest star to Earth?", "The Sun", "Proxima Centauri", "Sirius", "Polaris"],
      ["How many moons does Earth have?", "1", "0", "2", "4"],
      ["First human in space?", "Yuri Gagarin", "Neil Armstrong", "Valentina Tereshkova", "Alan Shepard"],
      ["Saturn is famous for its…", "Rings", "Red spot", "Volcanoes", "Twin moons"],
      ["Hottest planet in our solar system?", "Venus", "Mercury", "Mars", "Jupiter"],
      ["Sunlight reaches Earth in about…", "8 minutes", "8 seconds", "8 hours", "8 days"],
      ["The Great Red Spot is a storm on…", "Jupiter", "Mars", "Saturn", "Neptune"],
      ["Who first walked on the Moon?", "Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Yuri Gagarin"],
      ["Halley's Comet returns about every…", "76 years", "10 years", "120 years", "365 years"],
      ["Neptune is which numbered planet from the Sun?", "8th", "6th", "7th", "5th"],
    ],
  },
  {
    id: "ocean-life", name: "Ocean Life", icon: "🌊",
    desc: "Dive into the deep — reefs, giants and record depths",
    rows: [
      ["Largest ocean?", "Pacific", "Atlantic", "Indian", "Arctic"],
      ["Coral is actually a…", "Animal", "Plant", "Rock", "Fungus"],
      ["Largest animal ever?", "Blue whale", "Sperm whale", "Whale shark", "Giant squid"],
      ["Which parent seahorse gives birth?", "The male", "The female", "Both", "Neither — eggs hatch outside"],
      ["How many arms does an octopus have?", "8", "6", "10", "5"],
      ["Clownfish live among…", "Sea anemones", "Coral caves", "Kelp forests", "Shipwrecks"],
      ["Deepest known point in the ocean?", "Mariana Trench", "Java Trench", "Puerto Rico Trench", "Tonga Trench"],
      ["Dolphins sleep with…", "Half their brain awake", "Both eyes open", "No sleep at all", "Only 10 minutes a day"],
      ["Shark skeletons are made of…", "Cartilage", "Bone", "Shell", "Cartoon — they have none"],
      ["Sea turtles return to lay eggs…", "At the beach where they hatched", "Anywhere warm", "Only once ever", "In deep water"],
      ["Jellyfish are about how much water?", "95%", "60%", "75%", "40%"],
      ["How much of Earth is ocean?", "About 71%", "About 50%", "About 60%", "About 85%"],
    ],
  },
  {
    id: "india-kids", name: "India for Kids", icon: "🇮🇳",
    desc: "National symbols, cities and firsts — how well do you know India?",
    rows: [
      ["National animal of India?", "Tiger", "Lion", "Elephant", "Peacock"],
      ["National bird of India?", "Peacock", "Sparrow", "Parrot", "Eagle"],
      ["The Taj Mahal is in…", "Agra", "Delhi", "Jaipur", "Hyderabad"],
      ["National flower of India?", "Lotus", "Rose", "Sunflower", "Jasmine"],
      ["India's currency is the…", "Rupee", "Taka", "Dinar", "Yuan"],
      ["Capital of India?", "New Delhi", "Mumbai", "Kolkata", "Chennai"],
      ["India's first Prime Minister?", "Jawaharlal Nehru", "Sardar Patel", "Dr. Rajendra Prasad", "Lal Bahadur Shastri"],
      ["Longest river in India?", "Ganga", "Yamuna", "Godavari", "Brahmaputra"],
      ["ISRO's headquarters are in…", "Bengaluru", "Mumbai", "Chennai", "Hyderabad"],
      ["India's flag was designed by…", "Pingali Venkayya", "Rabindranath Tagore", "Bankim Chandra", "Sardar Patel"],
      ["Chennai was formerly called…", "Madras", "Calcutta", "Bombay", "Pondicherry"],
      ["The Ashoka Chakra has how many spokes?", "24", "22", "26", "20"],
    ],
  },
  {
    id: "inventions-kids", name: "Who Invented It?", icon: "💡",
    desc: "Match the invention to its brilliant inventor",
    rows: [
      ["Telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Marconi"],
      ["Practical light bulb?", "Thomas Edison", "Benjamin Franklin", "James Watt", "Nikola Tesla"],
      ["First powered aeroplane?", "Wright brothers", "Amelia Earhart", "Howard Hughes", "Igor Sikorsky"],
      ["Radio?", "Guglielmo Marconi", "John Baird", "Heinrich Hertz", "David Sarnoff"],
      ["Printing press?", "Johannes Gutenberg", "Leonardo da Vinci", "Aldus Manutius", "Caxton"],
      ["World Wide Web?", "Tim Berners-Lee", "Vint Cerf", "Bill Gates", "Larry Page"],
      ["Dynamite?", "Alfred Nobel", "Rudolf Diesel", "Nikola Tesla", "Alfred Krupp"],
      ["Penicillin?", "Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Robert Koch"],
      ["X-rays?", "Wilhelm Röntgen", "Marie Curie", "Niels Bohr", "Max Planck"],
      ["First computer programmer?", "Ada Lovelace", "Alan Turing", "Grace Hopper", "Charles Babbage"],
      ["Telescope pointed at the sky first?", "Galileo Galilei", "Copernicus", "Kepler", "Newton"],
      ["Steam engine improved for industry?", "James Watt", "Thomas Newcomen", "George Stephenson", "Richard Trevithick"],
    ],
  },
  {
    id: "body-basics", name: "My Body", icon: "🫀",
    desc: "Bones, blood and brains — the machine you live in",
    rows: [
      ["Which organ pumps blood?", "Heart", "Lungs", "Liver", "Brain"],
      ["How many bones does an adult have?", "206", "300", "186", "256"],
      ["Which body part controls everything?", "Brain", "Heart", "Spine", "Eyes"],
      ["How many milk teeth do kids have?", "20", "32", "16", "24"],
      ["Largest organ of the body?", "Skin", "Liver", "Brain", "Lungs"],
      ["The coloured part of the eye is the…", "Iris", "Pupil", "Retina", "Cornea"],
      ["Universal donor blood group?", "O negative", "AB positive", "A positive", "B negative"],
      ["Smallest bone is in the…", "Ear", "Nose", "Wrist", "Toe"],
      ["Fingernails grow faster than…", "Toenails", "Hair", "Skin", "Bones"],
      ["The body is about how much water?", "60%", "40%", "80%", "25%"],
      ["Which muscle never gets tired?", "The heart", "The tongue", "The jaw", "The legs"],
      ["Adults have how many teeth?", "32", "28", "30", "36"],
    ],
  },
  {
    id: "earth-wonders", name: "Earth Wonders", icon: "🏔️",
    desc: "Mountains, rivers and records of our planet",
    rows: [
      ["Which planet do we live on?", "Earth", "Mars", "Venus", "Jupiter"],
      ["Earth's shape is best described as…", "A sphere (round)", "Flat", "A cube", "An oval disc"],
      ["Tallest mountain above sea level?", "Mount Everest", "K2", "Kangchenjunga", "Denali"],
      ["How many continents are there?", "7", "5", "6", "8"],
      ["How many oceans are there?", "5", "4", "3", "7"],
      ["Largest hot desert?", "Sahara", "Thar", "Gobi", "Kalahari"],
      ["Longest river in the world?", "The Nile", "The Amazon", "The Yangtze", "The Ganga"],
      ["Deepest point on Earth's surface?", "Mariana Trench", "Death Valley", "Caspian Sea", "Dead Sea"],
      ["The imaginary line around Earth's middle?", "The equator", "The meridian", "The axis", "The orbit"],
      ["The North Star is also called…", "Polaris", "Sirius", "Orion", "Vega"],
      ["Earth takes how long to orbit the Sun?", "365.25 days", "360 days", "370 days", "350 days"],
      ["Largest cold desert?", "Antarctica", "Gobi", "Arctic tundra", "Patagonia"],
    ],
  },
  {
    id: "cartoon-world", name: "Cartoon World", icon: "🧸",
    desc: "Characters, pets and sidekicks from your favourite shows",
    rows: [
      ["Who is Mickey Mouse's creator company?", "Disney", "Warner Bros", "Nickelodeon", "Pixar"],
      ["Tom chases which mouse?", "Jerry", "Nibbles", "Speedy", "Pinky"],
      ["Doraemon is a robot from which century?", "22nd", "21st", "20th", "25th"],
      ["What does Chhota Bheem love to eat?", "Laddoos", "Samosas", "Jalebis", "Chikki"],
      ["Spider-Man's real name?", "Peter Parker", "Tony Stark", "Bruce Banner", "Steve Rogers"],
      ["Batman protects which city?", "Gotham", "Metropolis", "New York", "Star City"],
      ["Superman is weakened by…", "Kryptonite", "Silver", "Water", "Iron"],
      ["Pikachu is which type of Pokémon?", "Electric", "Fire", "Water", "Grass"],
      ["Elsa from Frozen has powers over…", "Ice and snow", "Fire", "Wind", "Water"],
      ["SpongeBob lives in a…", "Pineapple", "Mushroom", "Shell", "Coconut"],
      ["Scooby-Doo loves…", "Scooby Snacks", "Pizza", "Bones only", "Carrots"],
      ["Shin-chan's family name?", "Nohara", "Yamada", "Sato", "Tanaka"],
    ],
  },
  {
    id: "story-morals", name: "Story Morals", icon: "📖",
    desc: "Classic fables — remember how each story ends and what it teaches",
    rows: [
      ["Tortoise and the Hare teaches…", "Slow and steady wins", "Fastest always wins", "Never race", "Sleep mid-race"],
      ["The thirsty crow used…", "Pebbles to raise water", "A straw", "Its wings", "A bucket"],
      ["Boy who cried wolf teaches…", "Liars aren't believed", "Wolves are scary", "Never herd sheep", "Shout loudly"],
      ["Lion and the Mouse teaches…", "Even small friends help", "Lions are kind", "Never nap", "Mice are brave"],
      ["Ant and the Grasshopper teaches…", "Work today, rest later", "Sing all summer", "Winter is fun", "Share everything"],
      ["The Golden Goose teaches…", "Greed loses everything", "Golden is best", "Birds are lucky", "Feathers fly"],
      ["Bundle of Sticks teaches…", "Unity is strength", "Wood burns fast", "Old men are wise", "Sticks break alone — so stay alone"],
      ["Milkmaid and her Pail teaches…", "Don't count before it happens", "Milk is precious", "Walk carefully", "Dreams come true"],
      ["Fox and the Grapes teaches…", "Sour grapes — pretending not to care", "Grapes are sour", "Foxes can't jump", "Vineyards are tall"],
      ["Honest Woodcutter teaches…", "Honesty is rewarded", "Axes float", "Rivers grant wishes", "Gold beats silver"],
      ["Greedy Dog and the Bone teaches…", "Greed loses what you have", "Dogs can't swim", "Bones float", "Bridges are tricky"],
      ["The Boy Who Cried Wolf — what did he shout?", "Wolf! Wolf!", "Fire! Fire!", "Help! Help!", "Thief! Thief!"],
    ],
  },
  {
    id: "money-kids", name: "Money Basics", icon: "🪙",
    desc: "Saving, spending and smart habits with money",
    rows: [
      ["India's currency symbol?", "₹", "$", "€", "¥"],
      ["A piggy bank is used to…", "Save coins", "Cook food", "Store toys", "Water plants"],
      ["ATM stands for a machine that gives…", "Cash", "Advice", "Toys", "Tickets"],
      ["A price tag shows the…", "Cost", "Weight", "Colour", "Size"],
      ["A wallet is used to carry…", "Money and cards", "Books", "Food", "Keys only"],
      ["Savings means money you…", "Keep for later", "Spend today", "Lose", "Lend to shops"],
      ["Interest is extra money the bank…", "Pays you for saving", "Charges for fun", "Prints", "Gives everyone equally"],
      ["A budget is a…", "Plan for your money", "Type of wallet", "Bank building", "Currency"],
      ["UPI is a way to…", "Pay instantly from a phone", "Post letters", "Buy gold only", "Book trains only"],
      ["A debit card spends…", "Your own money", "The bank's money", "Imaginary money", "Only coins"],
      ["Inflation means prices…", "Rise over time", "Stay same forever", "Fall every year", "Only rise on Sundays"],
      ["GST is a tax collected in…", "India", "Only the USA", "Antarctica", "No country"],
    ],
  },
  {
    id: "good-habits", name: "Good Habits", icon: "🌟",
    desc: "Daily habits that make every day better",
    rows: [
      ["Brush your teeth…", "Twice a day", "Once a week", "Only mornings", "Never"],
      ["Before eating you should…", "Wash your hands", "Watch TV", "Run around", "Sleep"],
      ["The magic words when asking are…", "Please", "Now", "Quick", "Give"],
      ["When a friend wins you should…", "Congratulate them", "Ignore", "Get angry", "Brag"],
      ["When someone speaks you should…", "Listen", "Interrupt", "Leave", "Hum"],
      ["A tidy room helps you…", "Find things", "Lose things", "Sleep late", "Argue"],
      ["Saving part of pocket money is…", "A great habit", "Wasteful", "Scary", "Only for adults"],
      ["When you make a mistake you should…", "Apologise", "Hide", "Blame others", "Cry only"],
      ["Waiting your turn is called…", "Patience", "Laziness", "Fear", "Slowness"],
      ["Telling the truth even when hard is…", "Honesty", "Rudeness", "Weakness", "Bragging"],
      ["Reusing paper and plastic is…", "Recycling", "Wasting", "Hoarding", "Polluting"],
      ["Helping without being asked shows…", "Kindness", "Weakness", "Fear", "Pride"],
    ],
  },
  {
    id: "transport", name: "Things That Go", icon: "🚗",
    desc: "Cars, trains, planes — how we move around the world",
    rows: [
      ["How many wheels does a car usually have?", "4", "3", "6", "2"],
      ["You pedal a…", "Bicycle", "Bus", "Ship", "Rocket"],
      ["Trains run on…", "Tracks", "Roads", "Water", "Clouds"],
      ["Which vehicle flies?", "Aeroplane", "Ship", "Bus", "Tank"],
      ["Which travels on water?", "Ship", "Train", "Truck", "Cycle"],
      ["Which vehicle takes emergencies to hospital?", "Ambulance", "Fire truck", "Taxi", "Scooter"],
      ["Which vehicle travels underwater?", "Submarine", "Ship", "Yacht", "Ferry"],
      ["Helicopters fly using…", "Rotors (blades)", "Sails", "Wheels", "Balloons"],
      ["A metro is a train that often runs…", "Under the city", "On the sea", "In the sky", "On ropes"],
      ["A ferry carries people…", "Across water", "Across mountains", "To the moon", "Through tunnels only"],
      ["Which vehicle goes to space?", "Rocket", "Plane", "Helicopter", "Jet"],
      ["Which moves people up and down a building?", "Lift (elevator)", "Escalator only", "Crane", "Conveyor"],
    ],
  },
  {
    id: "shapes-colours", name: "Shapes & Colours", icon: "🔺",
    desc: "Sides, colours and mixing — the basics of art and geometry",
    rows: [
      ["How many sides does a triangle have?", "3", "4", "2", "5"],
      ["How many sides does a square have?", "4", "3", "5", "6"],
      ["How many colours in a rainbow?", "7", "5", "6", "8"],
      ["What colour is grass?", "Green", "Blue", "Yellow", "Red"],
      ["What colour do you get mixing red and blue?", "Purple", "Green", "Orange", "Brown"],
      ["A shape with no corners is a…", "Circle", "Square", "Triangle", "Hexagon"],
      ["Red + yellow makes…", "Orange", "Purple", "Green", "Pink"],
      ["Blue + yellow makes…", "Green", "Purple", "Orange", "Grey"],
      ["How many sides does a hexagon have?", "6", "5", "7", "8"],
      ["A stop sign is a…", "Octagon", "Hexagon", "Circle", "Square"],
      ["Red, blue and yellow are called…", "Primary colours", "Mixed colours", "Cool colours", "Pastel colours"],
      ["White light passed through a prism makes…", "A rainbow", "A shadow", "A laser", "Black light"],
    ],
  },
  {
    id: "music-kids", name: "Music Notes", icon: "🎵",
    desc: "Instruments, notes and sound basics",
    rows: [
      ["How many strings does a standard guitar have?", "6", "4", "5", "7"],
      ["A piano has how many keys?", "88", "76", "61", "100"],
      ["Sound travels through…", "Air", "Nothing at all", "Only water", "Only metal"],
      ["A violin's bow is strung with…", "Horsehair", "Steel", "Nylon", "Cotton"],
      ["Which instrument do you beat?", "Drums", "Flute", "Sitar", "Piano"],
      ["The flute is played by…", "Blowing air across it", "Plucking", "Hammering", "Bowing"],
      ["Beethoven famously composed while…", "Deaf", "Blind", "Sleeping", "Travelling"],
      ["How many notes are in a standard scale?", "7", "5", "8", "12"],
      ["The tabla is a pair of…", "Drums", "Flutes", "Strings", "Bells"],
      ["The treble clef is also called the…", "G clef", "F clef", "C clef", "B clef"],
      ["A slow, soft song for babies is a…", "Lullaby", "Anthem", "Ballad", "Chorus"],
      ["Which instrument has black and white keys?", "Piano", "Harp", "Guitar", "Veena"],
    ],
  },
  {
    id: "weather-watch", name: "Weather Watch", icon: "🌦️",
    desc: "Clouds, rain and why the sky does what it does",
    rows: [
      ["Rain falls from…", "Clouds", "Stars", "Mountains", "Birds"],
      ["The Sun gives us…", "Light and heat", "Only light", "Rain", "Wind"],
      ["A rainbow needs sun and…", "Rain", "Snow", "Wind", "Clouds only"],
      ["Lightning is seen before thunder because…", "Light travels faster than sound", "Thunder waits", "Clouds hide sound", "Ears are slow"],
      ["Snow is…", "Frozen ice crystals", "Soft rain", "Cloud dust", "White sand"],
      ["Wind is…", "Moving air", "Pushing trees", "Hot water", "Sky noise"],
      ["A storm's towering cloud is called…", "Cumulonimbus", "Cirrus", "Stratus", "Nimbus junior"],
      ["Fog is a cloud…", "At ground level", "Only in mountains", "Made of smoke", "That rains"],
      ["Hail is…", "Balls of ice", "Frozen snow", "Heavy rain", "Dew"],
      ["India's seasonal rains are the…", "Monsoon", "Alize", "Chinook", "Zephyr"],
      ["Temperature is measured with a…", "Thermometer", "Barometer", "Anemometer", "Hygrometer"],
      ["Water freezing point?", "0°C", "10°C", "-10°C", "4°C"],
    ],
  },
  {
    id: "science-sparks", name: "Science Sparks", icon: "🔬",
    desc: "Everyday physics and chemistry — why things happen",
    rows: [
      ["Water freezes at…", "0°C", "100°C", "32°C", "-32°C"],
      ["Water boils at…", "100°C", "0°C", "50°C", "212°C"],
      ["Ice…", "Floats on water", "Sinks", "Dissolves instantly", "Burns"],
      ["Magnets attract…", "Iron", "Wood", "Plastic", "Glass"],
      ["Light travels…", "Faster than sound", "Slower than sound", "Same as sound", "Only in water"],
      ["Plants release which gas?", "Oxygen", "Carbon dioxide", "Nitrogen", "Helium"],
      ["Gravity was famously linked to a falling…", "Apple", "Feather", "Ball", "Star"],
      ["Sound cannot travel through…", "A vacuum (space)", "Water", "Steel", "Air"],
      ["Normal human body temperature is about…", "37°C", "30°C", "40°C", "45°C"],
      ["Photosynthesis needs…", "Sunlight", "Moonlight", "Darkness", "Heat only"],
      ["Friction…", "Slows things down", "Speeds things up", "Makes light", "Makes gravity"],
      ["Which gas do we breathe in?", "Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    ],
  },
  {
    id: "computers-kids", name: "Computer Basics", icon: "💻",
    desc: "The parts, the words and how it all fits together",
    rows: [
      ["The computer's brain is the…", "CPU", "Mouse", "Screen", "Keyboard"],
      ["You type on a…", "Keyboard", "Monitor", "Printer", "Speaker"],
      ["You click with a…", "Mouse", "Keyboard", "Camera", "Mic"],
      ["The screen is also called the…", "Monitor", "CPU", "Disk", "Port"],
      ["The internet connects…", "Computers worldwide", "Only phones", "Only India", "Only shops"],
      ["Email stands for…", "Electronic mail", "Emergency mail", "Extra mail", "Easy mail"],
      ["RAM is…", "Temporary memory", "A screen type", "A port", "Permanent storage"],
      ["You visit websites using a…", "Browser", "Modem", "Router", "Scanner"],
      ["Junk email is called…", "Spam", "Toast", "Cache", "Ping"],
      ["USB stands for…", "Universal Serial Bus", "United System Board", "Ultra Save Button", "Useful Small Box"],
      ["Web pages are written in…", "HTML", "Hindi", "Excel", "Photoshop"],
      ["AI stands for…", "Artificial Intelligence", "Automatic Internet", "Apple Inside", "Advanced Icons"],
    ],
  },
  {
    id: "jobs-people-do", name: "Jobs People Do", icon: "👷",
    desc: "Who does what — from chefs to coders",
    rows: [
      ["Who cooks in a restaurant?", "Chef", "Farmer", "Pilot", "Dentist"],
      ["Who flies planes?", "Pilot", "Sailor", "Driver", "Captain of ship only"],
      ["Who fixes teeth?", "Dentist", "Doctor", "Surgeon", "Optician"],
      ["Who teaches in school?", "Teacher", "Principal only", "Coach", "Librarian"],
      ["Who treats animals?", "Veterinarian", "Doctor", "Trainer", "Groomer"],
      ["Who puts out fires?", "Firefighter", "Police", "Soldier", "Lifeguard"],
      ["Who studies stars?", "Astronomer", "Astrologer", "Geologist", "Biologist"],
      ["Who digs up ancient things?", "Archaeologist", "Historian", "Miner", "Curator"],
      ["Who gives out medicines at a pharmacy?", "Pharmacist", "Nurse", "Dentist", "Delivery person"],
      ["Who fixes wires?", "Electrician", "Plumber", "Carpenter", "Welder"],
      ["Who fixes pipes?", "Plumber", "Electrician", "Painter", "Mason"],
      ["Who reports the news?", "Journalist", "Newsreader", "Editor", "Publisher"],
    ],
  },
  {
    id: "sports-kids", name: "Sports Corner", icon: "🏏",
    desc: "Rules, records and legends across the field",
    rows: [
      ["Sachin Tendulkar played…", "Cricket", "Hockey", "Football", "Tennis"],
      ["How many players per football team?", "11", "9", "10", "12"],
      ["The Olympics happen every…", "4 years", "2 years", "3 years", "5 years"],
      ["In tennis, 'love' means…", "Zero", "One", "Deuce", "Ace"],
      ["A T20 match has how many overs per side?", "20", "15", "25", "50"],
      ["Badminton uses a…", "Shuttlecock", "Ball", "Frisbee", "Puck"],
      ["Usain Bolt's record is in…", "100m sprint", "Marathon", "Long jump", "High jump"],
      ["India's first Cricket World Cup win was…", "1983", "1975", "1992", "2011"],
      ["Michael Phelps is famous in…", "Swimming", "Boxing", "Cycling", "Rowing"],
      ["India has won how many hockey Olympic golds?", "8", "5", "6", "11"],
      ["A basketball hoop is how high?", "10 feet", "8 feet", "12 feet", "9 feet"],
      ["Kabaddi raiders chant…", "Kabaddi kabaddi", "Go go go", "One two three", "Hut hut"],
    ],
  },
  {
    id: "fruits-veggies", name: "Fruits & Veggies", icon: "🍎",
    desc: "Peel the facts — from mangoes to mushrooms",
    rows: [
      ["Which fruit is yellow and curved?", "Banana", "Mango", "Papaya", "Pear"],
      ["Which is a citrus fruit?", "Orange", "Banana", "Apple", "Grape"],
      ["Botanically, a tomato is a…", "Fruit", "Vegetable", "Root", "Leaf"],
      ["Which grows underground?", "Potato", "Apple", "Beans", "Tomato"],
      ["Which has the most water?", "Watermelon", "Banana", "Dry dates", "Rice"],
      ["Which fruit has seeds outside?", "Strawberry", "Mango", "Banana", "Orange"],
      ["Brinjal is also called…", "Eggplant", "Zucchini", "Squash", "Pepper"],
      ["A pineapple takes about how long to grow?", "2 years", "2 months", "2 weeks", "10 years"],
      ["Cutting which makes you cry?", "Onion", "Potato", "Carrot", "Beetroot"],
      ["India's national fruit?", "Mango", "Banana", "Apple", "Jackfruit"],
      ["Carrots were originally…", "Purple", "Orange only", "Blue", "Black"],
      ["An avocado is botanically a…", "Berry", "Nut", "Vegetable", "Drupe"],
    ],
  },
];
