export default [
  {
    category: "Image & Vision",
    type: "image",
    icon: "Image",
    groups: [
      {
        verbs: [
          [
            "Upscale",
            "Upscaling",
            "increase resolution and recover fine detail in",
            "Say the target resolution and how much invented detail is acceptable.",
            "the upscaled file plus a short note on which details were reconstructed",
          ],
          [
            "Enhance",
            "Enhance",
            "sharpen, denoise and improve overall quality of",
            "Point out which flaw bothers you most — noise, softness, or color cast.",
            "a cleaned-up version with a before/after quality comparison",
          ],
          [
            "Restore",
            "Restore",
            "repair damage, scratches and compression artifacts in",
            "Flag the worst-damaged regions so restoration effort focuses there first.",
            "a restored image with a log of every repaired area",
          ],
          [
            "Colorize",
            "Colorize",
            "add natural, believable color to",
            "Mention any known colors (clothing, walls, eyes) to anchor accuracy.",
            "a colorized image plus a palette explaining color choices",
          ],
          [
            "RemoveBg",
            "Background Removal",
            "cut out the subject and remove the background from",
            "Specify the export format needed — transparent PNG or a solid fill color.",
            "a clean cutout with alpha transparency ready for compositing",
          ],
          [
            "Relight",
            "Relighting",
            "re-light the scene with soft, controllable studio lighting for",
            "Describe the mood you want — bright and even, or moody and directional.",
            "a relit image and a note on the simulated light setup",
          ],
          [
            "Retouch",
            "Retouch",
            "apply natural, non-plastic retouching to",
            "Tell it how far to go, since over-smoothing looks fake fast.",
            "a subtly retouched photo that still looks like a real photo",
          ],
          [
            "Describe",
            "Captioning",
            "write a precise, alt-text ready description of",
            "Say whether the caption is for accessibility, SEO, or a caption feed.",
            "a concise description plus a shorter alt-text variant",
          ],
          [
            "StyleTransfer",
            "Style Transfer",
            "restyle while preserving structure and composition of",
            "Name the reference style or artist so the transfer has a clear target.",
            "a restyled image that keeps the original composition intact",
          ],
          [
            "Variations",
            "Variations",
            "produce four distinct creative variations of",
            "Clarify what should stay fixed versus what's free to change across variants.",
            "four visibly distinct variations with a one-line rationale each",
          ],
        ],
        objects: [
          [
            "Portrait",
            "a portrait photo",
            "portrait, people",
            "headshot.jpg — 820×820, soft window light, slight noise",
          ],
          [
            "Product",
            "a product photo",
            "ecommerce, product",
            "sneaker-01.png — white seamless background, harsh flash reflection on toe",
          ],
          [
            "Screenshot",
            "a UI screenshot",
            "ui, screenshot",
            "dashboard-dark.png — 1440×900, compressed twice, visible JPEG banding",
          ],
          [
            "Logo",
            "a logo or mark",
            "branding, logo",
            "acme-logo.svg exported to PNG, faded edges from an old fax scan",
          ],
          [
            "Scan",
            "a scanned page or photo",
            "scan, archive",
            "family-photo-1978.tif — creased, sepia shift, dust specks",
          ],
          [
            "Landscape",
            "a landscape or scenery shot",
            "landscape, nature",
            "coastline-sunset.jpg — 4000×2600, blown-out sky highlights",
          ],
        ],
      },
    ],
  },
  {
    category: "Documents & OCR",
    type: "document",
    icon: "FileText",
    groups: [
      {
        verbs: [
          [
            "Extract",
            "Extraction",
            "pull clean, structured text out of",
            "Specify which fields or sections matter most so nothing gets dropped.",
            "structured plain text plus a field-by-field extraction map",
          ],
          [
            "OCR",
            "OCR",
            "run high-accuracy OCR over",
            "Note the source language and scan quality so recognition tunes correctly.",
            "a searchable text layer aligned to the original page layout",
          ],
          [
            "Summarize",
            "Summaries",
            "produce a faithful, citation-anchored summary of",
            "Give a target length — one paragraph, one page, or bullet list.",
            "a summary with inline references back to source pages",
          ],
          [
            "Outline",
            "Outlines",
            "build a hierarchical outline of",
            "Say how many heading levels you need for the outline depth.",
            "a nested outline mirroring the document's actual structure",
          ],
          [
            "Tabulate",
            "Tables",
            "detect and convert every table inside",
            "Mention the desired output format — CSV, Markdown, or Excel.",
            "each detected table exported cleanly with headers preserved",
          ],
          [
            "Redact",
            "Redaction",
            "find and mask personal or sensitive data in",
            "List which data categories count as sensitive for this document.",
            "a redacted copy plus an audit list of what was masked",
          ],
          [
            "Compare",
            "Diffing",
            "diff two versions and list every substantive change in",
            "Upload both versions and say if formatting-only changes should be ignored.",
            "a change log grouped by addition, deletion, and edit",
          ],
          [
            "Classify",
            "Classification",
            "label document type, topic and confidence for",
            "Share the set of allowed categories if you already have a taxonomy.",
            "a classification label with a confidence score and rationale",
          ],
          [
            "Translate",
            "Translation",
            "translate while keeping layout and terminology of",
            "State the target language and any terms that must stay untranslated.",
            "a translated document with the original layout preserved",
          ],
          [
            "QA",
            "Question Answering",
            "answer questions strictly grounded in",
            "Ask specific questions rather than open-ended ones for tighter answers.",
            "direct answers with the exact source passage cited for each",
          ],
        ],
        objects: [
          ["Pdf", "a PDF file", "pdf", "q3-report.pdf — 42 pages, mixed scanned and native text"],
          [
            "Invoice",
            "an invoice or receipt",
            "finance, invoice",
            "vendor-invoice-2291.pdf — line items, tax, and a handwritten total",
          ],
          [
            "Contract",
            "a contract or agreement",
            "legal, contract",
            "msa-draft-v3.docx — 18 clauses, redlines from last review",
          ],
          [
            "Handwritten",
            "handwritten notes",
            "handwriting, notes",
            "meeting-notes.jpg — cursive, blue ink, coffee stain on corner",
          ],
          [
            "Slides",
            "a slide deck",
            "slides, deck",
            "board-deck-q2.pptx — 30 slides, dense charts on slides 12-18",
          ],
          [
            "Form",
            "a filled-in form",
            "forms, intake",
            "intake-form-scan.pdf — checkboxes, signature field, faint print",
          ],
        ],
      },
    ],
  },
  {
    category: "Writing & Communication",
    type: "text",
    icon: "PenLine",
    groups: [
      {
        verbs: [
          [
            "Draft",
            "Drafting",
            "write a strong first draft of",
            "Give the goal, audience, and any must-include points up front.",
            "a complete first draft ready for your edits",
          ],
          [
            "Rewrite",
            "Rewriting",
            "rewrite for clarity and rhythm",
            "Paste the current version and flag any sentences that feel clunky.",
            "a rewritten version with smoother flow and tighter phrasing",
          ],
          [
            "Shorten",
            "Editing",
            "cut length by half without losing meaning in",
            "State the hard word or character limit you need to hit.",
            "a trimmed version at roughly half the original length",
          ],
          [
            "Expand",
            "Editing",
            "add depth, examples and specifics to",
            "Say which points feel thin so the added detail lands there.",
            "an expanded draft with concrete examples woven in",
          ],
          [
            "Tone",
            "Tone",
            "adjust tone and register of",
            "Name the target tone precisely, like 'warmer but still professional'.",
            "a tone-adjusted version plus a note on what shifted",
          ],
          [
            "Proofread",
            "Proofreading",
            "fix grammar, spelling and punctuation in",
            "Mention if you're using US or UK spelling conventions.",
            "a corrected version with a list of the errors found",
          ],
          [
            "Simplify",
            "Clarity",
            "rewrite at a plain-language reading level",
            "Specify the target reading grade level or audience literacy.",
            "a simplified rewrite plus its estimated reading level",
          ],
          [
            "Headline",
            "Headlines",
            "generate ten sharp headline options for",
            "Share the core hook or angle you want emphasized.",
            "ten distinct headline options ranked by strength",
          ],
          [
            "Hook",
            "Hooks",
            "write scroll-stopping opening lines for",
            "Say which platform this opens on, since hooks differ by format.",
            "several opening-line options built for fast attention capture",
          ],
          [
            "Polish",
            "Polish",
            "do a final line-edit pass on",
            "Note if this is the truly final draft so edits stay minimal and safe.",
            "a polished near-final version with minimal, surgical changes",
          ],
        ],
        objects: [
          [
            "Email",
            "an email",
            "email",
            '"Following up on the proposal we sent Tuesday — any updates?"',
          ],
          [
            "Essay",
            "an essay",
            "essay, longform",
            "college-essay-draft.docx — 650 words on overcoming a setback",
          ],
          [
            "Post",
            "a social post",
            "social",
            '"Just shipped our biggest update yet 🚀 here\'s what changed:"',
          ],
          [
            "Story",
            "a short story",
            "fiction, story",
            "the-last-lighthouse.txt — 2,400 words, unfinished ending",
          ],
          [
            "Bio",
            "a personal or company bio",
            "bio, profile",
            '"Jordan is a product designer who loves ceramics and trail running."',
          ],
          [
            "Report",
            "a written report",
            "report",
            "incident-report-draft.md — 6 sections, missing a conclusion",
          ],
        ],
      },
    ],
  },
  {
    category: "Research & Knowledge",
    type: "research",
    icon: "Search",
    groups: [
      {
        verbs: [
          [
            "Research",
            "Deep Research",
            "run a structured research pass on",
            "Give the scope and depth you need, from a quick scan to exhaustive.",
            "a structured research report organized by subtopic",
          ],
          [
            "FactCheck",
            "Verification",
            "verify every claim and rate confidence for",
            "Paste the exact claims or the text containing them.",
            "a claim-by-claim verdict with confidence and source links",
          ],
          [
            "Sources",
            "Sourcing",
            "find and rank credible primary sources for",
            "Say what counts as credible here — academic, official, or press.",
            "a ranked source list with credibility notes for each",
          ],
          [
            "Compare",
            "Comparison",
            "build a side-by-side comparison table for",
            "List the specific items and the criteria to compare them on.",
            "a comparison table with a short recommendation summary",
          ],
          [
            "Timeline",
            "Timelines",
            "assemble a dated timeline of",
            "Give the date range so the timeline doesn't sprawl too wide.",
            "a dated timeline with sourced events in chronological order",
          ],
          [
            "LitReview",
            "Literature",
            "write a mini literature review on",
            "Mention any papers you already know of to anchor the search.",
            "a mini literature review with themes and key citations",
          ],
          [
            "Gaps",
            "Gap Analysis",
            "identify open questions and knowledge gaps in",
            "Share what's already well established so gaps are truly novel.",
            "a list of open questions ranked by research value",
          ],
          [
            "Brief",
            "Briefings",
            "write a one-page decision brief on",
            "State who the brief is for and what decision it should support.",
            "a one-page brief with a clear recommendation at the top",
          ],
          [
            "Debate",
            "Perspectives",
            "argue both sides fairly on",
            "Name the two positions if there are more than two plausible ones.",
            "a balanced two-sided argument with the strongest points each way",
          ],
          [
            "Glossary",
            "Glossaries",
            "define the key vocabulary of",
            "Say the audience level so definitions aren't too technical or too basic.",
            "an alphabetized glossary with plain-language definitions",
          ],
        ],
        objects: [
          ["Topic", "a topic", "topic", '"the economics of vertical farming"'],
          ["Market", "a market", "market", '"the US electric bike market, 2024–2026"'],
          [
            "Paper",
            "an academic paper",
            "academic, paper",
            "attention-is-all-you-need.pdf — 15 pages, dense math notation",
          ],
          ["Company", "a company", "company", '"Anthropic\'s public funding and product history"'],
          [
            "Technology",
            "a technology",
            "tech",
            '"solid-state EV batteries and their production readiness"',
          ],
          [
            "Policy",
            "a policy or regulation",
            "policy",
            '"EU AI Act, Title III, high-risk system obligations"',
          ],
        ],
      },
    ],
  },
  {
    category: "Data & Analytics",
    type: "data",
    icon: "Database",
    groups: [
      {
        verbs: [
          [
            "Clean",
            "Cleaning",
            "normalize, dedupe and fix types in",
            "Point out known dirty fields like inconsistent dates or duplicate rows.",
            "a cleaned dataset plus a log of every transformation applied",
          ],
          [
            "Profile",
            "Profiling",
            "profile distributions, nulls and outliers in",
            "Say which columns matter most if the dataset is very wide.",
            "a column-by-column profile with distributions and flagged outliers",
          ],
          [
            "Chart",
            "Visualization",
            "recommend and specify the right chart for",
            "Describe the story you want the chart to tell, not just the data.",
            "a chart specification plus a rendered preview",
          ],
          [
            "Pivot",
            "Reshaping",
            "pivot and aggregate",
            "Name the rows, columns, and aggregation metric you want.",
            "a pivoted table with the requested aggregations applied",
          ],
          [
            "Join",
            "Joining",
            "plan a safe join strategy across",
            "List the join keys and whether any are known to be imperfect.",
            "a join plan plus a warning list of potential row multiplication",
          ],
          [
            "Validate",
            "Validation",
            "write validation rules for",
            "Share business rules the data must satisfy, like ranges or uniqueness.",
            "a validation ruleset plus a report of current rule violations",
          ],
          [
            "Explain",
            "Explanation",
            "explain in plain English what is happening in",
            "Say what level of technical detail your audience can follow.",
            "a plain-English explanation with the key numbers called out",
          ],
          [
            "Forecast",
            "Forecasting",
            "produce a simple baseline forecast from",
            "Give the forecast horizon and any known seasonality.",
            "a baseline forecast with confidence bands and key assumptions",
          ],
          [
            "Anomaly",
            "Anomalies",
            "detect anomalies and explain each one in",
            "Mention the sensitivity level so normal noise isn't flagged.",
            "a list of anomalies each with a plausible cause",
          ],
          [
            "Schema",
            "Schema",
            "infer a typed schema and dictionary for",
            "Note if any fields have hidden meaning not obvious from the name.",
            "an inferred schema with types and a data dictionary",
          ],
        ],
        objects: [
          [
            "Csv",
            "a CSV file",
            "csv",
            "orders-2024.csv — 40,000 rows, mixed date formats in column D",
          ],
          [
            "Table",
            "a database table",
            "sql, table",
            "public.users — 2.1M rows, nullable email column",
          ],
          [
            "Json",
            "a JSON payload",
            "json",
            "webhook-payload.json — nested 4 levels deep, 12 event types",
          ],
          [
            "Spreadsheet",
            "a spreadsheet",
            "excel, sheets",
            "budget-2025.xlsx — 6 tabs, formulas breaking on tab 3",
          ],
          [
            "Logs",
            "application logs",
            "logs, observability",
            "api-error.log — 90MB, spikes at 03:00 UTC daily",
          ],
          [
            "Survey",
            "survey results",
            "survey",
            "nps-survey-responses.csv — 512 responses, free-text comments",
          ],
        ],
      },
      {
        verbs: [
          [
            "Analyze",
            "Analysis",
            "break down structure, drivers and implications of",
            "Say what decision this analysis needs to inform.",
            "a structured breakdown of drivers with clear implications",
          ],
          [
            "Critique",
            "Critique",
            "give a candid, specific critique of",
            "Ask for both strengths and weaknesses so feedback stays balanced.",
            "a candid critique with specific, actionable points",
          ],
          [
            "Risks",
            "Risk",
            "surface the top risks and mitigations in",
            "State your risk tolerance so severity ratings calibrate correctly.",
            "a ranked risk list each paired with a concrete mitigation",
          ],
          [
            "Assumptions",
            "Assumptions",
            "list and stress-test the assumptions behind",
            "Flag which assumptions you already suspect are shaky.",
            "a list of assumptions each stress-tested against a failure case",
          ],
          [
            "RootCause",
            "Root Cause",
            "run a five-whys root-cause analysis on",
            "Describe the observed symptom precisely, not just the general area.",
            "a five-whys chain ending in an actionable root cause",
          ],
          [
            "SWOT",
            "Frameworks",
            "produce a SWOT analysis of",
            "Give the competitive context so strengths and threats are relative.",
            "a filled SWOT grid with the top item highlighted per quadrant",
          ],
          [
            "Score",
            "Scoring",
            "score against explicit weighted criteria",
            "Provide the criteria and their weights, or ask for a suggested set.",
            "a weighted score plus the breakdown behind the final number",
          ],
          [
            "Sentiment",
            "Sentiment",
            "measure sentiment and emotional drivers in",
            "Say whether you need an aggregate score or per-item sentiment.",
            "a sentiment score with the phrases that drove it most",
          ],
          [
            "Themes",
            "Themes",
            "cluster recurring themes across",
            "Mention roughly how many themes you expect to keep clusters useful.",
            "clustered themes each with representative quotes",
          ],
          [
            "Decide",
            "Decisions",
            "recommend a decision with tradeoffs for",
            "Lay out the real options on the table, even the unpopular ones.",
            "a recommended decision with the key tradeoffs made explicit",
          ],
        ],
        objects: [
          [
            "Feedback",
            "customer feedback",
            "voc, feedback",
            '"Support was slow but the product itself saved us hours weekly."',
          ],
          [
            "Strategy",
            "a strategy document",
            "strategy",
            "gtm-strategy-2025.pdf — 12 pages, three market segments",
          ],
          [
            "Plan",
            "a project plan",
            "planning",
            "migration-plan.md — 8 phases, two owners unassigned",
          ],
          ["Pitch", "a pitch", "pitch", "seed-deck.pdf — 14 slides, traction slide looks weak"],
          [
            "Transcript",
            "a meeting transcript",
            "meeting, transcript",
            "standup-call-0619.vtt — 22 minutes, 4 speakers",
          ],
          [
            "Metrics",
            "a set of metrics",
            "metrics, kpi",
            "weekly-kpis.csv — churn up 1.2%, activation flat for 3 weeks",
          ],
        ],
      },
    ],
  },
];
