export default [
  {
    category: "Design & Creative",
    type: "image",
    icon: "Palette",
    groups: [
      {
        verbs: [
          ["Moodboard", "Moodboards", "assemble a moodboard direction for", "Share reference images or brands whose vibe you want to chase.", "a moodboard with 8-12 curated visuals and a written rationale"],
          ["Palette", "Color", "propose an accessible color palette for", "Name the brand mood and any fixed brand colors you must keep.", "a 6-swatch palette with hex values and WCAG contrast pairings"],
          ["Typography", "Type", "pair and scale typography for", "Specify the platforms (web, print, app) the type must render on.", "a type scale with two paired fonts and size/weight tokens"],
          ["Layout", "Layout", "propose a responsive layout grid for", "State the breakpoints and content blocks the layout must hold.", "a grid spec with columns, gutters and breakpoint rules"],
          ["Critique", "Critique", "give an honest design critique of", "Attach the current screens and describe who will see them.", "a prioritized critique list with fixes for each issue"],
          ["Icons", "Iconography", "define a consistent icon set for", "List the actions or concepts each icon needs to represent.", "an icon set spec with stroke weight, grid and naming rules"],
          ["Wireframe", "Wireframes", "wireframe the key screens of", "Identify the core user flows the wireframes must cover.", "low-fidelity wireframes for each named screen"],
          ["Motion", "Motion", "specify restrained motion and easing for", "Point out which interactions feel abrupt or need feedback.", "a motion spec with durations, easing curves and triggers"],
          ["DesignSystem", "Systems", "extract reusable design tokens from", "Provide the existing files or screenshots to reverse-engineer.", "a token set covering color, spacing, radius and shadow"],
          ["Darkmode", "Theming", "derive a dark theme from", "Confirm which brand colors must stay untouched in dark mode.", "a dark theme palette with contrast-checked component states"],
        ],
        objects: [
          ["App", "an app UI", "app-ui", "a 5-screen onboarding flow for a habit-tracking app"],
          ["Site", "a website", "web", "the homepage and pricing page of a B2B SaaS marketing site"],
          ["Deck", "a slide deck", "deck", "a 14-slide Series A pitch deck in Google Slides"],
          ["Poster", "a poster", "print, poster", "an A2 concert poster with a 3-color risograph look"],
          ["Brandkit", "a brand kit", "brand", "a startup brand kit with logo, two colors and one typeface"],
          ["Dashboard", "a dashboard", "dashboard", "an ops dashboard with 8 KPI tiles and two time-series charts"],
        ],
      },
    ],
  },
  {
    category: "Audio & Speech",
    type: "audio",
    icon: "AudioLines",
    groups: [
      {
        verbs: [
          ["Transcribe", "Transcription", "transcribe with speaker labels and timestamps", "Upload the audio file and note how many distinct speakers to expect.", "a timestamped transcript with labeled speaker turns"],
          ["Denoise", "Cleanup", "remove hiss, hum and room noise from", "Describe the noise source, like a fan or traffic, in the recording.", "a cleaned audio file with the noise profile removed"],
          ["Summarize", "Summaries", "summarize the key points and decisions in", "Say whether you want bullet points or a narrative summary.", "a short written summary of key points and decisions"],
          ["Chapters", "Chapters", "generate chapter markers for", "Provide the total runtime so chapter spacing feels natural.", "a list of chapter titles with timecodes"],
          ["Script", "Scripting", "write a tight spoken script for", "Give the target runtime and the tone you want spoken aloud.", "a word-for-word spoken script sized to the target runtime"],
          ["Translate", "Translation", "translate and re-time the audio of", "Specify the target language and whether dubbing or subtitles are needed.", "a translated transcript re-timed to the original audio"],
          ["Highlights", "Highlights", "pull the most quotable moments from", "Say how many highlight clips you need and their ideal length.", "a set of timestamped quotable clip picks"],
          ["Levels", "Mastering", "balance levels and loudness for", "State the target platform's loudness standard, like -16 LUFS.", "a loudness-normalized audio file meeting the target spec"],
          ["ShowNotes", "Show Notes", "write show notes with links and timestamps for", "List any guest names, links or sponsors to credit.", "formatted show notes with timestamps and linked references"],
          ["Clean", "Editing", "strip filler words and false starts from", "Flag any sections that must be preserved exactly as recorded.", "an edited audio file with fillers and false starts removed"],
        ],
        objects: [
          ["Podcast", "a podcast episode", "podcast", "episode 42 of a 45-minute weekly interview podcast"],
          ["Interview", "an interview recording", "interview", "a 30-minute recorded job candidate interview"],
          ["Voicenote", "a voice note", "voice-note", "a 2-minute rambling voice memo with three action items"],
          ["Lecture", "a recorded lecture", "lecture", "a 50-minute university lecture on thermodynamics"],
          ["Call", "a recorded call", "call", "a 20-minute customer support escalation call"],
          ["Music", "a music track", "music", "a 3-minute lo-fi instrumental demo with clipping on the bass"],
        ],
      },
    ],
  },
  {
    category: "Video",
    type: "video",
    icon: "Clapperboard",
    groups: [
      {
        verbs: [
          ["Storyboard", "Storyboards", "storyboard shot by shot", "Describe the narrative beats or script you already have.", "a shot-by-shot storyboard with framing notes"],
          ["Script", "Scripting", "write a timed script for", "Give the target length in seconds or minutes.", "a timed script with on-screen and voiceover lines"],
          ["Cutdown", "Editing", "propose a tight cut-down edit of", "Share the source runtime and your target final length.", "an edit decision list trimming to the target length"],
          ["Captions", "Captions", "generate accurate burned-in captions for", "Specify the caption style, font and safe-zone requirements.", "a caption file synced to the video timeline"],
          ["Thumbnail", "Thumbnails", "design thumbnail concepts for", "Share the video title and target platform for sizing.", "three thumbnail concepts with layout and text overlay notes"],
          ["Hooks", "Hooks", "write three-second hooks for", "Name the audience you need to stop from scrolling.", "five three-second hook lines with delivery notes"],
          ["Repurpose", "Repurposing", "repurpose into platform-native clips", "List the target platforms, like TikTok, Reels or Shorts.", "a set of platform-sized clip cuts with captions"],
          ["Describe", "Metadata", "write title, description and tags for", "Give the core topic and any keywords to include.", "an optimized title, description and tag list"],
          ["Pacing", "Pacing", "analyse pacing and retention risk in", "Share the viewer drop-off graph if you have one.", "a pacing report flagging slow sections and drop-off risk"],
          ["Shotlist", "Production", "build a shot list and gear list for", "Describe the locations and cast available for the shoot.", "a numbered shot list with a matching gear checklist"],
        ],
        objects: [
          ["Reel", "a short vertical video", "shorts, reels", "a 22-second product teaser reel for Instagram"],
          ["Tutorial", "a tutorial video", "tutorial", "a 9-minute screen-recorded Figma tutorial"],
          ["Ad", "a video ad", "ads", "a 15-second pre-roll ad for a fitness app"],
          ["Demo", "a product demo", "demo", "a 4-minute walkthrough demo of a checkout flow"],
          ["Vlog", "a vlog", "vlog", "a 12-minute day-in-the-life travel vlog from Lisbon"],
          ["Explainer", "an explainer video", "explainer", "a 90-second animated explainer for a fintech onboarding flow"],
        ],
      },
    ],
  },
  {
    category: "Marketing & SEO",
    type: "business",
    icon: "Megaphone",
    groups: [
      {
        verbs: [
          ["Campaign", "Campaigns", "plan a full campaign for", "Give the campaign goal, budget range and target launch date.", "a campaign plan with channels, timeline and budget split"],
          ["Copy", "Copywriting", "write conversion-focused copy for", "Share the offer and the single action you want readers to take.", "conversion-focused copy with a clear call to action"],
          ["Seo", "SEO", "build an SEO keyword and content plan for", "Provide your domain and top three competitor URLs.", "a keyword map with search volume and a content brief list"],
          ["Calendar", "Planning", "build a 30-day content calendar for", "Name the platforms and posting cadence you can sustain.", "a 30-day calendar with post topics and publish dates"],
          ["Ads", "Advertising", "write ad variants with angles for", "Specify the ad platform and any character or format limits.", "five ad variants each testing a distinct angle"],
          ["Funnel", "Funnels", "map the acquisition funnel for", "List your current traffic sources and conversion rates if known.", "a funnel map with stages, drop-off points and fixes"],
          ["Newsletter", "Email Marketing", "write a newsletter issue for", "Give the week's key updates or stories to feature.", "a formatted newsletter issue with subject line options"],
          ["Launch", "Launches", "write a launch plan and assets list for", "State the launch date and the primary announcement channel.", "a launch plan with a timeline and required asset checklist"],
          ["Testimonial", "Social Proof", "turn raw praise into usable social proof for", "Paste the raw customer quotes or reviews to work from.", "polished testimonial snippets formatted for reuse"],
          ["AB", "Experiments", "design A/B test variants for", "Name the metric you're trying to move and current baseline.", "two test variants with a hypothesis and success metric"],
        ],
        objects: [
          ["Brand", "a brand", "brand", "a 2-year-old direct-to-consumer skincare brand"],
          ["Feature", "a new feature", "feature", "a newly shipped bulk-export feature in a project tool"],
          ["Event", "an event", "event", "a 200-person in-person product launch event"],
          ["Landing", "a landing page", "landing-page", "the signup landing page for a freemium budgeting app"],
          ["Newsletter", "a newsletter", "newsletter", "a weekly 3,000-subscriber B2B newsletter"],
          ["Creator", "a creator account", "creator", "a 40k-follower TikTok account in the cooking niche"],
        ],
      },
    ],
  },
  {
    category: "Automation & Workflows",
    type: "productivity",
    icon: "Workflow",
    groups: [
      {
        verbs: [
          ["Automate", "Automation", "design an automation that handles", "Describe the manual steps you currently repeat by hand.", "an automation blueprint replacing the manual steps"],
          ["Trigger", "Triggers", "define triggers and conditions for", "List the events or thresholds that should kick off the process.", "a trigger and condition spec ready to configure"],
          ["Webhook", "Integration", "specify webhook payloads and retries for", "Name the source and destination systems to connect.", "a webhook payload schema with retry and backoff rules"],
          ["Sync", "Syncing", "plan a two-way sync for", "Identify the two systems and which one is the source of truth.", "a sync plan with conflict-resolution rules"],
          ["Notify", "Notifications", "design smart, low-noise notifications for", "State who should be alerted and how urgent each case is.", "a notification rule set with channels and thresholds"],
          ["Batch", "Batching", "batch and schedule repetitive work in", "Give the current frequency and volume of the repetitive task.", "a batching schedule with recommended run windows"],
          ["Failsafe", "Reliability", "add retries, alerts and fallbacks to", "Describe the most common way this process currently fails.", "a reliability plan with retries, alerts and fallback paths"],
          ["Map", "Mapping", "map fields between systems in", "List the field names on both the source and target systems.", "a field mapping table with transform notes"],
          ["Zap", "Recipes", "write a step-by-step no-code recipe for", "Name the no-code tool, like Zapier or Make, you plan to use.", "a numbered no-code recipe ready to rebuild step by step"],
          ["Audit", "Audit", "audit for silent failures in", "Share recent logs or incidents where the process quietly broke.", "an audit report listing silent failure points and fixes"],
        ],
        objects: [
          ["Email", "an email workflow", "email", "an auto-responder sequence for new trial signups"],
          ["Crm", "a CRM process", "crm", "the lead-to-opportunity handoff in a HubSpot pipeline"],
          ["Report", "recurring reporting", "reporting", "a weekly Monday-morning sales report emailed to leadership"],
          ["Intake", "an intake form process", "forms", "a Typeform client intake form feeding into Airtable"],
          ["Backup", "a backup routine", "backup", "a nightly database backup to S3 with 30-day retention"],
          ["Deploy", "a deployment routine", "devops", "a GitHub Actions deploy pipeline for a Node.js API"],
        ],
      },
    ],
  },
];
