/**
 * Catalog part 9 — Content & Social Media, Gaming & Esports, Food & Cooking,
 * Sports & Fitness, Events & Community.
 * Shape: category -> groups -> verbs [name, subcategory, phrase, ask, deliverable]
 *                            -> objects [name, phrase, tags, sample]
 */
export default [
  {
    category: "Content & Social Media",
    type: "text",
    icon: "Megaphone",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Drafting",
            "write a scroll-stopping draft of",
            "Give the topic, tone and platform so the voice matches your audience.",
            "a ready-to-post draft with a strong hook and a clear call to action",
          ],
          [
            "Hook",
            "Drafting",
            "craft a scroll-stopping opening line for",
            "Share the topic and the emotion you want the first line to trigger.",
            "five alternative hook lines ranked by likely engagement",
          ],
          [
            "Caption",
            "Drafting",
            "write punchy caption options for",
            "Describe the image or clip and the vibe you're going for.",
            "three caption variants in different tones with matching hashtags",
          ],
          [
            "Repurpose",
            "Distribution",
            "repurpose across formats the content in",
            "Paste the original piece and list the platforms you want it adapted for.",
            "platform-native rewrites sized for each format's best practices",
          ],
          [
            "Schedule",
            "Planning",
            "build a posting calendar for",
            "Share your goals, posting frequency and any key dates to hit.",
            "a week-by-week content calendar with themes and posting times",
          ],
          [
            "Critique",
            "Editing",
            "give honest editorial feedback on",
            "Paste the draft and mention who the audience is.",
            "line-by-line feedback plus a rewritten stronger version",
          ],
        ],
        objects: [
          ["Reel", "a short vertical video script", "video,social,short-form", "a 30-second reel about morning routines"],
          ["Carousel", "a multi-slide carousel post", "social,visual,slides", "a 7-slide carousel explaining a skincare routine"],
          ["Tweet", "a short punchy post", "social,micro-copy,twitter", "a tweet announcing a product launch"],
          ["LinkedInPost", "a professional networking post", "social,linkedin,b2b", "a linkedin post about a career pivot"],
          ["YouTubeScript", "a talking-head video script", "video,youtube,long-form", "a 5-minute script reviewing a new laptop"],
          ["Newsletter", "an email newsletter issue", "email,newsletter,recurring", "a weekly newsletter recapping industry news"],
          ["BlogPost", "a long-form article", "blog,seo,long-form", "a blog post comparing two project management tools"],
          ["Podcast", "a podcast episode outline", "audio,podcast,outline", "an episode outline interviewing a local chef"],
          ["StoryPost", "a disappearing story sequence", "social,instagram,ephemeral", "a 3-part story teasing a giveaway"],
          ["Bio", "a profile bio", "social,profile,identity", "a bio for a freelance photographer's instagram"],
          ["PressRelease", "a media announcement", "pr,media,announcement", "a press release for a new app feature"],
          ["ComментReply", "a public reply to a comment", "social,engagement,reply", "a reply to a customer complaint on facebook"],
        ],
      },
      {
        verbs: [
          [
            "Grow",
            "Strategy",
            "build a growth strategy for",
            "Share your current following, niche and biggest bottleneck.",
            "a 90-day growth plan with weekly experiments to run",
          ],
          [
            "Analyze",
            "Analytics",
            "break down the performance metrics of",
            "Paste the analytics screenshot or numbers you have.",
            "a plain-language breakdown of what's working and what to cut",
          ],
          [
            "Brand",
            "Identity",
            "define the visual and tonal identity for",
            "Describe your niche, values and any accounts you admire.",
            "a brand voice guide with tone words and content pillars",
          ],
          [
            "Monetize",
            "Revenue",
            "map monetization options for",
            "Share your audience size, niche and current income sources.",
            "a ranked list of monetization paths with realistic income estimates",
          ],
          [
            "Collaborate",
            "Partnerships",
            "draft a collaboration pitch for",
            "Name the creator or brand and what you'd bring to the partnership.",
            "a pitch message plus three collab format ideas",
          ],
          [
            "Audit",
            "Analytics",
            "audit the health of",
            "Share the profile link or recent stats you want reviewed.",
            "a profile audit with quick wins ranked by effort",
          ],
        ],
        objects: [
          ["TikTokAccount", "a short-video creator account", "tiktok,creator,growth", "a tiktok account posting comedy sketches"],
          ["InstagramProfile", "a photo and reels profile", "instagram,creator,growth", "an instagram profile for a fitness coach"],
          ["YouTubeChannel", "a video channel", "youtube,creator,growth", "a youtube channel reviewing tech gadgets"],
          ["TwitchStream", "a live streaming channel", "twitch,streaming,gaming", "a twitch channel streaming indie games"],
          ["PodcastShow", "a recurring audio show", "podcast,audio,growth", "a podcast about true crime stories"],
          ["Substack", "a paid newsletter publication", "newsletter,writing,subscription", "a substack about personal finance"],
          ["FacebookGroup", "a community group page", "facebook,community,group", "a facebook group for local parents"],
          ["PinterestBoard", "a curated visual board", "pinterest,visual,curation", "a pinterest board for wedding decor ideas"],
          ["DiscordServer", "a community chat server", "discord,community,chat", "a discord server for a gaming clan"],
          ["OnlineCourse", "a paid educational offering", "course,education,revenue", "an online course teaching watercolor painting"],
          ["MerchLine", "a branded product line", "merch,ecommerce,branding", "a merch line for a comedy podcast"],
          ["AffiliateLinks", "a set of referral partnerships", "affiliate,revenue,links", "affiliate links for camera gear reviews"],
        ],
      },
      {
        verbs: [
          [
            "Moderate",
            "CommunityOps",
            "draft moderation guidelines for",
            "Describe your community's tone and the worst incidents so far.",
            "a moderation policy with escalation steps and sample warnings",
          ],
          [
            "Respond",
            "CommunityOps",
            "write a response strategy for",
            "Paste the message or situation you need to respond to.",
            "a calm, on-brand response plus two alternate tones",
          ],
          [
            "Localize",
            "Distribution",
            "adapt for a new market",
            "Share the source content and the target country or language.",
            "a culturally adapted version with notes on what changed and why",
          ],
          [
            "Test",
            "Optimization",
            "design an A/B test for",
            "Share the current version and the metric you're trying to improve.",
            "two variants to test plus how to read the results",
          ],
          [
            "Trend",
            "Research",
            "spot trending angles for",
            "Share your niche and the platform you're focused on.",
            "five trending angles with why each fits your audience right now",
          ],
          [
            "Archive",
            "Documentation",
            "organize a content archive for",
            "Describe how much content you have and how it's currently stored.",
            "a tagged, searchable archive structure with a naming convention",
          ],
        ],
        objects: [
          ["CommunityGuidelines", "rules for member behavior", "community,rules,moderation", "guidelines for a book club discord"],
          ["CrisisComms", "a response to negative press", "crisis,pr,response", "a response to a viral customer complaint"],
          ["FAQPage", "a frequently asked questions page", "faq,support,copy", "an faq page for a subscription box service"],
          ["AdCopy", "paid advertisement text", "ads,copy,paid-media", "ad copy for a summer sale on sneakers"],
          ["EmailSequence", "an automated email series", "email,automation,sequence", "a 5-email welcome sequence for new subscribers"],
          ["Livestream", "a real-time broadcast", "livestream,video,realtime", "a livestream q&a about a product launch"],
          ["UserGeneratedContent", "content made by fans", "ugc,community,fans", "user-generated content contest for a coffee brand"],
          ["InfluencerBrief", "instructions for a paid creator", "influencer,brief,marketing", "a brief for an influencer promoting skincare"],
          ["ContentPillars", "core recurring themes", "strategy,pillars,planning", "content pillars for a personal finance page"],
          ["Rebrand", "an identity overhaul", "rebrand,identity,strategy", "a rebrand of a food blog into a lifestyle brand"],
          ["ViralMoment", "a sudden spike in attention", "viral,momentum,opportunity", "a viral moment after a video got 2 million views"],
          ["MediaKit", "a pitch document for brands", "mediakit,sponsorship,pitch", "a media kit for a travel influencer"],
        ],
      },
    ],
  },
  {
    category: "Gaming & Esports",
    type: "general",
    icon: "Gamepad2",
    groups: [
      {
        verbs: [
          [
            "Strategize",
            "Gameplay",
            "build a winning strategy for",
            "Share your rank, role and the matchup you're struggling with.",
            "a step-by-step strategy with common counters to watch for",
          ],
          [
            "Analyze",
            "Gameplay",
            "break down gameplay footage or stats from",
            "Paste the replay link, stats, or describe what happened.",
            "a breakdown of key mistakes and three concrete fixes",
          ],
          [
            "Build",
            "Loadouts",
            "optimize the loadout or build for",
            "Share your playstyle, current build and the content you're tackling.",
            "an optimized build with item/skill order and situational swaps",
          ],
          [
            "Coach",
            "Improvement",
            "coach a beginner through",
            "Share the player's current skill level and their main frustration.",
            "a practice plan with drills ordered from easiest to hardest",
          ],
          [
            "Predict",
            "Meta",
            "forecast the shifting meta around",
            "Share the current patch notes or season you're asking about.",
            "a meta forecast with which strategies to pick up or drop",
          ],
          [
            "Explain",
            "Mechanics",
            "explain the underlying mechanics of",
            "Say what confuses you and how much you already know.",
            "a clear mechanical breakdown with a practical example",
          ],
        ],
        objects: [
          ["RankedMatch", "a competitive ladder game", "ranked,competitive,pvp", "a ranked match that ended in a close loss"],
          ["BossFight", "a difficult single-player encounter", "boss,pve,single-player", "a boss fight with a tricky second phase"],
          ["DraftPick", "a champion or hero selection", "draft,moba,pick-ban", "a draft pick against a strong counter-pick team"],
          ["Speedrun", "a timed completion attempt", "speedrun,timing,optimization", "a speedrun route through the game's second level"],
          ["TeamComp", "a group of chosen characters", "team,composition,synergy", "a team comp built around crowd control"],
          ["Patch", "a game update with balance changes", "patch,balance,update", "a patch that nerfed the top-tier weapon"],
          ["Tournament", "a competitive bracket event", "tournament,esports,bracket", "a tournament with a double-elimination bracket"],
          ["Build", "a character equipment setup", "build,itemization,loadout", "a build focused on critical hit damage"],
          ["Map", "a game level or arena", "map,level,arena", "a map with three chokepoints and one open lane"],
          ["Economy", "the in-game resource system", "economy,resources,strategy", "an economy round in a tactical shooter"],
          ["Combo", "a chained sequence of moves", "combo,fighting-game,execution", "a combo that requires precise frame timing"],
          ["Scrim", "a practice match against another team", "scrim,practice,team", "a scrim against a rival team before playoffs"],
        ],
      },
      {
        verbs: [
          [
            "Cast",
            "Broadcasting",
            "write commentary for",
            "Describe the match context and the players or teams involved.",
            "play-by-play commentary lines with hype moments called out",
          ],
          [
            "Recruit",
            "TeamOps",
            "draft a recruitment pitch for",
            "Share your team's goals, region and the role you're filling.",
            "a recruitment post plus screening questions for applicants",
          ],
          [
            "Schedule",
            "Operations",
            "plan the logistics for",
            "Share dates, participant count and any venue constraints.",
            "a full event schedule with buffer time and contingency slots",
          ],
          [
            "Sponsor",
            "Business",
            "draft a sponsorship pitch for",
            "Share your audience size, past results and what you're asking for.",
            "a sponsorship deck outline with tiered offer packages",
          ],
          [
            "Rulebook",
            "Operations",
            "write the official rules for",
            "Share the game, format and any past disputes to prevent.",
            "a rulebook covering format, conduct and tie-breakers",
          ],
          [
            "Hype",
            "Marketing",
            "create hype content for",
            "Share the event date, participants and any storylines.",
            "a countdown content plan with key promotional beats",
          ],
        ],
        objects: [
          ["LANEvent", "an in-person competitive event", "lan,event,esports", "a lan event for a regional fighting game circuit"],
          ["OnlineLeague", "a recurring remote competition", "league,online,recurring", "an online league running for 8 weeks"],
          ["EsportsTeam", "a professional or amateur roster", "team,roster,esports", "an esports team looking for a fifth player"],
          ["StreamSetup", "broadcasting equipment and layout", "stream,broadcast,setup", "a stream setup for casting a valorant match"],
          ["PrizePool", "the reward fund for winners", "prizepool,rewards,tournament", "a prize pool split across top four teams"],
          ["Bracket", "the tournament matchup structure", "bracket,tournament,format", "a bracket for a 32-team single elimination cup"],
          ["CasterDuo", "a pair of live commentators", "casters,commentary,broadcast", "a caster duo covering a grand finals match"],
          ["FanEvent", "a community meetup for fans", "fanevent,community,gaming", "a fan event with a meet-and-greet with pros"],
          ["Roster", "the full list of team players", "roster,team,management", "a roster change after a player retires"],
          ["Contract", "a player or sponsor agreement", "contract,legal,esports", "a contract for a new starting player"],
          ["MatchOfficials", "referees and rule enforcers", "officials,rules,fairness", "match officials for a regional qualifier"],
          ["Watchparty", "a group viewing event", "watchparty,community,event", "a watchparty for the world championship finals"],
        ],
      },
      {
        verbs: [
          [
            "Design",
            "GameDesign",
            "prototype the design of",
            "Describe the genre, core loop and the feeling you want players to have.",
            "a design doc outline with the core loop and progression system",
          ],
          [
            "Balance",
            "GameDesign",
            "rebalance the numbers in",
            "Share the current stats or rules causing complaints.",
            "a rebalance proposal with before/after numbers and reasoning",
          ],
          [
            "Narrate",
            "Storytelling",
            "write the lore and story beats for",
            "Share the setting, tone and any characters already established.",
            "a story outline with key beats and one twist",
          ],
          [
            "Monetize",
            "GameDesign",
            "design an ethical monetization model for",
            "Share your genre, player base size and revenue goals.",
            "a monetization plan avoiding predatory mechanics",
          ],
          [
            "Playtest",
            "QA",
            "design a playtest plan for",
            "Share what you want feedback on and how many testers you have.",
            "a playtest script with specific questions to ask testers",
          ],
          [
            "Market",
            "Marketing",
            "write a launch marketing plan for",
            "Share your release date, platform and target audience.",
            "a launch plan with a content calendar and key beats",
          ],
        ],
        objects: [
          ["IndieGame", "a small independent game project", "indie,development,design", "an indie game about a lonely lighthouse keeper"],
          ["MobileGame", "a smartphone-based game", "mobile,casual,f2p", "a mobile game with match-three puzzle mechanics"],
          ["GameJamEntry", "a rapid-prototype competition entry", "gamejam,prototype,rapid", "a game jam entry made in 48 hours"],
          ["LevelDesign", "the layout of a playable stage", "level,design,layout", "level design for a stealth-based platformer"],
          ["CharacterAbility", "a special player power or skill", "ability,character,mechanics", "a character ability that freezes enemies briefly"],
          ["QuestLine", "a chain of in-game missions", "quest,narrative,rpg", "a questline about recovering a stolen artifact"],
          ["ProgressionSystem", "the way players level up", "progression,leveling,rpg", "a progression system with skill trees"],
          ["InGamePurchase", "a paid digital add-on", "iap,monetization,economy", "an in-game purchase for cosmetic skins"],
          ["BetaTest", "an early player testing phase", "beta,testing,feedback", "a beta test for an upcoming survival game"],
          ["GameTrailer", "a promotional video", "trailer,marketing,video", "a game trailer revealing the release date"],
          ["ModSupport", "community-made game modifications", "mods,community,customization", "mod support for a sandbox building game"],
          ["Achievement", "an in-game accomplishment badge", "achievement,rewards,design", "an achievement for completing the game without dying"],
        ],
      },
    ],
  },
  {
    category: "Food & Cooking",
    type: "general",
    icon: "ChefHat",
    groups: [
      {
        verbs: [
          [
            "Cook",
            "Recipes",
            "write a step-by-step recipe for",
            "Share dietary restrictions, skill level and what you have on hand.",
            "a full recipe with timings, substitutions and a plating tip",
          ],
          [
            "Substitute",
            "Adjustments",
            "find smart substitutions for",
            "Say what's missing and any allergies or preferences to respect.",
            "three substitute options ranked by how close they taste",
          ],
          [
            "Scale",
            "Adjustments",
            "scale the serving size of",
            "Share the original recipe and the new number of servings.",
            "a rescaled ingredient list with adjusted cook times",
          ],
          [
            "Pair",
            "Pairing",
            "suggest pairings to go with",
            "Share the main dish and whether you want drink or side pairings.",
            "three pairing options with a one-line reason for each",
          ],
          [
            "Troubleshoot",
            "Fixes",
            "diagnose what went wrong with",
            "Describe the result and each step you took while making it",
            "a likely cause plus how to fix it next time",
          ],
          [
            "PlanMenu",
            "Planning",
            "design a full menu around",
            "Share the occasion, guest count and any dietary needs.",
            "a complete menu with a prep timeline working backward from serving time",
          ],
        ],
        objects: [
          ["WeeknightDinner", "a fast everyday meal", "quick,dinner,weeknight", "a weeknight dinner ready in 25 minutes"],
          ["Sourdough", "a fermented bread loaf", "baking,bread,fermentation", "a sourdough loaf with a dense crumb"],
          ["MealPrep", "batch-cooked meals for the week", "mealprep,batch-cooking,planning", "meal prep for five lunches using one protein"],
          ["Dessert", "a sweet finishing course", "dessert,baking,sweet", "a dessert using overripe bananas"],
          ["Soup", "a warm liquid-based dish", "soup,comfort-food,stovetop", "a soup using leftover roast chicken"],
          ["Marinade", "a flavoring soak for protein", "marinade,flavor,prep", "a marinade for grilled chicken thighs"],
          ["Sauce", "a flavor-enhancing liquid or paste", "sauce,condiment,flavor", "a sauce for pasta using pantry staples"],
          ["Salad", "a mixed fresh dish", "salad,fresh,healthy", "a salad using seasonal summer vegetables"],
          ["Cocktail", "a mixed alcoholic drink", "cocktail,drinks,mixology", "a cocktail using gin and fresh citrus"],
          ["Ferment", "a preserved, cultured food", "fermentation,preservation,gut-health", "a ferment of cabbage into kimchi"],
          ["Casserole", "a baked one-dish meal", "casserole,baked,comfort-food", "a casserole using leftover rice and vegetables"],
          ["Smoothie", "a blended fruit or veg drink", "smoothie,breakfast,healthy", "a smoothie for a post-workout breakfast"],
        ],
      },
      {
        verbs: [
          [
            "Host",
            "Entertaining",
            "plan the full hosting logistics for",
            "Share guest count, dietary needs and how much time you have to prep.",
            "a hosting timeline with a shopping list and a do-ahead schedule",
          ],
          [
            "Theme",
            "Entertaining",
            "design a themed food experience for",
            "Share the occasion, guest count and any theme ideas you like.",
            "a themed menu with decor and music suggestions to match",
          ],
          [
            "Budget",
            "Planning",
            "plan a cost-effective menu for",
            "Share your budget, guest count and any must-have dishes.",
            "a budget-conscious menu with a per-person cost estimate",
          ],
          [
            "Batch",
            "Prep",
            "scale a recipe up for a crowd in",
            "Share the original recipe and how many people you're feeding.",
            "a crowd-sized recipe with equipment and timing adjustments",
          ],
          [
            "Present",
            "Presentation",
            "design the presentation and plating for",
            "Describe the dish and the style of tableware you have.",
            "a plating guide with garnish and arrangement suggestions",
          ],
          [
            "Wine",
            "Pairing",
            "select wine or drink pairings for",
            "Share the menu and whether guests prefer red, white or non-alcoholic.",
            "a course-by-course pairing list with why each choice works",
          ],
        ],
        objects: [
          ["DinnerParty", "a small hosted evening meal", "dinnerparty,hosting,entertaining", "a dinner party for six close friends"],
          ["Potluck", "a shared, guest-contributed meal", "potluck,shared,community", "a potluck for a neighborhood block party"],
          ["Barbecue", "an outdoor grilled gathering", "bbq,outdoor,grilling", "a barbecue for a fourth of july cookout"],
          ["Brunch", "a late-morning combined meal", "brunch,morning,gathering", "a brunch for a baby shower"],
          ["HolidayFeast", "a large seasonal celebration meal", "holiday,feast,celebration", "a holiday feast for twelve people at thanksgiving"],
          ["WineTasting", "a curated drink sampling event", "winetasting,event,pairing", "a wine tasting with five regional varietals"],
          ["FoodTruckMenu", "a compact mobile vendor menu", "foodtruck,menu,street-food", "a food truck menu for a summer festival"],
          ["CateringOrder", "a bulk food service order", "catering,bulk,event", "a catering order for a 50-person office event"],
          ["Picnic", "an outdoor casual meal", "picnic,outdoor,casual", "a picnic for a park afternoon with kids"],
          ["CookingClass", "a guided group cooking session", "cookingclass,teaching,group", "a cooking class teaching handmade pasta"],
          ["TastingMenu", "a multi-course curated meal", "tastingmenu,fine-dining,courses", "a tasting menu with five small courses"],
          ["Cheeseboard", "an arranged board of cheeses and sides", "cheeseboard,appetizer,sharing", "a cheeseboard for a wine and cheese night"],
        ],
      },
      {
        verbs: [
          [
            "Nourish",
            "Nutrition",
            "build a nutrition-focused version of",
            "Share your dietary goals and any restrictions or allergies.",
            "a nutrient breakdown with a version tuned to your goals",
          ],
          [
            "Stock",
            "PantryOps",
            "build a shopping and stocking plan for",
            "Share your budget, household size and how often you shop.",
            "a shopping list organized by store section with a pantry checklist",
          ],
          [
            "Preserve",
            "Storage",
            "plan the best storage method for",
            "Share how much you have and how long you need it to last.",
            "storage instructions with expected shelf life for each method",
          ],
          [
            "Source",
            "Sourcing",
            "find ethical or local sourcing options for",
            "Share your location and what matters most to you when sourcing.",
            "a sourcing guide with local or ethical alternatives ranked",
          ],
          [
            "Reduce",
            "Sustainability",
            "cut food waste around",
            "Describe what typically goes to waste in your kitchen.",
            "a waste-reduction plan with recipes to use up leftovers",
          ],
          [
            "Learn",
            "Technique",
            "teach the technique behind",
            "Say your current skill level and what keeps going wrong.",
            "a step-by-step technique guide with common mistakes to avoid",
          ],
        ],
        objects: [
          ["MealPlan", "a structured weekly eating plan", "mealplan,nutrition,weekly", "a meal plan for a high-protein diet"],
          ["Pantry", "a stock of shelf-stable ingredients", "pantry,storage,staples", "a pantry stocked for quick 20-minute meals"],
          ["Leftovers", "food remaining from a previous meal", "leftovers,waste-reduction,reuse", "leftovers from a roast chicken dinner"],
          ["FarmersMarket", "a local fresh produce market", "farmersmarket,local,sourcing", "a farmers market trip in early summer"],
          ["KnifeSkills", "techniques for cutting ingredients", "knifeskills,technique,prep", "knife skills for dicing an onion quickly"],
          ["FermentationCrock", "a vessel for fermenting food", "fermentation,equipment,preservation", "a fermentation crock for homemade sauerkraut"],
          ["SpecialDiet", "an eating plan with restrictions", "diet,restrictions,health", "a special diet plan for gluten intolerance"],
          ["FoodBudget", "planned spending on groceries", "budget,groceries,planning", "a food budget of $75 per week for two people"],
          ["KitchenTools", "cooking equipment and gadgets", "tools,equipment,kitchen", "kitchen tools for a small apartment kitchen"],
          ["SpiceRack", "a collection of seasoning ingredients", "spices,flavor,pantry", "a spice rack missing key baking spices"],
          ["CompostBin", "a container for food scraps", "compost,sustainability,waste", "a compost bin for kitchen scraps"],
          ["FreezerStock", "frozen food inventory", "freezer,storage,batch-cooking", "a freezer stock of pre-portioned soups"],
        ],
      },
    ],
  },
  {
    category: "Sports & Fitness",
    type: "learning",
    icon: "Dumbbell",
    groups: [
      {
        verbs: [
          [
            "Train",
            "Programming",
            "build a progressive training program for",
            "Share your current fitness level, goal and days available per week.",
            "a week-by-week program with sets, reps and progression rules",
          ],
          [
            "Warmup",
            "Preparation",
            "design a warmup routine for",
            "Share the activity and any tight or injury-prone areas.",
            "a 10-minute warmup sequence targeting the right muscle groups",
          ],
          [
            "Recover",
            "Recovery",
            "plan a recovery protocol for",
            "Describe your soreness or injury and your training schedule.",
            "a recovery plan with active rest days and warning signs to watch",
          ],
          [
            "Fuel",
            "Nutrition",
            "plan the nutrition strategy for",
            "Share your goal, weight and training intensity.",
            "a nutrition plan with timing around workouts",
          ],
          [
            "Track",
            "Analytics",
            "build a progress tracking system for",
            "Share what metrics matter most to you and how often you train.",
            "a tracking template with milestones to hit each month",
          ],
          [
            "Correct",
            "Technique",
            "fix the form or technique in",
            "Describe what you feel or share a video description of your movement.",
            "a form correction checklist with cues to fix each issue",
          ],
        ],
        objects: [
          ["StrengthTraining", "resistance-based muscle building", "strength,gym,muscle", "strength training for a beginner with dumbbells only"],
          ["RunningPlan", "a structured running schedule", "running,cardio,endurance", "a running plan to complete a first 10k"],
          ["Yoga", "a flexibility and mindfulness practice", "yoga,flexibility,mindfulness", "a yoga sequence for lower back tightness"],
          ["HIIT", "a high-intensity interval workout", "hiit,cardio,intensity", "a hiit workout with no equipment needed"],
          ["Swimming", "a pool-based cardio activity", "swimming,cardio,technique", "swimming technique for improving freestyle speed"],
          ["Cycling", "a bike-based endurance activity", "cycling,endurance,cardio", "a cycling plan to build up to a century ride"],
          ["Mobility", "joint and muscle range of motion work", "mobility,flexibility,injury-prevention", "mobility work for tight hips from sitting"],
          ["PowerliftingMeet", "a max-strength competition", "powerlifting,competition,strength", "a powerlifting meet with a squat, bench and deadlift"],
          ["HomeWorkout", "an equipment-free exercise routine", "homeworkout,bodyweight,convenience", "a home workout for a small apartment"],
          ["MarathonTraining", "a long-distance race preparation plan", "marathon,endurance,race", "marathon training with a 16-week buildup"],
          ["CoreWorkout", "abdominal and stability training", "core,abs,stability", "a core workout for lower back pain prevention"],
          ["Stretching", "muscle-lengthening movement work", "stretching,flexibility,cooldown", "stretching routine after a long run"],
        ],
      },
      {
        verbs: [
          [
            "Scout",
            "Analysis",
            "scout and analyze the strengths of",
            "Share footage notes or stats about the opponent or player.",
            "a scouting report with strengths, weaknesses and a game plan",
          ],
          [
            "Draft",
            "TeamOps",
            "plan the draft or lineup strategy for",
            "Share your league rules, current roster and priorities.",
            "a draft strategy with ranked targets and backup options",
          ],
          [
            "Officiate",
            "Rules",
            "clarify the rules and calls around",
            "Describe the situation or rule you need clarified.",
            "a clear rules explanation with the correct call and reasoning",
          ],
          [
            "Motivate",
            "Coaching",
            "write a motivational talk for",
            "Share the team's current morale and the situation they're facing.",
            "a short motivational speech tailored to the moment",
          ],
          [
            "Strategize",
            "GamePlan",
            "build the game plan for",
            "Share the opponent, your team's strengths and the format.",
            "a game plan with key matchups and adjustments to make mid-game",
          ],
          [
            "Review",
            "PostGame",
            "break down the performance after",
            "Share the final score and key moments you remember.",
            "a post-game review with what to keep and what to change",
          ],
        ],
        objects: [
          ["FantasyLeague", "a simulated team management league", "fantasy,league,strategy", "a fantasy league draft for the upcoming nfl season"],
          ["YouthTeam", "a team of young athletes", "youth,coaching,development", "a youth soccer team ages 8 to 10"],
          ["RivalryGame", "a high-stakes matchup between rivals", "rivalry,game,competition", "a rivalry game between two neighboring high schools"],
          ["Playoffs", "a postseason elimination series", "playoffs,postseason,competition", "playoffs in a recreational basketball league"],
          ["RosterSpot", "an open roster position", "roster,recruitment,team", "a roster spot strategy for the third overall pick"],
          ["RefereeCall", "an official's in-game decision", "referee,rules,officiating", "a referee call on a disputed offside play"],
          ["TeamRoster", "the full list of team members", "roster,team,management", "a team roster with two injured starters"],
          ["ScoutingReport", "a written analysis of an opponent", "scouting,analysis,opponent", "a scouting report on next week's opponent"],
          ["Timeout", "a strategic pause in play", "timeout,strategy,ingame", "a timeout called down by two points late in the game"],
          ["ChampionshipRun", "a season-long path to a title", "championship,season,competition", "a championship run for an underdog team"],
          ["Halftime", "the midpoint break in a game", "halftime,adjustments,coaching", "a halftime adjustment down by ten points"],
          ["TryoutSession", "a player selection evaluation", "tryouts,selection,evaluation", "a tryout session for a club volleyball team"],
        ],
      },
      {
        verbs: [
          [
            "Rehab",
            "Recovery",
            "design a rehab plan for",
            "Share the injury, how it happened and any doctor's guidance received.",
            "a phased rehab plan with pain-level checkpoints",
          ],
          [
            "Sleep",
            "Recovery",
            "optimize the sleep and rest routine for",
            "Share your training load and current sleep schedule.",
            "a sleep optimization plan aligned to your training days",
          ],
          [
            "Mentalprep",
            "Psychology",
            "build a mental preparation routine for",
            "Share the event and what usually makes you nervous.",
            "a pre-event mental routine with visualization steps",
          ],
          [
            "Gear",
            "Equipment",
            "recommend the right gear for",
            "Share your budget, body type and the conditions you'll train in.",
            "a gear list ranked by priority and price point",
          ],
          [
            "Habit",
            "Consistency",
            "build a habit system to stick with",
            "Share your past attempts and what usually causes you to quit.",
            "a habit-stacking plan with a minimum viable version for bad days",
          ],
          [
            "Measure",
            "Assessment",
            "assess the current baseline for",
            "Share what tests or numbers you already have, if any.",
            "a baseline assessment with which metrics to retest and when",
          ],
        ],
        objects: [
          ["RunningInjury", "a repetitive-strain running ailment", "injury,running,rehab", "a running injury from shin splints"],
          ["SleepSchedule", "a daily rest and wake pattern", "sleep,recovery,routine", "a sleep schedule disrupted by early morning training"],
          ["PreCompetitionNerves", "anxiety before a competitive event", "nerves,mental,competition", "pre-competition nerves before a first triathlon"],
          ["RunningShoes", "footwear for running activity", "shoes,gear,running", "running shoes for someone who overpronates"],
          ["MorningRoutine", "a consistent start-of-day sequence", "routine,habit,morning", "a morning routine to fit in a workout before work"],
          ["FitnessAssessment", "a baseline measurement of ability", "assessment,baseline,fitness", "a fitness assessment for a new gym member"],
          ["OveruseInjury", "damage from repetitive strain", "injury,overuse,rehab", "an overuse injury in the shoulder from swimming"],
          ["HydrationPlan", "a fluid intake strategy", "hydration,nutrition,performance", "a hydration plan for a hot-weather marathon"],
          ["WeightClass", "a competition weight category", "weightclass,combat-sports,cutting", "a weight class cut for an amateur boxing match"],
          ["ActiveRecoveryDay", "a low-intensity rest day", "recovery,rest,activeday", "an active recovery day after a heavy leg workout"],
          ["Concussion", "a head injury from impact", "concussion,injury,safety", "a concussion protocol after a collision in practice"],
          ["EnduranceBase", "the foundational aerobic fitness level", "endurance,base,cardio", "an endurance base before starting speed work"],
        ],
      },
    ],
  },
  {
    category: "Events & Community",
    type: "productivity",
    icon: "CalendarHeart",
    groups: [
      {
        verbs: [
          [
            "Plan",
            "Logistics",
            "build the full logistics plan for",
            "Share the date, guest count and venue you have in mind.",
            "a logistics plan with a timeline, vendor list and backup options",
          ],
          [
            "Budget",
            "Finance",
            "build a realistic budget for",
            "Share your total budget cap and the must-have elements.",
            "a line-item budget with where to splurge and where to save",
          ],
          [
            "Invite",
            "Communications",
            "write the invitation and reminders for",
            "Share the date, tone and any RSVP details guests need.",
            "an invitation plus two reminder messages timed before the event",
          ],
          [
            "Decorate",
            "Design",
            "design the decor and theme for",
            "Share the theme, venue and any colors you want to use.",
            "a decor plan with a shopping list and DIY alternatives",
          ],
          [
            "Schedule",
            "Timeline",
            "build the run-of-show timeline for",
            "Share the start and end time and every activity planned.",
            "a minute-by-minute run-of-show with buffer built in",
          ],
          [
            "Troubleshoot",
            "Contingency",
            "prepare a backup plan for",
            "Share what could go wrong and any constraints you're working with.",
            "a contingency plan covering the top three likely problems",
          ],
        ],
        objects: [
          ["Wedding", "a marriage celebration event", "wedding,celebration,milestone", "a wedding for 120 guests at an outdoor venue"],
          ["BirthdayParty", "a birthday celebration", "birthday,celebration,party", "a birthday party for a turning-30 milestone"],
          ["Fundraiser", "a money-raising community event", "fundraiser,nonprofit,charity", "a fundraiser for a local animal shelter"],
          ["Conference", "a professional gathering with sessions", "conference,professional,networking", "a conference for 300 attendees over two days"],
          ["Reunion", "a gathering of former connections", "reunion,family,nostalgia", "a family reunion with relatives from four states"],
          ["BabyShower", "a celebration before a birth", "babyshower,celebration,family", "a baby shower with a gender-reveal theme"],
          ["GraduationParty", "a celebration of academic completion", "graduation,celebration,milestone", "a graduation party for a high school senior"],
          ["CharityGala", "a formal fundraising evening", "gala,formal,fundraising", "a charity gala with a silent auction"],
          ["CommunityCleanup", "a volunteer neighborhood improvement event", "cleanup,volunteer,community", "a community cleanup of a local park"],
          ["HolidayParty", "a seasonal celebration gathering", "holiday,celebration,seasonal", "a holiday party for a 40-person office"],
          ["Workshop", "a hands-on learning session", "workshop,learning,handson", "a workshop teaching basic pottery skills"],
          ["OpenMicNight", "a live performance event for locals", "openmic,performance,local", "an open mic night at a neighborhood cafe"],
        ],
      },
      {
        verbs: [
          [
            "Recruit",
            "Volunteers",
            "write a volunteer recruitment plan for",
            "Share how many volunteers you need and what roles are open.",
            "a recruitment post plus a role sign-up sheet",
          ],
          [
            "Sponsor",
            "Fundraising",
            "draft a sponsorship pitch for",
            "Share your audience size, past events and what tiers you offer.",
            "a sponsorship pitch with tiered packages and benefits",
          ],
          [
            "Onboard",
            "Membership",
            "design an onboarding flow for new members of",
            "Share how people currently join and where they tend to drop off.",
            "a welcome sequence with a first-week checklist",
          ],
          [
            "Facilitate",
            "Meetings",
            "write a facilitation guide for",
            "Share the group size, purpose and any recurring tension points.",
            "a facilitation script with discussion prompts and time boxes",
          ],
          [
            "Survey",
            "Feedback",
            "design a feedback survey for",
            "Share what decisions the feedback will inform.",
            "a short survey with questions ordered from easy to reflective",
          ],
          [
            "Retain",
            "Engagement",
            "build a retention plan for",
            "Share your current dropout rate and when people tend to leave.",
            "a retention plan with re-engagement touchpoints",
          ],
        ],
        objects: [
          ["NonprofitBoard", "a governing volunteer leadership group", "nonprofit,board,governance", "a nonprofit board planning its annual retreat"],
          ["NeighborhoodAssociation", "a local resident governance group", "neighborhood,association,local", "a neighborhood association addressing parking complaints"],
          ["BookClub", "a recurring reading discussion group", "bookclub,reading,discussion", "a book club meeting monthly to discuss fiction"],
          ["SportsLeague", "an organized recreational league", "sportsleague,recreation,community", "a sports league for adult recreational soccer"],
          ["FaithCommunity", "a religious or spiritual gathering group", "faith,community,spiritual", "a faith community planning a weekend retreat"],
          ["AlumniNetwork", "former students or members group", "alumni,network,connection", "an alumni network hosting a city meetup"],
          ["MeetupGroup", "a recurring interest-based gathering", "meetup,interest,recurring", "a meetup group for local hikers"],
          ["ParentTeacherAssociation", "a school family involvement group", "pta,school,family", "a parent teacher association planning a fall festival"],
          ["SupportGroup", "a peer emotional support circle", "supportgroup,wellbeing,peer", "a support group for new parents"],
          ["HomeownersAssociation", "a residential community governance body", "hoa,residential,governance", "a homeowners association vote on new landscaping rules"],
          ["Cooperative", "a member-owned shared enterprise", "cooperative,shared,membership", "a cooperative planning its annual member meeting"],
          ["CommunityGarden", "a shared local growing space", "garden,community,shared-space", "a community garden assigning plots for spring"],
        ],
      },
      {
        verbs: [
          [
            "Livestream",
            "Broadcast",
            "plan the livestream setup for",
            "Share your platform, expected audience size and equipment on hand.",
            "a livestream checklist with equipment and a run-of-show",
          ],
          [
            "Register",
            "Operations",
            "design the registration flow for",
            "Share expected attendee count and any tiers or pricing.",
            "a registration flow with form fields and confirmation messaging",
          ],
          [
            "Vendor",
            "Procurement",
            "source and coordinate vendors for",
            "Share your budget, location and what services you still need.",
            "a vendor shortlist with questions to ask before booking",
          ],
          [
            "Safety",
            "RiskManagement",
            "build a safety and risk plan for",
            "Share the venue, crowd size and any past incidents.",
            "a safety plan covering crowd control, weather and medical needs",
          ],
          [
            "Followup",
            "PostEvent",
            "write the post-event follow-up for",
            "Share how the event went and what feedback you already received.",
            "a thank-you message plus a feedback request and recap",
          ],
          [
            "Measure",
            "Evaluation",
            "evaluate the success of",
            "Share your original goals and the numbers or feedback you collected.",
            "a post-event report scoring against original goals",
          ],
        ],
        objects: [
          ["VirtualSummit", "an online multi-session conference", "virtual,summit,online", "a virtual summit with speakers across three time zones"],
          ["StreetFestival", "an outdoor public celebration", "festival,outdoor,public", "a street festival with food vendors and live music"],
          ["FiveKRace", "a timed community running event", "5k,race,running", "a 5k race raising money for a school"],
          ["TradeShow", "a business exhibition event", "tradeshow,business,exhibition", "a trade show booth for a small startup"],
          ["FilmScreening", "a public movie viewing event", "filmscreening,movie,public", "a film screening followed by a director q&a"],
          ["AwardsCeremony", "a formal recognition event", "awards,ceremony,recognition", "an awards ceremony for local small businesses"],
          ["HackathonEvent", "a timed collaborative building competition", "hackathon,competition,building", "a hackathon for university students over 24 hours"],
          ["FarmersMarketEvent", "a recurring outdoor vendor market", "farmersmarket,vendors,outdoor", "a farmers market event every saturday morning"],
          ["BlockParty", "a neighborhood street celebration", "blockparty,neighborhood,celebration", "a block party closing off two streets"],
          ["CharityRun", "a fundraising athletic event", "charityrun,fundraising,athletic", "a charity run supporting cancer research"],
          ["PopUpShop", "a temporary retail experience", "popup,retail,temporary", "a pop-up shop for a local artisan collective"],
          ["TownHall", "a public community discussion meeting", "townhall,public,discussion", "a town hall about a proposed zoning change"],
        ],
      },
    ],
  },
];
