export default [
  {
    category: "Web & Frontend",
    type: "coding",
    icon: "Layout",
    groups: [
      {
        verbs: [
          [
            "Build",
            "Components",
            "scaffold a production-ready component for",
            "Describe the props, states and the design system you're using.",
            "a typed component with sensible defaults and usage example",
          ],
          [
            "Style",
            "Styling",
            "write clean, responsive styles for",
            "Share the layout goal and any breakpoints or design tokens to match.",
            "a responsive stylesheet with mobile-first breakpoints",
          ],
          [
            "Refactor",
            "Components",
            "refactor for clarity and smaller units in",
            "Paste the component and note which parts feel tangled.",
            "a split-up component with extracted hooks and clearer naming",
          ],
          [
            "Theme",
            "Styling",
            "add a dark-mode aware theme layer to",
            "Share the current colour palette and any brand constraints.",
            "a theming setup with tokens for light and dark modes",
          ],
          [
            "Animate",
            "Interaction",
            "add tasteful motion and transitions to",
            "Describe the interaction moment you want to feel smoother.",
            "a small animation patch using css transitions or a motion library",
          ],
          [
            "Document",
            "Components",
            "write prop docs and usage examples for",
            "Paste the component source or its prop types.",
            "a documented api reference with copy-paste usage snippets",
          ],
        ],
        objects: [
          [
            "Button",
            "a button component",
            "button,ui,component",
            "a primary cta button with loading and disabled states",
          ],
          [
            "Modal",
            "a modal or dialog",
            "modal,dialog,overlay",
            "a confirmation dialog with focus trap",
          ],
          [
            "Form",
            "a form layout",
            "form,inputs,validation",
            "a signup form with email, password and terms checkbox",
          ],
          [
            "NavBar",
            "a site navigation bar",
            "navbar,navigation,header",
            "a sticky navbar with a mobile hamburger menu",
          ],
          [
            "Card",
            "a content card component",
            "card,layout,ui",
            "a pricing card with a highlighted plan",
          ],
          [
            "Table",
            "a data table component",
            "table,data,grid",
            "a sortable table of 200 customer rows",
          ],
          [
            "Tooltip",
            "a tooltip or popover",
            "tooltip,popover,ui",
            "a hover tooltip explaining a disabled button",
          ],
          [
            "Sidebar",
            "a collapsible sidebar",
            "sidebar,layout,nav",
            "a dashboard sidebar that collapses to icons",
          ],
          [
            "Dropdown",
            "a dropdown or select menu",
            "dropdown,select,menu",
            "a searchable country select dropdown",
          ],
          [
            "Carousel",
            "an image or content carousel",
            "carousel,slider,ui",
            "a product image carousel with dot indicators",
          ],
          [
            "Badge",
            "a status badge component",
            "badge,status,ui",
            "a colored badge showing order status",
          ],
          [
            "Toast",
            "a toast notification system",
            "toast,notification,ui",
            "a stacked toast queue for success and error messages",
          ],
        ],
      },
      {
        verbs: [
          [
            "Audit",
            "Performance",
            "audit for load-time and rendering bottlenecks in",
            "Share the page url or bundle stats and your target load time.",
            "a prioritized list of performance fixes with expected impact",
          ],
          [
            "Optimize",
            "Performance",
            "shrink bundle size and speed up",
            "Paste the build output or dependency list you suspect is bloated.",
            "a smaller bundle with lazy-loaded chunks and removed dead weight",
          ],
          [
            "Improve",
            "Accessibility",
            "raise the accessibility score of",
            "Share the markup and note who uses assistive tech in your audience.",
            "an accessibility patch covering aria labels and focus order",
          ],
          [
            "Lazyload",
            "Performance",
            "defer and lazy-load heavy parts of",
            "List the images, scripts or sections that aren't needed immediately.",
            "a lazy-loading setup with placeholders for below-the-fold content",
          ],
          [
            "Contrast",
            "Accessibility",
            "fix color contrast and readability in",
            "Share the current palette and the wcag level you need to hit.",
            "an adjusted palette meeting wcag aa contrast ratios",
          ],
          [
            "Profile",
            "Performance",
            "profile rendering and re-renders in",
            "Paste the component tree or describe the sluggish interaction.",
            "a render-profile report with the top offenders memoized",
          ],
        ],
        objects: [
          [
            "LandingPage",
            "a marketing landing page",
            "landing,marketing,page",
            "a saas landing page with a hero video and pricing table",
          ],
          [
            "ImageGallery",
            "an image gallery",
            "gallery,images,media",
            "a photography portfolio gallery with 80 images",
          ],
          [
            "Homepage",
            "a website homepage",
            "homepage,website,page",
            "an ecommerce homepage with featured products",
          ],
          [
            "Dashboard",
            "a web dashboard",
            "dashboard,charts,ui",
            "an analytics dashboard with five live charts",
          ],
          [
            "SearchResults",
            "a search results page",
            "search,results,list",
            "a search results page returning 500 items",
          ],
          [
            "Checkout",
            "a checkout flow",
            "checkout,ecommerce,flow",
            "a three-step checkout with payment and shipping",
          ],
          [
            "BlogPost",
            "a blog post page",
            "blog,content,article",
            "a long-form blog post with embedded images",
          ],
          [
            "FontLoading",
            "webfont loading strategy",
            "fonts,typography,perf",
            "three custom webfonts loaded on every page",
          ],
          [
            "VideoPlayer",
            "an embedded video player",
            "video,media,player",
            "an autoplaying product demo video",
          ],
          [
            "InfiniteScroll",
            "an infinite-scroll feed",
            "feed,scroll,list",
            "a social feed loading 20 posts per scroll",
          ],
          [
            "SkipLinks",
            "keyboard navigation and skip links",
            "keyboard,a11y,nav",
            "a multi-section page with no current keyboard shortcuts",
          ],
          [
            "FormFields",
            "accessible form fields",
            "forms,a11y,inputs",
            "a checkout form with unlabeled inputs",
          ],
        ],
      },
      {
        verbs: [
          [
            "Migrate",
            "Frameworks",
            "migrate to the latest patterns in",
            "Share the current framework version and the version you're targeting.",
            "a migration plan with codemods and a list of breaking changes",
          ],
          [
            "Configure",
            "Tooling",
            "set up a solid build configuration for",
            "Describe your deployment target and any plugins you already rely on.",
            "a working config file with sensible defaults and comments",
          ],
          [
            "Convert",
            "Frameworks",
            "convert class-based patterns to modern ones in",
            "Paste the legacy code and note which behaviors must be preserved.",
            "a converted implementation using current framework idioms",
          ],
          [
            "Bundle",
            "Tooling",
            "set up bundling and code-splitting for",
            "Share your entry points and any libraries that should be externalized.",
            "a bundler config with route-based code-splitting",
          ],
          [
            "Lint",
            "Tooling",
            "set up linting and formatting rules for",
            "Share your style preferences or an existing config to extend.",
            "a lint and format config with a fixable rule set",
          ],
          [
            "Upgrade",
            "Frameworks",
            "plan a safe dependency upgrade for",
            "List the current versions and any plugins that might break.",
            "a staged upgrade plan with a rollback checkpoint",
          ],
        ],
        objects: [
          [
            "ReactApp",
            "a react application",
            "react,spa,framework",
            "a react 17 app being moved to react 18",
          ],
          [
            "VueProject",
            "a vue project",
            "vue,framework,spa",
            "a vue 2 options-api project",
          ],
          [
            "NextConfig",
            "a next.js configuration",
            "nextjs,ssr,config",
            "a next.js app router migration from pages router",
          ],
          [
            "ViteSetup",
            "a vite build setup",
            "vite,build,bundler",
            "a webpack project moving to vite",
          ],
          [
            "TailwindConfig",
            "a tailwind css configuration",
            "tailwind,css,config",
            "a tailwind config missing custom design tokens",
          ],
          [
            "ESLintConfig",
            "an eslint configuration",
            "eslint,lint,config",
            "a repo with no shared lint rules across packages",
          ],
          [
            "MonorepoSetup",
            "a frontend monorepo",
            "monorepo,workspaces,tooling",
            "a monorepo with three shared ui packages",
          ],
          [
            "StateManagement",
            "a state management layer",
            "state,redux,store",
            "a redux app being simplified to context and hooks",
          ],
          [
            "RoutingSetup",
            "a client-side routing setup",
            "routing,router,spa",
            "a react-router v5 app needing v6 routes",
          ],
          [
            "TypeScriptMigration",
            "a javascript-to-typescript migration",
            "typescript,migration,types",
            "a 40-file javascript codebase with no type coverage",
          ],
          [
            "CSSArchitecture",
            "a css architecture",
            "css,architecture,styles",
            "a legacy stylesheet with conflicting global classes",
          ],
          [
            "PackageJson",
            "a frontend package.json",
            "npm,dependencies,packagejson",
            "a package.json with 12 outdated major versions",
          ],
        ],
      },
    ],
  },
  {
    category: "Backend & APIs",
    type: "coding",
    icon: "Server",
    groups: [
      {
        verbs: [
          [
            "Design",
            "ApiDesign",
            "design a clean, versioned schema for",
            "Describe the resources involved and who consumes this api.",
            "an api design doc with endpoints, methods and status codes",
          ],
          [
            "Implement",
            "ApiDesign",
            "implement a working handler for",
            "Share the expected request and response shape you want.",
            "a working endpoint implementation with input validation",
          ],
          [
            "Document",
            "ApiDesign",
            "write clear reference docs for",
            "Paste the route definitions or an existing openapi spec.",
            "an openapi-style reference with example requests and responses",
          ],
          [
            "Version",
            "ApiDesign",
            "add a safe versioning strategy to",
            "Describe the breaking change you need to introduce.",
            "a versioning plan that keeps existing clients working",
          ],
          [
            "RateLimit",
            "ApiDesign",
            "add rate limiting and abuse protection to",
            "Share your expected traffic patterns and any abuse you've seen.",
            "a rate-limiting middleware with configurable thresholds",
          ],
          [
            "Validate",
            "ApiDesign",
            "add strict request validation to",
            "Paste the current handler and the fields that must be checked.",
            "a validation layer with clear error messages per field",
          ],
        ],
        objects: [
          [
            "RestEndpoint",
            "a rest api endpoint",
            "rest,api,endpoint",
            "a paginated /users listing endpoint",
          ],
          [
            "GraphQLSchema",
            "a graphql schema",
            "graphql,schema,api",
            "a schema mixing queries and mutations for orders",
          ],
          [
            "WebhookHandler",
            "a webhook receiver",
            "webhook,events,api",
            "a stripe webhook handler for payment events",
          ],
          [
            "AuthEndpoint",
            "an authentication endpoint",
            "auth,login,api",
            "a login endpoint issuing jwt tokens",
          ],
          [
            "FileUploadApi",
            "a file upload endpoint",
            "upload,files,api",
            "an endpoint accepting multipart image uploads",
          ],
          [
            "SearchApi",
            "a search api",
            "search,api,query",
            "a full-text search endpoint over product listings",
          ],
          [
            "PaginationLayer",
            "an api pagination scheme",
            "pagination,api,cursor",
            "an offset-based listing endpoint with 50k rows",
          ],
          [
            "BatchEndpoint",
            "a batch processing endpoint",
            "batch,bulk,api",
            "an endpoint accepting 1000 records per request",
          ],
          [
            "PublicApi",
            "a public developer-facing api",
            "public,developer,api",
            "a third-party integration api with api keys",
          ],
          [
            "InternalService",
            "an internal microservice api",
            "internal,microservice,api",
            "a billing microservice called by three other services",
          ],
          [
            "SSEStream",
            "a server-sent events stream",
            "sse,streaming,realtime",
            "a live order-status streaming endpoint",
          ],
          [
            "gRPCService",
            "a grpc service definition",
            "grpc,protobuf,rpc",
            "a grpc service for inventory lookups",
          ],
        ],
      },
      {
        verbs: [
          [
            "Model",
            "DataLayer",
            "design a normalized schema for",
            "Describe the entities and how they relate to each other.",
            "an entity-relationship schema with keys and constraints",
          ],
          [
            "Index",
            "DataLayer",
            "add performance indexes to",
            "Share the slow queries and current table structure.",
            "an indexing plan with expected query speedups",
          ],
          [
            "Migrate",
            "DataLayer",
            "write a safe migration for",
            "Describe the schema change and current row volume.",
            "a reversible migration script with a rollback path",
          ],
          [
            "Seed",
            "DataLayer",
            "generate realistic seed data for",
            "Describe the volume and variety of records you need.",
            "a seed script producing realistic sample rows",
          ],
          [
            "Optimize",
            "DataLayer",
            "rewrite slow queries against",
            "Paste the query and its current execution plan if you have one.",
            "an optimized query with an explained execution plan",
          ],
          [
            "Backup",
            "DataLayer",
            "design a backup and recovery plan for",
            "Share your uptime requirements and acceptable data loss window.",
            "a backup strategy with recovery time objectives",
          ],
        ],
        objects: [
          [
            "UsersTable",
            "a users database table",
            "users,table,schema",
            "a users table storing profile and auth data",
          ],
          [
            "OrdersSchema",
            "an orders and line-items schema",
            "orders,schema,ecommerce",
            "an orders table joined to line items and products",
          ],
          [
            "PostgresDatabase",
            "a postgres database",
            "postgres,sql,database",
            "a postgres database with 40 tables",
          ],
          [
            "MongoCollection",
            "a mongodb collection",
            "mongodb,nosql,collection",
            "a collection of 2 million event documents",
          ],
          [
            "RedisCache",
            "a redis caching layer",
            "redis,cache,performance",
            "a session cache backed by redis",
          ],
          [
            "ORMModels",
            "orm model definitions",
            "orm,models,prisma",
            "a set of prisma models for a saas app",
          ],
          [
            "DataWarehouse",
            "a data warehouse schema",
            "warehouse,analytics,etl",
            "a star-schema warehouse for sales analytics",
          ],
          [
            "SearchIndex",
            "a search engine index",
            "search,elasticsearch,index",
            "an elasticsearch index of product catalog data",
          ],
          [
            "TimeSeriesStore",
            "a time-series data store",
            "timeseries,metrics,database",
            "a metrics store ingesting 10k points per minute",
          ],
          [
            "MultiTenantSchema",
            "a multi-tenant database schema",
            "multitenant,saas,schema",
            "a shared schema serving 300 tenant orgs",
          ],
          [
            "AuditLogTable",
            "an audit log table",
            "audit,logging,compliance",
            "a table logging every admin action",
          ],
          [
            "ConnectionPool",
            "a database connection pool",
            "connections,pool,performance",
            "a pool exhausting under peak traffic",
          ],
        ],
      },
      {
        verbs: [
          [
            "Secure",
            "Security",
            "close common security holes in",
            "Share the code or flow and any compliance requirements.",
            "a hardened implementation with the vulnerabilities listed",
          ],
          [
            "Authenticate",
            "Auth",
            "add a robust authentication flow to",
            "Describe your user types and preferred login methods.",
            "an authentication flow with token refresh handled",
          ],
          [
            "Authorize",
            "Auth",
            "add fine-grained permission checks to",
            "Describe the roles and the actions each role can take.",
            "a role-based access layer with a permissions matrix",
          ],
          [
            "Encrypt",
            "Security",
            "add encryption for sensitive fields in",
            "List which fields are sensitive and any compliance standard to meet.",
            "an encryption approach with key rotation notes",
          ],
          [
            "Monitor",
            "Reliability",
            "add observability and alerting to",
            "Describe what failure looks like and who should be paged.",
            "a monitoring setup with dashboards and alert thresholds",
          ],
          [
            "Recover",
            "Reliability",
            "add graceful failure handling to",
            "Describe the dependency that sometimes fails and how it fails.",
            "a resilient implementation with retries and fallbacks",
          ],
        ],
        objects: [
          [
            "LoginFlow",
            "a user login flow",
            "login,auth,security",
            "a login flow storing passwords in plain text",
          ],
          [
            "JWTHandling",
            "jwt token handling",
            "jwt,tokens,auth",
            "an api issuing jwts with no expiry",
          ],
          [
            "PermissionsModel",
            "a permissions and roles model",
            "permissions,rbac,roles",
            "an app with only admin and user roles",
          ],
          [
            "PaymentService",
            "a payment processing service",
            "payments,pci,security",
            "a service storing raw card numbers",
          ],
          [
            "PasswordReset",
            "a password reset flow",
            "password,reset,security",
            "a reset flow using guessable tokens",
          ],
          [
            "ApiGateway",
            "an api gateway",
            "gateway,routing,security",
            "a gateway routing to five backend services",
          ],
          [
            "BackgroundJobQueue",
            "a background job queue",
            "queue,jobs,reliability",
            "a job queue that silently drops failed jobs",
          ],
          [
            "ThirdPartyIntegration",
            "a third-party api integration",
            "integration,external,api",
            "an integration that fails when the vendor api is slow",
          ],
          [
            "SecretsManagement",
            "application secrets management",
            "secrets,config,security",
            "a repo with api keys committed to git history",
          ],
          [
            "SessionStore",
            "a user session store",
            "sessions,auth,storage",
            "a session store with no expiry or invalidation",
          ],
          [
            "RateLimitedService",
            "a service under load",
            "load,reliability,scaling",
            "a checkout service that falls over on flash sales",
          ],
          [
            "CircuitBreaker",
            "a circuit-breaker pattern implementation",
            "circuitbreaker,resilience,microservices",
            "a service calling a flaky downstream dependency",
          ],
        ],
      },
    ],
  },
  {
    category: "DevOps & Cloud",
    type: "coding",
    icon: "Cloud",
    groups: [
      {
        verbs: [
          [
            "Automate",
            "CICD",
            "build an automated pipeline for",
            "Describe your current manual steps and how often you deploy.",
            "a ci/cd pipeline config with the stages laid out",
          ],
          [
            "Containerize",
            "CICD",
            "write a production-ready container setup for",
            "Share your runtime, dependencies and startup command.",
            "a dockerfile and compose setup with a small image size",
          ],
          [
            "Deploy",
            "CICD",
            "write a deployment workflow for",
            "Describe your target environment and rollback expectations.",
            "a deployment workflow with health checks and rollback",
          ],
          [
            "Test",
            "CICD",
            "wire automated checks into",
            "Describe your test suite and how long it currently takes.",
            "a pipeline stage running tests with clear pass/fail gating",
          ],
          [
            "Release",
            "CICD",
            "set up versioned releases for",
            "Describe your branching strategy and release cadence.",
            "a release workflow with changelog and semantic versioning",
          ],
          [
            "Cache",
            "CICD",
            "speed up build caching in",
            "Share your current build time and what steps are slowest.",
            "a caching strategy cutting build time significantly",
          ],
        ],
        objects: [
          [
            "GitHubActionsWorkflow",
            "a github actions workflow",
            "github,cicd,actions",
            "a workflow running tests on every pull request",
          ],
          [
            "Dockerfile",
            "a dockerfile",
            "docker,container,dockerfile",
            "a node app dockerfile with a 900mb image",
          ],
          [
            "DockerCompose",
            "a docker-compose setup",
            "docker,compose,local",
            "a compose file running app, db and redis locally",
          ],
          [
            "JenkinsPipeline",
            "a jenkins pipeline",
            "jenkins,cicd,pipeline",
            "a jenkinsfile with manual approval steps",
          ],
          [
            "GitLabCI",
            "a gitlab ci configuration",
            "gitlab,cicd,yaml",
            "a gitlab-ci.yml with slow sequential stages",
          ],
          [
            "ReleaseProcess",
            "a software release process",
            "release,versioning,semver",
            "a manual release process prone to missed steps",
          ],
          [
            "BuildPipeline",
            "a monorepo build pipeline",
            "build,monorepo,pipeline",
            "a pipeline rebuilding every package on each commit",
          ],
          [
            "PreCommitHooks",
            "pre-commit hook setup",
            "precommit,hooks,git",
            "a repo with no enforced formatting before commits",
          ],
          [
            "CanaryDeploy",
            "a canary deployment strategy",
            "canary,deployment,rollout",
            "a deployment that ships to 100% of traffic at once",
          ],
          [
            "ArtifactRegistry",
            "a build artifact registry setup",
            "artifacts,registry,packaging",
            "a registry storing untagged docker images",
          ],
          [
            "FeatureFlagRollout",
            "a feature-flag based rollout",
            "featureflags,rollout,deployment",
            "a risky feature launching to all users simultaneously",
          ],
          [
            "EndToEndPipeline",
            "an end-to-end test pipeline stage",
            "e2e,testing,pipeline",
            "a pipeline with no browser-based test coverage",
          ],
        ],
      },
      {
        verbs: [
          [
            "Provision",
            "Infra",
            "write infrastructure-as-code for",
            "Describe the cloud provider and the resources you need.",
            "an iac module provisioning the described resources",
          ],
          [
            "Scale",
            "Infra",
            "design an auto-scaling strategy for",
            "Share your traffic patterns and peak load numbers.",
            "a scaling policy with thresholds and cooldown periods",
          ],
          [
            "Migrate",
            "Infra",
            "plan a cloud migration for",
            "Describe the current hosting setup and the target provider.",
            "a migration plan with cutover steps and rollback",
          ],
          [
            "Cost",
            "Infra",
            "find cost-saving opportunities in",
            "Share your current cloud bill breakdown by service.",
            "a cost audit with ranked savings opportunities",
          ],
          [
            "Network",
            "Infra",
            "design a secure network topology for",
            "Describe your environments and which services must stay private.",
            "a network diagram with subnets and security groups",
          ],
          [
            "Harden",
            "Infra",
            "apply security best practices to",
            "Share your current configuration and compliance requirements.",
            "a hardened configuration with a checklist of fixes",
          ],
        ],
        objects: [
          [
            "TerraformModule",
            "a terraform module",
            "terraform,iac,infra",
            "a module provisioning a vpc and ec2 instances",
          ],
          [
            "KubernetesCluster",
            "a kubernetes cluster setup",
            "kubernetes,k8s,cluster",
            "a cluster running 12 microservices",
          ],
          [
            "AWSLambda",
            "an aws lambda function",
            "aws,lambda,serverless",
            "a lambda function timing out under load",
          ],
          [
            "LoadBalancer",
            "a load balancer configuration",
            "loadbalancer,networking,infra",
            "a load balancer routing to three app servers",
          ],
          [
            "CloudStorage",
            "a cloud object storage setup",
            "storage,s3,cloud",
            "an s3 bucket storing user-uploaded media",
          ],
          [
            "VPCNetwork",
            "a cloud vpc network",
            "vpc,networking,cloud",
            "a vpc with public and private subnets",
          ],
          [
            "KubernetesHelmChart",
            "a kubernetes helm chart",
            "helm,kubernetes,chart",
            "a helm chart deploying an api and worker",
          ],
          [
            "CloudBudget",
            "a cloud spending budget",
            "cost,budget,cloud",
            "a monthly cloud bill that doubled unexpectedly",
          ],
          [
            "CDNConfig",
            "a cdn configuration",
            "cdn,caching,edge",
            "a cdn serving static assets with poor cache hit rate",
          ],
          [
            "SecretsVault",
            "a secrets vault setup",
            "vault,secrets,infra",
            "a vault storing database credentials for five services",
          ],
          [
            "MultiRegionSetup",
            "a multi-region deployment",
            "multiregion,ha,infra",
            "a single-region app needing failover redundancy",
          ],
          [
            "ServerlessArchitecture",
            "a serverless application architecture",
            "serverless,faas,architecture",
            "an app mixing lambdas, queues and a database",
          ],
        ],
      },
      {
        verbs: [
          [
            "Instrument",
            "Observability",
            "add structured logging and metrics to",
            "Describe what signals matter most for this system.",
            "an instrumented service emitting structured logs and metrics",
          ],
          [
            "Alert",
            "Observability",
            "set up meaningful alerting for",
            "Describe what a real incident looks like versus noise.",
            "an alerting config with thresholds tuned to reduce noise",
          ],
          [
            "Trace",
            "Observability",
            "add distributed tracing across",
            "Describe the request path across your services.",
            "a tracing setup showing latency per service hop",
          ],
          [
            "Diagnose",
            "IncidentResponse",
            "investigate the root cause of an incident in",
            "Share the symptoms, timeline and any logs you have.",
            "a root-cause analysis with a timeline and fix",
          ],
          [
            "Runbook",
            "IncidentResponse",
            "write an incident runbook for",
            "Describe the failure mode and who typically responds.",
            "a step-by-step runbook for responding to this failure",
          ],
          [
            "Postmortem",
            "IncidentResponse",
            "draft a blameless postmortem for",
            "Share what happened, when it was noticed, and how it was fixed.",
            "a postmortem doc with root cause and action items",
          ],
        ],
        objects: [
          [
            "MicroservicesSystem",
            "a microservices system",
            "microservices,observability,tracing",
            "a system of eight services with no shared tracing",
          ],
          [
            "ProductionOutage",
            "a production outage",
            "outage,incident,production",
            "a two-hour checkout outage during a sale",
          ],
          [
            "LatencySpike",
            "a latency spike",
            "latency,performance,incident",
            "an api whose p99 latency tripled overnight",
          ],
          [
            "ErrorBudget",
            "an error budget and slo setup",
            "slo,sla,reliability",
            "a service with no defined slo or error budget",
          ],
          [
            "LogPipeline",
            "a centralized log pipeline",
            "logs,logging,pipeline",
            "logs scattered across ten unindexed servers",
          ],
          [
            "OnCallProcess",
            "an on-call rotation process",
            "oncall,pagerduty,process",
            "an on-call rotation with unclear escalation paths",
          ],
          [
            "MemoryLeak",
            "a memory leak in a running service",
            "memoryleak,debugging,performance",
            "a service whose memory grows steadily over 24 hours",
          ],
          [
            "DatabaseOutage",
            "a database outage",
            "database,outage,incident",
            "a primary database that failed over unexpectedly",
          ],
          [
            "DeploymentRollback",
            "a failed deployment needing rollback",
            "rollback,deployment,incident",
            "a bad deploy causing a spike in 500 errors",
          ],
          [
            "CapacityPlanning",
            "a capacity planning exercise",
            "capacity,scaling,planning",
            "a service expecting 10x traffic during a launch",
          ],
          [
            "SecurityIncident",
            "a security incident",
            "security,incident,breach",
            "unusual access patterns detected on an admin account",
          ],
          [
            "SyntheticMonitoring",
            "synthetic monitoring checks",
            "synthetic,monitoring,uptime",
            "a critical user flow with no automated uptime checks",
          ],
        ],
      },
    ],
  },
  {
    category: "Mobile & Apps",
    type: "coding",
    icon: "Smartphone",
    groups: [
      {
        verbs: [
          [
            "Build",
            "AppDev",
            "scaffold a working screen for",
            "Describe the layout, data source and navigation target.",
            "a working screen implementation with sample data wired in",
          ],
          [
            "Sync",
            "AppDev",
            "add offline-first sync to",
            "Describe what data must be available without a connection.",
            "a sync layer with conflict resolution for offline edits",
          ],
          [
            "Localize",
            "AppDev",
            "add multi-language support to",
            "List the target languages and any strings already extracted.",
            "a localization setup with strings extracted per language",
          ],
          [
            "Theme",
            "AppDev",
            "add light and dark theme support to",
            "Share your current color and spacing tokens if any exist.",
            "a theming layer that follows system appearance",
          ],
          [
            "Navigate",
            "AppDev",
            "design a clear navigation structure for",
            "Describe the main sections and how users move between them.",
            "a navigation graph with named routes and deep links",
          ],
          [
            "Notify",
            "AppDev",
            "add push notifications to",
            "Describe the events that should trigger a notification.",
            "a push notification setup with opt-in handling",
          ],
        ],
        objects: [
          [
            "OnboardingFlow",
            "an app onboarding flow",
            "onboarding,mobile,ux",
            "a three-screen onboarding for a fitness app",
          ],
          [
            "ProfileScreen",
            "a user profile screen",
            "profile,mobile,screen",
            "a profile screen with editable avatar and bio",
          ],
          [
            "FeedScreen",
            "a content feed screen",
            "feed,mobile,screen",
            "an infinite-scroll feed of posts",
          ],
          [
            "ChatScreen",
            "an in-app chat screen",
            "chat,messaging,mobile",
            "a one-to-one chat screen with typing indicators",
          ],
          [
            "CheckoutFlow",
            "an in-app purchase checkout flow",
            "checkout,iap,mobile",
            "an in-app subscription checkout flow",
          ],
          [
            "MapView",
            "a map-based screen",
            "maps,location,mobile",
            "a map view showing nearby delivery drivers",
          ],
          [
            "CameraFeature",
            "an in-app camera feature",
            "camera,media,mobile",
            "a camera screen for scanning receipts",
          ],
          [
            "SettingsScreen",
            "an app settings screen",
            "settings,mobile,screen",
            "a settings screen with notification toggles",
          ],
          [
            "OfflineMode",
            "offline data access for the app",
            "offline,sync,mobile",
            "a notes app that must work without connectivity",
          ],
          [
            "DeepLinking",
            "app deep-linking support",
            "deeplink,routing,mobile",
            "a marketing email that should open a specific in-app screen",
          ],
          [
            "BiometricLogin",
            "biometric authentication",
            "biometrics,auth,mobile",
            "a login screen needing face id and fingerprint support",
          ],
          [
            "WidgetExtension",
            "a home-screen widget",
            "widget,extension,mobile",
            "a small widget showing today's step count",
          ],
        ],
      },
      {
        verbs: [
          [
            "Optimize",
            "AppPerformance",
            "reduce startup time and jank in",
            "Share your current cold-start time and target device.",
            "a performance patch with measured startup time improvement",
          ],
          [
            "Shrink",
            "AppPerformance",
            "reduce install size of",
            "Share your current app size and platform.",
            "a smaller build with unused assets and code removed",
          ],
          [
            "Battery",
            "AppPerformance",
            "reduce battery and background drain in",
            "Describe what background work the app currently performs.",
            "a battery-friendly implementation with reduced wake-ups",
          ],
          [
            "Crash",
            "AppQuality",
            "investigate and fix a crash in",
            "Paste the stack trace or crash report you have.",
            "a root-cause explanation with a proposed fix",
          ],
          [
            "Memory",
            "AppPerformance",
            "fix memory growth and leaks in",
            "Describe when the memory usage climbs during app use.",
            "a memory-leak fix with before and after measurements",
          ],
          [
            "Accessibility",
            "AppQuality",
            "improve screen-reader support in",
            "Describe which screens are hardest to navigate by voice.",
            "an accessibility pass with labels and focus order fixed",
          ],
        ],
        objects: [
          [
            "AppStartup",
            "the app's cold-start sequence",
            "startup,performance,mobile",
            "an app taking 4 seconds to show its first screen",
          ],
          [
            "ImageHeavyScreen",
            "an image-heavy screen",
            "images,performance,mobile",
            "a gallery screen loading 100 full-resolution photos",
          ],
          [
            "BackgroundSync",
            "a background sync service",
            "background,sync,battery",
            "a background job polling a server every 30 seconds",
          ],
          [
            "AnimationLayer",
            "an app animation layer",
            "animation,performance,mobile",
            "a list with laggy scroll animations",
          ],
          [
            "AppBinarySize",
            "the compiled app binary",
            "binary,size,mobile",
            "an app binary that grew past the app-store size warning",
          ],
          [
            "LocationTracking",
            "continuous location tracking",
            "location,gps,battery",
            "a delivery app tracking gps every few seconds",
          ],
          [
            "CrashReport",
            "a crash report from production",
            "crash,stacktrace,debugging",
            "a crash report affecting 3% of android sessions",
          ],
          [
            "MemoryProfile",
            "a memory usage profile",
            "memory,profiling,mobile",
            "an app whose memory usage climbs during a long session",
          ],
          [
            "VoiceOverFlow",
            "a screen-reader navigation flow",
            "voiceover,accessibility,mobile",
            "a checkout flow that voiceover users can't complete",
          ],
          [
            "ListRendering",
            "a long scrollable list",
            "list,rendering,performance",
            "a list rendering 5000 items without virtualization",
          ],
          [
            "NetworkRequests",
            "the app's network request layer",
            "network,requests,performance",
            "a screen making 12 sequential api calls on load",
          ],
          [
            "AppLaunchAnalytics",
            "app launch performance analytics",
            "analytics,performance,launch",
            "launch metrics showing a regression after the last release",
          ],
        ],
      },
      {
        verbs: [
          [
            "Publish",
            "Distribution",
            "prepare a store-ready submission for",
            "Share your app name, category and target store.",
            "a submission checklist with assets and metadata ready",
          ],
          [
            "Ab",
            "Growth",
            "design an a/b test for",
            "Describe the metric you want to move and the audience size.",
            "an experiment design with a control and success metric",
          ],
          [
            "Onboard",
            "Growth",
            "improve the first-run experience of",
            "Describe where new users currently drop off.",
            "an improved first-run flow with a clearer activation step",
          ],
          [
            "Retain",
            "Growth",
            "design a re-engagement strategy for",
            "Describe your churn pattern and what triggers users to leave.",
            "a retention plan with triggered notifications or incentives",
          ],
          [
            "Monetize",
            "Growth",
            "design a monetization flow for",
            "Describe your current pricing model and target audience.",
            "a monetization flow with a clear upgrade path",
          ],
          [
            "Beta",
            "Distribution",
            "set up a structured beta test for",
            "Describe your beta audience size and what feedback you need.",
            "a beta rollout plan with feedback collection built in",
          ],
        ],
        objects: [
          [
            "AppStoreListing",
            "an app store listing",
            "appstore,listing,distribution",
            "a listing with outdated screenshots and no keywords",
          ],
          [
            "PlayStoreListing",
            "a google play store listing",
            "playstore,listing,distribution",
            "a play store listing with a low conversion rate",
          ],
          [
            "SubscriptionPricing",
            "an in-app subscription pricing tier",
            "pricing,subscription,monetization",
            "a single flat subscription price with no tiers",
          ],
          [
            "PaywallScreen",
            "an in-app paywall screen",
            "paywall,monetization,mobile",
            "a paywall with a 2% conversion rate",
          ],
          [
            "ReferralProgram",
            "an in-app referral program",
            "referral,growth,mobile",
            "an app with no incentive for users to invite friends",
          ],
          [
            "PushCampaign",
            "a push notification campaign",
            "push,campaign,retention",
            "a weekly push campaign with declining open rates",
          ],
          [
            "BetaProgram",
            "a beta testing program",
            "beta,testflight,testing",
            "a beta group of 200 users giving unstructured feedback",
          ],
          [
            "AppUpdateRollout",
            "a phased app update rollout",
            "rollout,update,distribution",
            "an update that must roll out gradually to catch bugs",
          ],
          [
            "ChurnAnalysis",
            "a user churn pattern",
            "churn,retention,analytics",
            "a subscription app losing 8% of users monthly",
          ],
          [
            "FeatureAdoption",
            "a new feature's adoption rate",
            "adoption,growth,analytics",
            "a new feature used by only 4% of active users",
          ],
          [
            "AppReviews",
            "app store review responses",
            "reviews,feedback,appstore",
            "a backlog of 300 unanswered app store reviews",
          ],
          [
            "OnboardingFunnel",
            "a signup and onboarding funnel",
            "funnel,onboarding,growth",
            "a signup funnel where 60% drop off before finishing",
          ],
        ],
      },
    ],
  },
  {
    category: "Testing & QA",
    type: "coding",
    icon: "FlaskConical",
    groups: [
      {
        verbs: [
          [
            "Write",
            "TestWriting",
            "write thorough unit tests for",
            "Paste the function or module and note the edge cases you worry about.",
            "a unit test suite covering the main paths and edge cases",
          ],
          [
            "Cover",
            "TestWriting",
            "close coverage gaps in",
            "Share the current coverage report and the file you're worried about.",
            "additional tests targeting the uncovered branches",
          ],
          [
            "Mock",
            "TestWriting",
            "add proper mocks and fixtures for",
            "Describe the external dependency you need to isolate.",
            "a mocking setup that isolates the dependency cleanly",
          ],
          [
            "Snapshot",
            "TestWriting",
            "add snapshot tests for",
            "Share the component or output that should stay stable.",
            "a snapshot test guarding against unintended output changes",
          ],
          [
            "Parametrize",
            "TestWriting",
            "convert repetitive tests into parametrized cases for",
            "Paste the duplicated test cases you want consolidated.",
            "a parametrized test covering the same cases more concisely",
          ],
          [
            "Review",
            "TestWriting",
            "review test quality and gaps in",
            "Paste the existing test file you'd like scrutinized.",
            "a review noting weak assertions and missing scenarios",
          ],
        ],
        objects: [
          [
            "UtilityFunction",
            "a utility function",
            "unit,function,tests",
            "a date-formatting utility used across the app",
          ],
          [
            "ReactHook",
            "a custom react hook",
            "react,hook,tests",
            "a usePagination hook with edge cases at page boundaries",
          ],
          [
            "ApiClient",
            "an api client module",
            "api,client,tests",
            "an http client wrapping fetch with retry logic",
          ],
          [
            "ReducerLogic",
            "state reducer logic",
            "reducer,state,tests",
            "a shopping cart reducer with add, remove and clear actions",
          ],
          [
            "ValidationSchema",
            "a form validation schema",
            "validation,schema,tests",
            "a schema validating signup form fields",
          ],
          [
            "PaymentCalculation",
            "a payment calculation module",
            "payments,calculation,tests",
            "a module calculating tax and discounts on an order",
          ],
          [
            "DateUtility",
            "a date and timezone utility",
            "dates,timezone,tests",
            "a utility converting timestamps across timezones",
          ],
          [
            "AuthMiddleware",
            "authentication middleware",
            "auth,middleware,tests",
            "middleware that verifies jwt tokens on protected routes",
          ],
          [
            "ParsingLogic",
            "a data parsing function",
            "parsing,data,tests",
            "a csv parser handling malformed rows",
          ],
          [
            "LegacyModule",
            "an untested legacy module",
            "legacy,coverage,tests",
            "a five-year-old module with zero test coverage",
          ],
          [
            "CustomHookLibrary",
            "a shared library of custom hooks",
            "hooks,library,tests",
            "an internal hooks package used by four apps",
          ],
          [
            "ErrorHandling",
            "error-handling logic",
            "errors,exceptions,tests",
            "a module that swallows errors without logging them",
          ],
        ],
      },
      {
        verbs: [
          [
            "Automate",
            "E2E",
            "automate an end-to-end test for",
            "Describe the user journey step by step as you'd walk through it.",
            "an automated e2e test following the described journey",
          ],
          [
            "Integrate",
            "Integration",
            "write integration tests covering",
            "Describe the systems involved and how they're expected to interact.",
            "an integration test exercising the real interaction path",
          ],
          [
            "Stub",
            "Integration",
            "stub external services in tests for",
            "Describe the third-party service and its expected responses.",
            "a test double standing in for the external service",
          ],
          [
            "Regress",
            "Regression",
            "build a regression suite around",
            "Describe the bug that keeps recurring and its symptoms.",
            "a regression test that fails if the bug reappears",
          ],
          [
            "Visual",
            "E2E",
            "add visual regression testing for",
            "Share the pages or components where layout must stay stable.",
            "a visual diffing setup flagging unintended layout shifts",
          ],
          [
            "Schedule",
            "Automation",
            "wire scheduled test runs for",
            "Describe how often the suite should run and who gets notified.",
            "a scheduled test run with notifications on failure",
          ],
        ],
        objects: [
          [
            "CheckoutJourney",
            "a full checkout user journey",
            "checkout,e2e,journey",
            "a journey from cart to order confirmation",
          ],
          [
            "SignupFlow",
            "a user signup flow",
            "signup,e2e,auth",
            "a signup flow with email verification",
          ],
          [
            "PaymentGatewayIntegration",
            "a payment gateway integration",
            "payments,integration,external",
            "an integration with a third-party payment processor",
          ],
          [
            "EmailDeliveryFlow",
            "an email delivery integration",
            "email,integration,notifications",
            "a flow that sends a receipt email after purchase",
          ],
          [
            "SearchAndFilter",
            "a search-and-filter interaction",
            "search,filter,e2e",
            "a product list filtered by price and category",
          ],
          [
            "MultiStepWizard",
            "a multi-step form wizard",
            "wizard,e2e,forms",
            "a five-step onboarding wizard with validation per step",
          ],
          [
            "ThirdPartyApiMock",
            "a mocked third-party api",
            "mock,api,integration",
            "a weather api that returns inconsistent test data",
          ],
          [
            "RecurringBug",
            "a recurring production bug",
            "regression,bug,tests",
            "a date-off-by-one bug that keeps resurfacing",
          ],
          [
            "DesignSystemComponents",
            "a shared design system's components",
            "visual,designsystem,ui",
            "a component library rendered across three themes",
          ],
          [
            "NightlyTestSuite",
            "a nightly automated test run",
            "nightly,automation,ci",
            "a full regression suite that should run every night",
          ],
          [
            "CrossBrowserSuite",
            "a cross-browser test suite",
            "crossbrowser,e2e,compatibility",
            "a suite that must pass on chrome, firefox and safari",
          ],
          [
            "MobileWebFlow",
            "a mobile-web responsive flow",
            "mobileweb,responsive,e2e",
            "a checkout flow tested only on desktop so far",
          ],
        ],
      },
      {
        verbs: [
          [
            "Triage",
            "BugManagement",
            "triage and prioritize bugs in",
            "Paste the bug list or backlog and any severity guidelines.",
            "a prioritized bug list with severity and owner suggestions",
          ],
          [
            "Reproduce",
            "BugManagement",
            "write clear reproduction steps for",
            "Describe what you observed and the environment it happened in.",
            "a minimal reproduction case with exact steps",
          ],
          [
            "LoadTest",
            "PerformanceTesting",
            "design a load test for",
            "Share your expected peak traffic and current capacity.",
            "a load-test plan with target rps and success thresholds",
          ],
          [
            "Fuzz",
            "PerformanceTesting",
            "design fuzz testing for",
            "Describe the input surface you're most worried about.",
            "a fuzzing setup targeting the risky input surface",
          ],
          [
            "Checklist",
            "QualityProcess",
            "build a manual QA checklist for",
            "Describe the feature and any high-risk edge cases.",
            "a step-by-step manual test checklist",
          ],
          [
            "Report",
            "QualityProcess",
            "write a clear bug report for",
            "Describe what happened, what you expected, and how to reproduce it.",
            "a well-structured bug report ready to file",
          ],
        ],
        objects: [
          [
            "IntermittentFailure",
            "an intermittent test failure",
            "flaky,bug,tests",
            "a test that fails roughly one run in twenty",
          ],
          [
            "ProductionBug",
            "a bug reported in production",
            "bug,production,triage",
            "a bug where some users can't complete checkout",
          ],
          [
            "HighTrafficEndpoint",
            "a high-traffic api endpoint",
            "loadtest,performance,api",
            "an endpoint expecting 5000 requests per second on launch day",
          ],
          [
            "UserInputForm",
            "a user-facing input form",
            "fuzzing,inputs,security",
            "a form accepting arbitrary text and file uploads",
          ],
          [
            "NewFeatureRelease",
            "a newly released feature",
            "qa,checklist,release",
            "a new checkout discount feature going live tomorrow",
          ],
          [
            "CrossDeviceBug",
            "a bug appearing only on some devices",
            "bug,devices,compatibility",
            "a layout bug appearing only on older android devices",
          ],
          [
            "DataCorruptionIssue",
            "a data corruption issue",
            "databug,integrity,triage",
            "reports of order totals being saved incorrectly",
          ],
          [
            "PerformanceRegression",
            "a performance regression",
            "performance,regression,loadtest",
            "an api that got noticeably slower after the last release",
          ],
          [
            "SecurityVulnerability",
            "a reported security vulnerability",
            "security,bug,report",
            "a report of an exposed admin endpoint",
          ],
          [
            "UserReportedIssue",
            "a vaguely described user-reported issue",
            "bugreport,triage,support",
            "a support ticket saying 'the app just doesn't work'",
          ],
          [
            "BetaFeedbackBacklog",
            "a backlog of beta tester feedback",
            "feedback,triage,qa",
            "40 unsorted feedback notes from a closed beta",
          ],
          [
            "StressTestScenario",
            "a system stress-test scenario",
            "stress,loadtest,reliability",
            "a system that must survive a 10x traffic spike",
          ],
        ],
      },
    ],
  },
];
