export default [
  {
    category: "Content & Social Media",
    type: "text",
    icon: "Hash",
    groups: [
      {
        verbs: [
          ["CutDown", "Editing", "cut a long video into a tight short-form edit of", "Paste the transcript with timestamps and pick a target length.", "a keep-list of time ranges with the reason each cut survived"],
          ["AutoCaption", "Captions", "write word-for-word styled captions for", "Paste the audio transcript and note the platform's caption style.", "caption blocks timed to speech with emphasis words marked"],
          ["BeatSync", "Editing", "map a beat-synced edit plan for", "Name the track's BPM and paste the shot list.", "a cut-on-the-beat timeline with shot numbers per bar"],
          ["HookTrim", "Editing", "re-cut the first three seconds of", "Describe the current opening and why viewers drop.", "three alternate openings, each under 3 seconds"],
          ["BrollPlan", "Editing", "plan b-roll coverage for", "Paste the voiceover script and list what footage you already have.", "a shot-needed list matched to every claim in the script"],
          ["TrendTemplate", "Templates", "adapt a trending edit template to", "Describe the template (transition, timing, text style) and your content.", "a fill-in plan keeping the trend's rhythm with your footage"],
        ],
        objects: [
          ["VlogCut", "a vlog edit", "vlog, editing, capcut", "a 12-minute day-in-the-life to cut to 45 seconds"],
          ["TalkingHead", "a talking-head video", "talking-head, interview, edit", "a 6-minute expert answer full of pauses"],
          ["TutorialCut", "a tutorial edit", "tutorial, howto, edit", "a 9-minute screen recording that loses people at step 3"],
          ["TravelMontage", "a travel montage", "travel, montage, edit", "60 clips from a Goa trip, no story yet"],
          ["ProductTeaser", "a product teaser", "product, teaser, edit", "a 20-second teaser for a handmade jewellery drop"],
        ],
      },
      {
        variants: ["chatgpt", "gemini", "claude", "perplexity", "copilot", "deepseek"],
        verbs: [
          ["HookForge", "Hooks", "forge three scroll-stopping opening lines for", "State the topic, the platform and the audience mood (funny, aspirational, hot take).", "three hook lines rated by stop-the-scroll strength"],
          ["ReelScript", "Reels", "write a beat-by-beat 30-second reel script for", "Say the topic, the vibe and whether you appear on camera or use b-roll only.", "a shot list with on-screen text, voiceover and b-roll notes"],
          ["CarouselCraft", "Carousels", "design a 8-slide carousel outline for", "Give the topic, the audience and the promise the cover makes.", "slide-by-slide copy under 25 words each plus a cover hook"],
          ["CaptionLab", "Captions", "write five caption variants with hashtag sets for", "Paste the post topic or draft; note the tone and any banned words.", "five captions (short, story, punchy, question, listicle) with 8 hashtags each"],
          ["TrendJack", "Trends", "map a rising trend onto", "Name the trend and your niche. Output stays evergreen-safe: no dated references.", "a trend brief: the format, three angles, and one caution"],
          ["SeriesPlanner", "Series", "plan a 12-post content series around", "State the theme, the posting cadence and the end goal (followers, sales, portfolio).", "a 12-post calendar with formats and hooks"],
          ["CommentAlchemist", "Comments", "turn top comments into fresh post ideas for", "Paste 5-10 comments (yours or a competitor's).", "five post ideas sourced from real audience language"],
          ["CollabPitch", "Collabs", "draft a collab DM to a fellow creator about", "Name both audiences and what each side brings. Keep it under 80 words.", "a short DM, a longer email variant, and one follow-up line"],
          ["DuetBuilder", "Duets", "write a duet or stitch response script for", "Paste or describe the original video and say what angle you add.", "a response script timed to the original's beats"],
          ["AnalyticsRead", "Analytics", "read last month's analytics for", "Paste reach, saves, shares and follower numbers per post.", "a plain-English diagnosis: what worked, what stalled, what to double"],
          ["BrandVoiceBook", "Voice", "codify a repeatable brand voice for", "Paste three captions you love and three you hate.", "a voice card: sentence rhythm, vocabulary, emoji policy, do-not list"],
          ["SaveMagnet", "Saves", "engineer a save-worthy reference post for", "Pick a topic people search again and again (checklists, prices, settings).", "a carousel or one-pager designed to be bookmarked"],
        ],
        objects: [
          ["Instagram", "an Instagram feed", "instagram, feed, grid", "a travel page pivoting to budget itineraries"],
          ["Reels", "a Reels strategy", "reels, short-form, video", "a food creator posting 3x weekly"],
          ["TikTok", "a TikTok channel", "tiktok, short-form", "a study-hack account for board-exam season"],
          ["YouTube", "a YouTube channel", "youtube, long-form", "a 10k-sub channel losing click-through"],
          ["Shorts", "a YouTube Shorts run", "shorts, viral, quick", "repurposed podcast highlights"],
          ["LinkedIn", "a LinkedIn presence", "linkedin, professional, b2b", "a founder posting twice a week"],
          ["X", "an X (Twitter) timeline", "twitter, threads, x", "a dev sharing build logs"],
          ["Threads", "a Threads account", "threads, meta, conversation", "a writer testing conversational posts"],
          ["Pinterest", "a Pinterest board strategy", "pinterest, evergreen, search", "a home-decor blogger chasing seasonal traffic"],
          ["Snapchat", "a Snapchat story flow", "snapchat, casual, daily", "a campus creator documenting hostel life"],
        ],
      },
    ],
  },
];
