export default [
  {
    category: "Translation & Languages",
    type: "text",
    icon: "Languages",
    groups: [
      {
        verbs: [
          ["Translate", "Translation", "translate faithfully with natural phrasing", "Give the source and target language plus any terms that must stay untranslated.", "the translated text with a short note on any wording judgement calls"],
          ["Localize", "Localization", "localize idioms, units and formats in", "State the target locale, including currency, date format and measurement units.", "a fully localized version with units and idioms adapted for that region"],
          ["BackTranslate", "Quality", "back-translate to verify fidelity of", "Provide the original source text alongside the translation being checked.", "a back-translation plus a list of any meaning drift found"],
          ["Glossary", "Terminology", "build a bilingual glossary for", "List the key domain terms and the two languages to pair them in.", "a bilingual term-by-term glossary table"],
          ["Formality", "Register", "adjust formality and honorifics in", "Specify the target formality level and the relationship between speaker and reader.", "a rewritten version with formality and honorifics adjusted"],
          ["Subtitle", "Subtitles", "produce timed subtitles for", "Attach the transcript or media and give the desired subtitle line length.", "a timed subtitle file with line breaks fitted to reading speed"],
          ["Transliterate", "Scripts", "transliterate between scripts for", "Name the source script and the target script or romanization system.", "the transliterated text plus a pronunciation guide"],
          ["Cultural", "Culture", "flag culturally sensitive wording in", "Share the text and the target audience's country or culture.", "a flagged list of sensitive phrases with safer alternatives"],
          ["Simplify", "Clarity", "translate into simple, learner-friendly language", "Indicate the learner's proficiency level and the target language.", "a simplified translation at the stated proficiency level"],
          ["Bilingual", "Side-by-side", "produce a bilingual side-by-side version of", "Paste the source text and name the second language to pair it with.", "a two-column side-by-side bilingual document"],
        ],
        objects: [
          ["Text", "a text passage", "text", "a 300-word blog excerpt about remote work burnout"],
          ["Ui", "UI strings", "ui, i18n", "a strings.json file with 42 button and error-message keys"],
          ["Doc", "a document", "document", "a 6-page product warranty PDF"],
          ["Support", "a support reply", "support", "a customer email complaining about a delayed refund"],
          ["Legal", "legal wording", "legal", "clause 4.2 of a freelance services agreement"],
          ["Menu", "a menu or listing", "menu", "a 24-item bistro menu with dish names and allergen notes"],
        ],
      },
    ],
  },
  {
    category: "Math & Science",
    type: "general",
    icon: "Sigma",
    groups: [
      {
        verbs: [
          ["Solve", "Solving", "solve step by step and verify", "Paste the exact problem statement and note any required method.", "a step-by-step solution with a final verified answer"],
          ["Derive", "Derivations", "derive the result from first principles for", "State the starting assumptions or axioms to derive from.", "a full derivation showing each algebraic or logical step"],
          ["CheckWork", "Verification", "check the working and find the error in", "Paste your worked solution exactly as written, including scratch steps.", "the located error plus a corrected line of working"],
          ["Visualize", "Visualization", "describe the right visual intuition for", "Name the concept and the audience's current math background.", "a description of the ideal diagram or graph with labeled axes"],
          ["Estimate", "Estimation", "do a Fermi estimate for", "Give the quantity to estimate and any known reference numbers.", "an order-of-magnitude estimate with the assumption chain shown"],
          ["Units", "Units", "convert and sanity-check units in", "List the values, their current units, and the target units.", "converted values with a sanity check flagging implausible results"],
          ["Model", "Modeling", "build a small quantitative model of", "Describe the system and the variables that drive its behavior.", "a small formula-based model with example inputs and outputs"],
          ["Proof", "Proofs", "write a rigorous proof sketch for", "State the claim precisely and the mathematical framework to use.", "a proof sketch with the key lemmas and logical steps"],
          ["Simulate", "Simulation", "outline a simulation approach for", "Describe the process to simulate and what randomness it involves.", "a simulation outline with algorithm steps and stopping conditions"],
          ["Interpret", "Interpretation", "interpret the statistical result in", "Paste the statistical output and the original research question.", "a plain-language interpretation of significance and effect size"],
        ],
        objects: [
          ["Equation", "an equation", "algebra", "3x^2 - 5x + 2 = 0 solved for x"],
          ["Statistics", "a statistics problem", "statistics", "a t-test comparing two sample means of 15 and 18 observations"],
          ["Physics", "a physics problem", "physics", "a projectile launched at 30 degrees at 20 m/s"],
          ["Geometry", "a geometry problem", "geometry", "the volume of a frustum with radii 3 and 5 and height 8"],
          ["Chemistry", "a chemistry problem", "chemistry", "balancing the combustion equation for C4H10"],
          ["Finance", "a finance calculation", "finance", "compound interest on $12,000 at 4.5% over 7 years"],
        ],
      },
    ],
  },
  {
    category: "Career",
    type: "productivity",
    icon: "UserRound",
    groups: [
      {
        verbs: [
          ["Tailor", "Tailoring", "tailor to the target role", "Paste the job posting and your current draft.", "a tailored version matched to the posting's keywords and priorities"],
          ["Review", "Review", "critique honestly against hiring bar", "Share the document and the seniority level you're targeting.", "a blunt critique against that hiring bar with concrete fixes"],
          ["Prep", "Interviews", "run focused interview prep for", "Name the role, company, and interview stage you're preparing for.", "a prep pack of likely questions with strong sample answers"],
          ["Story", "Storytelling", "shape STAR-format stories from", "List your raw work experiences or bullet points to draw from.", "polished STAR-format stories ready to tell in an interview"],
          ["Outreach", "Networking", "write warm, non-generic outreach for", "Name the person you're contacting and your specific reason for reaching out.", "a short, personalized outreach message"],
          ["Negotiate", "Offers", "prepare compensation negotiation for", "Share the offer details and your target range with justification.", "a negotiation script with counter-offer language and fallback lines"],
          ["Gap", "Growth", "identify skill gaps and a plan for", "Describe your current skills and the role you're aiming for.", "a gap analysis with a prioritized learning plan"],
          ["Brand", "Personal Brand", "sharpen personal positioning in", "Paste your bio or profile and describe your target audience.", "a sharpened positioning statement and rewritten bio"],
          ["Questions", "Questions", "prepare smart questions to ask about", "Name the role, team, or company you're interviewing with.", "a set of insightful questions organized by interview stage"],
          ["Plan30", "Onboarding", "write a 30-60-90 day plan for", "Describe the new role and its first-quarter priorities.", "a 30-60-90 day plan with milestones and success metrics"],
        ],
        objects: [
          ["Resume", "a resume", "resume, cv", "a two-page resume for a mid-level backend engineer"],
          ["Cover", "a cover letter", "cover-letter", "a cover letter draft for a marketing manager opening at a startup"],
          ["Linkedin", "a LinkedIn profile", "linkedin", "a LinkedIn headline and About section for a UX designer"],
          ["Portfolio", "a portfolio", "portfolio", "a case-study page describing a redesign project with metrics"],
          ["Role", "a target role", "role", "a Senior Product Manager posting at a fintech company"],
          ["Promotion", "a promotion case", "promotion", "a self-review packet arguing for promotion to staff engineer"],
        ],
      },
    ],
  },
  {
    category: "Security & Privacy",
    type: "general",
    icon: "ShieldCheck",
    groups: [
      {
        verbs: [
          ["Scrub", "Privacy", "remove personal identifiers from", "Paste the text or file and specify which identifier types to remove.", "a cleaned version with identifiers replaced by consistent placeholders"],
          ["ThreatModel", "Threat Modeling", "build a lightweight threat model for", "Describe the system's components, data flows, and trust boundaries.", "a threat model listing assets, attackers, and top risks"],
          ["Harden", "Hardening", "recommend concrete hardening steps for", "Describe the current configuration and its exposure level.", "a prioritized list of concrete hardening steps"],
          ["Policy", "Policy", "draft a clear internal policy for", "State the topic and the audience the policy must govern.", "a plain-language internal policy document"],
          ["Checklist", "Checklists", "produce a security review checklist for", "Name the system or process the checklist should cover.", "a security review checklist grouped by category"],
          ["Phishing", "Awareness", "spot social-engineering red flags in", "Paste the suspicious message exactly as received.", "a flagged breakdown of red flags and a recommended response"],
          ["Retention", "Data Retention", "define data retention and deletion rules for", "List the data types collected and any legal constraints that apply.", "a retention and deletion schedule per data type"],
          ["Consent", "Consent", "write plain-language consent copy for", "Describe what data is collected and how it will be used.", "plain-language consent copy ready for a form or banner"],
          ["Access", "Access Control", "design least-privilege access for", "List the roles involved and the resources they need to touch.", "a least-privilege access matrix mapping roles to permissions"],
          ["IncidentPlan", "Incident Response", "write an incident response runbook for", "Describe the system and the types of incidents it's exposed to.", "an incident response runbook with roles and escalation steps"],
        ],
        objects: [
          ["Dataset", "a dataset", "data", "a 50,000-row customer export with names, emails and order history"],
          ["App", "an application", "app", "a Node.js API service handling payment webhooks"],
          ["Team", "a team process", "team", "the engineering team's on-call rotation and handoff process"],
          ["Vendor", "a vendor relationship", "vendor", "a third-party analytics vendor with access to user event data"],
          ["Document", "a shared document", "document", "a shared spreadsheet of employee salaries and bank details"],
          ["Account", "an online account", "account", "a company Slack workspace admin account"],
        ],
      },
    ],
  },
  {
    category: "General AI",
    type: "general",
    icon: "Bot",
    groups: [
      {
        verbs: [
          ["Prompt", "Prompting", "turn a rough idea into a precise prompt for", "Describe the task loosely and the model or tool you'll run it on.", "a precise, well-structured prompt ready to run"],
          ["Persona", "Personas", "define a system persona for", "Describe the assistant's purpose and the tone it should keep.", "a system persona definition with tone and boundaries"],
          ["Chain", "Workflows", "chain multiple steps into one reliable flow for", "List the separate steps you're currently running manually.", "a chained prompt flow with defined handoffs between steps"],
          ["Constrain", "Guardrails", "add explicit constraints and output format to", "Paste the current prompt and describe the failure mode to prevent.", "a revised prompt with explicit constraints and output schema"],
          ["Fewshot", "Examples", "add well-chosen few-shot examples to", "Paste the prompt and one or two example inputs you already have.", "a prompt augmented with well-chosen few-shot examples"],
          ["Critique", "Self-review", "have the model critique and revise its own output for", "Paste the model's output and the criteria it should be judged against.", "a self-critique pass followed by a revised output"],
          ["Format", "Formatting", "force a strict output format for", "Specify the exact schema, such as JSON keys or table columns.", "a prompt addition enforcing the strict output format"],
          ["Rubricize", "Evaluation", "define pass/fail criteria for", "Describe the task and what a good versus bad output looks like.", "a scoring rubric with pass/fail criteria per dimension"],
          ["Reduce", "Efficiency", "reduce token cost while keeping quality in", "Paste the current prompt and note which parts feel redundant.", "a shortened prompt with estimated token savings"],
          ["Debug", "Troubleshooting", "diagnose why the model is failing at", "Describe the task, the expected output, and what the model actually returns.", "a diagnosis of the likely cause with a suggested fix"],
        ],
        objects: [
          ["Task", "a task", "task", "extracting invoice totals from scanned PDFs"],
          ["Agent", "an agent", "agent", "a customer-support agent that looks up order status via API"],
          ["Chatbot", "a chatbot", "chatbot", "a website FAQ chatbot for a SaaS billing product"],
          ["Summary", "a summarization job", "summarization", "daily summarization of a 200-message Slack channel"],
          ["Extraction", "an extraction job", "extraction", "pulling names and dates from handwritten meeting notes"],
          ["Creative", "a creative brief", "creative", "a brief for a whimsical mascot illustration for a coffee brand"],
        ],
      },
    ],
  },
];
