/**
 * Catalog part 8 — business categories: Sales & CRM, Customer Support,
 * Legal & Contracts, HR & Hiring, Ecommerce & Retail.
 */
export default [
  {
    category: "Sales & CRM",
    type: "business",
    icon: "HandCoins",
    groups: [
      {
        verbs: [
          [
            "Qualify",
            "Prospecting",
            "score and qualify leads from",
            "Paste the lead list or CRM export and describe your ideal customer.",
            "a ranked lead list with fit score and reasoning per lead",
          ],
          [
            "Prospect",
            "Prospecting",
            "build a targeted prospect list for",
            "Describe your ideal customer profile and any accounts to exclude.",
            "a prospect list with company, contact and outreach angle",
          ],
          [
            "Research",
            "Prospecting",
            "compile account intelligence on",
            "Name the account or contact and what you already know.",
            "an account brief with recent news, pain points and entry points",
          ],
          [
            "Draft",
            "Outreach",
            "write a personalised cold outreach message for",
            "Share the prospect's role, company and the value you offer.",
            "a short personalised outreach message with a clear ask",
          ],
          [
            "Sequence",
            "Outreach",
            "design a multi-touch outreach sequence for",
            "Describe the target segment and the number of touches you want.",
            "a 5-touch email and call sequence with timing and angles",
          ],
          [
            "Followup",
            "Outreach",
            "write a persistent but polite follow-up for",
            "Paste the last message sent and how long it's been since reply.",
            "a follow-up message that adds new value without sounding pushy",
          ],
        ],
        objects: [
          ["ColdLead", "a cold inbound or purchased lead", "lead,cold,prospect", "a signup from a gated ebook with no prior contact"],
          ["Enterprise", "a large enterprise target account", "enterprise,account,b2b", "a 5,000-employee logistics company evaluating vendors"],
          ["SMB", "a small business prospect", "smb,small-business", "a 12-person marketing agency comparing tools"],
          ["Referral", "a warm referral introduction", "referral,warm,intro", "a referral from an existing customer's CFO"],
          ["TradeShow", "a trade show or event contact", "event,tradeshow,networking", "a business card scanned at a SaaS conference booth"],
          ["Champion", "an internal champion at a target account", "champion,influencer,internal", "a product manager pushing for adoption internally"],
          ["Decisionmaker", "the economic decision-maker", "decisionmaker,exec,budget", "a VP of Ops who signs off on the budget"],
          ["ColdEmail", "a cold email list import", "coldemail,list,import", "a 200-row CSV of scraped LinkedIn contacts"],
          ["Webinar", "a webinar attendee list", "webinar,attendee,event", "attendees who stayed for the full product demo webinar"],
          ["Reseller", "a channel or reseller partner lead", "reseller,partner,channel", "a regional distributor asking about margins"],
          ["FreeTrial", "a free trial signup", "trial,freemium,signup", "a user who activated a 14-day trial three days ago"],
          ["LostDeal", "a previously lost deal to revisit", "lost,reengage,churn", "a deal lost to a competitor eight months ago"],
        ],
      },
      {
        verbs: [
          [
            "Forecast",
            "Pipeline",
            "forecast likely close outcomes for",
            "Share stage, deal size and last activity date for each deal.",
            "a weighted revenue forecast with confidence per deal",
          ],
          [
            "Prioritize",
            "Pipeline",
            "rank by urgency and value the deals in",
            "Paste your open pipeline with stage and close dates.",
            "a prioritized deal list with recommended next action each",
          ],
          [
            "Diagnose",
            "Pipeline",
            "identify what's stalling",
            "Describe the deal's history, stakeholders and objections raised.",
            "a stall diagnosis with the likely blocker and an unblock tactic",
          ],
          [
            "Negotiate",
            "Deals",
            "prepare a negotiation strategy for",
            "Share the current offer, their pushback and your walk-away point.",
            "a negotiation script with concessions to trade and lines to hold",
          ],
          [
            "Propose",
            "Deals",
            "draft a compelling sales proposal for",
            "Describe the client's needs, scope and pricing structure.",
            "a client-ready proposal with pricing tiers and clear next steps",
          ],
          [
            "Close",
            "Deals",
            "write the final closing push for",
            "Share where the deal stands and any remaining hesitations.",
            "a closing message that resolves the last objection and asks to sign",
          ],
        ],
        objects: [
          ["Opportunity", "an open sales opportunity", "opportunity,deal,open", "a $40k deal sitting in proposal stage for three weeks"],
          ["Renewal", "a subscription renewal", "renewal,retention,contract", "an annual contract renewing in 45 days"],
          ["Upsell", "an upsell or expansion opportunity", "upsell,expansion,upgrade", "a customer outgrowing their current seat count"],
          ["Discount", "a discount request from a buyer", "discount,pricing,pushback", "a procurement team asking for 20% off list price"],
          ["MultiStakeholder", "a deal with multiple stakeholders", "stakeholders,committee,b2b", "a deal needing sign-off from IT, finance and ops"],
          ["PriceObjection", "a price objection", "objection,price,pushback", "a buyer saying the quote is over budget by 15%"],
          ["CompetitorDeal", "a deal contested by a competitor", "competitor,compete,battlecard", "a prospect also evaluating a rival vendor"],
          ["StalledDeal", "a stalled deal with no response", "stalled,ghosted,silence", "a prospect who went quiet after a good demo"],
          ["ContractRedline", "a contract under legal redline", "redline,legal,contract", "a legal team pushing back on liability terms"],
          ["MultiYearDeal", "a multi-year contract deal", "multiyear,contract,term", "a 3-year deal with annual price escalators"],
          ["ChampionChange", "a deal where the champion left", "champion,turnover,risk", "the internal champion left the company mid-cycle"],
          ["VerbalYes", "a deal with a verbal commitment pending paperwork", "verbal,commitment,pending", "a buyer who verbally agreed but hasn't signed"],
        ],
      },
      {
        verbs: [
          [
            "Summarize",
            "CRM Ops",
            "turn call notes into a clean CRM update for",
            "Paste your raw call notes or voice-to-text transcript.",
            "a structured CRM note with next steps and follow-up date",
          ],
          [
            "Segment",
            "CRM Ops",
            "segment the customer base by",
            "Share your customer list and the criteria that matter most.",
            "customer segments with size, value and a tailored message per segment",
          ],
          [
            "Cleanse",
            "CRM Ops",
            "find and flag duplicate or stale records in",
            "Paste a sample of the CRM export you want cleaned up.",
            "a list of duplicate, stale or incomplete records with fixes",
          ],
          [
            "Report",
            "CRM Ops",
            "build a performance report from",
            "Share the raw sales activity or results data for the period.",
            "a rep or team performance report with trends and standouts",
          ],
          [
            "Onboard",
            "CRM Ops",
            "write the onboarding sequence for a newly signed",
            "Describe the deal terms and the customer's first goals.",
            "a welcome and kickoff sequence with milestones for the first 90 days",
          ],
          [
            "Coach",
            "CRM Ops",
            "give constructive coaching feedback on a call with",
            "Attach or paste the call transcript or recording notes.",
            "call feedback with strengths, gaps and one drill to practice",
          ],
        ],
        objects: [
          ["SalesCall", "a recorded sales call", "call,transcript,notes", "a 30-minute discovery call recording"],
          ["CustomerList", "a full customer or contact list", "list,export,contacts", "a 3,000-row CRM export with last purchase date"],
          ["QuarterlyPipeline", "the quarter's full pipeline", "pipeline,quarter,forecast", "all open deals expected to close this quarter"],
          ["NewCustomer", "a newly closed-won customer", "onboarding,new,closedwon", "a customer who just signed a 12-month contract"],
          ["DiscoveryCall", "a discovery call transcript", "discovery,call,qualify", "a first call where budget and timeline came up"],
          ["DemoCall", "a product demo call", "demo,call,product", "a 45-minute demo with three stakeholders on the line"],
          ["ChurnRisk", "an account showing churn risk signals", "churn,risk,retention", "a customer with declining product usage for two months"],
          ["TerritoryData", "sales territory performance data", "territory,region,performance", "regional sales numbers across four territories"],
          ["RepActivity", "a sales rep's activity log", "rep,activity,performance", "one rep's calls, emails and meetings for the month"],
          ["DuplicateRecords", "duplicate CRM contact records", "duplicates,cleanup,data", "the same company entered twice under different spellings"],
          ["LostReason", "reasons behind a batch of lost deals", "lostreasons,analysis,winloss", "the last 20 closed-lost deals with stated reasons"],
          ["AccountPlan", "a strategic account plan", "accountplan,strategy,keyaccount", "a top-10 account needing a growth roadmap"],
        ],
      },
    ],
  },
  {
    category: "Customer Support",
    type: "business",
    icon: "Headphones",
    groups: [
      {
        verbs: [
          [
            "Respond",
            "Ticket Handling",
            "draft an empathetic, resolving reply to",
            "Paste the customer's message and any relevant order or account details.",
            "a ready-to-send reply that resolves the issue and sets clear next steps",
          ],
          [
            "Triage",
            "Ticket Handling",
            "assess urgency and route",
            "Paste the incoming ticket text and your team's routing categories.",
            "a priority level, category tag and recommended assignee",
          ],
          [
            "Escalate",
            "Ticket Handling",
            "write the internal escalation note for",
            "Describe the issue, what's been tried, and why it needs escalation.",
            "an internal escalation summary with impact and requested action",
          ],
          [
            "Deescalate",
            "Ticket Handling",
            "calm down and redirect",
            "Paste the angry customer message and the facts of the situation.",
            "a de-escalating reply that acknowledges frustration and offers a fix",
          ],
          [
            "Apologize",
            "Ticket Handling",
            "write a sincere service-recovery apology for",
            "Describe what went wrong and any compensation you're able to offer.",
            "a genuine apology message with a concrete remedy attached",
          ],
          [
            "Close",
            "Ticket Handling",
            "write the resolution summary and closing message for",
            "Share how the issue was actually resolved.",
            "a closing message confirming resolution and inviting further contact",
          ],
        ],
        objects: [
          ["BillingComplaint", "a billing dispute complaint", "billing,dispute,refund", "a customer charged twice for the same subscription month"],
          ["ShippingDelay", "a shipping delay complaint", "shipping,delay,logistics", "an order stuck in transit for nine days past estimate"],
          ["DefectiveProduct", "a defective product report", "defective,product,quality", "a blender that stopped working after two uses"],
          ["LoginIssue", "a login or account access issue", "login,access,account", "a user locked out after a password reset failed"],
          ["CancellationRequest", "a subscription cancellation request", "cancellation,churn,retention", "a customer wanting to cancel after a price increase"],
          ["RefundRequest", "a refund request", "refund,return,money", "a customer requesting a refund outside the return window"],
          ["AngryCustomer", "an angry escalated customer", "angry,escalation,upset", "a customer threatening to leave a public bad review"],
          ["FeatureComplaint", "a complaint about a missing feature", "feature,gap,complaint", "a user frustrated that exports aren't available yet"],
          ["DataPrivacyConcern", "a data privacy concern", "privacy,data,compliance", "a user asking exactly how their data is stored"],
          ["OnboardingConfusion", "confusion during onboarding", "onboarding,confusion,support", "a new user unsure how to set up their first project"],
          ["VIPCustomer", "a high-value VIP customer issue", "vip,priority,keyaccount", "a top-tier customer reporting repeated outages"],
          ["SocialMediaComplaint", "a public social media complaint", "social,public,reputation", "a tweet tagging the brand about a bad experience"],
        ],
      },
      {
        verbs: [
          [
            "Document",
            "Knowledge Base",
            "turn a resolved issue into a help-center article about",
            "Paste the resolved ticket thread or describe the fix.",
            "a clear help-center article with steps and a screenshot placeholder",
          ],
          [
            "Simplify",
            "Knowledge Base",
            "rewrite in plain, friendly language the documentation for",
            "Paste the current technical documentation or notes.",
            "a customer-friendly rewrite free of jargon",
          ],
          [
            "Faq",
            "Knowledge Base",
            "build a FAQ section covering",
            "List the common questions customers ask about this topic.",
            "a structured FAQ with concise, accurate answers",
          ],
          [
            "Script",
            "Knowledge Base",
            "write a support agent script for handling",
            "Describe the scenario agents commonly face.",
            "a step-by-step agent script with sample phrasing",
          ],
          [
            "Troubleshoot",
            "Knowledge Base",
            "create a self-serve troubleshooting guide for",
            "Describe the symptom and the fixes that usually work.",
            "a decision-tree troubleshooting guide customers can follow themselves",
          ],
          [
            "Translate",
            "Knowledge Base",
            "translate and localize support content for",
            "Paste the article and specify the target language and region.",
            "a localized version adapted for tone and regional terms",
          ],
        ],
        objects: [
          ["PasswordReset", "the password reset process", "password,reset,account", "users forgetting their password after 90 days"],
          ["SetupGuide", "a product setup guide", "setup,onboarding,guide", "first-time setup of a new smart thermostat"],
          ["PaymentFailure", "a recurring payment failure issue", "payment,failure,billing", "cards declining due to expired expiry dates"],
          ["ReturnPolicy", "the return and refund policy", "returns,policy,refund", "a 30-day return window with restocking fee exceptions"],
          ["APIError", "a common API integration error", "api,error,integration", "a 401 error developers hit during first integration"],
          ["MobileAppCrash", "a mobile app crash issue", "mobile,crash,bug", "the app crashing when uploading large photos"],
          ["SubscriptionTiers", "the subscription plan tiers", "subscription,plans,pricing", "differences between the basic, pro and enterprise tiers"],
          ["DataExport", "the data export feature", "export,data,csv", "exporting a year of transaction history to csv"],
          ["AccountDeletion", "the account deletion process", "deletion,privacy,account", "a user wanting to permanently delete their account"],
          ["Integrations", "third-party integration setup", "integrations,thirdparty,setup", "connecting the product to a Slack workspace"],
          ["Warranty", "the product warranty terms", "warranty,coverage,terms", "a two-year limited warranty on hardware defects"],
          ["MultiLanguageSupport", "support content for non-English speakers", "language,localization,translation", "translating the help center into Spanish and French"],
        ],
      },
      {
        verbs: [
          [
            "Analyze",
            "Support Ops",
            "find recurring patterns in",
            "Paste a sample of tickets or a summary export from the period.",
            "a pattern analysis with top issue categories and root causes",
          ],
          [
            "Survey",
            "Support Ops",
            "design a post-resolution satisfaction survey for",
            "Describe the type of interaction you want feedback on.",
            "a short CSAT survey with 3-4 targeted questions",
          ],
          [
            "Report",
            "Support Ops",
            "compile a support performance report on",
            "Share the raw metrics or ticket volume data for the period.",
            "a support metrics report with trends and staffing implications",
          ],
          [
            "Automate",
            "Support Ops",
            "design an automated response flow for",
            "Describe the trigger condition and the desired outcome.",
            "an automation flow with trigger, conditions and message templates",
          ],
          [
            "Predict",
            "Support Ops",
            "forecast expected volume and staffing needs for",
            "Share historical ticket volume and any upcoming events.",
            "a staffing forecast with expected peak times flagged",
          ],
          [
            "Audit",
            "Support Ops",
            "review response quality across",
            "Paste a sample of agent replies you want evaluated.",
            "a quality audit scored against tone, accuracy and resolution speed",
          ],
        ],
        objects: [
          ["TicketBacklog", "the full ticket backlog", "backlog,tickets,volume", "600 unresolved tickets older than 48 hours"],
          ["CSATScores", "recent CSAT survey results", "csat,satisfaction,scores", "a week of CSAT responses averaging 3.8 out of 5"],
          ["ChatTranscripts", "a batch of live chat transcripts", "chat,transcript,livechat", "50 live chat sessions from the last support shift"],
          ["FirstResponseTime", "first response time metrics", "frt,response,sla", "average first response time creeping past the 2-hour sla"],
          ["AgentPerformance", "individual agent performance data", "agent,performance,qa", "one agent's ticket volume and resolution rate for the month"],
          ["SeasonalSpike", "an expected seasonal ticket spike", "seasonal,spike,forecast", "the holiday season return and shipping question surge"],
          ["EscalationLog", "a log of escalated tickets", "escalation,log,history", "tickets escalated to tier-2 in the last quarter"],
          ["ChurnFeedback", "feedback collected from churned customers", "churn,feedback,exitsurvey", "exit survey responses from cancelled subscribers"],
          ["ChannelMix", "support volume across channels", "channel,omnichannel,volume", "tickets split across email, chat and phone"],
          ["SLABreach", "SLA breach incidents", "sla,breach,compliance", "12 tickets that missed the 4-hour response sla"],
          ["BotHandoff", "chatbot-to-human handoff cases", "chatbot,handoff,automation", "cases where the bot failed to resolve and passed to a human"],
          ["ProductFeedback", "product feedback surfaced through support", "feedback,product,voiceofcustomer", "recurring feature requests logged across tickets"],
        ],
      },
    ],
  },
  {
    category: "Legal & Contracts",
    type: "business",
    icon: "Scale",
    groups: [
      {
        verbs: [
          [
            "Draft",
            "Contract Drafting",
            "draft a solid first version of",
            "Describe the parties, key terms and any deal-specific details.",
            "a draft agreement with standard protective clauses included",
          ],
          [
            "Review",
            "Contract Drafting",
            "review for risk and missing protections",
            "Paste the contract text you want reviewed.",
            "a clause-by-clause risk review with suggested edits",
          ],
          [
            "Redline",
            "Contract Drafting",
            "mark up counterparty edits to",
            "Paste both the original and the counterparty's redline.",
            "a tracked-change style summary of what changed and why it matters",
          ],
          [
            "Simplify",
            "Contract Drafting",
            "rewrite in plain English",
            "Paste the legal clause or section you want simplified.",
            "a plain-English version alongside the original clause",
          ],
          [
            "Compare",
            "Contract Drafting",
            "compare two versions of",
            "Paste both versions of the document you want compared.",
            "a side-by-side comparison highlighting substantive differences",
          ],
          [
            "Terminate",
            "Contract Drafting",
            "draft a formal termination notice for",
            "Share the contract terms and the reason for termination.",
            "a termination notice citing the correct clause and notice period",
          ],
        ],
        objects: [
          ["NDA", "a non-disclosure agreement", "nda,confidentiality,legal", "a mutual NDA between a startup and a potential investor"],
          ["ServiceAgreement", "a service agreement", "service,agreement,vendor", "a 12-month consulting agreement with milestone payments"],
          ["EmploymentContract", "an employment contract", "employment,contract,hr", "a full-time offer with a 90-day probation clause"],
          ["LeaseAgreement", "a commercial lease agreement", "lease,rental,property", "a 3-year office lease with an early exit option"],
          ["VendorContract", "a vendor supply contract", "vendor,supply,procurement", "a supplier agreement with volume-based pricing tiers"],
          ["PartnershipAgreement", "a business partnership agreement", "partnership,jointventure,equity", "a 50/50 partnership with defined exit terms"],
          ["LicensingAgreement", "a software licensing agreement", "license,ip,software", "a per-seat license with usage restrictions"],
          ["SaaSAgreement", "a SaaS terms of service agreement", "saas,tos,software", "a B2B SaaS agreement with an uptime SLA clause"],
          ["FreelanceContract", "a freelance or contractor agreement", "freelance,contractor,gig", "a project-based contract with IP assignment terms"],
          ["MergerAgreement", "a merger or acquisition agreement", "merger,acquisition,ma", "an asset purchase agreement for a small acquisition"],
          ["Consulting", "a consulting services agreement", "consulting,services,advisory", "a monthly retainer consulting arrangement"],
          ["DataProcessingAgreement", "a data processing agreement", "dpa,privacy,gdpr", "a DPA required for a new EU-based subprocessor"],
        ],
      },
      {
        verbs: [
          [
            "Assess",
            "Compliance",
            "assess regulatory exposure around",
            "Describe your business activity and the jurisdictions involved.",
            "a compliance risk assessment with priority gaps flagged",
          ],
          [
            "Checklist",
            "Compliance",
            "build a compliance checklist for",
            "State the regulation and the type of business it applies to.",
            "a step-by-step compliance checklist with owners and deadlines",
          ],
          [
            "Explain",
            "Compliance",
            "explain in plain terms the obligations under",
            "Name the law or regulation you need explained.",
            "a plain-language summary of obligations and penalties for non-compliance",
          ],
          [
            "Monitor",
            "Compliance",
            "design a monitoring process for ongoing",
            "Describe what you need to track and how often.",
            "a monitoring cadence with checkpoints and responsible owners",
          ],
          [
            "Remediate",
            "Compliance",
            "draft a remediation plan after a",
            "Describe the compliance gap or incident that occurred.",
            "a remediation plan with corrective actions and timelines",
          ],
          [
            "Report",
            "Compliance",
            "prepare the disclosure report required for",
            "State what triggered the reporting requirement.",
            "a disclosure report formatted for the relevant authority",
          ],
        ],
        objects: [
          ["GDPR", "GDPR data protection requirements", "gdpr,privacy,eu", "a company handling EU customer data for the first time"],
          ["CCPA", "CCPA consumer privacy requirements", "ccpa,privacy,california", "a business selling to california residents online"],
          ["AntiMoneyLaundering", "anti-money-laundering obligations", "aml,kyc,finance", "a fintech onboarding customers with kyc checks"],
          ["WorkplaceSafety", "workplace safety regulations", "safety,osha,workplace", "a warehouse updating its safety protocols"],
          ["DataBreach", "a data breach notification requirement", "breach,notification,security", "a leaked customer database requiring disclosure"],
          ["ExportControl", "export control compliance", "export,trade,customs", "a hardware company shipping to restricted countries"],
          ["Accessibility", "digital accessibility requirements", "accessibility,ada,wcag", "a website needing wcag 2.1 compliance"],
          ["EnvironmentalReg", "environmental regulatory compliance", "environmental,esg,regulation", "a manufacturer tracking emissions reporting requirements"],
          ["LaborLaw", "labor law compliance", "labor,employment,law", "a company classifying contractors versus employees"],
          ["IndustryLicensing", "industry-specific licensing requirements", "licensing,permits,industry", "a business needing a state licensing permit to operate"],
          ["TaxCompliance", "corporate tax compliance", "tax,filing,corporate", "a startup filing its first multi-state tax return"],
          ["AntiTrust", "antitrust and competition rules", "antitrust,competition,merger", "a merger review facing antitrust scrutiny"],
        ],
      },
      {
        verbs: [
          [
            "Prepare",
            "Disputes",
            "prepare the initial case summary for",
            "Describe the dispute, parties involved and key facts.",
            "a case summary with facts, claims and desired outcome",
          ],
          [
            "Demand",
            "Disputes",
            "draft a formal demand letter regarding",
            "State the breach or grievance and what remedy you want.",
            "a demand letter citing the breach and a deadline to respond",
          ],
          [
            "Mediate",
            "Disputes",
            "outline a mediation strategy for",
            "Describe both sides' positions and your ideal settlement range.",
            "a mediation strategy with opening position and fallback options",
          ],
          [
            "Respond",
            "Disputes",
            "draft a formal response to",
            "Paste the complaint or demand letter you received.",
            "a formal response addressing each claim point by point",
          ],
          [
            "Settle",
            "Disputes",
            "draft a settlement agreement for",
            "Describe the agreed terms both parties have reached.",
            "a settlement agreement with terms, release language and signatures",
          ],
          [
            "File",
            "Disputes",
            "prepare the filing documents for",
            "Describe the claim and the court or body you're filing with",
            "filing-ready documents formatted for the relevant venue",
          ],
        ],
        objects: [
          ["BreachOfContract", "a breach of contract dispute", "breach,contract,dispute", "a vendor failing to deliver goods on the agreed date"],
          ["WrongfulTermination", "a wrongful termination claim", "termination,employment,claim", "an employee disputing the grounds for dismissal"],
          ["IPInfringement", "an intellectual property infringement claim", "ip,infringement,trademark", "a competitor using a similar logo and name"],
          ["PaymentDispute", "an unpaid invoice dispute", "payment,invoice,dispute", "a client refusing to pay for delivered consulting work"],
          ["LandlordTenant", "a landlord-tenant dispute", "landlord,tenant,lease", "a tenant withholding rent over unresolved repairs"],
          ["PartnershipDispute", "a business partner dispute", "partnership,dispute,equity", "co-founders disagreeing over equity split"],
          ["ConsumerComplaint", "a formal consumer complaint", "consumer,complaint,warranty", "a customer alleging a defective product caused damage"],
          ["NonCompete", "a non-compete violation claim", "noncompete,restrictive,employment", "a former employee joining a direct competitor"],
          ["Defamation", "a defamation claim", "defamation,reputation,legal", "false statements made about a business in a public review"],
          ["InsuranceClaim", "a disputed insurance claim", "insurance,claim,denial", "an insurer denying a legitimate business interruption claim"],
          ["ShareholderDispute", "a shareholder dispute", "shareholder,equity,corporate", "a minority shareholder alleging exclusion from decisions"],
          ["SmallClaims", "a small claims court matter", "smallclaims,court,filing", "a $4,000 dispute over undelivered custom furniture"],
        ],
      },
    ],
  },
  {
    category: "HR & Hiring",
    type: "business",
    icon: "Users",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Recruiting",
            "write a compelling job posting for",
            "Describe the role, level, and the top three must-have skills.",
            "a job posting that attracts strong candidates and filters weak ones",
          ],
          [
            "Screen",
            "Recruiting",
            "screen resumes and shortlist for",
            "Paste the resumes or candidate list and the role requirements.",
            "a shortlist ranked by fit with reasoning per candidate",
          ],
          [
            "Interview",
            "Recruiting",
            "prepare a structured interview guide for",
            "Describe the role and the competencies you need to assess.",
            "an interview guide with questions, follow-ups and scoring rubric",
          ],
          [
            "Reject",
            "Recruiting",
            "write a respectful rejection message for",
            "Share the candidate's name and stage they reached.",
            "a kind, clear rejection message that keeps the door open",
          ],
          [
            "Negotiate",
            "Recruiting",
            "prepare a compensation negotiation approach for",
            "Share the candidate's ask, your budget range and constraints.",
            "a negotiation approach with a target offer and flexibility points",
          ],
          [
            "Offer",
            "Recruiting",
            "draft the formal offer letter for",
            "Share the role, compensation, start date and any conditions.",
            "an offer letter with all key terms clearly laid out",
          ],
        ],
        objects: [
          ["SoftwareEngineer", "a software engineer role", "engineer,tech,software", "a mid-level backend engineer role on the payments team"],
          ["SalesRep", "a sales representative role", "sales,rep,quota", "an account executive role covering the west region"],
          ["ProductManager", "a product manager role", "product,pm,strategy", "a senior PM role owning the onboarding experience"],
          ["Designer", "a product designer role", "design,ux,ui", "a product designer role for a mobile-first redesign"],
          ["MarketingLead", "a marketing lead role", "marketing,growth,lead", "a growth marketing lead role focused on paid acquisition"],
          ["CustomerSuccess", "a customer success manager role", "cs,success,account", "a CSM role managing a book of mid-market accounts"],
          ["Intern", "an internship position", "intern,entrylevel,student", "a summer engineering internship for undergrads"],
          ["ExecutiveHire", "a senior executive hire", "executive,csuite,leadership", "a VP of Engineering hire reporting to the CTO"],
          ["RemoteWorker", "a fully remote role", "remote,distributed,wfh", "a remote customer support role across time zones"],
          ["ContractHire", "a contract or temp hire", "contract,temp,freelance", "a six-month contract data analyst role"],
          ["CareerChanger", "a candidate switching careers", "careerchange,transition,nontraditional", "a former teacher moving into UX research"],
          ["BoomerangEmployee", "a former employee reapplying", "boomerang,rehire,alumni", "a former employee who left two years ago reapplying"],
        ],
      },
      {
        verbs: [
          [
            "Onboard",
            "Employee Lifecycle",
            "design a first-30-days onboarding plan for",
            "Describe the role and the team they're joining.",
            "a 30-day onboarding plan with milestones and check-ins",
          ],
          [
            "Review",
            "Employee Lifecycle",
            "write a fair, specific performance review for",
            "Share their goals, achievements and any areas of concern.",
            "a performance review with concrete examples and a growth plan",
          ],
          [
            "Promote",
            "Employee Lifecycle",
            "build the promotion case for",
            "Describe their recent accomplishments and the target level.",
            "a promotion case document with evidence mapped to the next level's criteria",
          ],
          [
            "Coach",
            "Employee Lifecycle",
            "write a supportive coaching plan for",
            "Describe the performance gap and what success looks like.",
            "a coaching plan with specific actions and a follow-up timeline",
          ],
          [
            "Transition",
            "Employee Lifecycle",
            "plan a smooth role transition for",
            "Describe the current role, the new role and the handover needs.",
            "a transition plan with a handover checklist and timeline",
          ],
          [
            "Offboard",
            "Employee Lifecycle",
            "create the offboarding checklist for",
            "Share their role, last day and any sensitive access to revoke.",
            "an offboarding checklist covering access, assets and knowledge transfer",
          ],
        ],
        objects: [
          ["NewHire", "a brand-new employee", "newhire,onboarding,day1", "a new hire starting on a fully remote engineering team"],
          ["UnderperformingEmployee", "an underperforming employee", "underperformance,pip,coaching", "an employee consistently missing sprint deadlines"],
          ["HighPerformer", "a high-performing employee up for promotion", "highperformer,promotion,growth", "a top performer ready to move into a lead role"],
          ["ManagerTransition", "an employee becoming a first-time manager", "manager,transition,leadership", "an IC promoted to manage a team of four"],
          ["RemoteNewHire", "a remote new hire in a different timezone", "remote,newhire,timezone", "a new hire based nine hours ahead of hq"],
          ["ResigningEmployee", "an employee who has resigned", "resignation,offboarding,departure", "a five-year employee giving two weeks notice"],
          ["Layoff", "an employee affected by a layoff", "layoff,severance,restructuring", "a role eliminated in a department restructuring"],
          ["ReturningParent", "an employee returning from parental leave", "parentalleave,return,transition", "an employee returning after four months of leave"],
          ["InternalTransfer", "an employee transferring between teams", "transfer,internal,mobility", "an engineer moving from platform to product team"],
          ["Underrepresented", "a career-development plan for retention focus", "dei,development,retention", "a high-potential employee from an underrepresented group"],
          ["ContractToFullTime", "a contractor converting to full-time", "conversion,contractor,fulltime", "a six-month contractor being converted to permanent staff"],
          ["TerminatedForCause", "an employee terminated for cause", "termination,cause,offboarding", "an employee dismissed for a policy violation"],
        ],
      },
      {
        verbs: [
          [
            "Design",
            "People Ops",
            "design a company policy for",
            "Describe your company size, culture and any legal constraints.",
            "a clear written policy with examples and an approval workflow",
          ],
          [
            "Survey",
            "People Ops",
            "build an engagement survey covering",
            "Describe what you want to learn and the team you're surveying.",
            "a short pulse survey with actionable, specific questions",
          ],
          [
            "Benchmark",
            "People Ops",
            "benchmark market rates for",
            "Share the role, level, location and any current pay data.",
            "a compensation benchmark with a recommended pay range",
          ],
          [
            "Plan",
            "People Ops",
            "build a headcount plan for",
            "Share your growth targets and current team structure.",
            "a headcount plan with roles, timing and budget impact",
          ],
          [
            "Announce",
            "People Ops",
            "write the internal announcement about",
            "Describe the change and who it affects.",
            "an internal announcement with a clear reason and next steps",
          ],
          [
            "Investigate",
            "People Ops",
            "outline a fair investigation process for",
            "Describe the complaint and the parties involved, without names if sensitive.",
            "a structured investigation plan with steps and confidentiality safeguards",
          ],
        ],
        objects: [
          ["RemoteWorkPolicy", "a remote work policy", "remote,policy,wfh", "a hybrid policy requiring two office days a week"],
          ["PTOPolicy", "a paid time off policy", "pto,vacation,policy", "an unlimited pto policy with a minimum-days guideline"],
          ["EmployeeEngagement", "employee engagement levels", "engagement,culture,survey", "declining engagement scores in the support team"],
          ["CompensationBands", "compensation bands for a role", "compensation,pay,benchmark", "pay bands for mid-level product designers"],
          ["OrgRestructure", "an organizational restructure", "restructure,orgchart,change", "merging two teams under one new director"],
          ["DEIProgram", "a diversity, equity and inclusion program", "dei,inclusion,culture", "a new mentorship program for underrepresented hires"],
          ["HarassmentComplaint", "a workplace harassment complaint", "harassment,investigation,hr", "a complaint filed against a team lead"],
          ["BurnoutRisk", "team burnout risk", "burnout,wellbeing,workload", "a team working consistent overtime for two months"],
          ["PerformanceImprovementPlan", "a performance improvement plan process", "pip,performance,process", "the standard company process for a formal pip"],
          ["Headcount", "headcount planning for next fiscal year", "headcount,budget,planning", "a plan to grow engineering from 12 to 20 people"],
          ["RemoteStipend", "a remote work stipend policy", "stipend,remote,benefits", "a monthly home-office stipend for remote staff"],
          ["ExitInterview", "an exit interview process", "exitinterview,offboarding,feedback", "structured exit interviews to reduce future attrition"],
        ],
      },
    ],
  },
  {
    category: "Ecommerce & Retail",
    type: "business",
    icon: "ShoppingCart",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Product Listings",
            "write a high-converting product listing for",
            "Describe the product, key features and target customer.",
            "a product listing with headline, bullets and SEO-friendly description",
          ],
          [
            "Optimize",
            "Product Listings",
            "optimize the search ranking of",
            "Paste the current listing and the marketplace it's on.",
            "an optimized listing with improved keywords and structure",
          ],
          [
            "Photograph",
            "Product Listings",
            "plan a product photography shoot for",
            "Describe the product and the platforms it will be listed on.",
            "a shot list covering angles, lifestyle and detail shots",
          ],
          [
            "Translate",
            "Product Listings",
            "localize the listing for a new market for",
            "Paste the listing and specify the target country and language.",
            "a localized listing adapted for language and cultural fit",
          ],
          [
            "ABTest",
            "Product Listings",
            "design an A/B test for the listing of",
            "Describe what element you want to test and your current baseline.",
            "an A/B test plan with variants and a success metric",
          ],
          [
            "Bundle",
            "Product Listings",
            "create a compelling product bundle around",
            "Describe your product catalog and typical customer purchase pattern.",
            "a bundle offer with pricing logic and a listing description",
          ],
        ],
        objects: [
          ["Electronics", "an electronics product", "electronics,gadget,tech", "a wireless earbuds listing for amazon"],
          ["ApparelItem", "a clothing or apparel item", "apparel,fashion,clothing", "a men's waterproof hiking jacket"],
          ["HomeGoods", "a home goods product", "homegoods,decor,household", "a ceramic pour-over coffee set"],
          ["BeautyProduct", "a beauty or skincare product", "beauty,skincare,cosmetics", "a vitamin c serum for sensitive skin"],
          ["Handmade", "a handmade or artisan product", "handmade,artisan,etsy", "a hand-thrown ceramic mug on etsy"],
          ["SubscriptionBox", "a subscription box product", "subscription,box,recurring", "a monthly curated snack subscription box"],
          ["DigitalProduct", "a digital download product", "digital,download,ebook", "a downloadable budgeting spreadsheet template"],
          ["Toy", "a children's toy product", "toy,kids,children", "a wooden building block set for toddlers"],
          ["PetProduct", "a pet product", "pet,petsupplies,animal", "an orthopedic dog bed for senior dogs"],
          ["FoodItem", "a packaged food or grocery item", "food,grocery,packaged", "a small-batch hot sauce three-pack"],
          ["FitnessGear", "a fitness equipment product", "fitness,gear,exercise", "an adjustable dumbbell set for home gyms"],
          ["SeasonalItem", "a seasonal or holiday product", "seasonal,holiday,limited", "a limited-run holiday-themed candle"],
        ],
      },
      {
        verbs: [
          [
            "Plan",
            "Merchandising",
            "plan the promotional calendar for",
            "Share your key sales dates and current inventory priorities.",
            "a promotional calendar with discounts and timing per event",
          ],
          [
            "Price",
            "Merchandising",
            "recommend a pricing strategy for",
            "Share your cost, competitor pricing and margin target.",
            "a pricing recommendation with margin analysis",
          ],
          [
            "Forecast",
            "Merchandising",
            "forecast demand for",
            "Share historical sales data and any upcoming promotions.",
            "a demand forecast with a recommended stock level",
          ],
          [
            "Markdown",
            "Merchandising",
            "design a markdown strategy to clear",
            "Share the current inventory level and how long it's been sitting.",
            "a phased markdown plan to clear stock while protecting margin",
          ],
          [
            "CrossSell",
            "Merchandising",
            "build a cross-sell strategy around",
            "Describe your catalog and typical shopping patterns.",
            "a cross-sell plan with product pairings and placement ideas",
          ],
          [
            "Launch",
            "Merchandising",
            "plan the go-to-market launch for",
            "Describe the product and your target launch date.",
            "a launch plan with pre-launch buzz, launch day and follow-up tactics",
          ],
        ],
        objects: [
          ["FlashSale", "a flash sale event", "flashsale,discount,urgency", "a 24-hour flash sale on last season's inventory"],
          ["NewArrival", "a new product arrival", "newarrival,launch,fresh", "a newly stocked line of ceramic planters"],
          ["SlowMover", "a slow-moving inventory item", "slowmover,clearance,deadstock", "a color variant that hasn't sold in 90 days"],
          ["SeasonalCollection", "a seasonal product collection", "seasonal,collection,catalog", "a summer swimwear collection launching in april"],
          ["BestSeller", "a current best-selling product", "bestseller,topseller,popular", "a phone case that's the store's top seller"],
          ["ClearanceStock", "end-of-season clearance stock", "clearance,endofseason,markdown", "winter coats left over after the season"],
          ["LimitedEdition", "a limited edition product drop", "limitededition,drop,exclusive", "a numbered limited-run sneaker collab"],
          ["BlackFriday", "Black Friday and Cyber Monday sales", "blackfriday,cybermonday,bfcm", "the annual bfcm weekend sales push"],
          ["BackInStock", "a restocked out-of-stock item", "restock,backinstock,inventory", "a popular skincare item back after a month out of stock"],
          ["PrivateLabel", "a new private-label product line", "privatelabel,ownbrand,launch", "a store's first own-brand protein powder"],
          ["Wholesale", "a wholesale or B2B product line", "wholesale,b2b,bulk", "bulk pricing tiers for boutique retailers"],
          ["GiftGuide", "a curated gift guide", "giftguide,curated,holiday", "a mother's day gift guide across price points"],
        ],
      },
      {
        verbs: [
          [
            "Respond",
            "Customer Retail Ops",
            "write a reply to a review for",
            "Paste the customer review you want to respond to.",
            "a genuine review response that fits the tone of the feedback",
          ],
          [
            "Recover",
            "Customer Retail Ops",
            "write an abandoned cart recovery message for",
            "Describe the product left in the cart and any discount you can offer.",
            "a recovery email sequence that nudges without being pushy",
          ],
          [
            "WinBack",
            "Customer Retail Ops",
            "design a win-back campaign for",
            "Describe the lapsed customer segment and their last purchase.",
            "a win-back email sequence with an incentive to return",
          ],
          [
            "Analyze",
            "Customer Retail Ops",
            "analyze return patterns in",
            "Share your return data including reasons and product categories.",
            "a return analysis with root causes and a reduction plan",
          ],
          [
            "Loyalty",
            "Customer Retail Ops",
            "design a loyalty program tier around",
            "Describe your customer base and repeat purchase behavior.",
            "a loyalty program structure with tiers and rewards",
          ],
          [
            "Personalize",
            "Customer Retail Ops",
            "create personalized recommendations for",
            "Share the customer's past purchases or browsing behavior.",
            "personalized product recommendations with reasoning",
          ],
        ],
        objects: [
          ["NegativeReview", "a negative product review", "review,negative,feedback", "a two-star review complaining about sizing"],
          ["PositiveReview", "a glowing five-star review", "review,positive,feedback", "a five-star review praising fast shipping"],
          ["AbandonedCart", "an abandoned shopping cart", "cart,abandoned,recovery", "a cart with two items left unpurchased for 48 hours"],
          ["LapsedCustomer", "a customer who hasn't purchased in months", "lapsed,winback,dormant", "a customer who hasn't ordered in six months"],
          ["FrequentReturner", "a customer with a high return rate", "returns,frequentreturner,pattern", "a customer returning 40% of their orders"],
          ["VIPShopper", "a top-spending VIP shopper", "vip,loyalty,topspender", "a customer who has spent over $2,000 this year"],
          ["FirstTimeBuyer", "a first-time buyer", "firsttime,newcustomer,welcome", "a customer who just placed their first order"],
          ["WishlistItem", "an item sitting in a customer's wishlist", "wishlist,saved,intent", "a jacket saved to wishlist for three weeks"],
          ["SizeExchange", "a size or fit exchange request", "exchange,sizing,fit", "a customer wanting to exchange for a larger size"],
          ["GiftPurchase", "a gift purchase for someone else", "gift,giftwrap,recipient", "a birthday gift order needing gift wrap"],
          ["SubscriberChurn", "a subscription box cancellation", "churn,subscription,cancel", "a subscriber cancelling after three months"],
          ["CrossBorderShopper", "an international cross-border shopper", "international,crossborder,shipping", "a customer ordering from overseas facing customs fees"],
        ],
      },
    ],
  },
];
