export default [
  {
    category: "Coding & Development",
    type: "coding",
    icon: "Code2",
    groups: [
      {
        verbs: [
          [
            "Review",
            "Code Review",
            "review for bugs, edge cases and readability",
            "Paste the diff or file and name the language plus the risk you care about most.",
            "an ordered list of findings with severity and a concrete fix for each",
          ],
          [
            "Refactor",
            "Refactoring",
            "refactor without changing behaviour",
            "Share the current code and state any constraints like framework version or style guide.",
            "a rewritten version with a summary of what changed and why",
          ],
          [
            "Debug",
            "Debugging",
            "diagnose the failure and propose a minimal fix for",
            "Provide the error message, stack trace and steps that trigger the bug.",
            "a root-cause explanation plus a minimal patch to apply",
          ],
          [
            "Test",
            "Testing",
            "write meaningful tests covering",
            "Point to the function or module and mention the testing framework in use.",
            "a test file with edge cases and a note on remaining coverage gaps",
          ],
          [
            "Document",
            "Documentation",
            "write accurate docs and doc comments for",
            "Give the code and specify the target audience, e.g. new hires or API consumers.",
            "inline doc comments plus a short usage section",
          ],
          [
            "Optimize",
            "Performance",
            "find and remove hot-path waste in",
            "Include a profiler trace or describe which operation feels slow.",
            "a prioritized list of bottlenecks with the expected speedup for each fix",
          ],
          [
            "Migrate",
            "Migration",
            "plan a stepwise migration of",
            "Name the source and target versions or platforms and any hard deadlines.",
            "a phased migration plan with rollback points",
          ],
          [
            "Explain",
            "Explanation",
            "walk through line-by-line what happens in",
            "Paste the snippet and say how much prior context the reader already has.",
            "a line-by-line narrative explanation in plain language",
          ],
          [
            "Types",
            "Typing",
            "add precise static types to",
            "Share the file and mention the type system, such as TypeScript strict mode.",
            "the same code annotated with precise types and any new type definitions",
          ],
          [
            "Secure",
            "Security",
            "audit for injection, authz and secret-handling issues in",
            "Provide the endpoint or module and describe who is allowed to call it.",
            "a vulnerability list ranked by severity with remediation steps",
          ],
        ],
        objects: [
          [
            "Function",
            "a function",
            "function",
            "a 40-line `parseInvoice(buffer)` helper in TypeScript",
          ],
          [
            "Component",
            "a UI component",
            "frontend, component",
            "a React `<PricingTable />` component with three tier props",
          ],
          [
            "Api",
            "an API endpoint",
            "api, backend",
            "a `POST /api/orders` Express handler with Stripe integration",
          ],
          [
            "Query",
            "a database query",
            "sql, query",
            "a 30-line PostgreSQL query joining orders, users and refunds",
          ],
          [
            "Script",
            "a script",
            "script, automation",
            "a Python script that renames 10,000 S3 objects nightly",
          ],
          [
            "Config",
            "a config file",
            "config, devops",
            "a `docker-compose.yml` running Postgres, Redis and the app",
          ],
        ],
      },
    ],
  },
  {
    category: "Productivity",
    type: "productivity",
    icon: "Zap",
    groups: [
      {
        verbs: [
          [
            "Plan",
            "Planning",
            "turn into a realistic, sequenced plan",
            "State the deadline and any dependencies or people already committed.",
            "a sequenced plan with milestones and estimated dates",
          ],
          [
            "Prioritize",
            "Prioritization",
            "rank by impact and effort",
            "List the candidate items and the resource or time constraint you're under.",
            "a ranked list with an impact-versus-effort rationale for each item",
          ],
          [
            "Checklist",
            "Checklists",
            "convert into an actionable checklist",
            "Describe the process and note any steps that must happen in strict order.",
            "a numbered checklist with clear pass/fail criteria per step",
          ],
          [
            "Delegate",
            "Delegation",
            "split into delegable work packets",
            "Name the people available and their skill levels or time availability.",
            "discrete work packets each with an owner and a definition of done",
          ],
          [
            "Estimate",
            "Estimation",
            "estimate time and confidence ranges for",
            "Share the scope and flag any unknowns or unfamiliar technology involved.",
            "a time estimate range with a stated confidence level and key risks",
          ],
          [
            "Recap",
            "Recaps",
            "write a concise recap with owners and dates for",
            "Paste the raw notes or transcript and who needs to receive the recap.",
            "a short recap with decisions, owners and due dates called out",
          ],
          [
            "Followup",
            "Follow-ups",
            "draft polite, specific follow-ups for",
            "Say who you're following up with and what response you still need.",
            "a ready-to-send follow-up message tailored to the recipient",
          ],
          [
            "Timebox",
            "Focus",
            "timebox into focused work blocks",
            "List the tasks and the total hours you have available today.",
            "a schedule of timeboxed blocks with breaks built in",
          ],
          [
            "Template",
            "Templates",
            "produce a reusable template for",
            "Describe the recurring situation this template needs to handle.",
            "a fill-in-the-blank template ready to reuse next time",
          ],
          [
            "Unblock",
            "Unblocking",
            "identify the blocker and the smallest next step for",
            "Explain where things stalled and who else is involved.",
            "the root blocker named plus the single smallest unblocking action",
          ],
        ],
        objects: [
          ["Meeting", "a meeting", "meeting", "a 45-minute product roadmap sync with 6 attendees"],
          ["Project", "a project", "project", "a website redesign project due in 8 weeks"],
          [
            "Inbox",
            "an inbox backlog",
            "email, inbox",
            "an inbox with 340 unread emails after two weeks of vacation",
          ],
          [
            "Day",
            "a working day",
            "schedule, day",
            "a Tuesday with 4 meetings and one deep-work deadline",
          ],
          ["Goal", "a goal", "goals, okr", "a Q3 OKR to grow trial signups by 25%"],
          [
            "Backlog",
            "a task backlog",
            "backlog, tasks",
            "a 60-item Jira backlog with no priority labels",
          ],
        ],
      },
    ],
  },
  {
    category: "Business & Management",
    type: "business",
    icon: "Briefcase",
    groups: [
      {
        verbs: [
          [
            "Model",
            "Modeling",
            "build a simple, defensible model for",
            "Give the revenue drivers and any historical numbers you already have.",
            "a spreadsheet-ready model with labeled assumptions",
          ],
          [
            "Pricing",
            "Pricing",
            "propose pricing tiers and rationale for",
            "Share your costs, target customer and competitor price points.",
            "two to three pricing tiers with feature splits and rationale",
          ],
          [
            "Positioning",
            "Positioning",
            "write sharp positioning and messaging for",
            "Describe the target buyer and the single biggest alternative they'd choose instead.",
            "a positioning statement plus three supporting message pillars",
          ],
          [
            "Personas",
            "Personas",
            "define buyer personas and jobs-to-be-done for",
            "Share what you know about current customers or your best guess at them.",
            "two to three personas with goals, pains and jobs-to-be-done",
          ],
          [
            "Competitors",
            "Competition",
            "map the competitive landscape around",
            "List the competitors you already know about, if any.",
            "a competitive map with positioning and gaps to exploit",
          ],
          [
            "Roadmap",
            "Roadmaps",
            "draft a quarterly roadmap for",
            "State the top business goal for the quarter and current team capacity.",
            "a quarter-by-theme roadmap with rough sequencing",
          ],
          [
            "Metrics",
            "Metrics",
            "define the metric tree and north star for",
            "Describe the business model and what success currently looks like.",
            "a metric tree rooted in one north-star metric",
          ],
          [
            "Proposal",
            "Proposals",
            "write a client-ready proposal for",
            "Share the client's stated problem and your proposed scope and price.",
            "a formatted proposal with scope, timeline and price",
          ],
          [
            "Negotiate",
            "Negotiation",
            "prepare negotiation levers and BATNA for",
            "Describe the deal, the other party's likely interests, and your walk-away point.",
            "a list of negotiation levers plus a clearly stated BATNA",
          ],
          [
            "Onepager",
            "One-pagers",
            "condense into an executive one-pager",
            "Paste the longer source material and who the executive reader is.",
            "a single-page summary with the ask stated up front",
          ],
        ],
        objects: [
          [
            "Startup",
            "a startup",
            "startup",
            "a pre-seed fintech startup with 3 founders and no revenue yet",
          ],
          [
            "Product",
            "a product",
            "product",
            "a B2B inventory-tracking product with 200 paying customers",
          ],
          [
            "Service",
            "a service business",
            "services",
            "a boutique bookkeeping firm serving 40 small businesses",
          ],
          ["Saas", "a SaaS offering", "saas", "a project-management SaaS charging $29/seat/month"],
          [
            "Store",
            "an online store",
            "ecommerce",
            "a Shopify store selling handmade ceramic mugs",
          ],
          [
            "Agency",
            "an agency",
            "agency",
            "a 12-person paid-media agency with 5 retainer clients",
          ],
        ],
      },
    ],
  },
  {
    category: "Quality & Performance",
    type: "general",
    icon: "Gauge",
    groups: [
      {
        verbs: [
          [
            "Audit",
            "Audits",
            "run a structured quality audit of",
            "Share access or a full export and state the standard you're auditing against.",
            "a structured audit report with a pass/fail score per section",
          ],
          [
            "Benchmark",
            "Benchmarks",
            "define fair benchmarks and baselines for",
            "Name what you're comparing against and any past performance numbers.",
            "a benchmark table with baseline, target and current values",
          ],
          [
            "Improve",
            "Improvement",
            "propose the three highest-leverage improvements to",
            "Share current performance data and the outcome you most want to move.",
            "the top three improvement recommendations ranked by expected impact",
          ],
          [
            "Stress",
            "Stress Testing",
            "stress-test the weakest points of",
            "Describe expected load or usage patterns and known failure history.",
            "a list of failure points found plus how each was triggered",
          ],
          [
            "Rubric",
            "Rubrics",
            "build a scoring rubric for",
            "Describe what 'good' looks like and who will apply the rubric.",
            "a scoring rubric with weighted criteria and score bands",
          ],
          [
            "Regression",
            "Regressions",
            "hunt for regressions introduced in",
            "Provide the before and after versions or a recent changelog.",
            "a list of suspected regressions with the change that likely caused each",
          ],
          [
            "Accessibility",
            "Accessibility",
            "check WCAG issues and fixes in",
            "Share a URL or markup and the WCAG level you're targeting.",
            "a list of WCAG violations each paired with a concrete fix",
          ],
          [
            "Consistency",
            "Consistency",
            "flag inconsistencies across",
            "Provide the set of items or pages to compare against each other.",
            "a table of inconsistencies found with the recommended standard to adopt",
          ],
          [
            "Latency",
            "Latency",
            "trace and reduce latency in",
            "Share a trace, timing log, or the slow endpoint's typical response time.",
            "a latency breakdown by stage with the biggest win highlighted",
          ],
          [
            "Cost",
            "Cost",
            "find cost waste and savings in",
            "Share the billing breakdown or usage report you're working from.",
            "a list of savings opportunities with estimated dollar impact",
          ],
        ],
        objects: [
          ["Website", "a website", "web", "a marketing site with a 6-second homepage load time"],
          ["App", "an application", "app", "a mobile banking app with 3.9M monthly active users"],
          [
            "Prompt",
            "a prompt",
            "prompting",
            "a 200-word support-ticket triage prompt used in production",
          ],
          [
            "Workflow",
            "a workflow",
            "workflow",
            "a 9-step employee onboarding workflow across 4 tools",
          ],
          [
            "Content",
            "a content library",
            "content",
            "a help center with 180 articles, 40 of them outdated",
          ],
          [
            "Pipeline",
            "a data or build pipeline",
            "pipeline",
            "a nightly ETL pipeline that occasionally times out after 45 minutes",
          ],
        ],
      },
    ],
  },
  {
    category: "Learning & Education",
    type: "learning",
    icon: "GraduationCap",
    groups: [
      {
        verbs: [
          [
            "Teach",
            "Teaching",
            "teach from first principles",
            "State your current knowledge level and how much time you can dedicate.",
            "a from-first-principles lesson building up to the target concept",
          ],
          [
            "ELI5",
            "Explainers",
            "explain in simple everyday language",
            "Name the concept and say whether an analogy would help you most.",
            "a plain-language explanation with a relatable everyday analogy",
          ],
          [
            "Quiz",
            "Quizzes",
            "generate a graded quiz on",
            "Specify the topic scope and how many questions you want.",
            "a graded quiz with an answer key and explanations",
          ],
          [
            "Flashcards",
            "Flashcards",
            "produce spaced-repetition flashcards for",
            "List the terms or facts you need to memorize.",
            "a deck of question-and-answer flashcards ready to import",
          ],
          [
            "Roadmap",
            "Curricula",
            "design a week-by-week learning path for",
            "State your goal, current level and hours per week available.",
            "a week-by-week curriculum with milestones and resources",
          ],
          [
            "Practice",
            "Practice",
            "create hands-on practice exercises for",
            "Say what skill you're practicing and your current proficiency.",
            "a set of graded practice exercises with solutions",
          ],
          [
            "Analogy",
            "Analogies",
            "explain through vivid analogies",
            "Name the concept and any domain you're already comfortable in.",
            "two or three vivid analogies mapped to the concept's parts",
          ],
          [
            "Mistakes",
            "Pitfalls",
            "list the common mistakes beginners make with",
            "Name the skill or tool and your own experience level so far.",
            "a list of common beginner mistakes each paired with how to avoid it",
          ],
          [
            "Recall",
            "Retrieval",
            "run an active-recall session on",
            "Share the material you studied and how recently you reviewed it.",
            "a series of recall prompts with immediate feedback",
          ],
          [
            "Feynman",
            "Technique",
            "run the Feynman technique over",
            "Try explaining the concept yourself first, then share that explanation.",
            "gaps identified in your explanation plus a simplified rewrite",
          ],
        ],
        objects: [
          [
            "Concept",
            "a concept",
            "concept",
            "the concept of eventual consistency in distributed databases",
          ],
          ["Language", "a spoken language", "language", "conversational Spanish at an A2 level"],
          ["Skill", "a practical skill", "skill", "touch typing at 40 words per minute"],
          [
            "Exam",
            "an exam syllabus",
            "exam",
            "the AWS Solutions Architect Associate exam syllabus",
          ],
          ["Book", "a book", "book", "'Thinking, Fast and Slow' by Daniel Kahneman"],
          ["Course", "a course", "course", "a 6-week online course on statistics for data science"],
        ],
      },
    ],
  },
];
