/**
 * Catalog part 7 — AI, ML, databases, spreadsheets, analytics.
 * Shape: category -> groups -> verbs [name, subcategory, phrase, ask, deliverable]
 *                            -> objects [name, phrase, tags, sample]
 */
export default [
  {
    category: "AI Agents & Prompting",
    type: "general",
    icon: "Bot",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Prompt Authoring",
            "write a high-quality prompt for",
            "Describe the task, the target model and the tone or format you want back.",
            "a ready-to-run prompt with role, context and output-format sections",
          ],
          [
            "Refine",
            "Prompt Authoring",
            "tighten up and remove ambiguity from",
            "Paste the current prompt and the output it produced that wasn't right.",
            "a rewritten prompt with the vague parts replaced by concrete instructions",
          ],
          [
            "Debug",
            "Prompt Authoring",
            "diagnose why the model is misbehaving on",
            "Paste the prompt, the bad output and what you expected instead.",
            "a root-cause note plus a fixed version of the prompt",
          ],
          [
            "Compress",
            "Prompt Authoring",
            "shrink the token footprint of",
            "Paste the long prompt and note which parts must never be cut.",
            "a shorter prompt that keeps the required behaviour with fewer tokens",
          ],
          [
            "Template",
            "Prompt Authoring",
            "turn into a reusable template with variables",
            "Give one worked example and list which parts change each run.",
            "a parameterised template with placeholder variables and usage notes",
          ],
          [
            "Jailbreak-proof",
            "Prompt Authoring",
            "harden against manipulation attempts in",
            "Share the prompt and the kind of misuse you're worried about.",
            "a revised prompt with guardrail language and refusal examples",
          ],
        ],
        objects: [
          [
            "SystemPrompt",
            "an assistant's system prompt",
            "system-prompt,persona,instructions",
            "a customer-support bot that must stay on-topic and never quote prices",
          ],
          [
            "FewShotSet",
            "a set of few-shot examples",
            "few-shot,examples,in-context",
            "five input-output pairs for a tone-of-voice rewriting task",
          ],
          [
            "ChainOfThought",
            "a chain-of-thought reasoning prompt",
            "chain-of-thought,reasoning,cot",
            "a multi-step word problem the model keeps getting wrong",
          ],
          [
            "FunctionCallSpec",
            "a function/tool-calling schema",
            "function-calling,tools,schema",
            "a get_weather tool with city and unit parameters",
          ],
          [
            "RagPrompt",
            "a retrieval-augmented generation prompt",
            "rag,retrieval,grounding",
            "a support-doc QA prompt that must cite the source paragraph",
          ],
          [
            "ClassificationPrompt",
            "a text-classification prompt",
            "classification,labeling,categorize",
            "sorting support tickets into billing, bug or feature-request",
          ],
          [
            "SummarizationPrompt",
            "a summarization prompt",
            "summarization,tldr,digest",
            "condensing a 40-minute meeting transcript into five bullet points",
          ],
          [
            "PersonaPrompt",
            "a persona or character prompt",
            "persona,roleplay,character",
            "a skeptical senior engineer who reviews pull requests",
          ],
          [
            "GuardrailPrompt",
            "a safety or refusal guardrail prompt",
            "guardrails,safety,refusal",
            "a medical-advice bot that must redirect to professionals",
          ],
          [
            "EvalRubric",
            "an evaluation rubric prompt for grading outputs",
            "eval,rubric,grading",
            "a rubric scoring email drafts on tone, clarity and length",
          ],
          [
            "MultiTurnScript",
            "a multi-turn conversation script",
            "multi-turn,dialogue,conversation",
            "an onboarding flow that asks four questions in sequence",
          ],
        ],
      },
      {
        verbs: [
          [
            "Design",
            "Agent Architecture",
            "design the architecture for",
            "Describe the goal, available tools and how much autonomy it should have.",
            "an agent design doc with roles, tools, memory and stop conditions",
          ],
          [
            "Orchestrate",
            "Agent Architecture",
            "plan the multi-agent orchestration for",
            "List the sub-tasks and which agent or model should own each one.",
            "a hand-off diagram describing which agent does what and when",
          ],
          [
            "Sandbox",
            "Agent Architecture",
            "define the safe execution sandbox for",
            "Say what actions the agent can take and which are off-limits.",
            "a permissions and sandbox spec listing allowed and blocked actions",
          ],
          [
            "Monitor",
            "Agent Architecture",
            "set up monitoring and alerting for",
            "Describe what a failed or runaway run looks like for this agent.",
            "a monitoring plan with metrics, thresholds and alert triggers",
          ],
          [
            "Retry",
            "Agent Architecture",
            "design the retry and fallback logic for",
            "Explain what typically fails and what an acceptable fallback is.",
            "a retry policy with backoff rules and a graceful fallback path",
          ],
          [
            "Evaluate",
            "Agent Architecture",
            "build an evaluation harness for",
            "Share example tasks and what counts as success or failure.",
            "an eval harness with test cases and pass/fail criteria",
          ],
        ],
        objects: [
          [
            "ResearchAgent",
            "an autonomous research agent",
            "research,web-browsing,agent",
            "an agent that compiles competitor pricing every week",
          ],
          [
            "CodingAgent",
            "a coding assistant agent",
            "coding,dev,agent",
            "an agent that opens pull requests to fix flaky tests",
          ],
          [
            "CustomerSupportAgent",
            "a customer-support agent",
            "support,helpdesk,agent",
            "an agent that resolves refund requests under $50 automatically",
          ],
          [
            "DataEntryAgent",
            "a data-entry automation agent",
            "data-entry,automation,agent",
            "an agent that copies invoice fields into the accounting system",
          ],
          [
            "SchedulingAgent",
            "a scheduling assistant agent",
            "scheduling,calendar,agent",
            "an agent that negotiates meeting times across three time zones",
          ],
          [
            "MemoryStore",
            "an agent's long-term memory store",
            "memory,vector-store,context",
            "conversation history that should persist across sessions",
          ],
          [
            "ToolRegistry",
            "a registry of tools an agent can call",
            "tools,registry,plugins",
            "a set of ten internal APIs an agent may invoke",
          ],
          [
            "HandoffProtocol",
            "a human-in-the-loop hand-off protocol",
            "handoff,escalation,human-in-the-loop",
            "escalating a support agent's uncertain answers to a human",
          ],
          [
            "CostBudget",
            "an agent's token and API cost budget",
            "cost,budget,tokens",
            "a daily token cap for an agent running on GPT-4 class models",
          ],
          [
            "PlannerLoop",
            "a plan-execute-reflect loop",
            "planner,react,reflection",
            "an agent that plans steps, executes and reflects before continuing",
          ],
        ],
      },
      {
        verbs: [
          [
            "Optimize",
            "Model Ops",
            "optimize latency and cost for",
            "Share current p95 latency, cost per call and traffic volume.",
            "an optimization plan with model, caching and batching changes",
          ],
          [
            "Compare",
            "Model Ops",
            "compare model options for",
            "List the models under consideration and your priority (cost, speed, quality).",
            "a comparison table with recommendation and trade-offs",
          ],
          [
            "FineTune",
            "Model Ops",
            "plan a fine-tuning run for",
            "Describe the base model, dataset size and target behaviour.",
            "a fine-tuning plan with dataset prep, hyperparameters and eval plan",
          ],
          [
            "RedTeam",
            "Model Ops",
            "red-team for failure modes and abuse cases in",
            "Share the deployed prompt or model and its intended use.",
            "a red-team report with attack attempts and suggested mitigations",
          ],
          [
            "Version",
            "Model Ops",
            "set up prompt/model versioning for",
            "Describe how many variants exist and how you currently track changes.",
            "a versioning scheme with changelog and rollback plan",
          ],
          [
            "Document",
            "Model Ops",
            "write internal documentation for",
            "Say who will read the docs and what they need to know to use it safely.",
            "a usage doc covering inputs, limits, costs and known failure modes",
          ],
        ],
        objects: [
          [
            "LlmApiCall",
            "a production LLM API integration",
            "api,integration,llm",
            "a call to a chat completion endpoint used in a checkout flow",
          ],
          [
            "PromptCache",
            "a prompt/response caching layer",
            "cache,latency,cost",
            "caching identical FAQ answers for one hour",
          ],
          [
            "EmbeddingPipeline",
            "an embedding generation pipeline",
            "embeddings,vectors,pipeline",
            "embedding 50,000 support articles nightly",
          ],
          [
            "ModelRouter",
            "a model-routing layer choosing between models",
            "routing,model-selection,fallback",
            "routing simple queries to a cheap model and hard ones to a bigger one",
          ],
          [
            "FineTunedModel",
            "a custom fine-tuned model",
            "fine-tuning,custom-model,training",
            "a model fine-tuned on 3,000 labeled support replies",
          ],
          [
            "GuardrailFilter",
            "an input/output content filter",
            "guardrails,moderation,filter",
            "a filter blocking PII from appearing in model responses",
          ],
          [
            "PromptLibrary",
            "a shared library of production prompts",
            "prompt-library,reuse,templates",
            "twelve prompts shared across three product teams",
          ],
          [
            "TokenBudgetPolicy",
            "a per-user token budget policy",
            "tokens,rate-limit,budget",
            "capping free-tier users at 10,000 tokens per day",
          ],
          [
            "EvalDataset",
            "a held-out evaluation dataset",
            "eval,dataset,benchmark",
            "200 hand-labeled examples used to score every new prompt version",
          ],
          [
            "IncidentPostmortem",
            "a postmortem for an AI-related incident",
            "incident,postmortem,reliability",
            "a bot that gave incorrect refund amounts for two hours",
          ],
        ],
      },
    ],
  },
  {
    category: "Machine Learning",
    type: "data",
    icon: "Brain",
    groups: [
      {
        verbs: [
          [
            "Clean",
            "Data Prep",
            "clean and validate the training data in",
            "Attach the dataset and describe any known quality issues.",
            "a cleaned dataset with a log of removed or corrected rows",
          ],
          [
            "Engineer",
            "Data Prep",
            "engineer useful features from",
            "Attach the raw data and describe what the model needs to predict.",
            "a feature set with definitions and rationale for each feature",
          ],
          [
            "Split",
            "Data Prep",
            "create a proper train/validation/test split of",
            "Attach the dataset and mention any grouping or time-ordering to respect.",
            "a leak-free split with sizes and a note on the splitting strategy",
          ],
          [
            "Balance",
            "Data Prep",
            "address class imbalance in",
            "Attach the dataset and state which class is under-represented.",
            "a resampling or weighting plan with before/after class ratios",
          ],
          [
            "Augment",
            "Data Prep",
            "generate synthetic augmentations for",
            "Attach sample data and describe the variation you want to add.",
            "an augmentation pipeline with example transformed samples",
          ],
          [
            "Audit",
            "Data Prep",
            "audit for bias and leakage in",
            "Attach the dataset and describe how it will be used downstream.",
            "a bias and leakage report with concrete remediation steps",
          ],
        ],
        objects: [
          [
            "TabularDataset",
            "a tabular training dataset",
            "tabular,csv,structured",
            "a churn dataset with 40 customer attributes",
          ],
          [
            "TextCorpus",
            "a text corpus",
            "nlp,text,corpus",
            "50,000 product reviews for sentiment training",
          ],
          [
            "ImageDataset",
            "an image dataset",
            "vision,images,cv",
            "10,000 labeled defect photos from a factory line",
          ],
          [
            "TimeSeriesData",
            "a time-series dataset",
            "time-series,forecasting,sequential",
            "three years of daily store sales",
          ],
          [
            "LabelSet",
            "a set of ground-truth labels",
            "labels,annotations,ground-truth",
            "labels applied by three different annotators with disagreements",
          ],
          [
            "FeatureStore",
            "a feature store schema",
            "feature-store,mlops,features",
            "customer features shared across five models",
          ],
          [
            "MissingValueReport",
            "a missing-value profile",
            "missing-data,imputation,quality",
            "a dataset with 12% missing income values",
          ],
          [
            "OutlierSet",
            "a set of detected outliers",
            "outliers,anomalies,quality",
            "transactions flagged as statistically unusual",
          ],
          [
            "MetadataSchema",
            "a dataset metadata schema",
            "metadata,documentation,schema",
            "a data card describing source, licensing and collection date",
          ],
          [
            "SyntheticSample",
            "a synthetic data sample",
            "synthetic,generated,augmentation",
            "generated variations of rare fraud cases",
          ],
        ],
      },
      {
        verbs: [
          [
            "Select",
            "Modeling",
            "recommend a model architecture for",
            "Describe the problem type, data size and latency constraints.",
            "a shortlist of suitable model architectures with trade-offs",
          ],
          [
            "Tune",
            "Modeling",
            "tune hyperparameters for",
            "Share the current model, metric and the search budget you have.",
            "a hyperparameter search plan with ranges and expected gains",
          ],
          [
            "Evaluate",
            "Modeling",
            "design a rigorous evaluation for",
            "Describe the deployment goal and which errors matter most.",
            "an evaluation plan with metrics, baselines and a holdout strategy",
          ],
          [
            "Interpret",
            "Modeling",
            "explain and interpret the predictions of",
            "Share the model type and an example prediction you want explained.",
            "a feature-importance and explanation report for the model",
          ],
          [
            "Compress",
            "Modeling",
            "compress and speed up",
            "Share the model size, target hardware and acceptable accuracy drop.",
            "a compression plan (pruning/quantization/distillation) with expected impact",
          ],
          [
            "Deploy",
            "Modeling",
            "plan the production deployment of",
            "Describe expected traffic, latency budget and rollback needs.",
            "a deployment plan with serving infra, monitoring and rollback steps",
          ],
        ],
        objects: [
          [
            "ClassificationModel",
            "a classification model",
            "classification,supervised,ml",
            "predicting whether a loan application will default",
          ],
          [
            "RegressionModel",
            "a regression model",
            "regression,supervised,ml",
            "predicting next month's delivery volume",
          ],
          [
            "ClusteringModel",
            "a clustering model",
            "clustering,unsupervised,segmentation",
            "grouping customers into five behavioural segments",
          ],
          [
            "RecommenderSystem",
            "a recommendation system",
            "recommender,personalization,ranking",
            "recommending products based on browsing history",
          ],
          [
            "ForecastingModel",
            "a forecasting model",
            "forecasting,time-series,prediction",
            "forecasting weekly demand for 200 SKUs",
          ],
          [
            "AnomalyDetector",
            "an anomaly detection model",
            "anomaly-detection,outliers,monitoring",
            "flagging unusual login patterns in real time",
          ],
          [
            "NlpClassifier",
            "an NLP text classifier",
            "nlp,text-classification,ml",
            "classifying support tickets by urgency",
          ],
          [
            "ComputerVisionModel",
            "a computer vision model",
            "vision,cnn,image-classification",
            "detecting defective parts on an assembly line",
          ],
          [
            "EnsembleModel",
            "an ensemble of models",
            "ensemble,stacking,boosting",
            "combining three models to improve fraud detection recall",
          ],
          [
            "BaselineModel",
            "a simple baseline model",
            "baseline,benchmark,heuristic",
            "a rule-based baseline to compare a new model against",
          ],
        ],
      },
      {
        verbs: [
          [
            "Track",
            "MLOps",
            "set up experiment tracking for",
            "Describe how many experiments you run per week and what you log now.",
            "an experiment tracking setup with metrics, params and comparisons",
          ],
          [
            "Monitor",
            "MLOps",
            "design production monitoring for",
            "Describe what a silent failure or drift would look like for this model.",
            "a monitoring dashboard spec with drift, latency and accuracy alerts",
          ],
          [
            "Retrain",
            "MLOps",
            "design the retraining pipeline for",
            "Describe how often fresh data arrives and current retraining cadence.",
            "a retraining pipeline with triggers, validation gates and rollback",
          ],
          [
            "Version",
            "MLOps",
            "set up model and data versioning for",
            "Describe your current storage setup and team size.",
            "a versioning scheme covering data, code and model artifacts",
          ],
          [
            "Explain",
            "MLOps",
            "write a stakeholder-friendly explanation of",
            "Say who the audience is and how technical they are.",
            "a plain-language explainer with an analogy and one worked example",
          ],
          [
            "Postmortem",
            "MLOps",
            "write an incident postmortem for",
            "Describe what went wrong, when it was noticed and the impact.",
            "a postmortem with timeline, root cause and prevention steps",
          ],
        ],
        objects: [
          [
            "TrainingPipeline",
            "an end-to-end training pipeline",
            "pipeline,mlops,training",
            "a nightly pipeline retraining a demand-forecasting model",
          ],
          [
            "ModelRegistry",
            "a model registry",
            "registry,versioning,mlops",
            "a registry tracking five production model versions",
          ],
          [
            "DataDriftReport",
            "a data drift report",
            "drift,monitoring,quality",
            "input feature distributions shifting after a product change",
          ],
          [
            "ConceptDriftAlert",
            "a concept drift alert",
            "concept-drift,monitoring,ml",
            "a fraud model whose accuracy has quietly dropped 8%",
          ],
          [
            "ServingEndpoint",
            "a model serving endpoint",
            "serving,api,inference",
            "a REST endpoint serving predictions at 200 requests per second",
          ],
          [
            "ABTestResult",
            "an A/B test comparing model versions",
            "ab-test,experiment,comparison",
            "champion vs challenger models tested over two weeks",
          ],
          [
            "FairnessAudit",
            "a model fairness audit",
            "fairness,bias,ethics",
            "checking a hiring model for disparate impact across groups",
          ],
          [
            "ModelCard",
            "a model card document",
            "model-card,documentation,transparency",
            "documenting intended use, limits and training data for a model",
          ],
          [
            "IncidentReport",
            "an ML production incident report",
            "incident,outage,ml",
            "a recommender that started serving irrelevant results for six hours",
          ],
          [
            "CostReport",
            "an ML infrastructure cost report",
            "cost,infra,mlops",
            "monthly GPU spend across training and inference workloads",
          ],
        ],
      },
    ],
  },
  {
    category: "Databases & SQL",
    type: "data",
    icon: "Database",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Query Authoring",
            "write an efficient SQL query for",
            "Describe the tables involved and exactly what result you need.",
            "a working SQL query with a short explanation of each clause",
          ],
          [
            "Optimize",
            "Query Authoring",
            "optimize the performance of",
            "Paste the query, the execution plan if you have it, and table sizes.",
            "a rewritten query plus recommended indexes with expected speedup",
          ],
          [
            "Debug",
            "Query Authoring",
            "find and fix the bug in",
            "Paste the query and describe the wrong result you're getting.",
            "a corrected query with an explanation of what was wrong",
          ],
          [
            "Explain",
            "Query Authoring",
            "explain step by step what",
            "Paste the query you want explained and your current SQL level.",
            "a plain-language walkthrough of what the query does and why",
          ],
          [
            "Convert",
            "Query Authoring",
            "convert to a different SQL dialect",
            "Paste the query and name the source and target database engines.",
            "an equivalent query rewritten for the target dialect",
          ],
          [
            "Parameterize",
            "Query Authoring",
            "parameterize and secure against injection",
            "Paste the query and note which values come from user input.",
            "a parameterized query safe from SQL injection with usage notes",
          ],
        ],
        objects: [
          [
            "JoinQuery",
            "a multi-table join query",
            "join,sql,relational",
            "joining orders, customers and products for a sales report",
          ],
          [
            "AggregateQuery",
            "an aggregation query",
            "aggregate,groupby,sql",
            "total revenue by region and month",
          ],
          [
            "WindowFunctionQuery",
            "a window function query",
            "window-function,analytics,sql",
            "running totals of daily signups per week",
          ],
          [
            "SubqueryChain",
            "a nested subquery",
            "subquery,nested,sql",
            "finding customers whose spend is above their region's average",
          ],
          [
            "RecursiveCte",
            "a recursive common table expression",
            "cte,recursive,sql",
            "traversing an employee-manager hierarchy",
          ],
          [
            "UpsertStatement",
            "an upsert (insert-or-update) statement",
            "upsert,merge,sql",
            "syncing a nightly product feed into a catalog table",
          ],
          [
            "PivotQuery",
            "a pivot/unpivot query",
            "pivot,reshape,sql",
            "turning monthly rows into columns for a dashboard",
          ],
          [
            "DeduplicationQuery",
            "a deduplication query",
            "dedupe,cleanup,sql",
            "removing duplicate customer records keeping the most recent",
          ],
          [
            "SlowQuery",
            "a slow-running production query",
            "performance,slow-query,sql",
            "a report query that now takes 40 seconds instead of 2",
          ],
          [
            "MigrationScript",
            "a data migration SQL script",
            "migration,etl,sql",
            "moving legacy order data into a new normalized schema",
          ],
          [
            "StoredProcedure",
            "a stored procedure",
            "stored-procedure,plsql,sql",
            "a procedure that recalculates loyalty points nightly",
          ],
        ],
      },
      {
        verbs: [
          [
            "Design",
            "Schema Design",
            "design a normalized schema for",
            "Describe the entities involved and how they relate to each other.",
            "an ER diagram description with tables, keys and relationships",
          ],
          [
            "Normalize",
            "Schema Design",
            "normalize and remove redundancy from",
            "Describe the current table structure and any repeated data you've noticed.",
            "a normalized schema up to an appropriate normal form with rationale",
          ],
          [
            "Index",
            "Schema Design",
            "recommend indexes for",
            "Share the schema and the queries that run most frequently.",
            "an indexing plan with expected read/write trade-offs",
          ],
          [
            "Partition",
            "Schema Design",
            "design a partitioning strategy for",
            "Describe table size, growth rate and common filter columns.",
            "a partitioning scheme with the key column and maintenance plan",
          ],
          [
            "VersionSchema",
            "Schema Design",
            "plan a safe migration path for",
            "Describe the current schema and the change you need to make.",
            "a zero-downtime migration plan with rollback steps",
          ],
          [
            "Document",
            "Schema Design",
            "write data-dictionary documentation for",
            "Share the schema and who will be reading the documentation.",
            "a data dictionary listing tables, columns, types and constraints",
          ],
        ],
        objects: [
          [
            "EcommerceSchema",
            "an e-commerce database schema",
            "ecommerce,schema,relational",
            "products, orders, customers and inventory tables",
          ],
          [
            "MultiTenantSchema",
            "a multi-tenant database schema",
            "multi-tenant,saas,schema",
            "isolating data for 500 SaaS customers in one database",
          ],
          [
            "AuditLogTable",
            "an audit log table",
            "audit-log,compliance,schema",
            "tracking every change made to sensitive customer fields",
          ],
          [
            "EventTable",
            "a high-volume event tracking table",
            "events,analytics,schema",
            "logging 2 million app events per day",
          ],
          [
            "UserPermissionModel",
            "a role-based permission model",
            "rbac,permissions,schema",
            "roles and permissions for an internal admin tool",
          ],
          [
            "InventorySchema",
            "an inventory management schema",
            "inventory,warehouse,schema",
            "tracking stock levels across five warehouses",
          ],
          [
            "TimeSeriesTable",
            "a time-series data table",
            "time-series,schema,metrics",
            "storing sensor readings taken every minute",
          ],
          [
            "GraphLikeRelation",
            "a graph-like relational structure",
            "graph,relations,schema",
            "modeling friendships in a social app using a relational database",
          ],
          [
            "SoftDeletePattern",
            "a soft-delete data pattern",
            "soft-delete,schema,pattern",
            "marking records deleted without losing historical data",
          ],
          [
            "LegacySchema",
            "a messy legacy database schema",
            "legacy,tech-debt,schema",
            "a 15-year-old schema with inconsistent naming and no foreign keys",
          ],
        ],
      },
      {
        verbs: [
          [
            "Backup",
            "Operations",
            "design a backup and recovery plan for",
            "Describe data size, acceptable data loss window and current backups.",
            "a backup schedule with retention policy and a tested restore plan",
          ],
          [
            "Secure",
            "Operations",
            "harden access control and security for",
            "Describe who currently has access and any compliance requirements.",
            "a security hardening checklist covering access, encryption and auditing",
          ],
          [
            "Scale",
            "Operations",
            "plan how to scale",
            "Share current load, growth projections and current infrastructure.",
            "a scaling plan covering read replicas, caching and sharding options",
          ],
          [
            "Monitor",
            "Operations",
            "set up health monitoring for",
            "Describe what a slow or failing database would look like for you.",
            "a monitoring plan with key metrics, thresholds and alerts",
          ],
          [
            "Replicate",
            "Operations",
            "design a replication strategy for",
            "Describe your consistency requirements and geographic spread of users.",
            "a replication topology with failover behaviour described",
          ],
          [
            "Cost",
            "Operations",
            "review and reduce the running cost of",
            "Share current usage metrics and your current billing plan.",
            "a cost-reduction report with specific configuration changes",
          ],
        ],
        objects: [
          [
            "ProductionCluster",
            "a production database cluster",
            "cluster,production,ops",
            "a Postgres cluster serving a checkout system",
          ],
          [
            "ReadReplica",
            "a read replica setup",
            "replica,scaling,ops",
            "a reporting replica lagging behind the primary during peak hours",
          ],
          [
            "ConnectionPool",
            "a database connection pool",
            "connection-pool,performance,ops",
            "an app hitting connection limits under load",
          ],
          [
            "BackupPolicy",
            "a backup retention policy",
            "backup,retention,ops",
            "daily backups kept for 30 days with weekly long-term archives",
          ],
          [
            "AccessControlList",
            "a database access control list",
            "access-control,security,ops",
            "restricting write access to a payments table to two services",
          ],
          [
            "EncryptionSetup",
            "an encryption-at-rest and in-transit setup",
            "encryption,security,compliance",
            "encrypting customer PII columns and all database connections",
          ],
          [
            "ShardingStrategy",
            "a sharding strategy",
            "sharding,scaling,ops",
            "sharding a users table by region as traffic grows",
          ],
          [
            "FailoverPlan",
            "a failover and disaster recovery plan",
            "failover,dr,ops",
            "switching to a standby region within five minutes of an outage",
          ],
          [
            "QueryCache",
            "a query result caching layer",
            "cache,performance,ops",
            "caching expensive dashboard queries for two minutes",
          ],
          [
            "ComplianceAudit",
            "a data compliance audit",
            "compliance,gdpr,audit",
            "checking whether customer data deletion requests are fully honored",
          ],
        ],
      },
    ],
  },
  {
    category: "Spreadsheets",
    type: "data",
    icon: "Table",
    groups: [
      {
        verbs: [
          [
            "Write",
            "Formulas",
            "write the right formula for",
            "Describe the columns involved and the result you're trying to calculate.",
            "a working formula with a short explanation of how it works",
          ],
          [
            "Debug",
            "Formulas",
            "find and fix the error in",
            "Paste the formula and describe the error or wrong result you see.",
            "a corrected formula with an explanation of the original mistake",
          ],
          [
            "Simplify",
            "Formulas",
            "simplify an overly complex",
            "Paste the current formula and what it's meant to calculate.",
            "a shorter, more readable formula producing the same result",
          ],
          [
            "Convert",
            "Formulas",
            "convert between spreadsheet dialects for",
            "Paste the formula and name the source and target apps.",
            "an equivalent formula rewritten for the target spreadsheet app",
          ],
          [
            "Explain",
            "Formulas",
            "explain in plain terms how",
            "Paste the formula you want explained and your comfort level with spreadsheets.",
            "a plain-language explanation broken down piece by piece",
          ],
          [
            "Array-ify",
            "Formulas",
            "turn into a single dynamic array formula",
            "Paste the range of repeated formulas you want combined into one.",
            "one array formula replacing many copy-pasted cells",
          ],
        ],
        objects: [
          [
            "LookupFormula",
            "a lookup formula (VLOOKUP/XLOOKUP)",
            "lookup,vlookup,xlookup",
            "matching product IDs to prices across two sheets",
          ],
          [
            "PivotTableSetup",
            "a pivot table configuration",
            "pivot-table,summary,analysis",
            "summarizing sales by rep and quarter",
          ],
          [
            "ConditionalFormattingRule",
            "a conditional formatting rule",
            "conditional-formatting,visual,rules",
            "highlighting overdue invoices in red",
          ],
          [
            "DateCalculation",
            "a date/time calculation",
            "dates,time,calculation",
            "calculating business days until a project deadline",
          ],
          [
            "TextParsingFormula",
            "a text parsing/extraction formula",
            "text,parsing,extraction",
            "splitting a full name column into first and last name",
          ],
          [
            "ArrayFormula",
            "an array or dynamic-array formula",
            "array-formula,dynamic-array,spilled",
            "summing sales for every unique product in one formula",
          ],
          [
            "NestedIfChain",
            "a deeply nested IF statement",
            "if,nested,logic",
            "grading students into five tiers based on score",
          ],
          [
            "CrossSheetReference",
            "a cross-sheet reference formula",
            "cross-sheet,reference,linking",
            "pulling totals from twelve monthly tabs into a summary tab",
          ],
          [
            "ErrorHandlingFormula",
            "an error-handling formula",
            "error-handling,iferror,robustness",
            "a lookup that shows blank instead of #N/A when nothing matches",
          ],
          [
            "ValidationRule",
            "a data validation rule",
            "data-validation,rules,input-control",
            "restricting a column to only approved status values",
          ],
        ],
      },
      {
        verbs: [
          [
            "Build",
            "Modeling",
            "build a working model for",
            "Describe the inputs, outputs and any assumptions to bake in.",
            "a structured spreadsheet model with clearly labeled inputs and outputs",
          ],
          [
            "Forecast",
            "Modeling",
            "build a forecast within",
            "Share historical data and how far ahead you need to forecast.",
            "a forecast model with assumptions called out and a sensitivity range",
          ],
          [
            "Scenario",
            "Modeling",
            "add scenario/what-if analysis to",
            "Describe the variable you want to flex and the range to test.",
            "a scenario toggle with best/base/worst case outputs",
          ],
          [
            "Reconcile",
            "Modeling",
            "reconcile discrepancies between",
            "Attach the two data sources that should match but don't.",
            "a reconciliation sheet flagging every mismatch and its likely cause",
          ],
          [
            "Automate",
            "Modeling",
            "reduce manual work in",
            "Describe the repetitive steps you currently do by hand each time.",
            "a formula or macro plan that automates the repetitive steps",
          ],
          [
            "Stress-test",
            "Modeling",
            "stress-test the assumptions in",
            "Share the model and the assumption you're least confident about.",
            "a sensitivity analysis showing how outputs move with each assumption",
          ],
        ],
        objects: [
          [
            "BudgetModel",
            "a departmental budget model",
            "budget,finance,model",
            "a marketing budget split across five campaigns",
          ],
          [
            "CashFlowModel",
            "a cash flow model",
            "cash-flow,finance,forecast",
            "projecting monthly cash flow for a small business",
          ],
          [
            "SalesForecastModel",
            "a sales forecast model",
            "sales,forecast,model",
            "forecasting next quarter's revenue from pipeline data",
          ],
          [
            "HeadcountPlan",
            "a headcount planning model",
            "headcount,hr,planning",
            "planning hires across four teams over the next year",
          ],
          [
            "BreakEvenAnalysis",
            "a break-even analysis",
            "break-even,finance,analysis",
            "finding the sales volume needed to cover fixed costs",
          ],
          [
            "InventoryTracker",
            "an inventory tracking sheet",
            "inventory,tracking,operations",
            "tracking stock levels and reorder points for 80 SKUs",
          ],
          [
            "ProjectTimeline",
            "a project timeline/Gantt sheet",
            "project,timeline,gantt",
            "an eight-week product launch plan with dependencies",
          ],
          [
            "CommissionCalculator",
            "a sales commission calculator",
            "commission,sales,payroll",
            "tiered commission rates based on quota attainment",
          ],
          [
            "LoanAmortizationSheet",
            "a loan amortization sheet",
            "loan,amortization,finance",
            "a 30-year mortgage with monthly payment breakdown",
          ],
          [
            "CapacityPlanningSheet",
            "a team capacity planning sheet",
            "capacity,planning,resourcing",
            "matching engineer hours available against project demand",
          ],
        ],
      },
      {
        verbs: [
          [
            "Clean",
            "Data Hygiene",
            "clean up messy data in",
            "Attach the sheet and describe the inconsistencies you've noticed.",
            "a cleaned sheet with a log of what was standardized or removed",
          ],
          [
            "Dedupe",
            "Data Hygiene",
            "find and remove duplicates in",
            "Attach the sheet and say which columns define a duplicate.",
            "a deduplicated sheet plus a count of removed duplicate rows",
          ],
          [
            "Validate",
            "Data Hygiene",
            "spot-check for errors in",
            "Attach the sheet and mention any values that look suspicious to you.",
            "a list of flagged cells with the likely error and suggested fix",
          ],
          [
            "Merge",
            "Data Hygiene",
            "merge and reconcile columns from",
            "Attach the separate sheets or columns you need combined.",
            "one merged sheet with a note on how conflicts were resolved",
          ],
          [
            "Standardize",
            "Data Hygiene",
            "standardize formats across",
            "Attach the sheet and specify the format you want everything to match.",
            "a sheet with consistent formatting across every relevant column",
          ],
          [
            "Protect",
            "Data Hygiene",
            "add protection and access rules to",
            "Describe who should be able to view versus edit each part.",
            "a protection plan with locked ranges and share settings",
          ],
        ],
        objects: [
          [
            "ContactList",
            "a contact list",
            "contacts,crm,cleanup",
            "3,000 leads exported from three different tools",
          ],
          [
            "SurveyResponses",
            "raw survey response data",
            "survey,responses,cleanup",
            "500 open-text survey answers with inconsistent capitalization",
          ],
          [
            "ExpenseReport",
            "an expense report sheet",
            "expenses,finance,cleanup",
            "a quarter's worth of employee expense submissions",
          ],
          [
            "ImportedCsv",
            "a freshly imported CSV file",
            "csv,import,cleanup",
            "an export from an old system with garbled date formats",
          ],
          [
            "AddressColumn",
            "a column of mailing addresses",
            "addresses,formatting,cleanup",
            "addresses entered in five different formats",
          ],
          [
            "PhoneNumberColumn",
            "a column of phone numbers",
            "phone-numbers,formatting,cleanup",
            "phone numbers with and without country codes and dashes",
          ],
          [
            "ProductCatalogSheet",
            "a product catalog sheet",
            "catalog,products,cleanup",
            "a catalog with duplicate SKUs entered by different teams",
          ],
          [
            "MultiSourceSheet",
            "data merged from multiple source sheets",
            "merge,multi-source,cleanup",
            "customer lists exported from two CRMs after a merger",
          ],
          [
            "SharedTeamSheet",
            "a shared team working sheet",
            "shared,permissions,collaboration",
            "a planning sheet edited by twenty people with no locked cells",
          ],
          [
            "TimesheetData",
            "employee timesheet data",
            "timesheet,hr,cleanup",
            "logged hours with overlapping and missing entries",
          ],
        ],
      },
    ],
  },
  {
    category: "Analytics & Reporting",
    type: "data",
    icon: "ChartLine",
    groups: [
      {
        verbs: [
          [
            "Analyze",
            "Analysis",
            "run a thorough analysis of",
            "Attach the data and describe the question you're trying to answer.",
            "a written analysis with the key findings ranked by importance",
          ],
          [
            "Segment",
            "Analysis",
            "segment and break down",
            "Attach the data and say which dimensions matter most to you.",
            "a segmented breakdown with the most actionable segment highlighted",
          ],
          [
            "Correlate",
            "Analysis",
            "find correlations and drivers within",
            "Attach the data and list the outcome metric you care about.",
            "a ranked list of likely drivers with correlation strength noted",
          ],
          [
            "Forecast",
            "Analysis",
            "forecast the future trend of",
            "Attach historical data and specify how far ahead to forecast.",
            "a forecast with a confidence range and key assumptions listed",
          ],
          [
            "Benchmark",
            "Analysis",
            "benchmark against industry norms for",
            "Share your numbers and your industry or comparable set.",
            "a benchmark comparison showing where you over- or under-perform",
          ],
          [
            "Diagnose",
            "Analysis",
            "diagnose the root cause of a change in",
            "Attach the data and describe the change you noticed and when.",
            "a root-cause breakdown ranking the most likely explanations",
          ],
        ],
        objects: [
          [
            "SalesData",
            "sales performance data",
            "sales,revenue,analysis",
            "monthly sales across six regions for the past two years",
          ],
          [
            "WebTrafficData",
            "website traffic data",
            "traffic,web-analytics,visitors",
            "daily sessions and bounce rate for the past 90 days",
          ],
          [
            "CustomerChurnData",
            "customer churn data",
            "churn,retention,customers",
            "monthly churn broken down by plan tier",
          ],
          [
            "MarketingCampaignData",
            "marketing campaign performance data",
            "marketing,campaigns,roi",
            "spend and conversions across five ad channels",
          ],
          [
            "ProductUsageData",
            "product usage/telemetry data",
            "usage,telemetry,engagement",
            "feature adoption rates across 20,000 active users",
          ],
          [
            "SurveyData",
            "customer survey data",
            "survey,nps,feedback",
            "NPS scores and comments from last quarter's survey",
          ],
          [
            "SupportTicketData",
            "customer support ticket data",
            "support,tickets,customer-service",
            "ticket volume and resolution time over six months",
          ],
          [
            "FinancialStatement",
            "a company financial statement",
            "finance,statement,p&l",
            "a quarterly profit and loss statement",
          ],
          [
            "OperationsData",
            "operational performance data",
            "operations,efficiency,throughput",
            "order fulfillment times across three warehouses",
          ],
          [
            "HrAttritionData",
            "employee attrition data",
            "hr,attrition,workforce",
            "resignation data segmented by tenure and department",
          ],
        ],
      },
      {
        verbs: [
          [
            "Design",
            "Reporting",
            "design a recurring report for",
            "Describe the audience, how often it's needed and the key metrics.",
            "a report template with sections, metrics and a distribution plan",
          ],
          [
            "Automate",
            "Reporting",
            "automate the generation of",
            "Describe the current manual process and how often it runs.",
            "an automation plan that removes the manual steps involved",
          ],
          [
            "Summarize",
            "Reporting",
            "write an executive summary for",
            "Attach the underlying data or report and name the audience.",
            "a one-page executive summary with three key takeaways",
          ],
          [
            "Visualize",
            "Reporting",
            "recommend the right visualizations for",
            "Describe the data and the point you're trying to make with it.",
            "chart recommendations with reasoning for each choice",
          ],
          [
            "Narrate",
            "Reporting",
            "write the narrative commentary for",
            "Attach the numbers and mention anything unusual that happened.",
            "written commentary explaining the numbers in plain language",
          ],
          [
            "Distribute",
            "Reporting",
            "plan the distribution and cadence for",
            "Describe who needs to see it and how they currently receive updates.",
            "a distribution plan with cadence, channel and owner for each recipient",
          ],
        ],
        objects: [
          [
            "WeeklyBusinessReview",
            "a weekly business review report",
            "wbr,reporting,recurring",
            "a weekly snapshot of revenue, signups and churn",
          ],
          [
            "BoardDeck",
            "a board meeting deck",
            "board,deck,executive",
            "a quarterly update for investors and board members",
          ],
          [
            "KpiDashboard",
            "a KPI dashboard",
            "kpi,dashboard,metrics",
            "a dashboard tracking five north-star metrics",
          ],
          [
            "MonthlyMetricsReport",
            "a monthly metrics report",
            "monthly,metrics,report",
            "a recurring report sent to department heads",
          ],
          [
            "AdHocAnalysisRequest",
            "an ad-hoc analysis request",
            "ad-hoc,one-off,analysis",
            "a one-off question from the CEO about regional performance",
          ],
          [
            "CustomerHealthScorecard",
            "a customer health scorecard",
            "customer-success,health-score,scorecard",
            "scoring accounts by usage, support tickets and NPS",
          ],
          [
            "ExperimentReadout",
            "an A/B test readout",
            "experiment,ab-test,readout",
            "results of a pricing page experiment after two weeks",
          ],
          [
            "FunnelReport",
            "a conversion funnel report",
            "funnel,conversion,report",
            "signup-to-paid conversion across each onboarding step",
          ],
          [
            "CohortAnalysisReport",
            "a cohort analysis report",
            "cohort,retention,report",
            "monthly signup cohorts tracked over six months",
          ],
          [
            "IncidentImpactReport",
            "a report on the business impact of an incident",
            "incident,impact,report",
            "estimating revenue lost during a two-hour outage",
          ],
        ],
      },
      {
        verbs: [
          [
            "Define",
            "Metrics & Governance",
            "define and standardize the metric definition for",
            "Describe how the metric is currently calculated by different teams.",
            "a single agreed-upon metric definition with edge cases documented",
          ],
          [
            "Audit",
            "Metrics & Governance",
            "audit the data quality behind",
            "Attach the report and describe why you suspect the numbers are off.",
            "a data-quality audit listing discrepancies and their likely sources",
          ],
          [
            "Reconcile",
            "Metrics & Governance",
            "reconcile conflicting numbers across",
            "Attach the two conflicting reports or dashboards.",
            "a reconciliation note explaining the discrepancy and the correct number",
          ],
          [
            "Alert",
            "Metrics & Governance",
            "set up anomaly alerts for",
            "Describe the metric and what change would be worth flagging.",
            "an alerting rule with thresholds and who gets notified",
          ],
          [
            "Document",
            "Metrics & Governance",
            "write a data dictionary entry for",
            "Describe the metric, its source tables and calculation logic.",
            "a documented metric definition with source, formula and owner",
          ],
          [
            "Prioritize",
            "Metrics & Governance",
            "prioritize which of these metrics actually matter for",
            "Describe your current list of tracked metrics and your main goal.",
            "a prioritized short list of metrics tied directly to the stated goal",
          ],
        ],
        objects: [
          [
            "NorthStarMetric",
            "a company north-star metric",
            "north-star,strategy,metric",
            "choosing between revenue growth and active-user growth",
          ],
          [
            "RevenueMetric",
            "a revenue metric definition",
            "revenue,finance,metric",
            "reconciling booked revenue versus recognized revenue",
          ],
          [
            "ActiveUserMetric",
            "an active-user metric definition",
            "dau,mau,engagement",
            "defining what counts as a daily active user",
          ],
          [
            "ChurnMetric",
            "a churn rate definition",
            "churn,retention,metric",
            "reconciling logo churn versus revenue churn",
          ],
          [
            "ConversionRateMetric",
            "a conversion rate metric",
            "conversion,funnel,metric",
            "two teams calculating checkout conversion differently",
          ],
          [
            "DataPipelineHealth",
            "the health of a metrics data pipeline",
            "data-pipeline,quality,governance",
            "a pipeline that silently dropped 5% of events last week",
          ],
          [
            "DashboardSprawl",
            "an overgrown collection of dashboards",
            "dashboards,sprawl,governance",
            "40 dashboards built by different teams with overlapping metrics",
          ],
          [
            "MetricOwnershipMap",
            "a metric ownership map",
            "ownership,governance,accountability",
            "assigning a clear owner to each of twelve key metrics",
          ],
          [
            "SlaMetric",
            "a service-level metric",
            "sla,reliability,metric",
            "defining uptime and response-time SLAs for a support team",
          ],
          [
            "VanityMetric",
            "a suspected vanity metric",
            "vanity-metric,strategy,focus",
            "page views that don't correlate with actual revenue",
          ],
        ],
      },
    ],
  },
];
