/**
 * Reference-table kit seeds: the periodic table, Indian states, world
 * currencies, countries data, exam boards and study tables. Each table spawns
 * individual kits (per-element, per-state) plus a table browser.
 */

/* ── periodic table: [number, symbol, name, mass, category] ─────────── */
export const ELEMENTS: [number, string, string, number, string][] = [
  [1, "H", "Hydrogen", 1.008, "Nonmetal"],
  [2, "He", "Helium", 4.0026, "Noble gas"],
  [3, "Li", "Lithium", 6.94, "Alkali metal"],
  [4, "Be", "Beryllium", 9.0122, "Alkaline earth"],
  [5, "B", "Boron", 10.81, "Metalloid"],
  [6, "C", "Carbon", 12.011, "Nonmetal"],
  [7, "N", "Nitrogen", 14.007, "Nonmetal"],
  [8, "O", "Oxygen", 15.999, "Nonmetal"],
  [9, "F", "Fluorine", 18.998, "Halogen"],
  [10, "Ne", "Neon", 20.18, "Noble gas"],
  [11, "Na", "Sodium", 22.99, "Alkali metal"],
  [12, "Mg", "Magnesium", 24.305, "Alkaline earth"],
  [13, "Al", "Aluminium", 26.982, "Post-transition"],
  [14, "Si", "Silicon", 28.085, "Metalloid"],
  [15, "P", "Phosphorus", 30.974, "Nonmetal"],
  [16, "S", "Sulfur", 32.06, "Nonmetal"],
  [17, "Cl", "Chlorine", 35.45, "Halogen"],
  [18, "Ar", "Argon", 39.948, "Noble gas"],
  [19, "K", "Potassium", 39.098, "Alkali metal"],
  [20, "Ca", "Calcium", 40.078, "Alkaline earth"],
  [21, "Sc", "Scandium", 44.956, "Transition"],
  [22, "Ti", "Titanium", 47.867, "Transition"],
  [23, "V", "Vanadium", 50.942, "Transition"],
  [24, "Cr", "Chromium", 51.996, "Transition"],
  [25, "Mn", "Manganese", 54.938, "Transition"],
  [26, "Fe", "Iron", 55.845, "Transition"],
  [27, "Co", "Cobalt", 58.933, "Transition"],
  [28, "Ni", "Nickel", 58.693, "Transition"],
  [29, "Cu", "Copper", 63.546, "Transition"],
  [30, "Zn", "Zinc", 65.38, "Transition"],
  [31, "Ga", "Gallium", 69.723, "Post-transition"],
  [32, "Ge", "Germanium", 72.63, "Metalloid"],
  [33, "As", "Arsenic", 74.922, "Metalloid"],
  [34, "Se", "Selenium", 78.971, "Nonmetal"],
  [35, "Br", "Bromine", 79.904, "Halogen"],
  [36, "Kr", "Krypton", 83.798, "Noble gas"],
  [37, "Rb", "Rubidium", 85.468, "Alkali metal"],
  [38, "Sr", "Strontium", 87.62, "Alkaline earth"],
  [39, "Y", "Yttrium", 88.906, "Transition"],
  [40, "Zr", "Zirconium", 91.224, "Transition"],
  [41, "Nb", "Niobium", 92.906, "Transition"],
  [42, "Mo", "Molybdenum", 95.95, "Transition"],
  [43, "Tc", "Technetium", 98, "Transition"],
  [44, "Ru", "Ruthenium", 101.07, "Transition"],
  [45, "Rh", "Rhodium", 102.91, "Transition"],
  [46, "Pd", "Palladium", 106.42, "Transition"],
  [47, "Ag", "Silver", 107.87, "Transition"],
  [48, "Cd", "Cadmium", 112.41, "Transition"],
  [49, "In", "Indium", 114.82, "Post-transition"],
  [50, "Sn", "Tin", 118.71, "Post-transition"],
  [51, "Sb", "Antimony", 121.76, "Metalloid"],
  [52, "Te", "Tellurium", 127.6, "Metalloid"],
  [53, "I", "Iodine", 126.9, "Halogen"],
  [54, "Xe", "Xenon", 131.29, "Noble gas"],
  [55, "Cs", "Caesium", 132.91, "Alkali metal"],
  [56, "Ba", "Barium", 137.33, "Alkaline earth"],
  [57, "La", "Lanthanum", 138.91, "Lanthanide"],
  [58, "Ce", "Cerium", 140.12, "Lanthanide"],
  [59, "Pr", "Praseodymium", 140.91, "Lanthanide"],
  [60, "Nd", "Neodymium", 144.24, "Lanthanide"],
  [61, "Pm", "Promethium", 145, "Lanthanide"],
  [62, "Sm", "Samarium", 150.36, "Lanthanide"],
  [63, "Eu", "Europium", 151.96, "Lanthanide"],
  [64, "Gd", "Gadolinium", 157.25, "Lanthanide"],
  [65, "Tb", "Terbium", 158.93, "Lanthanide"],
  [66, "Dy", "Dysprosium", 162.5, "Lanthanide"],
  [67, "Ho", "Holmium", 164.93, "Lanthanide"],
  [68, "Er", "Erbium", 167.26, "Lanthanide"],
  [69, "Tm", "Thulium", 168.93, "Lanthanide"],
  [70, "Yb", "Ytterbium", 173.05, "Lanthanide"],
  [71, "Lu", "Lutetium", 174.97, "Lanthanide"],
  [72, "Hf", "Hafnium", 178.49, "Transition"],
  [73, "Ta", "Tantalum", 180.95, "Transition"],
  [74, "W", "Tungsten", 183.84, "Transition"],
  [75, "Re", "Rhenium", 186.21, "Transition"],
  [76, "Os", "Osmium", 190.23, "Transition"],
  [77, "Ir", "Iridium", 192.22, "Transition"],
  [78, "Pt", "Platinum", 195.08, "Transition"],
  [79, "Au", "Gold", 196.97, "Transition"],
  [80, "Hg", "Mercury", 200.59, "Transition"],
  [81, "Tl", "Thallium", 204.38, "Post-transition"],
  [82, "Pb", "Lead", 207.2, "Post-transition"],
  [83, "Bi", "Bismuth", 208.98, "Post-transition"],
  [84, "Po", "Polonium", 209, "Post-transition"],
  [85, "At", "Astatine", 210, "Halogen"],
  [86, "Rn", "Radon", 222, "Noble gas"],
  [87, "Fr", "Francium", 223, "Alkali metal"],
  [88, "Ra", "Radium", 226, "Alkaline earth"],
  [89, "Ac", "Actinium", 227, "Actinide"],
  [90, "Th", "Thorium", 232.04, "Actinide"],
  [91, "Pa", "Protactinium", 231.04, "Actinide"],
  [92, "U", "Uranium", 238.03, "Actinide"],
  [93, "Np", "Neptunium", 237, "Actinide"],
  [94, "Pu", "Plutonium", 244, "Actinide"],
  [95, "Am", "Americium", 243, "Actinide"],
  [96, "Cm", "Curium", 247, "Actinide"],
  [97, "Bk", "Berkelium", 247, "Actinide"],
  [98, "Cf", "Californium", 251, "Actinide"],
  [99, "Es", "Einsteinium", 252, "Actinide"],
  [100, "Fm", "Fermium", 257, "Actinide"],
  [101, "Md", "Mendelevium", 258, "Actinide"],
  [102, "No", "Nobelium", 259, "Actinide"],
  [103, "Lr", "Lawrencium", 266, "Actinide"],
];

export const ELEMENT_CATEGORIES: Record<string, string> = {
  "Nonmetal": "#34d399",
  "Noble gas": "#a78bfa",
  "Alkali metal": "#fb7185",
  "Alkaline earth": "#f59e0b",
  "Metalloid": "#2dd4bf",
  "Halogen": "#60a5fa",
  "Transition": "#94a3b8",
  "Post-transition": "#cbd5e1",
  "Lanthanide": "#f472b6",
  "Actinide": "#c084fc",
};

/* ── Indian states: [state, capital, stats, knownFor] ───────────────── */
export const INDIA_STATES: [string, string, string, string][] = [
  ["Andhra Pradesh", "Amaravati", "49.4M people · 162,968 km²", "Kuchipudi, Tirupati temple, longest coastline in the south"],
  ["Arunachal Pradesh", "Itanagar", "1.6M people · 83,743 km²", "Tawang monastery, first sunrise in India"],
  ["Assam", "Dispur", "36.0M people · 78,438 km²", "Tea gardens, one-horned rhinos, Bihu"],
  ["Bihar", "Patna", "128.1M people · 94,163 km²", "Nalanda ruins, Bodh Gaya, Ashoka's empire"],
  ["Chhattisgarh", "Raipur", "30.6M people · 135,192 km²", "Chitrakote falls, steel plants, tribal art"],
  ["Goa", "Panaji", "1.6M people · 3,702 km²", "Beaches, Portuguese heritage, seafood"],
  ["Gujarat", "Gandhinagar", "71.5M people · 196,244 km²", "Statue of Unity, Gir lions, Rann of Kutch"],
  ["Haryana", "Chandigarh", "29.6M people · 44,212 km²", "Kurukshetra, wrestlers, dairy farming"],
  ["Himachal Pradesh", "Shimla", "7.5M people · 55,673 km²", "Shimla hills, Spiti valley, apples"],
  ["Jharkhand", "Ranchi", "39.6M people · 79,716 km²", "Baidyanath Dham, mines, waterfalls"],
  ["Karnataka", "Bengaluru", "68.0M people · 191,791 km²", "IT capital, Hampi, Coorg coffee"],
  ["Kerala", "Thiruvananthapuram", "35.7M people · 38,852 km²", "Backwaters, ayurveda, 100% literacy push"],
  ["Madhya Pradesh", "Bhopal", "87.3M people · 308,252 km²", "Khajuraho, Kanha tigers, Sanchi stupa"],
  ["Maharashtra", "Mumbai", "126.4M people · 307,713 km²", "Bollywood, Ajanta caves, financial capital"],
  ["Manipur", "Imphal", "3.3M people · 22,327 km²", "Loktak floating lake, Manipuri dance"],
  ["Meghalaya", "Shillong", "3.4M people · 22,429 km²", "Living root bridges, wettest place on Earth"],
  ["Mizoram", "Aizawl", "1.3M people · 21,081 km²", "Bamboo dances, highest literacy among NE states"],
  ["Nagaland", "Kohima", "2.2M people · 16,579 km²", "Hornbill Festival, Dzukou valley"],
  ["Odisha", "Bhubaneswar", "46.4M people · 155,707 km²", "Konark Sun Temple, Chilika lake, Puri"],
  ["Punjab", "Chandigarh", "30.7M people · 50,362 km²", "Golden Temple region, bhangra, wheat bowl"],
  ["Rajasthan", "Jaipur", "81.0M people · 342,239 km²", "Thar desert, Jaipur's pink city, forts"],
  ["Sikkim", "Gangtok", "0.7M people · 7,096 km²", "Kanchenjunga, organic state, monasteries"],
  ["Tamil Nadu", "Chennai", "77.9M people · 130,058 km²", "Temples, Bharatanatyam, filter coffee"],
  ["Telangana", "Hyderabad", "37.7M people · 112,077 km²", "Charminar, biryani, HITEC City"],
  ["Tripura", "Agartala", "4.1M people · 10,486 km²", "Ujjayanta palace, bamboo crafts"],
  ["Uttar Pradesh", "Lucknow", "241.1M people · 240,928 km²", "Taj Mahal, Varanasi, Kumbh Mela"],
  ["Uttarakhand", "Dehradun", "11.7M people · 53,483 km²", "Char Dham, Rishikesh yoga, hill stations"],
  ["West Bengal", "Kolkata", "101.4M people · 88,752 km²", "Durga Puja, sweets, colonial capital"],
];

/* ── world currencies: [code, name, symbol, countries] ──────────────── */
export const CURRENCIES: [string, string, string, string][] = [
  ["INR", "Indian Rupee", "₹", "India"],
  ["USD", "US Dollar", "$", "United States"],
  ["EUR", "Euro", "€", "Eurozone (20 countries)"],
  ["GBP", "British Pound", "£", "United Kingdom"],
  ["JPY", "Japanese Yen", "¥", "Japan"],
  ["CNY", "Chinese Yuan", "¥", "China"],
  ["AUD", "Australian Dollar", "$", "Australia"],
  ["CAD", "Canadian Dollar", "$", "Canada"],
  ["CHF", "Swiss Franc", "Fr", "Switzerland, Liechtenstein"],
  ["AED", "UAE Dirham", "د.إ", "United Arab Emirates"],
  ["SAR", "Saudi Riyal", "﷼", "Saudi Arabia"],
  ["SGD", "Singapore Dollar", "$", "Singapore, Brunei"],
  ["ZAR", "South African Rand", "R", "South Africa, Lesotho, Namibia"],
  ["BRL", "Brazilian Real", "R$", "Brazil"],
  ["RUB", "Russian Ruble", "₽", "Russia"],
  ["KRW", "South Korean Won", "₩", "South Korea"],
  ["TRY", "Turkish Lira", "₺", "Turkey"],
  ["MXN", "Mexican Peso", "$", "Mexico"],
  ["IDR", "Indonesian Rupiah", "Rp", "Indonesia"],
  ["THB", "Thai Baht", "฿", "Thailand"],
  ["BDT", "Bangladeshi Taka", "৳", "Bangladesh"],
  ["PKR", "Pakistani Rupee", "₨", "Pakistan"],
  ["LKR", "Sri Lankan Rupee", "Rs", "Sri Lanka"],
  ["NGN", "Nigerian Naira", "₦", "Nigeria"],
  ["EGP", "Egyptian Pound", "E£", "Egypt"],
  ["KES", "Kenyan Shilling", "KSh", "Kenya"],
  ["NZD", "New Zealand Dollar", "$", "New Zealand"],
  ["HKD", "Hong Kong Dollar", "HK$", "Hong Kong"],
  ["SEK", "Swedish Krona", "kr", "Sweden"],
  ["NOK", "Norwegian Krone", "kr", "Norway"],
];

/* ── study tables (times tables, squares, primes) ───────────────────── */
export const STUDY_TABLES: { id: string; name: string; icon: string; desc: string; upto: number; kind: "table" | "squares" | "cubes" | "primes" | "powers" }[] = [
  { id: "2", name: "Table of 2", icon: "✌️", desc: "the first table every kid learns", upto: 20, kind: "table" },
  { id: "3", name: "Table of 3", icon: "🍀", desc: "threes up to 3 × 20", upto: 20, kind: "table" },
  { id: "4", name: "Table of 4", icon: "🙋", desc: "fours up to 4 × 20", upto: 20, kind: "table" },
  { id: "5", name: "Table of 5", icon: "🖐️", desc: "fives — the easiest table, ends in 0 or 5", upto: 20, kind: "table" },
  { id: "6", name: "Table of 6", icon: "🎲", desc: "sixes up to 6 × 20", upto: 20, kind: "table" },
  { id: "7", name: "Table of 7", icon: "🍀", desc: "sevens — the tricky one", upto: 20, kind: "table" },
  { id: "8", name: "Table of 8", icon: "🕷️", desc: "eights up to 8 × 20", upto: 20, kind: "table" },
  { id: "9", name: "Table of 9", icon: "✨", desc: "nines — watch the tens digit climb", upto: 20, kind: "table" },
  { id: "10", name: "Table of 10", icon: "🔟", desc: "tens — just add a zero", upto: 20, kind: "table" },
  { id: "11", name: "Table of 11", icon: "🪜", desc: "elevens, up to 11 × 20", upto: 20, kind: "table" },
  { id: "12", name: "Table of 12", icon: "🕐", desc: "twelves — the old-style dozen table", upto: 20, kind: "table" },
  { id: "13", name: "Table of 13", icon: "🌙", desc: "teens table, good for exams", upto: 20, kind: "table" },
  { id: "14", name: "Table of 14", icon: "💝", desc: "fourteens up to 14 × 20", upto: 20, kind: "table" },
  { id: "15", name: "Table of 15", icon: "🕰️", desc: "fifteens — handy for clocks and quarters", upto: 20, kind: "table" },
  { id: "16", name: "Table of 16", icon: "🍬", desc: "sixteens up to 16 × 20", upto: 20, kind: "table" },
  { id: "17", name: "Table of 17", icon: "🌰", desc: "seventeens up to 17 × 20", upto: 20, kind: "table" },
  { id: "18", name: "Table of 18", icon: "🏒", desc: "eighteens up to 18 × 20", upto: 20, kind: "table" },
  { id: "19", name: "Table of 19", icon: "🌌", desc: "nineteens up to 19 × 20", upto: 20, kind: "table" },
  { id: "20", name: "Table of 20", icon: "🏏", desc: "twenties — big-league table", upto: 20, kind: "table" },
  { id: "squares", name: "Square Numbers", icon: "◼️", desc: "n² from 1 to 50 — perfect squares", upto: 50, kind: "squares" },
  { id: "cubes", name: "Cube Numbers", icon: "🧊", desc: "n³ from 1 to 30", upto: 30, kind: "cubes" },
  { id: "primes", name: "Prime Numbers", icon: "💎", desc: "every prime up to 541", upto: 100, kind: "primes" },
  { id: "powers-2", name: "Powers of 2", icon: "⚡", desc: "1, 2, 4, 8… up to 2⁴⁹ — how data sizes grow", upto: 50, kind: "powers" },
];

/* ── cheat sheets: [title, icon, group, rows] ───────────────────────── */
export const CHEATSHEETS: { id: string; name: string; icon: string; group: string; desc: string; rows: [string, string][] }[] = [
  {
    id: "git", name: "Git Cheat Sheet", icon: "🌿", group: "Dev",
    desc: "The 24 commands that cover 95% of daily git use",
    rows: [
      ["git status", "show what changed and what's staged"],
      ["git add .", "stage everything in the current folder"],
      ["git commit -m \"msg\"", "save a snapshot with a message"],
      ["git push", "upload commits to the remote"],
      ["git pull", "download and merge remote changes"],
      ["git clone URL", "copy a repo to your machine"],
      ["git branch name", "create a new branch"],
      ["git checkout name", "switch to a branch"],
      ["git switch -c name", "create and switch in one go"],
      ["git merge name", "merge a branch into the current one"],
      ["git log --oneline", "compact history view"],
      ["git diff", "see unstaged changes"],
      ["git restore file", "discard local changes to a file"],
      ["git reset --soft HEAD~1", "undo last commit, keep changes"],
      ["git stash", "shelve changes temporarily"],
      ["git stash pop", "restore shelved changes"],
      ["git remote -v", "list remotes"],
      ["git tag v1.0", "mark a release point"],
      ["git blame file", "who last touched each line"],
      ["git cherry-pick sha", "copy one commit over"],
      ["git rebase main", "replay your branch onto main"],
      ["git fetch", "download remote changes without merging"],
      ["git clean -fd", "delete untracked files (careful!)"],
      ["git help command", "manual for any command"],
    ],
  },
  {
    id: "excel", name: "Excel Shortcuts", icon: "📊", group: "Work",
    desc: "Formulas and shortcuts for daily spreadsheet work",
    rows: [
      ["Ctrl+Shift+L", "toggle filters"],
      ["Ctrl+T", "convert range to table"],
      ["Alt+= ", "auto-sum"],
      ["F2", "edit cell"],
      ["F4", "lock references ($A$1) / repeat last action"],
      ["Ctrl+Arrow keys", "jump to edge of data"],
      ["Ctrl+Shift+Arrow", "select to edge of data"],
      ["SUM(range)", "add numbers"],
      ["AVERAGE(range)", "mean value"],
      ["IF(test, yes, no)", "conditional value"],
      ["VLOOKUP(v, table, col, FALSE)", "find in first column"],
      ["XLOOKUP(v, find, return)", "modern lookup, any direction"],
      ["INDEX(range, n)", "nth item of a range"],
      ["MATCH(v, range, 0)", "position of a value"],
      ["COUNT(range)", "count numbers"],
      ["COUNTIF(range, criteria)", "conditional count"],
      ["SUMIF(range, crit, sumRange)", "conditional sum"],
      ["CONCAT(a, b)", "join text"],
      ["LEFT(text, n)", "first n characters"],
      ["TRIM(text)", "strip extra spaces"],
      ["TODAY()", "current date"],
      ["Ctrl+;", "insert today's date"],
      ["Ctrl+1", "format cells dialog"],
      ["Alt+Enter", "new line inside a cell"],
    ],
  },
  {
    id: "css-flex", name: "CSS Flexbox Sheet", icon: "🎨", group: "Dev",
    desc: "Every flexbox property and what it actually does",
    rows: [
      ["display: flex", "turn a container into a flex row"],
      ["flex-direction: column", "stack children vertically"],
      ["justify-content: center", "center along the main axis"],
      ["align-items: center", "center along the cross axis"],
      ["gap: 1rem", "space between children (use this!)"],
      ["flex-wrap: wrap", "wrap children to new lines"],
      ["flex: 1", "child grows to fill free space"],
      ["flex: 0 0 auto", "child stays at its natural size"],
      ["align-self: flex-end", "override alignment for one child"],
      ["order: -1", "move a child to the front"],
      ["flex-grow: 2", "take double share of free space"],
      ["flex-shrink: 0", "never shrink below content size"],
      ["min-width: 0", "let flex children truncate text"],
      ["margin-left: auto", "push everything after it right"],
      ["height: 100dvh", "full mobile viewport height"],
    ],
  },
  {
    id: "hindi-alphabet", name: "Hindi Varnamala", icon: "🪔", group: "Learn",
    desc: "All 13 vowels and 33 consonants with romanisation",
    rows: [
      ["अ a", "vowel — as in 'about'"],
      ["आ aa", "vowel — long a as in 'father'"],
      ["इ i", "vowel — short i as in 'it'"],
      ["ई ee", "vowel — long ee as in 'see'"],
      ["उ u", "vowel — short u as in 'put'"],
      ["ऊ oo", "vowel — long oo as in 'boot'"],
      ["ए e", "vowel — e as in 'they'"],
      ["ऐ ai", "vowel — ai as in 'main'"],
      ["ओ o", "vowel — o as in 'go'"],
      ["औ au", "vowel — au as in 'aussie'"],
      ["अं an", "nasal sound"],
      ["अः ah", "breathy ending"],
      ["क ka", "consonant — k"],
      ["ख kha", "consonant — kh (aspirated)"],
      ["ग ga", "consonant — g"],
      ["घ gha", "consonant — gh (aspirated)"],
      ["च cha", "consonant — ch"],
      ["ज ja", "consonant — j"],
      ["ट ta", "consonant — retroflex T"],
      ["ठ tha", "consonant — retroflex Th"],
      ["ड da", "consonant — retroflex D"],
      ["ण na", "consonant — retroflex N"],
      ["त ta", "consonant — soft t"],
      ["द da", "consonant — soft d"],
      ["न na", "consonant — n"],
      ["प pa", "consonant — p"],
      ["फ pha", "consonant — ph"],
      ["ब ba", "consonant — b"],
      ["भ bha", "consonant — bh"],
      ["म ma", "consonant — m"],
      ["य ya", "consonant — y"],
      ["र ra", "consonant — r"],
      ["ल la", "consonant — l"],
      ["व va", "consonant — v/w"],
      ["श sha", "consonant — sh"],
      ["ष sha", "consonant — deep sh"],
      ["स sa", "consonant — s"],
      ["ह ha", "consonant — h"],
      ["क्ष ksha", "conjunct — ksh"],
      ["त्र tra", "conjunct — tr"],
      ["ज्ञ gya", "conjunct — gya (as in gyaan)"],
    ],
  },
  {
    id: "keyboard-dev", name: "Dev Keyboard Shortcuts", icon: "⌨️", group: "Dev",
    desc: "VS Code moves that make you look fast (because you are)",
    rows: [
      ["Ctrl/Cmd+P", "quick-open any file"],
      ["Ctrl/Cmd+Shift+P", "command palette"],
      ["Ctrl/Cmd+D", "select next occurrence"],
      ["Ctrl/Cmd+Shift+L", "select all occurrences"],
      ["Alt+Up/Down", "move line up/down"],
      ["Shift+Alt+Up/Down", "copy line up/down"],
      ["Ctrl/Cmd+/", "toggle comment"],
      ["Ctrl/Cmd+B", "toggle sidebar"],
      ["Ctrl/Cmd+`", "toggle terminal"],
      ["Ctrl/Cmd+Shift+F", "search across project"],
      ["Ctrl/Cmd+Shift+K", "delete line"],
      ["Ctrl/Cmd+Enter", "insert line below"],
      ["Ctrl/Cmd+]", "indent line"],
      ["Ctrl/Cmd+G", "go to line number"],
      ["F2", "rename symbol everywhere"],
      ["Ctrl/Cmd+Space", "trigger autocomplete"],
      ["Ctrl/Cmd+K Ctrl/Cmd+S", "all keyboard shortcuts"],
      ["Alt+Click", "multiple cursors"],
    ],
  },
];
