/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AlternativesRouteImport } from './routes/alternatives'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FindRouteImport } from './routes/find'
import { Route as GlassRouteImport } from './routes/glass'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KeyboardRouteImport } from './routes/keyboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MeRouteImport } from './routes/me'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as AssistantAboutRouteImport } from './routes/assistant.about'
import { Route as BuildIdeasIndexRouteImport } from './routes/build-ideas.index'
import { Route as BuildIdeasSlugRouteImport } from './routes/build-ideas.$slug'
import { Route as BuildIdeasProjectsRouteImport } from './routes/build-ideas.projects'
import { Route as BuildIdeasValidateRouteImport } from './routes/build-ideas.validate'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as DiscoverSectionRouteImport } from './routes/discover.$section'
import { Route as DiscoverReelsRouteImport } from './routes/discover.reels'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as GeneratorsIndexRouteImport } from './routes/generators.index'
import { Route as GeneratorsIdRouteImport } from './routes/generators.$id'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubAudienceRouteImport } from './routes/hub.$audience'
import { Route as HubIslamRouteImport } from './routes/hub.islam'
import { Route as HubQuotesRouteImport } from './routes/hub.quotes'
import { Route as HubUrduRouteImport } from './routes/hub.urdu'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsAgeCalculatorRouteImport } from './routes/tools.age-calculator'
import { Route as ToolsAsciiRouteImport } from './routes/tools.ascii'
import { Route as ToolsAspectRouteImport } from './routes/tools.aspect'
import { Route as ToolsBase64RouteImport } from './routes/tools.base64'
import { Route as ToolsBioRouteImport } from './routes/tools.bio'
import { Route as ToolsBmiCalculatorRouteImport } from './routes/tools.bmi-calculator'
import { Route as ToolsBudgetRouteImport } from './routes/tools.budget'
import { Route as ToolsColorPaletteRouteImport } from './routes/tools.color-palette'
import { Route as ToolsContractRouteImport } from './routes/tools.contract'
import { Route as ToolsCountdownRouteImport } from './routes/tools.countdown'
import { Route as ToolsCronRouteImport } from './routes/tools.cron'
import { Route as ToolsCsvToJsonRouteImport } from './routes/tools.csv-to-json'
import { Route as ToolsCvRouteImport } from './routes/tools.cv'
import { Route as ToolsDiffRouteImport } from './routes/tools.diff'
import { Route as ToolsDuaMakerRouteImport } from './routes/tools.dua-maker'
import { Route as ToolsEmiCalculatorRouteImport } from './routes/tools.emi-calculator'
import { Route as ToolsEmojiRouteImport } from './routes/tools.emoji'
import { Route as ToolsExpenseRouteImport } from './routes/tools.expense'
import { Route as ToolsFlashcardMakerRouteImport } from './routes/tools.flashcard-maker'
import { Route as ToolsFlipClockRouteImport } from './routes/tools.flip-clock'
import { Route as ToolsFocusRouteImport } from './routes/tools.focus'
import { Route as ToolsFocusScreenRouteImport } from './routes/tools.focus-screen'
import { Route as ToolsGiftRouteImport } from './routes/tools.gift'
import { Route as ToolsGradientRouteImport } from './routes/tools.gradient'
import { Route as ToolsGstCalculatorRouteImport } from './routes/tools.gst-calculator'
import { Route as ToolsHabitsRouteImport } from './routes/tools.habits'
import { Route as ToolsHtmlToPdfRouteImport } from './routes/tools.html-to-pdf'
import { Route as ToolsImageCompressRouteImport } from './routes/tools.image-compress'
import { Route as ToolsImageConvertRouteImport } from './routes/tools.image-convert'
import { Route as ToolsImagesToPdfRouteImport } from './routes/tools.images-to-pdf'
import { Route as ToolsInvoiceRouteImport } from './routes/tools.invoice'
import { Route as ToolsKharchRouteImport } from './routes/tools.kharch'
import { Route as ToolsLinktreeRouteImport } from './routes/tools.linktree'
import { Route as ToolsLoremRouteImport } from './routes/tools.lorem'
import { Route as ToolsMarkdownEditorRouteImport } from './routes/tools.markdown-editor'
import { Route as ToolsMarkdownToHtmlRouteImport } from './routes/tools.markdown-to-html'
import { Route as ToolsMeetingRouteImport } from './routes/tools.meeting'
import { Route as ToolsMetaRouteImport } from './routes/tools.meta'
import { Route as ToolsMuhurratRouteImport } from './routes/tools.muhurrat'
import { Route as ToolsMultiTimerRouteImport } from './routes/tools.multi-timer'
import { Route as ToolsNameRouteImport } from './routes/tools.name'
import { Route as ToolsNamecardRouteImport } from './routes/tools.namecard'
import { Route as ToolsNewTabRouteImport } from './routes/tools.new-tab'
import { Route as ToolsNotesRouteImport } from './routes/tools.notes'
import { Route as ToolsOneLinerRouteImport } from './routes/tools.one-liner'
import { Route as ToolsPasswordRouteImport } from './routes/tools.password'
import { Route as ToolsPercentageRouteImport } from './routes/tools.percentage'
import { Route as ToolsPlantRouteImport } from './routes/tools.plant'
import { Route as ToolsPollRouteImport } from './routes/tools.poll'
import { Route as ToolsPomodoroRouteImport } from './routes/tools.pomodoro'
import { Route as ToolsQuoteScreenRouteImport } from './routes/tools.quote-screen'
import { Route as ToolsRainScreenRouteImport } from './routes/tools.rain-screen'
import { Route as ToolsReadabilityRouteImport } from './routes/tools.readability'
import { Route as ToolsRegexRouteImport } from './routes/tools.regex'
import { Route as ToolsScreenshotRouteImport } from './routes/tools.screenshot'
import { Route as ToolsSipCalculatorRouteImport } from './routes/tools.sip-calculator'
import { Route as ToolsSmartPasteRouteImport } from './routes/tools.smart-paste'
import { Route as ToolsStandupRouteImport } from './routes/tools.standup'
import { Route as ToolsStarfieldRouteImport } from './routes/tools.starfield'
import { Route as ToolsTableRouteImport } from './routes/tools.table'
import { Route as ToolsTypingTestRouteImport } from './routes/tools.typing-test'
import { Route as ToolsUpiRouteImport } from './routes/tools.upi'
import { Route as ToolsWatermarkRouteImport } from './routes/tools.watermark'
import { Route as ToolsWorldClockRouteImport } from './routes/tools.world-clock'
import { Route as ExploreCategoryIndexRouteImport } from './routes/explore.$category.index'
import { Route as ExploreCategorySubcategoryRouteImport } from './routes/explore.$category.$subcategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesRoute = AlternativesRouteImport.update({
  id: '/alternatives',
  path: '/alternatives',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRoute = GlassRouteImport.update({
  id: '/glass',
  path: '/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyboardRoute = KeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantAboutRoute = AssistantAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AssistantRoute,
} as any)
const BuildIdeasIndexRoute = BuildIdeasIndexRouteImport.update({
  id: '/build-ideas/',
  path: '/build-ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdeasSlugRoute = BuildIdeasSlugRouteImport.update({
  id: '/build-ideas/$slug',
  path: '/build-ideas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdeasProjectsRoute = BuildIdeasProjectsRouteImport.update({
  id: '/build-ideas/projects',
  path: '/build-ideas/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdeasValidateRoute = BuildIdeasValidateRouteImport.update({
  id: '/build-ideas/validate',
  path: '/build-ideas/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSectionRoute = DiscoverSectionRouteImport.update({
  id: '/discover/$section',
  path: '/discover/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverReelsRoute = DiscoverReelsRouteImport.update({
  id: '/discover/reels',
  path: '/discover/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorsIndexRoute = GeneratorsIndexRouteImport.update({
  id: '/generators/',
  path: '/generators/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorsIdRoute = GeneratorsIdRouteImport.update({
  id: '/generators/$id',
  path: '/generators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubAudienceRoute = HubAudienceRouteImport.update({
  id: '/hub/$audience',
  path: '/hub/$audience',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIslamRoute = HubIslamRouteImport.update({
  id: '/hub/islam',
  path: '/hub/islam',
  getParentRoute: () => rootRouteImport,
} as any)
const HubQuotesRoute = HubQuotesRouteImport.update({
  id: '/hub/quotes',
  path: '/hub/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const HubUrduRoute = HubUrduRouteImport.update({
  id: '/hub/urdu',
  path: '/hub/urdu',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAgeCalculatorRoute = ToolsAgeCalculatorRouteImport.update({
  id: '/age-calculator',
  path: '/age-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAsciiRoute = ToolsAsciiRouteImport.update({
  id: '/ascii',
  path: '/ascii',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAspectRoute = ToolsAspectRouteImport.update({
  id: '/aspect',
  path: '/aspect',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBioRoute = ToolsBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBmiCalculatorRoute = ToolsBmiCalculatorRouteImport.update({
  id: '/bmi-calculator',
  path: '/bmi-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBudgetRoute = ToolsBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsColorPaletteRoute = ToolsColorPaletteRouteImport.update({
  id: '/color-palette',
  path: '/color-palette',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsContractRoute = ToolsContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCountdownRoute = ToolsCountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCronRoute = ToolsCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCsvToJsonRoute = ToolsCsvToJsonRouteImport.update({
  id: '/csv-to-json',
  path: '/csv-to-json',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCvRoute = ToolsCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDiffRoute = ToolsDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDuaMakerRoute = ToolsDuaMakerRouteImport.update({
  id: '/dua-maker',
  path: '/dua-maker',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEmiCalculatorRoute = ToolsEmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEmojiRoute = ToolsEmojiRouteImport.update({
  id: '/emoji',
  path: '/emoji',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsExpenseRoute = ToolsExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFlashcardMakerRoute = ToolsFlashcardMakerRouteImport.update({
  id: '/flashcard-maker',
  path: '/flashcard-maker',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFlipClockRoute = ToolsFlipClockRouteImport.update({
  id: '/flip-clock',
  path: '/flip-clock',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFocusRoute = ToolsFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFocusScreenRoute = ToolsFocusScreenRouteImport.update({
  id: '/focus-screen',
  path: '/focus-screen',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGiftRoute = ToolsGiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGradientRoute = ToolsGradientRouteImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGstCalculatorRoute = ToolsGstCalculatorRouteImport.update({
  id: '/gst-calculator',
  path: '/gst-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHabitsRoute = ToolsHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHtmlToPdfRoute = ToolsHtmlToPdfRouteImport.update({
  id: '/html-to-pdf',
  path: '/html-to-pdf',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageCompressRoute = ToolsImageCompressRouteImport.update({
  id: '/image-compress',
  path: '/image-compress',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageConvertRoute = ToolsImageConvertRouteImport.update({
  id: '/image-convert',
  path: '/image-convert',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImagesToPdfRoute = ToolsImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsInvoiceRoute = ToolsInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKharchRoute = ToolsKharchRouteImport.update({
  id: '/kharch',
  path: '/kharch',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsLinktreeRoute = ToolsLinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsLoremRoute = ToolsLoremRouteImport.update({
  id: '/lorem',
  path: '/lorem',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMarkdownEditorRoute = ToolsMarkdownEditorRouteImport.update({
  id: '/markdown-editor',
  path: '/markdown-editor',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMarkdownToHtmlRoute = ToolsMarkdownToHtmlRouteImport.update({
  id: '/markdown-to-html',
  path: '/markdown-to-html',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMeetingRoute = ToolsMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMetaRoute = ToolsMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMuhurratRoute = ToolsMuhurratRouteImport.update({
  id: '/muhurrat',
  path: '/muhurrat',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMultiTimerRoute = ToolsMultiTimerRouteImport.update({
  id: '/multi-timer',
  path: '/multi-timer',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNameRoute = ToolsNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNamecardRoute = ToolsNamecardRouteImport.update({
  id: '/namecard',
  path: '/namecard',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNewTabRoute = ToolsNewTabRouteImport.update({
  id: '/new-tab',
  path: '/new-tab',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNotesRoute = ToolsNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsOneLinerRoute = ToolsOneLinerRouteImport.update({
  id: '/one-liner',
  path: '/one-liner',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPasswordRoute = ToolsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPercentageRoute = ToolsPercentageRouteImport.update({
  id: '/percentage',
  path: '/percentage',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPlantRoute = ToolsPlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPollRoute = ToolsPollRouteImport.update({
  id: '/poll',
  path: '/poll',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPomodoroRoute = ToolsPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQuoteScreenRoute = ToolsQuoteScreenRouteImport.update({
  id: '/quote-screen',
  path: '/quote-screen',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRainScreenRoute = ToolsRainScreenRouteImport.update({
  id: '/rain-screen',
  path: '/rain-screen',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsReadabilityRoute = ToolsReadabilityRouteImport.update({
  id: '/readability',
  path: '/readability',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRegexRoute = ToolsRegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsScreenshotRoute = ToolsScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSipCalculatorRoute = ToolsSipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSmartPasteRoute = ToolsSmartPasteRouteImport.update({
  id: '/smart-paste',
  path: '/smart-paste',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsStandupRoute = ToolsStandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsStarfieldRoute = ToolsStarfieldRouteImport.update({
  id: '/starfield',
  path: '/starfield',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTableRoute = ToolsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTypingTestRoute = ToolsTypingTestRouteImport.update({
  id: '/typing-test',
  path: '/typing-test',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUpiRoute = ToolsUpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWatermarkRoute = ToolsWatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWorldClockRoute = ToolsWorldClockRouteImport.update({
  id: '/world-clock',
  path: '/world-clock',
  getParentRoute: () => ToolsRoute,
} as any)
const ExploreCategoryIndexRoute = ExploreCategoryIndexRouteImport.update({
  id: '/explore/$category/',
  path: '/explore/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategorySubcategoryRoute =
  ExploreCategorySubcategoryRouteImport.update({
    id: '/explore/$category/$subcategory',
    path: '/explore/$category/$subcategory',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/alternatives': typeof AlternativesRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/designs': typeof DesignsRoute
  '/favorites': typeof FavoritesRoute
  '/find': typeof FindRoute
  '/glass': typeof GlassRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/keyboard': typeof KeyboardRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/movies': typeof MoviesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/radar': typeof RadarRoute
  '/recent': typeof RecentRoute
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/whats-new': typeof WhatsNewRoute
  '/youtube': typeof YoutubeRoute
  '/assistant/about': typeof AssistantAboutRoute
  '/build-ideas/$slug': typeof BuildIdeasSlugRoute
  '/build-ideas/projects': typeof BuildIdeasProjectsRoute
  '/build-ideas/validate': typeof BuildIdeasValidateRoute
  '/c/$slug': typeof CSlugRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/discover/$section': typeof DiscoverSectionRoute
  '/discover/reels': typeof DiscoverReelsRoute
  '/generators/$id': typeof GeneratorsIdRoute
  '/hub/$audience': typeof HubAudienceRoute
  '/hub/islam': typeof HubIslamRoute
  '/hub/quotes': typeof HubQuotesRoute
  '/hub/urdu': typeof HubUrduRoute
  '/r/$id': typeof RIdRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/ascii': typeof ToolsAsciiRoute
  '/tools/aspect': typeof ToolsAspectRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bio': typeof ToolsBioRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/budget': typeof ToolsBudgetRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/contract': typeof ToolsContractRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/cv': typeof ToolsCvRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/dua-maker': typeof ToolsDuaMakerRoute
  '/tools/emi-calculator': typeof ToolsEmiCalculatorRoute
  '/tools/emoji': typeof ToolsEmojiRoute
  '/tools/expense': typeof ToolsExpenseRoute
  '/tools/flashcard-maker': typeof ToolsFlashcardMakerRoute
  '/tools/flip-clock': typeof ToolsFlipClockRoute
  '/tools/focus': typeof ToolsFocusRoute
  '/tools/focus-screen': typeof ToolsFocusScreenRoute
  '/tools/gift': typeof ToolsGiftRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/habits': typeof ToolsHabitsRoute
  '/tools/html-to-pdf': typeof ToolsHtmlToPdfRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-convert': typeof ToolsImageConvertRoute
  '/tools/images-to-pdf': typeof ToolsImagesToPdfRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/kharch': typeof ToolsKharchRoute
  '/tools/linktree': typeof ToolsLinktreeRoute
  '/tools/lorem': typeof ToolsLoremRoute
  '/tools/markdown-editor': typeof ToolsMarkdownEditorRoute
  '/tools/markdown-to-html': typeof ToolsMarkdownToHtmlRoute
  '/tools/meeting': typeof ToolsMeetingRoute
  '/tools/meta': typeof ToolsMetaRoute
  '/tools/muhurrat': typeof ToolsMuhurratRoute
  '/tools/multi-timer': typeof ToolsMultiTimerRoute
  '/tools/name': typeof ToolsNameRoute
  '/tools/namecard': typeof ToolsNamecardRoute
  '/tools/new-tab': typeof ToolsNewTabRoute
  '/tools/notes': typeof ToolsNotesRoute
  '/tools/one-liner': typeof ToolsOneLinerRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/percentage': typeof ToolsPercentageRoute
  '/tools/plant': typeof ToolsPlantRoute
  '/tools/poll': typeof ToolsPollRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/tools/quote-screen': typeof ToolsQuoteScreenRoute
  '/tools/rain-screen': typeof ToolsRainScreenRoute
  '/tools/readability': typeof ToolsReadabilityRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/screenshot': typeof ToolsScreenshotRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/smart-paste': typeof ToolsSmartPasteRoute
  '/tools/standup': typeof ToolsStandupRoute
  '/tools/starfield': typeof ToolsStarfieldRoute
  '/tools/table': typeof ToolsTableRoute
  '/tools/typing-test': typeof ToolsTypingTestRoute
  '/tools/upi': typeof ToolsUpiRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
  '/tools/world-clock': typeof ToolsWorldClockRoute
  '/build-ideas/': typeof BuildIdeasIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/generators/': typeof GeneratorsIndexRoute
  '/hub/': typeof HubIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/explore/$category/$subcategory': typeof ExploreCategorySubcategoryRoute
  '/explore/$category/': typeof ExploreCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/alternatives': typeof AlternativesRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/designs': typeof DesignsRoute
  '/favorites': typeof FavoritesRoute
  '/find': typeof FindRoute
  '/glass': typeof GlassRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/keyboard': typeof KeyboardRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/movies': typeof MoviesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/radar': typeof RadarRoute
  '/recent': typeof RecentRoute
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/whats-new': typeof WhatsNewRoute
  '/youtube': typeof YoutubeRoute
  '/assistant/about': typeof AssistantAboutRoute
  '/build-ideas/$slug': typeof BuildIdeasSlugRoute
  '/build-ideas/projects': typeof BuildIdeasProjectsRoute
  '/build-ideas/validate': typeof BuildIdeasValidateRoute
  '/c/$slug': typeof CSlugRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/discover/$section': typeof DiscoverSectionRoute
  '/discover/reels': typeof DiscoverReelsRoute
  '/generators/$id': typeof GeneratorsIdRoute
  '/hub/$audience': typeof HubAudienceRoute
  '/hub/islam': typeof HubIslamRoute
  '/hub/quotes': typeof HubQuotesRoute
  '/hub/urdu': typeof HubUrduRoute
  '/r/$id': typeof RIdRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/ascii': typeof ToolsAsciiRoute
  '/tools/aspect': typeof ToolsAspectRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bio': typeof ToolsBioRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/budget': typeof ToolsBudgetRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/contract': typeof ToolsContractRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/cv': typeof ToolsCvRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/dua-maker': typeof ToolsDuaMakerRoute
  '/tools/emi-calculator': typeof ToolsEmiCalculatorRoute
  '/tools/emoji': typeof ToolsEmojiRoute
  '/tools/expense': typeof ToolsExpenseRoute
  '/tools/flashcard-maker': typeof ToolsFlashcardMakerRoute
  '/tools/flip-clock': typeof ToolsFlipClockRoute
  '/tools/focus': typeof ToolsFocusRoute
  '/tools/focus-screen': typeof ToolsFocusScreenRoute
  '/tools/gift': typeof ToolsGiftRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/habits': typeof ToolsHabitsRoute
  '/tools/html-to-pdf': typeof ToolsHtmlToPdfRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-convert': typeof ToolsImageConvertRoute
  '/tools/images-to-pdf': typeof ToolsImagesToPdfRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/kharch': typeof ToolsKharchRoute
  '/tools/linktree': typeof ToolsLinktreeRoute
  '/tools/lorem': typeof ToolsLoremRoute
  '/tools/markdown-editor': typeof ToolsMarkdownEditorRoute
  '/tools/markdown-to-html': typeof ToolsMarkdownToHtmlRoute
  '/tools/meeting': typeof ToolsMeetingRoute
  '/tools/meta': typeof ToolsMetaRoute
  '/tools/muhurrat': typeof ToolsMuhurratRoute
  '/tools/multi-timer': typeof ToolsMultiTimerRoute
  '/tools/name': typeof ToolsNameRoute
  '/tools/namecard': typeof ToolsNamecardRoute
  '/tools/new-tab': typeof ToolsNewTabRoute
  '/tools/notes': typeof ToolsNotesRoute
  '/tools/one-liner': typeof ToolsOneLinerRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/percentage': typeof ToolsPercentageRoute
  '/tools/plant': typeof ToolsPlantRoute
  '/tools/poll': typeof ToolsPollRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/tools/quote-screen': typeof ToolsQuoteScreenRoute
  '/tools/rain-screen': typeof ToolsRainScreenRoute
  '/tools/readability': typeof ToolsReadabilityRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/screenshot': typeof ToolsScreenshotRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/smart-paste': typeof ToolsSmartPasteRoute
  '/tools/standup': typeof ToolsStandupRoute
  '/tools/starfield': typeof ToolsStarfieldRoute
  '/tools/table': typeof ToolsTableRoute
  '/tools/typing-test': typeof ToolsTypingTestRoute
  '/tools/upi': typeof ToolsUpiRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
  '/tools/world-clock': typeof ToolsWorldClockRoute
  '/build-ideas': typeof BuildIdeasIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/generators': typeof GeneratorsIndexRoute
  '/hub': typeof HubIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/explore/$category/$subcategory': typeof ExploreCategorySubcategoryRoute
  '/explore/$category': typeof ExploreCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/alternatives': typeof AlternativesRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/designs': typeof DesignsRoute
  '/favorites': typeof FavoritesRoute
  '/find': typeof FindRoute
  '/glass': typeof GlassRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/keyboard': typeof KeyboardRoute
  '/live': typeof LiveRoute
  '/me': typeof MeRoute
  '/movies': typeof MoviesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/radar': typeof RadarRoute
  '/recent': typeof RecentRoute
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/whats-new': typeof WhatsNewRoute
  '/youtube': typeof YoutubeRoute
  '/assistant/about': typeof AssistantAboutRoute
  '/build-ideas/$slug': typeof BuildIdeasSlugRoute
  '/build-ideas/projects': typeof BuildIdeasProjectsRoute
  '/build-ideas/validate': typeof BuildIdeasValidateRoute
  '/c/$slug': typeof CSlugRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/discover/$section': typeof DiscoverSectionRoute
  '/discover/reels': typeof DiscoverReelsRoute
  '/generators/$id': typeof GeneratorsIdRoute
  '/hub/$audience': typeof HubAudienceRoute
  '/hub/islam': typeof HubIslamRoute
  '/hub/quotes': typeof HubQuotesRoute
  '/hub/urdu': typeof HubUrduRoute
  '/r/$id': typeof RIdRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/ascii': typeof ToolsAsciiRoute
  '/tools/aspect': typeof ToolsAspectRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bio': typeof ToolsBioRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/budget': typeof ToolsBudgetRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/contract': typeof ToolsContractRoute
  '/tools/countdown': typeof ToolsCountdownRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/csv-to-json': typeof ToolsCsvToJsonRoute
  '/tools/cv': typeof ToolsCvRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/dua-maker': typeof ToolsDuaMakerRoute
  '/tools/emi-calculator': typeof ToolsEmiCalculatorRoute
  '/tools/emoji': typeof ToolsEmojiRoute
  '/tools/expense': typeof ToolsExpenseRoute
  '/tools/flashcard-maker': typeof ToolsFlashcardMakerRoute
  '/tools/flip-clock': typeof ToolsFlipClockRoute
  '/tools/focus': typeof ToolsFocusRoute
  '/tools/focus-screen': typeof ToolsFocusScreenRoute
  '/tools/gift': typeof ToolsGiftRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/habits': typeof ToolsHabitsRoute
  '/tools/html-to-pdf': typeof ToolsHtmlToPdfRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/image-convert': typeof ToolsImageConvertRoute
  '/tools/images-to-pdf': typeof ToolsImagesToPdfRoute
  '/tools/invoice': typeof ToolsInvoiceRoute
  '/tools/kharch': typeof ToolsKharchRoute
  '/tools/linktree': typeof ToolsLinktreeRoute
  '/tools/lorem': typeof ToolsLoremRoute
  '/tools/markdown-editor': typeof ToolsMarkdownEditorRoute
  '/tools/markdown-to-html': typeof ToolsMarkdownToHtmlRoute
  '/tools/meeting': typeof ToolsMeetingRoute
  '/tools/meta': typeof ToolsMetaRoute
  '/tools/muhurrat': typeof ToolsMuhurratRoute
  '/tools/multi-timer': typeof ToolsMultiTimerRoute
  '/tools/name': typeof ToolsNameRoute
  '/tools/namecard': typeof ToolsNamecardRoute
  '/tools/new-tab': typeof ToolsNewTabRoute
  '/tools/notes': typeof ToolsNotesRoute
  '/tools/one-liner': typeof ToolsOneLinerRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/percentage': typeof ToolsPercentageRoute
  '/tools/plant': typeof ToolsPlantRoute
  '/tools/poll': typeof ToolsPollRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/tools/quote-screen': typeof ToolsQuoteScreenRoute
  '/tools/rain-screen': typeof ToolsRainScreenRoute
  '/tools/readability': typeof ToolsReadabilityRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/screenshot': typeof ToolsScreenshotRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/smart-paste': typeof ToolsSmartPasteRoute
  '/tools/standup': typeof ToolsStandupRoute
  '/tools/starfield': typeof ToolsStarfieldRoute
  '/tools/table': typeof ToolsTableRoute
  '/tools/typing-test': typeof ToolsTypingTestRoute
  '/tools/upi': typeof ToolsUpiRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
  '/tools/world-clock': typeof ToolsWorldClockRoute
  '/build-ideas/': typeof BuildIdeasIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/generators/': typeof GeneratorsIndexRoute
  '/hub/': typeof HubIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/explore/$category/$subcategory': typeof ExploreCategorySubcategoryRoute
  '/explore/$category/': typeof ExploreCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/alternatives'
    | '/assistant'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/designs'
    | '/favorites'
    | '/find'
    | '/glass'
    | '/glossary'
    | '/journal'
    | '/keyboard'
    | '/live'
    | '/me'
    | '/movies'
    | '/play'
    | '/privacy'
    | '/quiz'
    | '/radar'
    | '/recent'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/trending'
    | '/whats-new'
    | '/youtube'
    | '/assistant/about'
    | '/build-ideas/$slug'
    | '/build-ideas/projects'
    | '/build-ideas/validate'
    | '/c/$slug'
    | '/collections/$id'
    | '/discover/$section'
    | '/discover/reels'
    | '/generators/$id'
    | '/hub/$audience'
    | '/hub/islam'
    | '/hub/quotes'
    | '/hub/urdu'
    | '/r/$id'
    | '/tools/age-calculator'
    | '/tools/ascii'
    | '/tools/aspect'
    | '/tools/base64'
    | '/tools/bio'
    | '/tools/bmi-calculator'
    | '/tools/budget'
    | '/tools/color-palette'
    | '/tools/contract'
    | '/tools/countdown'
    | '/tools/cron'
    | '/tools/csv-to-json'
    | '/tools/cv'
    | '/tools/diff'
    | '/tools/dua-maker'
    | '/tools/emi-calculator'
    | '/tools/emoji'
    | '/tools/expense'
    | '/tools/flashcard-maker'
    | '/tools/flip-clock'
    | '/tools/focus'
    | '/tools/focus-screen'
    | '/tools/gift'
    | '/tools/gradient'
    | '/tools/gst-calculator'
    | '/tools/habits'
    | '/tools/html-to-pdf'
    | '/tools/image-compress'
    | '/tools/image-convert'
    | '/tools/images-to-pdf'
    | '/tools/invoice'
    | '/tools/kharch'
    | '/tools/linktree'
    | '/tools/lorem'
    | '/tools/markdown-editor'
    | '/tools/markdown-to-html'
    | '/tools/meeting'
    | '/tools/meta'
    | '/tools/muhurrat'
    | '/tools/multi-timer'
    | '/tools/name'
    | '/tools/namecard'
    | '/tools/new-tab'
    | '/tools/notes'
    | '/tools/one-liner'
    | '/tools/password'
    | '/tools/percentage'
    | '/tools/plant'
    | '/tools/poll'
    | '/tools/pomodoro'
    | '/tools/quote-screen'
    | '/tools/rain-screen'
    | '/tools/readability'
    | '/tools/regex'
    | '/tools/screenshot'
    | '/tools/sip-calculator'
    | '/tools/smart-paste'
    | '/tools/standup'
    | '/tools/starfield'
    | '/tools/table'
    | '/tools/typing-test'
    | '/tools/upi'
    | '/tools/watermark'
    | '/tools/world-clock'
    | '/build-ideas/'
    | '/collections/'
    | '/discover/'
    | '/explore/'
    | '/generators/'
    | '/hub/'
    | '/tools/'
    | '/explore/$category/$subcategory'
    | '/explore/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/alternatives'
    | '/assistant'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/designs'
    | '/favorites'
    | '/find'
    | '/glass'
    | '/glossary'
    | '/journal'
    | '/keyboard'
    | '/live'
    | '/me'
    | '/movies'
    | '/play'
    | '/privacy'
    | '/quiz'
    | '/radar'
    | '/recent'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/terms'
    | '/trending'
    | '/whats-new'
    | '/youtube'
    | '/assistant/about'
    | '/build-ideas/$slug'
    | '/build-ideas/projects'
    | '/build-ideas/validate'
    | '/c/$slug'
    | '/collections/$id'
    | '/discover/$section'
    | '/discover/reels'
    | '/generators/$id'
    | '/hub/$audience'
    | '/hub/islam'
    | '/hub/quotes'
    | '/hub/urdu'
    | '/r/$id'
    | '/tools/age-calculator'
    | '/tools/ascii'
    | '/tools/aspect'
    | '/tools/base64'
    | '/tools/bio'
    | '/tools/bmi-calculator'
    | '/tools/budget'
    | '/tools/color-palette'
    | '/tools/contract'
    | '/tools/countdown'
    | '/tools/cron'
    | '/tools/csv-to-json'
    | '/tools/cv'
    | '/tools/diff'
    | '/tools/dua-maker'
    | '/tools/emi-calculator'
    | '/tools/emoji'
    | '/tools/expense'
    | '/tools/flashcard-maker'
    | '/tools/flip-clock'
    | '/tools/focus'
    | '/tools/focus-screen'
    | '/tools/gift'
    | '/tools/gradient'
    | '/tools/gst-calculator'
    | '/tools/habits'
    | '/tools/html-to-pdf'
    | '/tools/image-compress'
    | '/tools/image-convert'
    | '/tools/images-to-pdf'
    | '/tools/invoice'
    | '/tools/kharch'
    | '/tools/linktree'
    | '/tools/lorem'
    | '/tools/markdown-editor'
    | '/tools/markdown-to-html'
    | '/tools/meeting'
    | '/tools/meta'
    | '/tools/muhurrat'
    | '/tools/multi-timer'
    | '/tools/name'
    | '/tools/namecard'
    | '/tools/new-tab'
    | '/tools/notes'
    | '/tools/one-liner'
    | '/tools/password'
    | '/tools/percentage'
    | '/tools/plant'
    | '/tools/poll'
    | '/tools/pomodoro'
    | '/tools/quote-screen'
    | '/tools/rain-screen'
    | '/tools/readability'
    | '/tools/regex'
    | '/tools/screenshot'
    | '/tools/sip-calculator'
    | '/tools/smart-paste'
    | '/tools/standup'
    | '/tools/starfield'
    | '/tools/table'
    | '/tools/typing-test'
    | '/tools/upi'
    | '/tools/watermark'
    | '/tools/world-clock'
    | '/build-ideas'
    | '/collections'
    | '/discover'
    | '/explore'
    | '/generators'
    | '/hub'
    | '/tools'
    | '/explore/$category/$subcategory'
    | '/explore/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-tools'
    | '/alternatives'
    | '/assistant'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/designs'
    | '/favorites'
    | '/find'
    | '/glass'
    | '/glossary'
    | '/journal'
    | '/keyboard'
    | '/live'
    | '/me'
    | '/movies'
    | '/play'
    | '/privacy'
    | '/quiz'
    | '/radar'
    | '/recent'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/trending'
    | '/whats-new'
    | '/youtube'
    | '/assistant/about'
    | '/build-ideas/$slug'
    | '/build-ideas/projects'
    | '/build-ideas/validate'
    | '/c/$slug'
    | '/collections/$id'
    | '/discover/$section'
    | '/discover/reels'
    | '/generators/$id'
    | '/hub/$audience'
    | '/hub/islam'
    | '/hub/quotes'
    | '/hub/urdu'
    | '/r/$id'
    | '/tools/age-calculator'
    | '/tools/ascii'
    | '/tools/aspect'
    | '/tools/base64'
    | '/tools/bio'
    | '/tools/bmi-calculator'
    | '/tools/budget'
    | '/tools/color-palette'
    | '/tools/contract'
    | '/tools/countdown'
    | '/tools/cron'
    | '/tools/csv-to-json'
    | '/tools/cv'
    | '/tools/diff'
    | '/tools/dua-maker'
    | '/tools/emi-calculator'
    | '/tools/emoji'
    | '/tools/expense'
    | '/tools/flashcard-maker'
    | '/tools/flip-clock'
    | '/tools/focus'
    | '/tools/focus-screen'
    | '/tools/gift'
    | '/tools/gradient'
    | '/tools/gst-calculator'
    | '/tools/habits'
    | '/tools/html-to-pdf'
    | '/tools/image-compress'
    | '/tools/image-convert'
    | '/tools/images-to-pdf'
    | '/tools/invoice'
    | '/tools/kharch'
    | '/tools/linktree'
    | '/tools/lorem'
    | '/tools/markdown-editor'
    | '/tools/markdown-to-html'
    | '/tools/meeting'
    | '/tools/meta'
    | '/tools/muhurrat'
    | '/tools/multi-timer'
    | '/tools/name'
    | '/tools/namecard'
    | '/tools/new-tab'
    | '/tools/notes'
    | '/tools/one-liner'
    | '/tools/password'
    | '/tools/percentage'
    | '/tools/plant'
    | '/tools/poll'
    | '/tools/pomodoro'
    | '/tools/quote-screen'
    | '/tools/rain-screen'
    | '/tools/readability'
    | '/tools/regex'
    | '/tools/screenshot'
    | '/tools/sip-calculator'
    | '/tools/smart-paste'
    | '/tools/standup'
    | '/tools/starfield'
    | '/tools/table'
    | '/tools/typing-test'
    | '/tools/upi'
    | '/tools/watermark'
    | '/tools/world-clock'
    | '/build-ideas/'
    | '/collections/'
    | '/discover/'
    | '/explore/'
    | '/generators/'
    | '/hub/'
    | '/tools/'
    | '/explore/$category/$subcategory'
    | '/explore/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiToolsRoute: typeof AiToolsRoute
  AlternativesRoute: typeof AlternativesRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  DesignsRoute: typeof DesignsRoute
  FavoritesRoute: typeof FavoritesRoute
  FindRoute: typeof FindRoute
  GlassRoute: typeof GlassRoute
  GlossaryRoute: typeof GlossaryRoute
  JournalRoute: typeof JournalRoute
  KeyboardRoute: typeof KeyboardRoute
  LiveRoute: typeof LiveRoute
  MeRoute: typeof MeRoute
  MoviesRoute: typeof MoviesRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  RadarRoute: typeof RadarRoute
  RecentRoute: typeof RecentRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  WhatsNewRoute: typeof WhatsNewRoute
  YoutubeRoute: typeof YoutubeRoute
  BuildIdeasSlugRoute: typeof BuildIdeasSlugRoute
  BuildIdeasProjectsRoute: typeof BuildIdeasProjectsRoute
  BuildIdeasValidateRoute: typeof BuildIdeasValidateRoute
  CSlugRoute: typeof CSlugRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  DiscoverSectionRoute: typeof DiscoverSectionRoute
  DiscoverReelsRoute: typeof DiscoverReelsRoute
  GeneratorsIdRoute: typeof GeneratorsIdRoute
  HubAudienceRoute: typeof HubAudienceRoute
  HubIslamRoute: typeof HubIslamRoute
  HubQuotesRoute: typeof HubQuotesRoute
  HubUrduRoute: typeof HubUrduRoute
  RIdRoute: typeof RIdRoute
  BuildIdeasIndexRoute: typeof BuildIdeasIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  GeneratorsIndexRoute: typeof GeneratorsIndexRoute
  HubIndexRoute: typeof HubIndexRoute
  ExploreCategorySubcategoryRoute: typeof ExploreCategorySubcategoryRoute
  ExploreCategoryIndexRoute: typeof ExploreCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives': {
      id: '/alternatives'
      path: '/alternatives'
      fullPath: '/alternatives'
      preLoaderRoute: typeof AlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass': {
      id: '/glass'
      path: '/glass'
      fullPath: '/glass'
      preLoaderRoute: typeof GlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyboard': {
      id: '/keyboard'
      path: '/keyboard'
      fullPath: '/keyboard'
      preLoaderRoute: typeof KeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/about': {
      id: '/assistant/about'
      path: '/about'
      fullPath: '/assistant/about'
      preLoaderRoute: typeof AssistantAboutRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/build-ideas/': {
      id: '/build-ideas/'
      path: '/build-ideas'
      fullPath: '/build-ideas/'
      preLoaderRoute: typeof BuildIdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-ideas/$slug': {
      id: '/build-ideas/$slug'
      path: '/build-ideas/$slug'
      fullPath: '/build-ideas/$slug'
      preLoaderRoute: typeof BuildIdeasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-ideas/projects': {
      id: '/build-ideas/projects'
      path: '/build-ideas/projects'
      fullPath: '/build-ideas/projects'
      preLoaderRoute: typeof BuildIdeasProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-ideas/validate': {
      id: '/build-ideas/validate'
      path: '/build-ideas/validate'
      fullPath: '/build-ideas/validate'
      preLoaderRoute: typeof BuildIdeasValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$section': {
      id: '/discover/$section'
      path: '/discover/$section'
      fullPath: '/discover/$section'
      preLoaderRoute: typeof DiscoverSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/reels': {
      id: '/discover/reels'
      path: '/discover/reels'
      fullPath: '/discover/reels'
      preLoaderRoute: typeof DiscoverReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generators/': {
      id: '/generators/'
      path: '/generators'
      fullPath: '/generators/'
      preLoaderRoute: typeof GeneratorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generators/$id': {
      id: '/generators/$id'
      path: '/generators/$id'
      fullPath: '/generators/$id'
      preLoaderRoute: typeof GeneratorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$audience': {
      id: '/hub/$audience'
      path: '/hub/$audience'
      fullPath: '/hub/$audience'
      preLoaderRoute: typeof HubAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/islam': {
      id: '/hub/islam'
      path: '/hub/islam'
      fullPath: '/hub/islam'
      preLoaderRoute: typeof HubIslamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/quotes': {
      id: '/hub/quotes'
      path: '/hub/quotes'
      fullPath: '/hub/quotes'
      preLoaderRoute: typeof HubQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/urdu': {
      id: '/hub/urdu'
      path: '/hub/urdu'
      fullPath: '/hub/urdu'
      preLoaderRoute: typeof HubUrduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/age-calculator': {
      id: '/tools/age-calculator'
      path: '/age-calculator'
      fullPath: '/tools/age-calculator'
      preLoaderRoute: typeof ToolsAgeCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ascii': {
      id: '/tools/ascii'
      path: '/ascii'
      fullPath: '/tools/ascii'
      preLoaderRoute: typeof ToolsAsciiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/aspect': {
      id: '/tools/aspect'
      path: '/aspect'
      fullPath: '/tools/aspect'
      preLoaderRoute: typeof ToolsAspectRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/bio': {
      id: '/tools/bio'
      path: '/bio'
      fullPath: '/tools/bio'
      preLoaderRoute: typeof ToolsBioRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/bmi-calculator': {
      id: '/tools/bmi-calculator'
      path: '/bmi-calculator'
      fullPath: '/tools/bmi-calculator'
      preLoaderRoute: typeof ToolsBmiCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/budget': {
      id: '/tools/budget'
      path: '/budget'
      fullPath: '/tools/budget'
      preLoaderRoute: typeof ToolsBudgetRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/color-palette': {
      id: '/tools/color-palette'
      path: '/color-palette'
      fullPath: '/tools/color-palette'
      preLoaderRoute: typeof ToolsColorPaletteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/contract': {
      id: '/tools/contract'
      path: '/contract'
      fullPath: '/tools/contract'
      preLoaderRoute: typeof ToolsContractRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/countdown': {
      id: '/tools/countdown'
      path: '/countdown'
      fullPath: '/tools/countdown'
      preLoaderRoute: typeof ToolsCountdownRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cron': {
      id: '/tools/cron'
      path: '/cron'
      fullPath: '/tools/cron'
      preLoaderRoute: typeof ToolsCronRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/csv-to-json': {
      id: '/tools/csv-to-json'
      path: '/csv-to-json'
      fullPath: '/tools/csv-to-json'
      preLoaderRoute: typeof ToolsCsvToJsonRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cv': {
      id: '/tools/cv'
      path: '/cv'
      fullPath: '/tools/cv'
      preLoaderRoute: typeof ToolsCvRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/diff': {
      id: '/tools/diff'
      path: '/diff'
      fullPath: '/tools/diff'
      preLoaderRoute: typeof ToolsDiffRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/dua-maker': {
      id: '/tools/dua-maker'
      path: '/dua-maker'
      fullPath: '/tools/dua-maker'
      preLoaderRoute: typeof ToolsDuaMakerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/emi-calculator': {
      id: '/tools/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/tools/emi-calculator'
      preLoaderRoute: typeof ToolsEmiCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/emoji': {
      id: '/tools/emoji'
      path: '/emoji'
      fullPath: '/tools/emoji'
      preLoaderRoute: typeof ToolsEmojiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/expense': {
      id: '/tools/expense'
      path: '/expense'
      fullPath: '/tools/expense'
      preLoaderRoute: typeof ToolsExpenseRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/flashcard-maker': {
      id: '/tools/flashcard-maker'
      path: '/flashcard-maker'
      fullPath: '/tools/flashcard-maker'
      preLoaderRoute: typeof ToolsFlashcardMakerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/flip-clock': {
      id: '/tools/flip-clock'
      path: '/flip-clock'
      fullPath: '/tools/flip-clock'
      preLoaderRoute: typeof ToolsFlipClockRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/focus': {
      id: '/tools/focus'
      path: '/focus'
      fullPath: '/tools/focus'
      preLoaderRoute: typeof ToolsFocusRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/focus-screen': {
      id: '/tools/focus-screen'
      path: '/focus-screen'
      fullPath: '/tools/focus-screen'
      preLoaderRoute: typeof ToolsFocusScreenRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/gift': {
      id: '/tools/gift'
      path: '/gift'
      fullPath: '/tools/gift'
      preLoaderRoute: typeof ToolsGiftRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/gradient': {
      id: '/tools/gradient'
      path: '/gradient'
      fullPath: '/tools/gradient'
      preLoaderRoute: typeof ToolsGradientRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/gst-calculator': {
      id: '/tools/gst-calculator'
      path: '/gst-calculator'
      fullPath: '/tools/gst-calculator'
      preLoaderRoute: typeof ToolsGstCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/habits': {
      id: '/tools/habits'
      path: '/habits'
      fullPath: '/tools/habits'
      preLoaderRoute: typeof ToolsHabitsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/html-to-pdf': {
      id: '/tools/html-to-pdf'
      path: '/html-to-pdf'
      fullPath: '/tools/html-to-pdf'
      preLoaderRoute: typeof ToolsHtmlToPdfRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-compress': {
      id: '/tools/image-compress'
      path: '/image-compress'
      fullPath: '/tools/image-compress'
      preLoaderRoute: typeof ToolsImageCompressRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-convert': {
      id: '/tools/image-convert'
      path: '/image-convert'
      fullPath: '/tools/image-convert'
      preLoaderRoute: typeof ToolsImageConvertRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/images-to-pdf': {
      id: '/tools/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/tools/images-to-pdf'
      preLoaderRoute: typeof ToolsImagesToPdfRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/invoice': {
      id: '/tools/invoice'
      path: '/invoice'
      fullPath: '/tools/invoice'
      preLoaderRoute: typeof ToolsInvoiceRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kharch': {
      id: '/tools/kharch'
      path: '/kharch'
      fullPath: '/tools/kharch'
      preLoaderRoute: typeof ToolsKharchRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/linktree': {
      id: '/tools/linktree'
      path: '/linktree'
      fullPath: '/tools/linktree'
      preLoaderRoute: typeof ToolsLinktreeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/lorem': {
      id: '/tools/lorem'
      path: '/lorem'
      fullPath: '/tools/lorem'
      preLoaderRoute: typeof ToolsLoremRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/markdown-editor': {
      id: '/tools/markdown-editor'
      path: '/markdown-editor'
      fullPath: '/tools/markdown-editor'
      preLoaderRoute: typeof ToolsMarkdownEditorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/markdown-to-html': {
      id: '/tools/markdown-to-html'
      path: '/markdown-to-html'
      fullPath: '/tools/markdown-to-html'
      preLoaderRoute: typeof ToolsMarkdownToHtmlRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/meeting': {
      id: '/tools/meeting'
      path: '/meeting'
      fullPath: '/tools/meeting'
      preLoaderRoute: typeof ToolsMeetingRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/meta': {
      id: '/tools/meta'
      path: '/meta'
      fullPath: '/tools/meta'
      preLoaderRoute: typeof ToolsMetaRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/muhurrat': {
      id: '/tools/muhurrat'
      path: '/muhurrat'
      fullPath: '/tools/muhurrat'
      preLoaderRoute: typeof ToolsMuhurratRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/multi-timer': {
      id: '/tools/multi-timer'
      path: '/multi-timer'
      fullPath: '/tools/multi-timer'
      preLoaderRoute: typeof ToolsMultiTimerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/name': {
      id: '/tools/name'
      path: '/name'
      fullPath: '/tools/name'
      preLoaderRoute: typeof ToolsNameRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/namecard': {
      id: '/tools/namecard'
      path: '/namecard'
      fullPath: '/tools/namecard'
      preLoaderRoute: typeof ToolsNamecardRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/new-tab': {
      id: '/tools/new-tab'
      path: '/new-tab'
      fullPath: '/tools/new-tab'
      preLoaderRoute: typeof ToolsNewTabRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/notes': {
      id: '/tools/notes'
      path: '/notes'
      fullPath: '/tools/notes'
      preLoaderRoute: typeof ToolsNotesRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/one-liner': {
      id: '/tools/one-liner'
      path: '/one-liner'
      fullPath: '/tools/one-liner'
      preLoaderRoute: typeof ToolsOneLinerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/password': {
      id: '/tools/password'
      path: '/password'
      fullPath: '/tools/password'
      preLoaderRoute: typeof ToolsPasswordRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/percentage': {
      id: '/tools/percentage'
      path: '/percentage'
      fullPath: '/tools/percentage'
      preLoaderRoute: typeof ToolsPercentageRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/plant': {
      id: '/tools/plant'
      path: '/plant'
      fullPath: '/tools/plant'
      preLoaderRoute: typeof ToolsPlantRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/poll': {
      id: '/tools/poll'
      path: '/poll'
      fullPath: '/tools/poll'
      preLoaderRoute: typeof ToolsPollRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pomodoro': {
      id: '/tools/pomodoro'
      path: '/pomodoro'
      fullPath: '/tools/pomodoro'
      preLoaderRoute: typeof ToolsPomodoroRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/quote-screen': {
      id: '/tools/quote-screen'
      path: '/quote-screen'
      fullPath: '/tools/quote-screen'
      preLoaderRoute: typeof ToolsQuoteScreenRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/rain-screen': {
      id: '/tools/rain-screen'
      path: '/rain-screen'
      fullPath: '/tools/rain-screen'
      preLoaderRoute: typeof ToolsRainScreenRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/readability': {
      id: '/tools/readability'
      path: '/readability'
      fullPath: '/tools/readability'
      preLoaderRoute: typeof ToolsReadabilityRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/regex': {
      id: '/tools/regex'
      path: '/regex'
      fullPath: '/tools/regex'
      preLoaderRoute: typeof ToolsRegexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/screenshot': {
      id: '/tools/screenshot'
      path: '/screenshot'
      fullPath: '/tools/screenshot'
      preLoaderRoute: typeof ToolsScreenshotRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sip-calculator': {
      id: '/tools/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/tools/sip-calculator'
      preLoaderRoute: typeof ToolsSipCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/smart-paste': {
      id: '/tools/smart-paste'
      path: '/smart-paste'
      fullPath: '/tools/smart-paste'
      preLoaderRoute: typeof ToolsSmartPasteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/standup': {
      id: '/tools/standup'
      path: '/standup'
      fullPath: '/tools/standup'
      preLoaderRoute: typeof ToolsStandupRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/starfield': {
      id: '/tools/starfield'
      path: '/starfield'
      fullPath: '/tools/starfield'
      preLoaderRoute: typeof ToolsStarfieldRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/table': {
      id: '/tools/table'
      path: '/table'
      fullPath: '/tools/table'
      preLoaderRoute: typeof ToolsTableRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/typing-test': {
      id: '/tools/typing-test'
      path: '/typing-test'
      fullPath: '/tools/typing-test'
      preLoaderRoute: typeof ToolsTypingTestRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/upi': {
      id: '/tools/upi'
      path: '/upi'
      fullPath: '/tools/upi'
      preLoaderRoute: typeof ToolsUpiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/watermark': {
      id: '/tools/watermark'
      path: '/watermark'
      fullPath: '/tools/watermark'
      preLoaderRoute: typeof ToolsWatermarkRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/world-clock': {
      id: '/tools/world-clock'
      path: '/world-clock'
      fullPath: '/tools/world-clock'
      preLoaderRoute: typeof ToolsWorldClockRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/explore/$category/': {
      id: '/explore/$category/'
      path: '/explore/$category'
      fullPath: '/explore/$category/'
      preLoaderRoute: typeof ExploreCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category/$subcategory': {
      id: '/explore/$category/$subcategory'
      path: '/explore/$category/$subcategory'
      fullPath: '/explore/$category/$subcategory'
      preLoaderRoute: typeof ExploreCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssistantRouteChildren {
  AssistantAboutRoute: typeof AssistantAboutRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantAboutRoute: AssistantAboutRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

interface ToolsRouteChildren {
  ToolsAgeCalculatorRoute: typeof ToolsAgeCalculatorRoute
  ToolsAsciiRoute: typeof ToolsAsciiRoute
  ToolsAspectRoute: typeof ToolsAspectRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsBioRoute: typeof ToolsBioRoute
  ToolsBmiCalculatorRoute: typeof ToolsBmiCalculatorRoute
  ToolsBudgetRoute: typeof ToolsBudgetRoute
  ToolsColorPaletteRoute: typeof ToolsColorPaletteRoute
  ToolsContractRoute: typeof ToolsContractRoute
  ToolsCountdownRoute: typeof ToolsCountdownRoute
  ToolsCronRoute: typeof ToolsCronRoute
  ToolsCsvToJsonRoute: typeof ToolsCsvToJsonRoute
  ToolsCvRoute: typeof ToolsCvRoute
  ToolsDiffRoute: typeof ToolsDiffRoute
  ToolsDuaMakerRoute: typeof ToolsDuaMakerRoute
  ToolsEmiCalculatorRoute: typeof ToolsEmiCalculatorRoute
  ToolsEmojiRoute: typeof ToolsEmojiRoute
  ToolsExpenseRoute: typeof ToolsExpenseRoute
  ToolsFlashcardMakerRoute: typeof ToolsFlashcardMakerRoute
  ToolsFlipClockRoute: typeof ToolsFlipClockRoute
  ToolsFocusRoute: typeof ToolsFocusRoute
  ToolsFocusScreenRoute: typeof ToolsFocusScreenRoute
  ToolsGiftRoute: typeof ToolsGiftRoute
  ToolsGradientRoute: typeof ToolsGradientRoute
  ToolsGstCalculatorRoute: typeof ToolsGstCalculatorRoute
  ToolsHabitsRoute: typeof ToolsHabitsRoute
  ToolsHtmlToPdfRoute: typeof ToolsHtmlToPdfRoute
  ToolsImageCompressRoute: typeof ToolsImageCompressRoute
  ToolsImageConvertRoute: typeof ToolsImageConvertRoute
  ToolsImagesToPdfRoute: typeof ToolsImagesToPdfRoute
  ToolsInvoiceRoute: typeof ToolsInvoiceRoute
  ToolsKharchRoute: typeof ToolsKharchRoute
  ToolsLinktreeRoute: typeof ToolsLinktreeRoute
  ToolsLoremRoute: typeof ToolsLoremRoute
  ToolsMarkdownEditorRoute: typeof ToolsMarkdownEditorRoute
  ToolsMarkdownToHtmlRoute: typeof ToolsMarkdownToHtmlRoute
  ToolsMeetingRoute: typeof ToolsMeetingRoute
  ToolsMetaRoute: typeof ToolsMetaRoute
  ToolsMuhurratRoute: typeof ToolsMuhurratRoute
  ToolsMultiTimerRoute: typeof ToolsMultiTimerRoute
  ToolsNameRoute: typeof ToolsNameRoute
  ToolsNamecardRoute: typeof ToolsNamecardRoute
  ToolsNewTabRoute: typeof ToolsNewTabRoute
  ToolsNotesRoute: typeof ToolsNotesRoute
  ToolsOneLinerRoute: typeof ToolsOneLinerRoute
  ToolsPasswordRoute: typeof ToolsPasswordRoute
  ToolsPercentageRoute: typeof ToolsPercentageRoute
  ToolsPlantRoute: typeof ToolsPlantRoute
  ToolsPollRoute: typeof ToolsPollRoute
  ToolsPomodoroRoute: typeof ToolsPomodoroRoute
  ToolsQuoteScreenRoute: typeof ToolsQuoteScreenRoute
  ToolsRainScreenRoute: typeof ToolsRainScreenRoute
  ToolsReadabilityRoute: typeof ToolsReadabilityRoute
  ToolsRegexRoute: typeof ToolsRegexRoute
  ToolsScreenshotRoute: typeof ToolsScreenshotRoute
  ToolsSipCalculatorRoute: typeof ToolsSipCalculatorRoute
  ToolsSmartPasteRoute: typeof ToolsSmartPasteRoute
  ToolsStandupRoute: typeof ToolsStandupRoute
  ToolsStarfieldRoute: typeof ToolsStarfieldRoute
  ToolsTableRoute: typeof ToolsTableRoute
  ToolsTypingTestRoute: typeof ToolsTypingTestRoute
  ToolsUpiRoute: typeof ToolsUpiRoute
  ToolsWatermarkRoute: typeof ToolsWatermarkRoute
  ToolsWorldClockRoute: typeof ToolsWorldClockRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsAgeCalculatorRoute: ToolsAgeCalculatorRoute,
  ToolsAsciiRoute: ToolsAsciiRoute,
  ToolsAspectRoute: ToolsAspectRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsBioRoute: ToolsBioRoute,
  ToolsBmiCalculatorRoute: ToolsBmiCalculatorRoute,
  ToolsBudgetRoute: ToolsBudgetRoute,
  ToolsColorPaletteRoute: ToolsColorPaletteRoute,
  ToolsContractRoute: ToolsContractRoute,
  ToolsCountdownRoute: ToolsCountdownRoute,
  ToolsCronRoute: ToolsCronRoute,
  ToolsCsvToJsonRoute: ToolsCsvToJsonRoute,
  ToolsCvRoute: ToolsCvRoute,
  ToolsDiffRoute: ToolsDiffRoute,
  ToolsDuaMakerRoute: ToolsDuaMakerRoute,
  ToolsEmiCalculatorRoute: ToolsEmiCalculatorRoute,
  ToolsEmojiRoute: ToolsEmojiRoute,
  ToolsExpenseRoute: ToolsExpenseRoute,
  ToolsFlashcardMakerRoute: ToolsFlashcardMakerRoute,
  ToolsFlipClockRoute: ToolsFlipClockRoute,
  ToolsFocusRoute: ToolsFocusRoute,
  ToolsFocusScreenRoute: ToolsFocusScreenRoute,
  ToolsGiftRoute: ToolsGiftRoute,
  ToolsGradientRoute: ToolsGradientRoute,
  ToolsGstCalculatorRoute: ToolsGstCalculatorRoute,
  ToolsHabitsRoute: ToolsHabitsRoute,
  ToolsHtmlToPdfRoute: ToolsHtmlToPdfRoute,
  ToolsImageCompressRoute: ToolsImageCompressRoute,
  ToolsImageConvertRoute: ToolsImageConvertRoute,
  ToolsImagesToPdfRoute: ToolsImagesToPdfRoute,
  ToolsInvoiceRoute: ToolsInvoiceRoute,
  ToolsKharchRoute: ToolsKharchRoute,
  ToolsLinktreeRoute: ToolsLinktreeRoute,
  ToolsLoremRoute: ToolsLoremRoute,
  ToolsMarkdownEditorRoute: ToolsMarkdownEditorRoute,
  ToolsMarkdownToHtmlRoute: ToolsMarkdownToHtmlRoute,
  ToolsMeetingRoute: ToolsMeetingRoute,
  ToolsMetaRoute: ToolsMetaRoute,
  ToolsMuhurratRoute: ToolsMuhurratRoute,
  ToolsMultiTimerRoute: ToolsMultiTimerRoute,
  ToolsNameRoute: ToolsNameRoute,
  ToolsNamecardRoute: ToolsNamecardRoute,
  ToolsNewTabRoute: ToolsNewTabRoute,
  ToolsNotesRoute: ToolsNotesRoute,
  ToolsOneLinerRoute: ToolsOneLinerRoute,
  ToolsPasswordRoute: ToolsPasswordRoute,
  ToolsPercentageRoute: ToolsPercentageRoute,
  ToolsPlantRoute: ToolsPlantRoute,
  ToolsPollRoute: ToolsPollRoute,
  ToolsPomodoroRoute: ToolsPomodoroRoute,
  ToolsQuoteScreenRoute: ToolsQuoteScreenRoute,
  ToolsRainScreenRoute: ToolsRainScreenRoute,
  ToolsReadabilityRoute: ToolsReadabilityRoute,
  ToolsRegexRoute: ToolsRegexRoute,
  ToolsScreenshotRoute: ToolsScreenshotRoute,
  ToolsSipCalculatorRoute: ToolsSipCalculatorRoute,
  ToolsSmartPasteRoute: ToolsSmartPasteRoute,
  ToolsStandupRoute: ToolsStandupRoute,
  ToolsStarfieldRoute: ToolsStarfieldRoute,
  ToolsTableRoute: ToolsTableRoute,
  ToolsTypingTestRoute: ToolsTypingTestRoute,
  ToolsUpiRoute: ToolsUpiRoute,
  ToolsWatermarkRoute: ToolsWatermarkRoute,
  ToolsWorldClockRoute: ToolsWorldClockRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiToolsRoute: AiToolsRoute,
  AlternativesRoute: AlternativesRoute,
  AssistantRoute: AssistantRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  DesignsRoute: DesignsRoute,
  FavoritesRoute: FavoritesRoute,
  FindRoute: FindRoute,
  GlassRoute: GlassRoute,
  GlossaryRoute: GlossaryRoute,
  JournalRoute: JournalRoute,
  KeyboardRoute: KeyboardRoute,
  LiveRoute: LiveRoute,
  MeRoute: MeRoute,
  MoviesRoute: MoviesRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  RadarRoute: RadarRoute,
  RecentRoute: RecentRoute,
  RoadmapsRoute: RoadmapsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TrendingRoute: TrendingRoute,
  WhatsNewRoute: WhatsNewRoute,
  YoutubeRoute: YoutubeRoute,
  BuildIdeasSlugRoute: BuildIdeasSlugRoute,
  BuildIdeasProjectsRoute: BuildIdeasProjectsRoute,
  BuildIdeasValidateRoute: BuildIdeasValidateRoute,
  CSlugRoute: CSlugRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  DiscoverSectionRoute: DiscoverSectionRoute,
  DiscoverReelsRoute: DiscoverReelsRoute,
  GeneratorsIdRoute: GeneratorsIdRoute,
  HubAudienceRoute: HubAudienceRoute,
  HubIslamRoute: HubIslamRoute,
  HubQuotesRoute: HubQuotesRoute,
  HubUrduRoute: HubUrduRoute,
  RIdRoute: RIdRoute,
  BuildIdeasIndexRoute: BuildIdeasIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  GeneratorsIndexRoute: GeneratorsIndexRoute,
  HubIndexRoute: HubIndexRoute,
  ExploreCategorySubcategoryRoute: ExploreCategorySubcategoryRoute,
  ExploreCategoryIndexRoute: ExploreCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
