/**
 * Free APIs catalog — keyless or free-tier public APIs, each with a real
 * sample endpoint in `notes`. Auth limits are stated exactly as documented
 * by the provider at verification time.
 */
import type { Resource } from "../resources";
import { r } from "./_shared";

export const API_RESOURCES: Resource[] = [
  // ------------------------------------------------------ Weather & Climate
  r({
    id: "api-open-meteo", name: "Open-Meteo",
    url: "https://open-meteo.com/en/docs",
    description: "Keyless global weather forecasts, historical data, air quality and marine API.",
    section: "free-apis", category: "Weather & Climate", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["weather", "air-quality", "no-key", "unlimited"], notes: "Base: api.open-meteo.com/v1 · Sample: /v1/forecast?latitude=17.4&longitude=78.5&current=temperature_2m",
  }),
  r({
    id: "api-open-meteo-air", name: "Open-Meteo Air Quality",
    url: "https://open-meteo.com/en/docs/air-quality-api",
    description: "Hourly PM2.5, PM10, pollen and US/EU AQI for any coordinate.",
    section: "free-apis", category: "Weather & Climate", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["aqi", "pollution", "no-key"], notes: "Base: air-quality-api.open-meteo.com/v1 · Sample: /v1/air-quality?latitude=17.4&longitude=78.5&current=us_aqi",
  }),
  r({
    id: "api-open-meteo-geocode", name: "Open-Meteo Geocoding",
    url: "https://open-meteo.com/en/docs/geocoding-api",
    description: "Search city names to coordinates with population and timezone metadata.",
    section: "free-apis", category: "Weather & Climate", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["geocoding", "no-key"], notes: "Base: geocoding-api.open-meteo.com/v1 · Sample: /v1/search?name=Hyderabad&count=5",
  }),
  r({
    id: "api-sunrise-sunset", name: "Sunrise-Sunset",
    url: "https://sunrise-sunset.org/api",
    description: "Sunrise, sunset and golden-hour times for any lat/lng, no key needed.",
    section: "free-apis", category: "Weather & Climate", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["sun", "astronomy", "no-key"], notes: "Sample: api.sunrise-sunset.org/json?lat=17.4&lng=78.5",
  }),
  r({
    id: "api-usgs-quakes", name: "USGS Earthquakes",
    url: "https://earthquake.usgs.gov/fdsnws/event/1/",
    description: "Real-time worldwide earthquake feed queryable by magnitude, time and region.",
    section: "free-apis", category: "Weather & Climate", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["earthquake", "geo", "no-key"], notes: "Sample: earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=5&limit=10",
  }),

  // ---------------------------------------------------------------- Finance
  r({
    id: "api-coingecko", name: "CoinGecko",
    url: "https://www.coingecko.com/en/api",
    description: "Crypto prices, market caps and 24h change; free tier needs no key.",
    section: "free-apis", category: "Finance", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["crypto", "bitcoin", "no-key", "rate-limit-30-min"], notes: "Sample: api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=inr,usd",
  }),
  r({
    id: "api-frankfurter", name: "Frankfurter",
    url: "https://www.frankfurter.app/docs/",
    description: "ECB-backed currency conversion with no key and no rate limit.",
    section: "free-apis", category: "Finance", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["forex", "currency", "no-key"], notes: "Sample: api.frankfurter.app/latest?from=USD&to=INR",
  }),
  r({
    id: "api-erapi", name: "ExchangeRate-API (open endpoint)",
    url: "https://www.exchangerate-api.com/docs/free",
    description: "Daily-updated fiat rates; the open endpoint works with no key at all.",
    section: "free-apis", category: "Finance", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["forex", "currency", "no-key"], notes: "Sample: open.er-api.com/v6/latest/USD",
  }),
  r({
    id: "api-yahoo-chart", name: "Yahoo Finance chart (unofficial)",
    url: "https://finance.yahoo.com",
    description: "Unofficial JSON quote endpoint for stocks and indices like ^NSEI.",
    section: "free-apis", category: "Finance", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["stocks", "nifty", "sensex", "no-key", "unofficial"], notes: "Sample: query1.finance.yahoo.com/v8/finance/chart/^NSEI?range=1d&interval=1d",
  }),
  r({
    id: "api-amfi", name: "AMFI NAV India",
    url: "https://www.amfiindia.com/spages/NAVAll.txt",
    description: "Official daily NAV for every mutual fund scheme in India, plain text.",
    section: "free-apis", category: "Finance", audience: ["Developers", "Professionals"], region: "India only.",
    pricing: "Completely Free", type: "Dataset",
    tags: ["mutual-funds", "nav", "no-key", "india"], notes: "Returns the full NAVAll.txt list — parse scheme code, name and NAV per line.",
  }),

  // ------------------------------------------------------------------ Space
  r({
    id: "api-nasa-apod", name: "NASA APOD",
    url: "https://api.nasa.gov",
    description: "Astronomy Picture of the Day plus Mars rovers, NEOs and EPIC imagery.",
    section: "free-apis", category: "Space", audience: ["Developers", "Everyone"],
    pricing: "Free Tier", type: "API",
    eligibility: "DEMO_KEY allows ~30 req/hour; a free email key raises the limit.",
    tags: ["space", "nasa", "images"], notes: "Sample: api.nasa.gov/planetary/apod?api_key=DEMO_KEY",
  }),
  r({
    id: "api-wheretheiss", name: "WhereTheISS.at",
    url: "https://wheretheiss.at/w/developer",
    description: "Live International Space Station position, altitude and velocity, no key.",
    section: "free-apis", category: "Space", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["iss", "satellite", "no-key"], notes: "Sample: api.wheretheiss.at/v1/satellites/25544",
  }),
  r({
    id: "api-spacex", name: "SpaceX Data (r/SpaceX)",
    url: "https://github.com/r-spacex/SpaceX-API",
    description: "Community-maintained launch history, rockets, ships and Starlink data.",
    section: "free-apis", category: "Space", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["spacex", "launches", "no-key"], notes: "Sample: api.spacexdata.com/v4/launches/latest",
  }),
  r({
    id: "api-open-notify", name: "Open Notify",
    url: "http://open-notify.org/Open-Notify-API/",
    description: "Tiny classic API for ISS location and humans currently in space.",
    section: "free-apis", category: "Space", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["iss", "astronauts", "no-key", "http-only"], notes: "Sample: api.open-notify.org/astros.json (HTTP only)",
  }),

  // -------------------------------------------------------- Government & India
  r({
    id: "api-data-gov-in", name: "data.gov.in APIs",
    url: "https://data.gov.in/apis",
    description: "Thousands of Indian government datasets via API — agriculture, PIN codes, prices.",
    section: "free-apis", category: "Government & India", audience: ["Developers", "Researchers"], region: "India datasets.",
    pricing: "Free Tier", type: "API",
    eligibility: "Free key issued instantly on registration.",
    tags: ["government", "datasets", "india"], notes: "Register on data.gov.in to get an instant API key for any dataset.",
  }),
  r({
    id: "api-india-post", name: "India Post PIN Code API",
    url: "https://data.gov.in/resource/pincode-api",
    description: "Look up post offices by PIN code with district and state details.",
    section: "free-apis", category: "Government & India", audience: ["Developers"], region: "India only.",
    pricing: "Free Tier", type: "API",
    tags: ["pincode", "post-office", "india"], notes: "Requires the free data.gov.in key; dataset updated officially by India Post.",
  }),
  r({
    id: "api-world-bank", name: "World Bank Open Data",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589",
    description: "Development indicators for every country — GDP, literacy, energy — no key.",
    section: "free-apis", category: "Government & India", audience: ["Researchers", "Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["development", "economics", "no-key"], notes: "Sample: api.worldbank.org/v2/country/IND/indicator/NY.GDP.MKTP.CD?format=json",
  }),
  r({
    id: "api-rest-countries", name: "REST Countries",
    url: "https://restcountries.com",
    description: "Country profiles: flags, capitals, currencies, languages and timezones.",
    section: "free-apis", category: "Government & India", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["countries", "flags", "no-key"], notes: "Sample: restcountries.com/v3.1/name/india",
  }),

  // ------------------------------------------------------------------- News
  r({
    id: "api-hackernews", name: "HackerNews Firebase API",
    url: "https://github.com/HackerNews/API",
    description: "Read-only Hacker News items, users and top/new/best story lists.",
    section: "free-apis", category: "News", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["hacker-news", "stories", "no-key"], notes: "Sample: hacker-news.firebaseio.com/v0/topstories.json",
  }),
  r({
    id: "api-rss2json", name: "rss2json",
    url: "https://rss2json.com",
    description: "Turns any RSS feed into clean JSON without writing a parser.",
    section: "free-apis", category: "News", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "Public endpoint works without a key for basic feeds.",
    tags: ["rss", "feeds", "json"], notes: "Sample: api.rss2json.com/v1/api.json?rss_url=https://feeds.feedburner.com/ndtvnews-india-news",
  }),
  r({
    id: "api-reddit-json", name: "Reddit JSON endpoints",
    url: "https://www.reddit.com/dev/api/",
    description: "Append .json to almost any Reddit URL to get its data as JSON, no OAuth needed.",
    section: "free-apis", category: "News", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["reddit", "social", "no-key", "read-only"], notes: "Sample: reddit.com/r/india/hot.json?limit=10 (set a descriptive User-Agent)",
  }),

  // ------------------------------------------------------------------- Food
  r({
    id: "api-mealdb", name: "TheMealDB",
    url: "https://www.themealdb.com/api.php",
    description: "Recipes with ingredients, steps, categories and images; test key '1' is free.",
    section: "free-apis", category: "Food & Recipes", audience: ["Developers", "Everyone"],
    pricing: "Free Tier", type: "API",
    tags: ["recipes", "cooking", "images"], notes: "Sample: themealdb.com/api/json/v1/1/search.php?s=biryani",
  }),
  r({
    id: "api-cocktaildb", name: "TheCocktailDB",
    url: "https://www.thecocktaildb.com/api.php",
    description: "Cocktail and mocktail recipes with ingredients, glassware and images.",
    section: "free-apis", category: "Food & Recipes", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    tags: ["cocktails", "drinks", "images"], notes: "Sample: thecocktaildb.com/api/json/v1/1/search.php?s=margarita",
  }),
  r({
    id: "api-openfoodfacts", name: "Open Food Facts",
    url: "https://world.openfoodfacts.org/data",
    description: "Crowdsourced nutrition and ingredient data for millions of packaged foods.",
    section: "free-apis", category: "Food & Recipes", audience: ["Developers", "Everyone"],
    pricing: "Completely Free", type: "API",
    tags: ["nutrition", "barcodes", "open-data", "no-key"], notes: "Sample: world.openfoodfacts.org/api/v2/product/8901058000292.json",
  }),

  // ---------------------------------------------------------- Entertainment
  r({
    id: "api-pokeapi", name: "PokéAPI",
    url: "https://pokeapi.co",
    description: "Every Pokémon's stats, moves, evolutions and sprites, fully keyless.",
    section: "free-apis", category: "Entertainment", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["pokemon", "games", "no-key"], notes: "Sample: pokeapi.co/api/v2/pokemon/pikachu",
  }),
  r({
    id: "api-swapi", name: "SWAPI",
    url: "https://swapi.dev",
    description: "The original Star Wars data API — films, characters, planets, starships.",
    section: "free-apis", category: "Entertainment", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["star-wars", "fun", "no-key"], notes: "Sample: swapi.dev/api/people/1/",
  }),
  r({
    id: "api-rickmorty", name: "Rick and Morty API",
    url: "https://rickandmortyapi.com",
    description: "Characters, locations and episodes from the show, GraphQL included.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["tv", "graphql", "no-key"], notes: "Sample: rickandmortyapi.com/api/character/1",
  }),
  r({
    id: "api-trivia", name: "Open Trivia DB",
    url: "https://opentdb.com/api_config.php",
    description: "Quiz questions across categories and difficulty, session tokens included.",
    section: "free-apis", category: "Entertainment", audience: ["Developers", "Students", "Teachers"],
    pricing: "Completely Free", type: "API",
    tags: ["quiz", "trivia", "no-key"], notes: "Sample: opentdb.com/api.php?amount=10&category=9",
  }),
  r({
    id: "api-jokeapi", name: "JokeAPI v2",
    url: "https://sv443.net/jokeapi/v2/",
    description: "Programming and general jokes with safe-mode filtering, no key.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["jokes", "fun", "no-key"], notes: "Sample: v2.jokeapi.dev/joke/programming?type=single",
  }),
  r({
    id: "api-chucknorris", name: "Chuck Norris IO",
    url: "https://api.chucknorris.io",
    description: "Random Chuck Norris jokes grouped into categories, no key.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["jokes", "fun", "no-key"], notes: "Sample: api.chucknorris.io/jokes/random",
  }),
  r({
    id: "api-zenquotes", name: "ZenQuotes",
    url: "https://zenquotes.io/",
    description: "Inspirational quotes of the day and random quotes, no key.",
    section: "free-apis", category: "Entertainment", audience: ["Developers", "Creators"],
    pricing: "Completely Free", type: "API",
    tags: ["quotes", "motivation", "no-key"], notes: "Sample: zenquotes.io/api/random (limit 5 req/30 s)",
  }),
  r({
    id: "api-advice", name: "Advice Slip",
    url: "https://api.adviceslip.com",
    description: "One random piece of advice per request, searchable by topic.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["advice", "fun", "no-key"], notes: "Sample: api.adviceslip.com/advice",
  }),
  r({
    id: "api-bored", name: "Bored API",
    url: "https://bored-api.appbrewery.com/",
    description: "Suggests a random activity when you have nothing to do.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["activities", "fun", "no-key"], notes: "Original bored-api.herokuapp.com was retired; this mirror keeps the same shape.",
  }),
  r({
    id: "api-numbers", name: "Numbers API",
    url: "http://numbersapi.com",
    description: "Trivia, math facts and date facts about any number.",
    section: "free-apis", category: "Entertainment", audience: ["Developers", "Teachers"],
    pricing: "Completely Free", type: "API",
    tags: ["math", "trivia", "no-key"], notes: "Sample: numbersapi.com/42/trivia",
  }),
  r({
    id: "api-lyricsovh", name: "Lyrics.ovh",
    url: "https://lyricsovh.docs.apiary.io",
    description: "Simple keyless lyrics lookup by artist and song title.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["lyrics", "music", "no-key"], notes: "Sample: api.lyrics.ovh/Coldplay/Yellow (availability can fluctuate)",
  }),
  r({
    id: "api-itunes-search", name: "iTunes Search",
    url: "https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/",
    description: "Apple's keyless search over music, movies, podcasts, apps and books.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["music", "movies", "apple", "no-key"], notes: "Sample: itunes.apple.com/search?term=arijit&entity=song&limit=5",
  }),
  r({
    id: "api-deezer", name: "Deezer Public API",
    url: "https://developers.deezer.com/api",
    description: "Music search with 30-second previews and charts, no auth for reads.",
    section: "free-apis", category: "Entertainment", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["music", "previews", "no-key"], notes: "Sample: api.deezer.com/search?q=weeknd",
  }),

  // -------------------------------------------------------------- Geolocation
  r({
    id: "api-ipapi", name: "IP-API",
    url: "http://ip-api.com/docs/",
    description: "Geolocate an IP to city, ISP and timezone; no key for non-commercial use.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "Non-commercial use, 45 requests/minute, HTTP only on the free plan.",
    tags: ["ip", "geolocation", "rate-limit-45-min"], notes: "Sample: ip-api.com/json/8.8.8.8",
  }),
  r({
    id: "api-ipinfo", name: "IPinfo",
    url: "https://ipinfo.io/developers",
    description: "Accurate IP lookup with ASN and company data on a generous free tier.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "50,000 requests/month with a free account.",
    tags: ["ip", "asn", "geolocation"], notes: "Sample: ipinfo.io/8.8.8.8/json (token optional for basic fields)",
  }),
  r({
    id: "api-nominatim", name: "OSM Nominatim",
    url: "https://nominatim.org/release-docs/latest/api/Search/",
    description: "OpenStreetMap geocoding and reverse geocoding, no key, fair-use policy.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    eligibility: "Max 1 request/second with a valid User-Agent or Referer.",
    tags: ["maps", "osm", "geocoding", "no-key"], notes: "Sample: nominatim.openstreetmap.org/search?q=Charminar&format=json&limit=1",
  }),
  r({
    id: "api-opencage", name: "OpenCage Geocoder",
    url: "https://opencagedata.com/api",
    description: "Forward/reverse geocoding built on open data with a real free tier.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "2,500 requests/day free, no card required.",
    tags: ["geocoding", "maps"], notes: "Free key after email signup.",
  }),
  r({
    id: "api-worldtime", name: "WorldTimeAPI",
    url: "https://worldtimeapi.org",
    description: "Current time and offsets for any IANA timezone, no key.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["time", "timezone", "no-key"], notes: "Sample: worldtimeapi.org/api/timezone/Asia/Kolkata",
  }),
  r({
    id: "api-geonames", name: "GeoNames",
    url: "https://www.geonames.org/export/web-services.html",
    description: "Millions of place names with postal codes, elevation and population.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "Free account required; 30,000 credits/day.",
    tags: ["cities", "postal-codes", "geo"], notes: "Enable the free web-services flag on your GeoNames account.",
  }),
  r({
    id: "api-aladhan", name: "Aladhan",
    url: "https://aladhan.com/prayer-times-api",
    description: "Prayer times, Hijri calendar conversion and Qibla direction worldwide.",
    section: "free-apis", category: "Geolocation", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["prayer-times", "islamic", "hijri", "no-key"], notes: "Sample: api.aladhan.com/v1/timingsByCity?city=Hyderabad&country=India&method=1",
  }),

  // ---------------------------------------------------------------- Utilities
  r({
    id: "api-colorapi", name: "The Color API",
    url: "https://www.thecolorapi.com/docs",
    description: "Color names, schemes and HEX/RGB/HSL/CMYK conversions, no key.",
    section: "free-apis", category: "Utilities", audience: ["Designers", "Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["color", "design", "no-key"], notes: "Sample: www.thecolorapi.com/id?hex=24B1E0",
  }),
  r({
    id: "api-colormind", name: "Colormind",
    url: "http://colormind.io/api-access/",
    description: "Deep-learning color palette generator returning five hex colors per call.",
    section: "free-apis", category: "Utilities", audience: ["Designers", "Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["palette", "ai", "design", "no-key"], notes: "POST {\"model\":\"default\"} to colormind.io/api/",
  }),
  r({
    id: "api-dicebear", name: "DiceBear Avatars",
    url: "https://www.dicebear.com/styles/",
    description: "Deterministic SVG avatars from any seed across 30+ art styles, keyless.",
    section: "free-apis", category: "Utilities", audience: ["Developers", "Designers"],
    pricing: "Completely Free", type: "API",
    tags: ["avatars", "svg", "no-key"], notes: "Sample: api.dicebear.com/9.x/adventurer/svg?seed=Aneesh",
  }),
  r({
    id: "api-uiavatars", name: "UI Avatars",
    url: "https://ui-avatars.com/",
    description: "Generate initial-letter avatar images straight from a URL.",
    section: "free-apis", category: "Utilities", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["avatars", "initials", "no-key"], notes: "Sample: ui-avatars.com/api/?name=Slash+AI&background=0D8ABC",
  }),
  r({
    id: "api-picsum", name: "Picsum Photos",
    url: "https://picsum.photos",
    description: "Random Unsplash-sourced placeholder photos served by size URL.",
    section: "free-apis", category: "Utilities", audience: ["Developers", "Designers"],
    pricing: "Completely Free", type: "API",
    tags: ["placeholder", "images", "no-key"], notes: "Sample: picsum.photos/seed/slashai/600/400",
  }),
  r({
    id: "api-clearbit-logo", name: "Clearbit Logo API",
    url: "https://clearbit.com/logo",
    description: "Fetch a company logo image directly from its domain, no key.",
    section: "free-apis", category: "Utilities", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["logos", "branding", "no-key"], notes: "Sample: logo.clearbit.com/zomato.com",
  }),
  r({
    id: "api-microlink", name: "Microlink",
    url: "https://microlink.io/docs/api/getting-started/overview",
    description: "Extract metadata, screenshots or PDFs from any URL on a free tier.",
    section: "free-apis", category: "Utilities", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "~50 req/day free without signup.",
    tags: ["metadata", "og-image", "screenshots"], notes: "Sample: api.microlink.io/?url=https%3A%2F%2Fslashai.lovable.app",
  }),
  r({
    id: "api-internetdb", name: "Shodan InternetDB",
    url: "https://internetdb.shodan.io",
    description: "Check any IP for open ports, vulnerabilities and hostnames, no key.",
    section: "free-apis", category: "Utilities", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["security", "ports", "no-key"], notes: "Sample: internetdb.shodan.io/8.8.8.8",
  }),
  r({
    id: "api-abuseipdb", name: "AbuseIPDB",
    url: "https://docs.abuseipdb.com/",
    description: "Reputation check on IPs — spam, brute-force and abuse reports.",
    section: "free-apis", category: "Utilities", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "Free key: 1,000 checks/day.",
    tags: ["security", "ip-reputation"], notes: "Free key after registration; check endpoint /api/v2/check.",
  }),
  r({
    id: "api-carbon-intensity", name: "UK Carbon Intensity",
    url: "https://carbonintensity.org.uk/",
    description: "Real-time grid carbon intensity and generation mix for Great Britain.",
    section: "free-apis", category: "Utilities", audience: ["Developers", "Researchers"],
    pricing: "Completely Free", type: "API",
    tags: ["energy", "climate", "uk", "no-key"], notes: "Sample: api.carbonintensity.org.uk/intensity",
  }),
  r({
    id: "api-dogceo", name: "Dog CEO API",
    url: "https://dog.ceo/dog-api/",
    description: "Over 20,000 indexed dog images browsable by breed, no key.",
    section: "free-apis", category: "Utilities", audience: ["Developers", "Everyone"],
    pricing: "Completely Free", type: "API",
    tags: ["dogs", "images", "fun", "no-key"], notes: "Sample: dog.ceo/api/breeds/image/random",
  }),

  // ------------------------------------------------------------------ Testing
  r({
    id: "api-dummyjson", name: "DummyJSON",
    url: "https://dummyjson.com/docs",
    description: "Fake products, carts, users, recipes and auth flows for prototyping.",
    section: "free-apis", category: "Testing", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["mock-data", "prototyping", "no-key"], notes: "Sample: dummyjson.com/products/1",
  }),
  r({
    id: "api-jsonplaceholder", name: "JSONPlaceholder",
    url: "https://jsonplaceholder.typicode.com/",
    description: "The classic fake REST API of posts, todos and albums for demos.",
    section: "free-apis", category: "Testing", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["mock-data", "rest", "no-key"], notes: "Sample: jsonplaceholder.typicode.com/posts/1",
  }),
  r({
    id: "api-randomuser", name: "RandomUser.me",
    url: "https://randomuser.me/documentation",
    description: "Generate consistent fake user profiles with photos for UI testing.",
    section: "free-apis", category: "Testing", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    tags: ["fake-users", "testing", "no-key"], notes: "Sample: randomuser.me/api/?results=5&nat=in",
  }),
  r({
    id: "api-agify", name: "Agify / Genderize / Nationalize",
    url: "https://agify.io",
    description: "Estimate age, gender and nationality probabilities from first names.",
    section: "free-apis", category: "Testing", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "1,000 free lookups/day per service, no card.",
    tags: ["names", "demographics"], notes: "Sample: api.agify.io/?name=aarav&country_id=IN",
  }),

  // ------------------------------------------------------------- AI & Data
  r({
    id: "api-wikipedia", name: "Wikipedia API",
    url: "https://www.mediawiki.org/wiki/API:REST_API",
    description: "Search, summaries and full article content from Wikipedia, keyless.",
    section: "free-apis", category: "AI & Data", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["encyclopedia", "search", "no-key"], notes: "Sample: en.wikipedia.org/api/rest_v1/page/summary/Hyderabad",
  }),
  r({
    id: "api-openlibrary", name: "Open Library",
    url: "https://openlibrary.org/developers/api",
    description: "Books, authors, covers and reading lists from the Internet Archive.",
    section: "free-apis", category: "AI & Data", audience: ["Developers", "Students"],
    pricing: "Completely Free", type: "API",
    tags: ["books", "authors", "no-key"], notes: "Sample: openlibrary.org/search.json?q=wingsoffire",
  }),
  r({
    id: "api-github-rest", name: "GitHub REST API",
    url: "https://docs.github.com/rest",
    description: "Repos, users, issues and trends; 60 unauthenticated requests/hour.",
    section: "free-apis", category: "AI & Data", audience: ["Developers"],
    pricing: "Completely Free", type: "API",
    eligibility: "60 req/hr anonymous; raise to 5,000/hr with any free token.",
    tags: ["github", "repos", "trending"], notes: "Sample: api.github.com/repos/facebook/react",
  }),
  r({
    id: "api-pagespeed", name: "PageSpeed Insights API",
    url: "https://developers.google.com/speed/docs/insights/v5/get-started",
    description: "Google Lighthouse scores and Core Web Vitals for any URL.",
    section: "free-apis", category: "AI & Data", audience: ["Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "25,000 free requests/day with a free API key.",
    tags: ["performance", "lighthouse", "seo"], notes: "Run with ?url=https://yoursite.com&key=YOUR_KEY",
  }),
  r({
    id: "api-open-fda", name: "openFDA",
    url: "https://open.fda.gov/apis/",
    description: "US drug approvals, recalls, adverse events and device safety data.",
    section: "free-apis", category: "AI & Data", audience: ["Researchers", "Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "240 req/min without a key.",
    tags: ["health", "drugs", "safety", "no-key"], notes: "Sample: api.fda.gov/drug/label.json?limit=1",
  }),
  r({
    id: "api-census", name: "US Census Bureau API",
    url: "https://www.census.gov/data/developers/data-sets.html",
    description: "Population, housing and demographic statistics down to block level.",
    section: "free-apis", category: "AI & Data", audience: ["Researchers", "Developers"],
    pricing: "Free Tier", type: "API",
    eligibility: "Instant free key by email; 500 queries/day default.",
    tags: ["demographics", "population", "us"], notes: "Most datasets work keyless at low volume.",
  }),
];
