/**
 * YouTube channel catalog — expanded to 80+ hand-picked channels across
 * AI, development, data, business, productivity, design and Indian creators.
 */
import type { Resource } from "../resources";
import { r } from "./_shared";

export const YOUTUBE_EXTRA: Resource[] = [
  // --------------------------------------------------------------------- AI
  r({ id: "yt-yannic", name: "Yannic Kilcher", url: "https://www.youtube.com/@YannicKilcher", description: "Deep paper walkthroughs and frank takes on new AI models.", section: "youtube", category: "AI", audience: ["Developers", "Researchers"], pricing: "Completely Free", type: "YouTube", tags: ["ai", "papers", "llms"] }),
  r({ id: "yt-karpathy", name: "Andrej Karpathy", url: "https://www.youtube.com/@AndrejKarpathy", description: "From-scratch neural network lessons by a former Tesla AI director.", section: "youtube", category: "AI", audience: ["Developers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["deep-learning", "from-scratch", "llms"], notes: "\"Neural Networks: Zero to Hero\" is the best free intro to how LLMs actually work." }),
  r({ id: "yt-primeagen", name: "The Primeagen", url: "https://www.youtube.com/@ThePrimeagen", description: "Opinionated programming culture, Vim and Rust content with real depth.", section: "youtube", category: "Development", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["rust", "vim", "career"] }),
  r({ id: "yt-theo", name: "Theo (t3.gg)", url: "https://www.youtube.com/@theo-browne", description: "Web framework news, ecosystem drama and tooling reviews from a practitioner.", section: "youtube", category: "Development", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["web", "typescript", "news"] }),
  r({ id: "yt-wds", name: "Web Dev Simplified", url: "https://www.youtube.com/@WebDevSimplified", description: "Clear short lessons on JavaScript, React and CSS concepts.", section: "youtube", category: "Development", audience: ["Developers", "Students"], pricing: "Completely Free", type: "YouTube", difficulty: "Beginner", tags: ["javascript", "react", "css"] }),
  r({ id: "yt-kevinpowell", name: "Kevin Powell", url: "https://www.youtube.com/@KevinPowell", description: "The go-to channel for modern CSS explained calmly and correctly.", section: "youtube", category: "Design", audience: ["Developers", "Designers"], pricing: "Completely Free", type: "YouTube", tags: ["css", "layout", "responsive"] }),
  r({ id: "yt-traversy", name: "Traversy Media", url: "https://www.youtube.com/@TraversyMedia", description: "Crash courses on nearly every web technology and framework.", section: "youtube", category: "Development", audience: ["Developers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["webdev", "crash-course", "fullstack"] }),
  r({ id: "yt-bytebytego", name: "ByteByteGo", url: "https://www.youtube.com/@ByteByteGo", description: "System design concepts animated clearly — caching, load balancers, queues.", section: "youtube", category: "Development", audience: ["Developers", "Job Seekers"], pricing: "Completely Free", type: "YouTube", tags: ["system-design", "interviews", "architecture"] }),
  r({ id: "yt-hussein", name: "Hussein Nasser", url: "https://www.youtube.com/@HusseinNasser-software-engineering", description: "Databases, networking and backend internals explained from the trenches.", section: "youtube", category: "Development", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["databases", "networking", "backend"] }),
  r({ id: "yt-nana", name: "TechWorld with Nana", url: "https://www.youtube.com/@TechWorldwithNana", description: "DevOps bootcamps — Docker, Kubernetes, CI/CD and Terraform.", section: "youtube", category: "Development", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["devops", "docker", "kubernetes"] }),

  // -------------------------------------------------------- Data & Analytics
  r({ id: "yt-alex-analyst", name: "Alex The Analyst", url: "https://www.youtube.com/@AlexTheAnalyst", description: "Full data-analyst career paths: SQL, Excel, Tableau and portfolio projects.", section: "youtube", category: "Data & Analytics", audience: ["Job Seekers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["sql", "tableau", "career"] }),
  r({ id: "yt-luke-barousse", name: "Luke Barousse", url: "https://www.youtube.com/@LukeBarousse", description: "Data analytics tutorials grounded in real job-market salary data.", section: "youtube", category: "Data & Analytics", audience: ["Job Seekers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["data-analytics", "python", "salary-data"] }),
  r({ id: "yt-kenjee", name: "Ken Jee", url: "https://www.youtube.com/@KenJee_ds", description: "Data science careers, portfolios and practical project advice.", section: "youtube", category: "Data & Analytics", audience: ["Students", "Job Seekers"], pricing: "Completely Free", type: "YouTube", tags: ["data-science", "portfolio", "career"] }),
  r({ id: "yt-statquest", name: "StatQuest with Josh Starmer", url: "https://www.youtube.com/@statquest", description: "Statistics and machine learning concepts broken into tiny clear pieces.", section: "youtube", category: "Learning", audience: ["Students", "Researchers"], pricing: "Completely Free", type: "YouTube", tags: ["statistics", "ml", "fundamentals"] }),
  r({ id: "yt-robmulla", name: "Rob Mulla", url: "https://www.youtube.com/@RobMulla", description: "Practical pandas and Python data-wrangling walkthroughs.", section: "youtube", category: "Data & Analytics", audience: ["Developers", "Researchers"], pricing: "Completely Free", type: "YouTube", tags: ["pandas", "python", "kaggle"] }),
  r({ id: "yt-dataschool", name: "Data School", url: "https://www.youtube.com/@dataschool", description: "Focused scikit-learn and pandas lessons for working analysts.", section: "youtube", category: "Data & Analytics", audience: ["Developers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["scikit-learn", "pandas", "tutorials"] }),
  r({ id: "yt-renotte", name: "Nicholas Renotte", url: "https://www.youtube.com/@NicholasRenotte", description: "End-to-end applied ML projects in Python, explained energetically.", section: "youtube", category: "Data & Analytics", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["machine-learning", "projects", "python"] }),

  // ------------------------------------------------------ Business & Finance
  r({ id: "yt-ycombinator", name: "Y Combinator", url: "https://www.youtube.com/@ycombinator", description: "Startup School lectures, founder talks and How to Start a Startup series.", section: "youtube", category: "Business & Finance", audience: ["Entrepreneurs"], pricing: "Completely Free", type: "YouTube", tags: ["startups", "founders", "yc"] }),
  r({ id: "yt-codiesanchez", name: "Codie Sanchez", url: "https://www.youtube.com/@Codie-Sanchez", description: "Buying and running boring businesses instead of chasing startups.", section: "youtube", category: "Business & Finance", audience: ["Entrepreneurs"], pricing: "Completely Free", type: "YouTube", tags: ["small-business", "acquisition", "cashflow"] }),
  r({ id: "yt-grahamstephan", name: "Graham Stephan", url: "https://www.youtube.com/@GrahamStephan", description: "Personal finance, saving and investing explained for normal incomes.", section: "youtube", category: "Business & Finance", audience: ["Everyone"], pricing: "Completely Free", type: "YouTube", tags: ["personal-finance", "investing", "budgeting"] }),
  r({ id: "yt-andreijikh", name: "Andrei Jikh", url: "https://www.youtube.com/@AndrejJikh", description: "Cinematic personal finance and dividend investing videos.", section: "youtube", category: "Business & Finance", audience: ["Everyone"], pricing: "Completely Free", type: "YouTube", tags: ["dividends", "investing", "finance"] }),
  r({ id: "yt-marktilbury", name: "Mark Tilbury", url: "https://www.youtube.com/@marktilbury", description: "Money habits and side-income ideas aimed at younger viewers.", section: "youtube", category: "Business & Finance", audience: ["Students", "Everyone"], pricing: "Completely Free", type: "YouTube", tags: ["money", "side-hustle", "habits"] }),
  r({ id: "yt-nateobrien", name: "Nate O'Brien", url: "https://www.youtube.com/@NateOBrien", description: "Frugal living, investing and financial independence without hype.", section: "youtube", category: "Business & Finance", audience: ["Everyone"], pricing: "Completely Free", type: "YouTube", tags: ["frugal-living", "fire", "investing"] }),
  r({ id: "yt-warikoo", name: "Ankur Warikoo", url: "https://www.youtube.com/@warikoo", description: "Personal finance and career advice in Hindi and English for Indian audiences.", section: "youtube", category: "Indian Creators", audience: ["Everyone", "Students"], region: "Content is India-focused.", pricing: "Completely Free", type: "YouTube", tags: ["finance", "careers", "hindi", "india"] }),

  // ------------------------------------------------------------- Productivity
  r({ id: "yt-thomasfrank", name: "Thomas Frank", url: "https://www.youtube.com/@ThomasFrank", description: "Productivity systems, Notion templates and study strategies.", section: "youtube", category: "Productivity", audience: ["Students", "Professionals"], pricing: "Completely Free", type: "YouTube", tags: ["notion", "productivity", "systems"] }),
  r({ id: "yt-mattdavella", name: "Matt D'Avella", url: "https://www.youtube.com/@mattdavella", description: "Minimalism, habits and slow productivity through documentary-style films.", section: "youtube", category: "Productivity", audience: ["Everyone"], pricing: "Completely Free", type: "YouTube", tags: ["minimalism", "habits", "focus"] }),
  r({ id: "yt-jeffsu", name: "Jeff Su", url: "https://www.youtube.com/@Jeff_Su", description: "Workflow automation, resume teardowns and corporate productivity tips.", section: "youtube", category: "Productivity", audience: ["Professionals", "Job Seekers"], pricing: "Completely Free", type: "YouTube", tags: ["workflow", "resume", "google-workspace"] }),
  r({ id: "yt-mikeandmatty", name: "Mike and Matty", url: "https://www.youtube.com/@mikeandmatty", description: "Study techniques and learning science from two med school friends.", section: "youtube", category: "Learning", audience: ["Students"], pricing: "Completely Free", type: "YouTube", tags: ["study-techniques", "learning-science"] }),

  // ------------------------------------------------------------------ Design
  r({ id: "yt-designcourse", name: "DesignCourse", url: "https://www.youtube.com/@DesignCourse", description: "UI design critiques and front-end implementation together.", section: "youtube", category: "Design", audience: ["Designers", "Developers"], pricing: "Completely Free", type: "YouTube", tags: ["ui", "ux", "figma"] }),
  r({ id: "yt-mizko", name: "Mizko", url: "https://www.youtube.com/@mizko", description: "High-craft UI/UX case studies and freelancing advice for designers.", section: "youtube", category: "Design", audience: ["Designers"], pricing: "Completely Free", type: "YouTube", tags: ["ui-ux", "freelance", "case-studies"] }),
  r({ id: "yt-fluxacademy", name: "Flux Academy", url: "https://www.youtube.com/@FluxAcademy", description: "Web design business skills alongside visual craft lessons.", section: "youtube", category: "Design", audience: ["Designers", "Creators"], pricing: "Completely Free", type: "YouTube", tags: ["web-design", "clients", "branding"] }),
  r({ id: "yt-juxtopposed", name: "Juxtopposed", url: "https://www.youtube.com/@juxtopposed", description: "Playful experiments in UI, motion and creative coding aesthetics.", section: "youtube", category: "Design", audience: ["Designers", "Developers"], pricing: "Completely Free", type: "YouTube", tags: ["motion", "creative-ui", "experiments"] }),
  r({ id: "yt-femke", name: "Femke Design", url: "https://www.youtube.com/@femkesvs", description: "Working as a product designer: craft, process and career growth.", section: "youtube", category: "Design", audience: ["Designers", "Job Seekers"], pricing: "Completely Free", type: "YouTube", tags: ["product-design", "career", "process"] }),

  // -------------------------------------------------------------- Marketing
  r({ id: "yt-neilpatel", name: "Neil Patel", url: "https://www.youtube.com/@neilpatel", description: "SEO and digital marketing tactics in quick, actionable clips.", section: "youtube", category: "Marketing", audience: ["Entrepreneurs", "Creators"], pricing: "Completely Free", type: "YouTube", tags: ["seo", "marketing", "growth"] }),
  r({ id: "yt-wesmcdowell", name: "Wes McDowell", url: "https://www.youtube.com/@WesMcDowellOfficial", description: "Small-business websites and local marketing that convert.", section: "youtube", category: "Marketing", audience: ["Entrepreneurs"], pricing: "Completely Free", type: "YouTube", tags: ["websites", "local-marketing", "conversion"] }),
  r({ id: "yt-incomeschool", name: "Income School", url: "https://www.youtube.com/@IncomeSchool", description: "Building content sites and niche businesses without ads or spam.", section: "youtube", category: "Marketing", audience: ["Entrepreneurs", "Creators"], pricing: "Completely Free", type: "YouTube", tags: ["content", "seo", "niche-sites"] }),
  r({ id: "yt-ahrefs", name: "Ahrefs", url: "https://www.youtube.com/@AhrefsCom", description: "Technical SEO tutorials from the team behind the SEO toolset.", section: "youtube", category: "Marketing", audience: ["Entrepreneurs", "Creators"], pricing: "Completely Free", type: "YouTube", tags: ["seo", "link-building", "keyword-research"] }),

  // -------------------------------------------------------- Indian creators
  r({ id: "yt-ishansharma", name: "Ishan Sharma", url: "https://www.youtube.com/@IshanSharma7390", description: "Career, freelancing and startup interviews for Indian students.", section: "youtube", category: "Indian Creators", audience: ["Students", "Job Seekers"], region: "India-focused.", pricing: "Completely Free", type: "YouTube", tags: ["careers", "freelancing", "india"] }),
  r({ id: "yt-varunmayya", name: "Varun Mayya", url: "https://www.youtube.com/@VarunMayya", description: "Building companies and creator businesses from India, documented openly.", section: "youtube", category: "Indian Creators", audience: ["Entrepreneurs", "Students"], region: "India-focused.", pricing: "Completely Free", type: "YouTube", tags: ["startups", "creators", "india"] }),
  r({ id: "yt-apnacollege", name: "Apna College", url: "https://www.youtube.com/@ApnaCollegeOfficial", description: "Placement-focused DSA and development courses taught in Hindi.", section: "youtube", category: "Indian Creators", audience: ["Students"], region: "Teaches in Hindi.", pricing: "Completely Free", type: "YouTube", tags: ["dsa", "placement", "hindi", "india"] }),
  r({ id: "yt-codewithharry", name: "CodeWithHarry", url: "https://www.youtube.com/@CodeWithHarry", description: "Beginner-friendly web dev and Python playlists in Hindi.", section: "youtube", category: "Indian Creators", audience: ["Students"], region: "Teaches in Hindi.", pricing: "Completely Free", type: "YouTube", tags: ["webdev", "python", "hindi", "india"] }),
  r({ id: "yt-technicalguruji", name: "Technical Guruji", url: "https://www.youtube.com/@TechnicalGuruji", description: "Smartphone and gadget reviews in Hindi, among India's biggest tech channels.", section: "youtube", category: "Indian Creators", audience: ["Everyone"], region: "Reviews in Hindi.", pricing: "Completely Free", type: "YouTube", tags: ["gadgets", "reviews", "hindi", "india"] }),
  r({ id: "yt-dhruvrathee", name: "Dhruv Rathee", url: "https://www.youtube.com/@dhruvrathee", description: "Explainers on current affairs, economics and environment in plain language.", section: "youtube", category: "Indian Creators", audience: ["Everyone"], region: "India-focused current affairs.", pricing: "Completely Free", type: "YouTube", tags: ["current-affairs", "explainers", "india"] }),
  r({ id: "yt-rachnaranade", name: "CA Rachna Ranade", url: "https://www.youtube.com/@CARachanaRanade", description: "Reading balance sheets and stock basics, explained by a practising CA.", section: "youtube", category: "Business & Finance", audience: ["Everyone", "Professionals"], region: "India-focused finance education.", pricing: "Completely Free", type: "YouTube", tags: ["stocks", "balance-sheet", "finance", "india"] }),
  r({ id: "yt-pranjalkamra", name: "Pranjal Kamra", url: "https://www.youtube.com/@pranjalkamra", description: "Value investing and mutual-fund strategy for Indian investors.", section: "youtube", category: "Business & Finance", audience: ["Everyone"], region: "India-focused.", pricing: "Completely Free", type: "YouTube", tags: ["value-investing", "mutual-funds", "india"] }),
  r({ id: "yt-akshat", name: "Akshat Shrivastava", url: "https://www.youtube.com/@AkshatZee", description: "Macro trends, stocks and wealth-building frameworks for Indian markets.", section: "youtube", category: "Business & Finance", audience: ["Professionals", "Everyone"], region: "India + global markets.", pricing: "Completely Free", type: "YouTube", tags: ["macro", "investing", "india"] }),

  // --------------------------------------------------------------- Coding
  r({ id: "yt-csdojo", name: "CS Dojo", url: "https://www.youtube.com/@csdojo", description: "Gentle Python and data-structures lessons for absolute beginners.", section: "youtube", category: "Learning", audience: ["Students"], pricing: "Completely Free", type: "YouTube", difficulty: "Beginner", tags: ["python", "dsa", "beginners"] }),
  r({ id: "yt-sentdex", name: "Sentdex", url: "https://www.youtube.com/@sentdex", description: "Applied Python: finance bots, game AI and ML with real datasets.", section: "youtube", category: "Development", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["python", "ml", "applied"] }),
  r({ id: "yt-mosh", name: "Programming with Mosh", url: "https://www.youtube.com/@programmingwithmosh", description: "Polished full-length courses on Python, JS, C# and interview prep.", section: "youtube", category: "Development", audience: ["Students", "Developers"], pricing: "Completely Free", type: "YouTube", tags: ["courses", "beginners", "interviews"] }),
  r({ id: "yt-brocode", name: "Bro Code", url: "https://www.youtube.com/@BroCodez", description: "Long-form language courses plus bite-sized concept explainers.", section: "youtube", category: "Development", audience: ["Students"], pricing: "Completely Free", type: "YouTube", tags: ["java", "python", "courses"] }),
  r({ id: "yt-techwithtim", name: "Tech With Tim", url: "https://www.youtube.com/@TechWithTim", description: "Python, Discord bots and modern web projects step by step.", section: "youtube", category: "Development", audience: ["Developers", "Students"], pricing: "Completely Free", type: "YouTube", tags: ["python", "projects", "react"] }),
  r({ id: "yt-coreyschafer", name: "Corey Schafer", url: "https://www.youtube.com/@coreyms", description: "Widely considered the cleanest Python tutorials on YouTube.", section: "youtube", category: "Learning", audience: ["Students", "Developers"], pricing: "Completely Free", type: "YouTube", tags: ["python", "django", "best-of"] }),
  r({ id: "yt-realpython", name: "Real Python", url: "https://www.youtube.com/@realpython", description: "Video companion to the respected Real Python written tutorials.", section: "youtube", category: "Learning", audience: ["Developers"], pricing: "Completely Free", type: "YouTube", tags: ["python", "tips", "intermediate"] }),
  r({ id: "yt-striver", name: "take U forward (Striver)", url: "https://www.youtube.com/@striver_79", description: "Structured DSA sheets that thousands use for placement preparation.", section: "youtube", category: "Learning", audience: ["Students", "Job Seekers"], pricing: "Completely Free", type: "YouTube", tags: ["dsa", "placements", "interviews"] }),
];
